### ISSUE TITLE
Ability to have a customized view of Rounds on the dashboard and submissions tabs

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1036]
The current listing for rounds displays closed or open rounds only, defaulting to closed. Many managers are actively working rounds that are both open and closed, meaning this default requires extra clicks between closed and open. Also, the rounds listing takes up a lot of space.

Proposed solution:

- [ ] Ability to star rounds in both your dashboard and submissions page, open or closed
- [ ] Add a new 'Starred' tab in addition to Open and Closed for both dashboard and submission pages
- [ ] By default, if starred rounds exist, the starred tab is the one that displays in both dashboard and submission pages
- [ ] On both pages, one can minimize or maximize the rounds listing and this will persist (save your personal setting) between sessions, ie if you roll it up and leave it that way, it will stay that way.

**Comment by newbie15423** [comment]
@danblah Is this really a priority for the next release? Its not clear to me how much PMs will actually use this in reality? Or am I missing something and most every ticket is getting a priority tag?
