### ISSUE TITLE
Extend Wagtail embed field to support Google Doc

### ISSUE THREAD

**Issue by becklm** [HyphaApp/hypha#1070]
See: https://apply.opentech.fund/admin/pages/822/

The Google Sheet referenced should display, but nothing appears when published (only other text).

**Comment by frjo** [comment]
@becklm @danblah  Wagtails embeds field does not support Google Doc out of the box. A lot of other providers are supported, mainly for video. See https://github.com/wagtail/wagtail/blob/master/wagtail/embeds/oembed_providers.py

A custom solution must be built I believe, could not find one on a quick search at least.

**Comment by Parbhat** [comment]
@danblah @frjo Wagtail embeds content from URL using oEmbed protocol. But Google docs, sheet do not support it. There is also a paid service [Embed.ly](https://embed.ly/providers) supported by Wagtail but it also does not support Google sheets. Seems that embedding Google docs/sheets is not common. Google suggest embedding sheets manually as described [here](https://support.google.com/docs/answer/183965?hl=en). It provides the HTML code that can be added to the page. Not sure about the page type of URL mentioned in the issue description but we have two options here:

- [Custom embed finder class](https://docs.wagtail.io/en/v2.4/advanced_topics/embeds.html#custom-embed-finder-classes): Admin users can use the URL directly and we can create the required HTML code for embedding.

- [Use RawHTMLBlock](https://docs.wagtail.io/en/v2.4/topics/streamfield.html#rawhtmlblock): Users can get the embed HTML code from service like Google sheets and paste it directly. Not recommended as it will give editors full access to embed any HTML.

We may also have to style the iframe as tried to embed a test google sheet and it is not looking nice.

**Comment by frjo** [comment]
@Parbhat Good research of the problem! This seems time consuming and I think OTF is better served if you use your time on other issues for the moment. 

I have removed this from Q1. Let's revisit this when we have more time.

**Comment by danblah** [comment]
Is there a way for some [app script](https://developers.google.com/apps-script/guides/sheets) to be embedded into the google sheet that exports the sheet data (a sort of export) into a [wagtail table block](https://docs.wagtail.io/en/latest/reference/contrib/table_block.html)?

**Comment by Parbhat** [comment]
We do not need app script if the requirement is to access sheets data and display/store in our application. We can use [sheets](https://developers.google.com/sheets/api/guides/concepts) API to access sheet data.
