### ISSUE TITLE
Add a "Require MFA" option to the groups setting page

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1083]
Add additional sub-setting for "Allowed MFA methods" where options are: Any, Email, App, Security Key

An additional setting "How long do new members have to enable MFA?" where the values are Immediately, 2 days, 7 days, or 14 days.

If a new member is added to the group and doesn't have MFA enabled, they get an email letting them know how to set it up and that they won't be able to log in if they don't set it up by the set time.

If the setting is enabled on a pre-existing group, send the above email to all members who do not have MFA enabled.

**Comment by fourthletter** [comment]
Closing this issue because work will be carried out here https://github.com/OpenTechFund/apply-app/issues/62
