### ISSUE TITLE
Added partners don't persist to invited applications

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1138]
**Is your feature request related to an existing functionality? Please describe.**
The add partners function.

**Describe the solution you'd like**
For submissions that have multiple stages, if a partner(s) are associated to the first-stage application, when invited to proposal, associate the same partner(s) to the newly created/invited application. Ideally, the partners get the same notifications that an applicant does.

**Describe alternatives you've considered**
Adding partners again manually is possible but wastes time.

**Additional context**

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Applicants
- Partners

**Ideal deadline**
Q2/Q3

**Comment by saoun** [comment]
is this still the case @frjo or was it addressed?

**Comment by frjo** [comment]
I think this is still an issue.

But it doesn't seem to be that critical because it has not come up as a problem after this was posted.

**Comment by ei8fdb** [comment]
@danblah what permissions would these partners have? E.g. permissions to edit the application at subsequent stages? Permissions to submit an application?

**Comment by frjo** [comment]
Today they have the same permission as the applicant of the submission in question.

**Comment by ei8fdb** [comment]
@frjo OK. Does that mean this issue has been implemented

**Comment by frjo** [comment]
This issue is about having the partners you add to a concept note migrate/copied to the proposal.

**Comment by fourthletter** [comment]
I could see the value in adding partners in the first stage (concept note) to the second stage (proposal). However, we need to probe further into the 'Partner' user role and why this is necessary from one round to the next. The 'Partner' role could now be used as 1) a secondary account for applicants and 2) an entity that could view the application but could not submit a review

The 'problem' or 'challenge' in this issue has not been fully scoped. A case could be made for this migration but we need to identify a technical solution that would address the actual 'problem' once it has been fully scoped. A case could also be made for a user that does NOT want partners to migrate from the first to second stage. We need a use case or  more discovery to understand end-user needs. 

**I am closing this issue for now**
