### ISSUE TITLE
On the communications tab, provide a filter for comments by visibility and type

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1176]

**Comment by ei8fdb** [comment]
![On the communications tab, provide a filter for comments by visibility and type](https://user-images.githubusercontent.com/1899506/116209725-1956e900-a73a-11eb-9092-54323b16f2fd.png)


## Summary
This design also takes into account some of the changes from issue #1445.

### 1. Move comment visibility control to the RHS of the input field.
I've moved the comment visibility control to the right hand side of the comment input field.

The reason for this is to make it clearer this control is connected to the comment the user is writing.

### 2. Remove the comment output
There is no need to display the comment output.

### 3. Remove visibility explanation text
I've removed the unnecessary comment visibility explainer text as it was duplication.

### 4. Move the comment button closer to the input field.
Make it clearer this is related to the comment input field.

### 5. Comment visibility filter
By default, when the page loads, comments visible to all users are displayed.

The user can use this dropdown to filter what comments they want to see.

### 6. Comment visibility options
When the user clicks the dropdown, they see the options to choose which comments they want visible. Right now the user can choose only 1 option.

**Comment by fourthletter** [comment]
Related to #1445

**Comment by fourthletter** [comment]
Closing this issue because it was developed and completed in 2021.
