### ISSUE TITLE
Add a "archived" flag to all categories and allow it to be set via wagtail admin

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1183]
Terms flagged with "archive" should:

* Show on content where they where added before being archived.
* Not be available to set on new content.
* Admins can toggle this flag on/off in wagtail admin edit view for each term.

**Comment by danblah** [comment]
* Add a button/[icon](https://thenounproject.com/search/?q=archive&i=977039) before trashcan, after arrows that is this archive function.
* Create a "show archived" link at the bottom of a term list that when clicked expands the list showing a different icon (reverse the colors/backgrouds) indicating they are archived terms
* Undo archive when clicking the archived button for an archived term

Non-mvp
* Add an [icon](https://thenounproject.com/search/?q=visible&i=1707883) after archive (last one) that when clicked goes to a page listing all content labeled with that term
* Set trashcan visibility

**Comment by danblah** [comment]
Bump!
