### ISSUE TITLE
Enhance the existing required "Requested Amount" streamfield element to be a calculated value

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1243]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2420%20Funded-%2300A156.svg" />](https://issuehunt.io/r/OpenTechFund/opentech.fund/issues/1243)

**Is your feature request related to a problem? Please describe.**
Since every OTF project is different, we do not have a single template for budgets. However, there are a few basic values a project budget must now include to ensure that the OTF team and our finance department have everything they need to properly review the financials of a proposed project.

**Is your feature request related to an existing functionality? Please describe.**
We need to capture the following values:
* **Labor**: Hours billed to OTF for work on specific project objectives or tasks
* **Equipment**: Purchases of equipment or other supplies related to work on the project
* **Travel**: Costs associated with project-related trips 
* **Other expenses**: Consultants, hosting any other direct project costs not covered in the previous categories
* **Total**: A calculated value from any of the above

We'd also like this field to include a non-required file attachment for a budget xls. This would allow us to know consistently where supplementary budgets are in the data base moving forward. 

**Describe the solution you'd like**
As a team member, when building an application form, we'd like a single field that's required, that we can change the title of (just like we can now for the "Requested Amount" field), that when rendered as a submission form, presents the applicant 4 boxes to insert a value in. The total can't be zero (ie at least one of the 4 boxes has to have a value greater than zero). 

When viewing a submission, we'd like to see a nice table or rendering of the values and the total. The total now becomes the value of "Requested Amount". 

**Priority**
- Medium (slowing you down). 

**Affected roles**
- Team
- Applicants
- Reviewers

**Ideal deadline**
Ideally this happens in the 2019-Q2 or start of 2019-Q3.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $20.00)

- [<img src='https://avatars1.githubusercontent.com/u/620336?v=4' alt='danblah' width=24 height=24> danblah](https://issuehunt.io/u/danblah) ($20.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/OpenTechFund/opentech.fund/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by fourthletter** [comment]
Relates to #286
