### ISSUE TITLE
Make it possible to lock meta categories so only super admins can edit

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1291]
Add a "protected" checkbox for super admins that lock that term so only super admins can edit it.

**Comment by saoun** [comment]
what's a use case for something like that? as in, *not* giving anyone on staff the ability to edit meta categories?

**Comment by frjo** [comment]
So nobody by accident delete terms used in e.g. some analytics functionality.

**Comment by saoun** [comment]
Ah yes, I thought this was in reference to just checking categories.
