### ISSUE TITLE
For New Projects, New Project Email Spike 

### ISSUE THREAD

**Issue by abigail-hampson** [HyphaApp/hypha#1375]

**Comment by todd-dembrey** [comment]
At this point we feel the best course of action for the welcome email is to keep this process manual for the time being. 

There is variation in the information that the user is expected to send to the system and we have not sufficiently captured that logic for OTF, let alone other potential users of the system.

@danblah @saoun @fourthletter Are you happy with this approach and would you be happy to add this into the backlog so we can look at this in more depth in the future?
