### ISSUE TITLE
Revision View - bring back formatting

### ISSUE THREAD

**Issue by arduina** [HyphaApp/hypha#1409]
**Describe the bug**
Recently, the revision view was stripped of formatting, as a workaround for this issue: https://github.com/OpenTechFund/opentech.fund/issues/1299
While this has worked for this particular application (https://apply.opentech.fund/apply/submissions/4043/) it makes it hard to read, understand and review revisions overall. 

**To Reproduce**
1. See revision view.

**Expected behavior**

**Priority**
- Medium

**Affected roles**
- Staff
- Reviewers

**Additional context**
We might run into the same problem at some point, but there needs to be proper solution on the long run for this problem,rather than having formatting stripped off for every application.

**Comment by frjo** [comment]
The diff functions needs to be completely rebuilt and we have an issue for that https://github.com/OpenTechFund/opentech.fund/issues/748.

I see no way to improve the current function in any substantial way unfortunately.
