### ISSUE TITLE
Improve submission comment visibility interface

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1445]
Replace the radio options with checkboxes so the user can pick the role(s) that the comment should be available for. The "All" option can then be removed.

This will need work on the backend to update code that controls the visibility of comments.

![comment_visibility_interface](https://user-images.githubusercontent.com/191392/63432952-7d33f500-c422-11e9-8f18-962f969b040c.png)

**Comment by harumhelmy** [comment]
Hi @frjo! I'm slowly moving on this -- thanks for your patience as I continue to get comfortable with Django and Python! After tinkering and chatting with @jheretic, I'm thinking the best way to move forward is to add the following three BooleanFields to the Activity model: `visible_to_applicants`, `visible_to_reviewers`, and `visible_to_partners`. We'd want to be clear on the frontend that any and all comments are always visible to the OTF team. 

I've pushed some code up to the enhancement/comment_visibility_interface branch along these lines, though they are still WIPs. Let me know if you have concerns -- I'm wondering if this approach is a bigger change than what you initially envisioned.

**Comment by frjo** [comment]
@harumhelmy I prefer not to hardcode in user roles in the db. Not all funds using Hypha will have the same requirements as OTF so I want to build features as flexible as possible. Code is fairly easy to override, but db model harder.

Can we let "Visibility" be a string field and save the groups as a comma separated list that we join/split? Or maybe a JSON field if we need to store more complex information? Django has a really neat JSON field type. It's varchar 30 now so that must be changed in any way.

Good idea about making it clear that the team can always see all comments. Maybe a greyed out checkbox named "Team" that is always checked? or is that a very "dev" way of showing it?

**Comment by saoun** [comment]
@harumhelmy, just a quick note with this: could we switch to "staff" instead of "team"?

**Comment by fourthletter** [comment]
As a user I would like to specific radio option for "internal review notes" with the same parameters as "Team" because we frequently record meeting notes. 

[ ] comments designated for team contain notes are internal and exchanged among team members
[ ] comments or notes designated as "internal review notes" is a NEW category. This category is necessary because these meeting notes are comprehensive.

**Comment by saoun** [comment]
I see. Not sure if this proposed solution would address what you're raising though. Even if we were to create a "team notes" option, someone could still fill this out on submissions that are not necessarily discussed on a particular day. So maybe best to think of another solution for this.

**Comment by ei8fdb** [comment]
What is the improvement needed here? 
- More granularity on who can see communications?
- Communications being visible to more than one user group?

**Comment by fourthletter** [comment]
Related to #1176

**Comment by fourthletter** [comment]
The button to send a message is labeled 'comment' and is not closely situated to the input field. Users may not find it intuitive to send messages. 

<img width="1222" alt="Send message button is very frar from the input field" src="https://user-images.githubusercontent.com/20019656/129389582-00f694b8-d846-41ea-8522-979a9cde6dca.png">

[BT recommend this design ](https://github.com/HyphaApp/hypha/issues/1176#issuecomment-826895769)

![116209725-1956e900-a73a-11eb-9092-54323b16f2fd-1](https://user-images.githubusercontent.com/20019656/129390232-9aa54154-e36a-48b7-ab99-b8887e1da8b4.png)

![116209725-1956e900-a73a-11eb-9092-54323b16f2fd](https://user-images.githubusercontent.com/20019656/129390242-d18b2f95-4b3f-4ac4-991a-0d1c4fbb0b35.png)

**Comment by fourthletter** [comment]
It looks beautiful 💥
