### ISSUE TITLE
[Epic/META] Ability for managers to use a peer review workflow (applicants reviewing applicants)

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1522]
- [ ] Needs issue template filled @Erioldoesdesign 

**Is your feature request related to a problem? Please describe.**

**Is your feature request related to an existing functionality? Please describe.**

A clear and concise description of what or where the existing page or function is. Include URLs.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Include ideal URLs, if they don't already exist.

**Describe alternatives you've considered**

**Additional context**

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers

**Ideal deadline**
Recommend review in Q2 rebasing for priority level.

--- 

Below are a historic list of functions, capabilities, ideas and acceptance criteria for the over 'Epic/META' of this feature.

How it could work...
1. Manager creates new fund, assigns new workflow Concept+PeerReview+Proposal
2. Manager has option to make peer review required or opt-in, to offer honorarium (and choose which are offered) or not to those who opt-in, and make specific fields not viewable by reviewers. They select opt-in and to offer a choice of honorariums.
3. Manager has option to choose which concept note questions to use for peer review assignment grouping.
4. Applicant applies, opt-ing in to peer review, and clearly seeing what info will and won't be visible to reviewers.
5. Round closes 
6. Lead does initial review, marking in/out of remit, sends dismissals for out of remit
7. Lead moves remaining concepts into Peer Review Open, setting deadline
8. Those applicants who opted-in are assigned 2 concepts to review by a deadline (priority to those like their based on similarly answered concept note questions) and receive notification.
9. Deadline passes, system moves rounds into Peer Review Closed, removing applicants ability to access and review assigned concepts
10. All who completed their assignment are sent a notification on how to claim their honorarium.
11. Lead reviews, submissions, writes reviews, determinations as needed, and dismisses or advances to invite for proposal
12. Everything here after proceeds as existing workflows (team/AC review)

On honorarium... These would be things that are able to be acquired in bulk as tokens and individually distributed, such as: opencollective.org gift cards, mullvad time vouchers, pia gift cards, adguard coupons, etc. Each available honorarium would have a page we'd create for a title, description, to upload tokens, etc. 

Why would we do this? To save us time, open up our process, accelerate the spread of knowledge, and to create a deterrent for some types of applications.. for funds where it's appropriate/desired. 

What y'all think?

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Removed from milestones 'backlog'https://github.com/HyphaApp/hypha/milestones/Backlog
* Added the issue template to body without content yet and assigned Eriol to issue to fill at a later date.
* Cleared assignes
* This is not a single issue, it's an Epic/META. - **PM needed to build out Epic/META details**
* Converted to an EPIC in Zenhub extension.
* Size estimated at XL
* Removed priority low label
* Added to forum post for Ideation meeting topics: https://we.hypha.app/t/candidate-topics-for-ideation-sessions-for-pinning/341
* Recommend review in Q2 rebasing for priority level.

**Comment by fourthletter** [comment]
A majority of functionalities for this issue already exist. Several current workflows accommodate non-staff reviewers, including "peer reviewers." Applicants could be assigned the "reviewer role" or be given the same level of permissions as reviewers.

The only missing functionality is [paying an honorarium to reviewers within the platform.](https://github.com/HyphaApp/hypha/issues/2074)


<img width="780" alt="Screen Shot 2022-01-07 at 6 41 10 PM" src="https://user-images.githubusercontent.com/20019656/148585346-978a2e24-5c6a-4db0-9aa9-7c4b9bca5452.png">

<img width="774" alt="Screen Shot 2022-01-07 at 6 41 19 PM" src="https://user-images.githubusercontent.com/20019656/148585350-4d80adf4-1861-44c2-9bce-346ed7b61da2.png">
