### ISSUE TITLE
No way to remove staff reviewer once assigned

### ISSUE THREAD

**Issue by tarakiyee** [HyphaApp/hypha#1575]
**Describe the bug**
The edit reviewers modal box doesn't allow a reviewer to be removed from the list of reviewers. 

**To Reproduce**
1. Go to an application with one or two reviewers assigned
2. Click Reviewers. 
3. Dropdown only allows you to change reviewer to another reviewer, no option to set no one. 

**Expected behavior**
The ability to remove a reviewer from an assigned application. 

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff
- Reviewers

**Comment by frjo** [comment]
We are reverting the first attempt at a solution so reopen this issue. See https://github.com/OpenTechFund/hypha/pull/1843

**Comment by saoun** [comment]
@frjo what is the status on this? is it still impossible to remove a reviewer once assigned?

**Comment by frjo** [comment]
@saoun You can change reviewers as you want. What you can't do is first assign reviewers then reset so there are no reviewers.

But should not a submission always have reviewers in any case?

**Comment by ei8fdb** [comment]
The behaviour as described above by @tarakiyee still occurs.

@frjo is there a technical reason why a reviewer cannot be unassigned once assigned? This would be expected for a number of reasons, for example:
- the reviewer was assigned incorrectly, 
- the reviewer has a conflict of interest and so should not review that application
- the reviewer requested for whatever reason to not review that application

In terms of design, there's none needed:
- when the user opens the reviewer modal (as seen in 00:22 and 00:26 in the below video), they should be able to unselect the previously assigned reviewers

https://user-images.githubusercontent.com/1899506/116275115-352eaf00-a77b-11eb-8782-e22d9913e3db.mov

**Comment by frjo** [comment]
This issue is concerning staff reviewers not AC reviewers.

**Comment by fourthletter** [comment]
@sandeepsajan0 I added your name as a 'reviewer' to this application on test so you can try for yourself. Please try to remove yourself as a reviewer:
https://test-apply.hypha.app/apply/submissions/11/

As a user, I would like to **unassign** myself as a reviewer from applications. This should apply to a) staff or b) external reviewer when they are associated with an application. The above comment contains a [video ](https://github.com/HyphaApp/hypha/issues/1575#issuecomment-827730606)


<img width="389" alt="Screen Shot 2021-08-29 at 7 38 47 PM" src="https://user-images.githubusercontent.com/20019656/131259985-c472c04f-df8a-4764-81e9-82b0ea477a4a.png">

**Comment by sandeepsajan0** [comment]
Thanks @fourthletter.
I checked, we can only change reviewers, we can't unassign. Let me look into this.

**Comment by ei8fdb** [comment]
After discussion with @fourthletter and @frjo this morning, we've come to agreement on the following design.

This design will satisfy the 2 scenarios: 

**Scenario 1: No reviewer is assigned**
- if no reviewer is assigned the UI will look like this:
![Screenshot 2021-09-15 at 10 35 16](https://user-images.githubusercontent.com/1899506/133416351-f87f4bb8-db06-4e72-b291-141cd025a66e.png)

**Scenario 2: An assigned reviewer wants to remove themselves from the review process**
- firstly, the user will select the dropdown,
![Screenshot 2021-09-15 at 10 32 12](https://user-images.githubusercontent.com/1899506/133416950-8af9b21b-c6f5-4c6f-af14-f6966c1cbc07.png)
- then they'll choose "No reviewer selected"
![Screenshot 2021-09-15 at 10 35 16](https://user-images.githubusercontent.com/1899506/133416351-f87f4bb8-db06-4e72-b291-141cd025a66e.png)

@sandeepsajan0 if you have any questions - or this design doesn't cover some scenarios - please let me know.

**Comment by frjo** [comment]
@fourthletter This is on the test site now.

**Comment by fourthletter** [comment]
Works like a charm! 💥
