### ISSUE TITLE
Yearly ability for reviewers to sign a 'Reviewer Agreement" else I can not view/review applications

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#176]
As a reviewer, ability to sign a 'Reviewer Agreement" that I agree to each year or upon change to the agreement text, else I can not view/review applications.

**Is your feature request related to a problem? Please describe.**
Hypothesis problem: Reviewer panels either 'go stale' or want to not review anymore they can have a journey out of the review process. 

**Is your feature request related to an existing functionality? Please describe.**
It is related to the existence of reviewers but the process for reviewer agreeing on a yearly basis is new. This sits somewhere between a feature and an enhancement.

**Describe the solution you'd like**
Here's a proposed workflow (from Dan in a comment below)

* In settings, there is a "Reviewer agreement".
*  In that settings, options include: Enable/disable; specification of which role this applies to; a text box for the agreement itself; a "Re-require acceptance" check-box, and save.
* When someone in the role Reviewer visits an application page after this feature has been enabled or after "Re-require acceptance" has been checked, they are redirected to an agreement page and asked to accept or deny the agreement.
* If they accept, they are redirected to the application. If they are decline, they are not able to view the application
* Their acceptance is saved so they don't have to do this every time.

**Describe alternatives you've considered**
* Expect that the current 'sign on' process is either not done or done via comms like email/text etc.
* We could consider an elapsed time period of zero activity to be a 'non sign'
* We also should consider what notifications via email (or other) are needed here

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

Primary:
- Reviewers

Secondary:
- Staff
- Partners
- Applicants

**Ideal deadline**
To be reviewed in future Rebasing for importance across adopters

**Additional context**
Validation questions:
* Do adopters need to do this as a legal/compliance process?
* Have reviewers asked for this feature/process?
* How critical is this to reviewers? 
* is this enhancement only about the yearly agreement 
* What happens if they refuse for now but want to return? a manual re-adding process or is a pause function needed

This sits somewhere between a feature and an enhancement.

**Comment by danblah** [comment]
Bumping this.

Here's a proposed worfklow:

1. In settings, there is a "Reviewer agreement".
2. In that settings, options include: Enable/disable; specification of which role this applies to; a text box for the agreement itself; a "Re-require acceptance" check-box, and save.
3. When someone in the role Reviewer visits an application page after this feature has been enabled or after "Re-require acceptance" has been checked, they are redirected to an agreement page and asked to accept or deny the agreement.
3. If they accept, they are redirected to the application. If they are decline, they are not able to view the application
4. Their acceptance is saved so they don't have to do this every time.

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Removed feature label
* Added enhancement label
* Size estimated at S and/or M
* Priority needed label could be removed - **Adopters needed to confirm** + **Could benefit from user research with reviewers**
* This is not a single issue, it's more of an Epic/META about reviewers experience. - **PM needed to build out Epic/META details**
* Added the issue template to body with content.
* Recommend review in Q2 rebasing for priority level.
* Updated title of issue to shortened version
* Removed from dev backlog board: https://github.com/HyphaApp/hypha/projects/2
