### ISSUE TITLE
Project feature should have delete and edit functionalities

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#1760]
- Any personally identifying information: I once went up a hill but came down a mountain

**Is your feature request related to a problem? Please describe.**
I foresee a time in the distant, or not so distant, future when team members would need to either delete or edit project pages or PAFs

**Is your feature request related to an existing functionality? Please describe.**
These functionalities do not exist for Projects, but they exist for Submissions.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

**Comment by frjo** [comment]
If you have the approver roles you can already edit projects.

**Comment by saoun** [comment]
@fourthletter could you test and confirm that you are able to edit projects?

**Comment by fourthletter** [comment]
@frjo I am currently designated as an approver. I am not able to edit a PAF that has been submitted and approved. In addition, I am not able to delete projects that have been created. The issue of deleting a project will not arise as much as deleting submissions.

**Comment by frjo** [comment]
@fourthletter A link to a project you can not edit?

**Comment by saoun** [comment]
@fourthletter a ping on this!

**Comment by fourthletter** [comment]
@frjo https://test-apply.opentech.fund/apply/projects/9/

**Comment by frjo** [comment]
@fourthletter You can not currently edit projects that are already approved. After approving a project it gets locked.

Is this not what you want?

**Comment by fourthletter** [comment]
@frjo My rationale for this request is similar to how it is sometimes necessary to delete a submission in the system.
