### ISSUE TITLE
"Show All" button in Dashboard not directing to intended purpose

### ISSUE THREAD

**Issue by saoun** [HyphaApp/hypha#1765]
In Dashboard, the "Show All" button under "Waiting for your Review" section will redirect to Concept Notes and Proposals that have already been reviewed (as opposed to waiting for review).

To recreate, view Dashboard as Tara (staff)

**Comment by frjo** [comment]
The Submissions list view, where the "Show all" link direct, has no function to filter on review or not.

The "Show all" links therefor show all reviews assigned to you.

The fix is to extend the submissions list view with filters for reviewed by user or not.

**Comment by fourthletter** [comment]
## User story
When a user selects 'Show All', the dashboard shows all submissions in the Hypha. I've assigned 9 submissions to Fredrik-OTF, they're in your dashboard awaiting review. You want to see this for yourself on the test site.

## Describe the solution you'd like in Hypha
@frjo You are correct in the [above comment](https://github.com/HyphaApp/hypha/issues/1765#issuecomment-580629440), the "Show all" link direct has no function to filter on review or not. The fix is to extend the submissions list view with filters for assigned for reviews or awaiting reviews. 

![Kapture DashBoard_ShowAll](https://user-images.githubusercontent.com/20019656/131096545-6723c410-775f-4843-86f3-2df36c7a1cae.gif)

**Comment by sandeepsajan0** [comment]
@fourthletter @frjo I tried to add a filter for review_status(awaiting) but it leads me to another known issue(Filter button is getting hidden).  So, I don't think we can add another simple filter there until it is solved. I think we may try ordering for awaiting if that can work?
![image](https://user-images.githubusercontent.com/23638629/137470343-ca8dffd1-0f44-49d7-94ea-630523bfab19.png)

**Comment by frjo** [comment]
@sandeepsajan0 Yes, wait with this until later.

**Comment by Erioldoesdesign** [comment]
@sandeepsajan0 
Regarding your comment:
> another known issue(Filter button is getting hidden)

Can you link the GitHub issue for this filter button getting hidden (if it exists?) please.

**Comment by sandeepsajan0** [comment]
@Erioldoesdesign Yes, It is here. https://github.com/HyphaApp/hypha/issues/2432
Same thing is happening if we are adding more filters there(actually it is a kind of width issue).

**Comment by Erioldoesdesign** [comment]
@ei8fdb just an FYI I worked on a similar problem with a table interface with lots of filter options that struggled to fit in the width of the page. I don't know if this UX 'bug' is captured anywhere but I can certainly help with it if it does :)

**Comment by fourthletter** [comment]
@sandeepsajan0 @frjo the  "Show all" links on **OTF's live Hypha** does NOT show all reviews assigned to an individual's dashboard. 

When I am on the OTF's live hypha dashboard, clicking on the "Show all" link renders more applications than what has been assigned to the user. The GIF below shows that I have **6** applications assigned to me on the dashboard. When I click on the "Show all" link, the dashboard now has a total of **13** applications. 

![Kapture Show All bug](https://user-images.githubusercontent.com/20019656/140023939-915ce923-0b71-42b8-812e-897f6ab9d7f4.gif)

**Comment by fourthletter** [comment]
> @ei8fdb just an FYI I worked on a similar problem with a table interface with lots of filter options that struggled to fit in the width of the page. I don't know if this UX 'bug' is captured anywhere but I can certainly help with it if it does :)

@Erioldoesdesign here is the suggested redesign for filters #2501

**Comment by frjo** [comment]
@sandeepsajan0 I think we need to solve this with a separate table view.

The the View all link should go to this new view and not to https://test-apply.hypha.app/apply/submissions/all/?* as now.

What do you think of "/apply/submissions/reviwer/[uid]"?

This table view should show exactly the same information as "Waiting for your review" table on the Dashboard. But on a separate page with pager at the bottom. Show 25 items per page, then the pager should seldom show.

The columns should be sortable as well but no filters are needed.

**Comment by sandeepsajan0** [comment]
@frjo A new separate table view sounds good. But I think we don't need reviewer uid`/reviewer/{uid}/` because we have to show submissions with awaiting reviews for the logged in user.

What about `apply/submissions/awaiting_reviews/`?

**Comment by frjo** [comment]
@sandeepsajan0 Good point, your suggestion is a good solution that fits well with Hypha.

**Comment by fourthletter** [comment]
@sandeepsajan0 thank you for picking this up and carrying it over the finish line 🏃‍♂️

**Comment by frjo** [comment]
This is now deploying to test.

**Comment by fourthletter** [comment]
@frjo I just tested. It is as perfect as a cup of cocoa in December ☕ ❄️
