### ISSUE TITLE
New projects created in the webapp notifications should appear in slack channel for new projects

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#1823]

**Comment by frjo** [comment]
@fourthletter There seem to already be Slack notifications about new projects.

You want these sent to a special Slack channel?

**Comment by saoun** [comment]
@frjo these would need to go to the slack channel named 'newprojects'

is that the current behavior ?

**Comment by frjo** [comment]
@saoun No, they go to #notice, the system was designed to send everything to that single channel. I do not think anyone envisioned any other need. 

A number of issue have now been about sending information to special channels. We should rebuild that part of the system to make it more flexible. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by frjo** [comment]
But on the other hand, my feeling is that people always will feel overwhelmed with information in Slack. Regardless of number of channels. I would personally prefer to get this info via e-mail where I can organise it to fit my brain. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by saoun** [comment]
The behavior currently for staff is to send new projects for approval to the slack channel named 'newprojects', where a senior staff member reviews the document and approves it. 

So, transitioning away from google docs, i think the idea is to replicate the same behavior. Where a new project created would go to 'newprojects' for approval, as opposed to notify. 

Does that make sense ?
