### ISSUE TITLE
[Meta] Data retention features to align with stated policies more easily

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1863]
We need the ability for application data to automatically align with a bespoke data retention policy. For example, a policy may say something like:
* All personally-identifying information (PII) or intellectual property (IP) will be removed from applications that are out of remit and dismissed.
* All PII and IP will be removed within 3yrs for any applications that are not approved.
* All PII and IP will be removed from all applications after 6yrs, regardless of the outcome.
* All non-PII/IP (categories/meta tags, amounts, etc) for all applications will be stored indefinitely for long-term analysis.

To have the app automatically comply, we'd need the ability to flag specific fields that contain PII/IP and then to define the policy conditions. @frjo and @Parbhat, how can we do this rightly and quickly?

cc @saoun @fourthletter

**Comment by frjo** [comment]
1. Simplify the rules as much as possible. E.g. delete all PII and IP info as soon as the application is dismissed even if it's allow for x month/years. Scheduling things years ahed is meaningless in my opinion.
2. We could add PII/IP options to every field but they already have help links etc. Better to create custom PII/IP fields with hard coded help text.

**Comment by Parbhat** [comment]
Agree with points by Fredrik. There are two possible scenarios

1. **The PII/IP fields can be uniquely identified**: The form fields type required to tag for PII/IP are uniform across all funds. For example, duration and requested amount etc. These fields are present in every fund. So, we can simply fetch these fields in our code for the update. This is the simplest scenario and does not require any change in the admin area. But the number of these fields is very small and our required PII/IP fields may not be covered in it.

2. **The PII/IP fields are created from generic form field blocks**: For example, Richtext Field and Text field (multi-line). These fields vary across application forms for funds. We can not fetch these fields using code only as can not be uniquely identified. We need a way to give Staff user an option to mark a form field for PII/IP while creating application forms. From implementation point of view, it seems better to create an abstract PII/IP block. Then create new form field block like Rich text field (PII/IP) from it.
Currently, we have three groups (Required, Custom and Fields) for form fields under Apply > Application forms. We can create a fourth group for PII/IP fields. This will help admin user to distinguish between normal and PII/IP fields.
More information about the possible fields needed for PII/IP will help to choose from the above possible scenarios. But looks like our requirement will probably fall in the second scenario.

**Comment by frjo** [comment]
Heroku saves database backups for up to one month. This needs to be taken in to account when stating how long we keep data.
