### ISSUE TITLE
Add fancy new duration or date widget to application form

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#1866]
**It looks like this now...**

![Screenshot 2020-03-19 at 2 36 56 PM](https://user-images.githubusercontent.com/20019656/77116607-d12da900-6a06-11ea-90d1-291d7f9430ab.png)

**Isn't this better? (This is a rhetorical question)**

<img width="402" alt="Screen Shot 2020-03-19 at 5 24 10 PM" src="https://user-images.githubusercontent.com/20019656/77116435-962b7580-6a06-11ea-9353-a9381d87d4ad.png">

**Comment by frjo** [comment]
So not an amount of time but a fixed date? Maybe the framing of the question should change as well to something like "When will you be done?"?

We already have a date widget like that in other places so not hard to change.

**Comment by fourthletter** [comment]
@frjo We still need a duration or timeframe like 12 months, 13 months, 14 months, etc. The proposal system currently enables 1-12 months, 18 months, 24 months. I was suggesting a solution that is easier than a drop down menu. We can continue using a drop down menu if this is the easiest solution.
