### ISSUE TITLE
'Closed' rounds copy on Dashboard

### ISSUE THREAD

**Issue by tmsndrs** [HyphaApp/hypha#1879]
On the dashboard the 'closed' rounds and labs section reads 'There are no open rounds' when there aren't any closed rounds. It should read 'You have no closed rounds or labs assigned to you'. Likewise the Open tab should read 'You have no open rounds or labs assigned to you'. 

<img width="1334" alt="Screenshot 2020-03-24 at 10 47 22" src="https://user-images.githubusercontent.com/7290588/77417143-e31f9b00-6dbc-11ea-9fc5-e0164d94c323.png">

This is what I currently see on the 'Test' environment.

**Comment by fourthletter** [comment]
Hello @sandeepsajan0 - please use your account to log into Hypha's test site. If you go to the 'Your rounds and labs' dashboard, you will see that the phrase has not rendered on test. Thanks.


<img width="905" alt="Screen Shot 2021-09-09 at 10 33 32 AM" src="https://user-images.githubusercontent.com/20019656/132651936-381f0ad8-8c44-4e6a-8471-91551f220fbb.png">

<img width="880" alt="Screen Shot 2021-09-09 at 10 33 44 AM" src="https://user-images.githubusercontent.com/20019656/132651959-2e704309-186e-48e5-984b-46643989ed42.png">

**Comment by frjo** [comment]
@fourthletter @sandeepsajan0 This is my fault, I pulled it from test and forgot to follow up here.

I hade issues with the PR on test, got a server 500 error for the Dashboard page. Nothing in the logs to help me track it down either. Did not see this issue in my local environment.

**Comment by frjo** [comment]
@sandeepsajan0 @fourthletter Fix the small issue and redeployed to test. Now it works.

**Comment by fourthletter** [comment]
Looks amazing! 💥 

<img width="885" alt="Screen Shot 2021-09-10 at 3 47 23 PM" src="https://user-images.githubusercontent.com/20019656/132863386-30c67c40-b182-4e22-981d-4e7c8d3a1c76.png">
