### ISSUE TITLE
When editing an active round's application, an option to save changes to the original/master application

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1909]
- [ ] Needs issue template filled @Erioldoesdesign 

**Is your feature request related to a problem? Please describe.**

I want an option to save application form changes in active rounds to the original/master application. Right now, you have to make the same changes twice. This is annoying and slow, especially if you forget about changes and create a new round.

**Is your feature request related to an existing functionality? Please describe.**

A clear and concise description of what or where the existing page or function is. Include URLs.

**Describe the solution you'd like**

A clear and concise description of what you want to happen. Include ideal URLs, if they don't already exist.

**Describe alternatives you've considered**

**Additional context**

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Ideal deadline**

* Recommend review in Q2 rebasing for priority level.

**Comment by fourthletter** [comment]
Related to #1509

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Added the issue template to body without content yet and assigned Eriol to issue to fill at a later date.
* Removed priority low label
* Removed open/close label
* Removed needs team review label
* Added label partner:RST
* Added label Theme:Admin
* Added label L
* Added to forum post for Ideation meeting topics: https://we.hypha.app/t/candidate-topics-for-ideation-sessions-for-pinning/341
* Removed from dev backlog board: https://github.com/HyphaApp/hypha/projects/2 (for now)
* Removed from milestones 'horizon 2' https://github.com/HyphaApp/hypha/milestone/25
* Recommend review in Q2 rebasing for priority level.
