### ISSUE TITLE
Allow applicants to see basic information about all other applications

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1934]
We'd like the ability for all applicants to see basic information about all other applications when specific conditions are met. 

Conditions for applications to be shared:

* The application submitted has fields marked as to be shared
* On submission of application, applicant opts-in to sharing their application information
* The application has been screened as within the scope of the open call (see #1948)

Conditions for applicants to view:

* The account is assigned a role
* The account is active/verified
* The account has had an application meeting the above conditions within a set amount of time.

Requirements

* A way to enable this feature that is fund/round independent
  * Also want to make sure all deployments don't have this enabled by default.
* A page listing all of the applications (somewhere in /apply)
* A way to select which field to check before including an application in the list
* A way to select which fields to expose to applicants 
* An indication on the application form for applicants which fields will be shared

On the listing page
* Base this off the All submissions table, using the same one or a new one if needed.
* Display: Title, Status, Fund, Round, Submitted
* Allow search and filters
* Upon click, they go to the application page, but only see the fields that have been allowed for viewing.
  * If not possible, maybe on click an overlay with just the fields or another page?

Possible implementation

* Create a new site setting called "Application sharing". Options within include: enable or disable; option to choose specific screening statuses; Application age to allow (in days); and notification template. 
* Upon enabling, a new form element is offered for applications called "Application sharing consent", which is a single checkbox field. Title, helptext, etc are all able to be customized as a normal field.
* For all other application elements, there is a new checkbox option called "Share"
* A check to make sure if any fields are marked "Share" the sharing consent element is included
* When viewing the application, the field automatically lists the fields that will be shared so the applicant knows when they are giving consent
* Upon conditions being met (ie when the application is screened), a notification goes out using the template, letting them know their application has been shared and that they can now view other applications.

cc @stuartmessenger and @scott-psycle. Would love to see y'all get cracking on this one and the dependency #1948. also @georgiamoon and/or anyone on your team who'd want to get involved on ui/ux.

**Comment by georgiamoon** [comment]
An idea here — perhaps the easiest way to approach this would be to introduce a new type of "reviewer" role and handle this as basically a stage progression or a special "fund" for both applications and users? 

Basically I'm thinking that you'd screen incoming applications and then move them into this "reviewer" pool OR move the applications (or a copy of the applications) to a fund and add the users as reviewers on that fund.

Does that make any sense as a potential approach?

Another idea would be to introduce a concept, e.g. groups or teams _(maybe this exists already, I'm not sure)_ and a group might have access to applications or rounds of funds, and potentially other features that you might want to be limited to specific groups.

**Comment by danblah** [comment]
@frjo, mvp:

* Create a new box on the right side called "Sharing"
* Add an option just like the flag options "Share with applicants" available to role team
* When checked, add applications to a list a submissions/shared
* Submissions/shared fields: Title, Name, Email (no links to application pages)
* Do not give applicants permission to view application pages.
* Add submissions/shared to submissions/ page, with a show all going to submissions/shared like all the others.

**Comment by georgiamoon** [comment]
@danblah coming back to this, I just almost pitched the same idea I wrote in May: https://github.com/OpenTechFund/hypha/issues/1934#issuecomment-627720080 of using a fund and a modified "Reviewer" role for this. Just flagging that that still feels like it'd potentially work for an MVP. I think you'd just need to basically duplicate the fields from the original applications into a new limited project pitch application form.

**Comment by fourthletter** [comment]
Group Settings in WagTail address this issue. These settings could be adjusted so applicants could access other applications and other data within the platform.

![image](https://user-images.githubusercontent.com/20019656/172020077-6cb47b1d-4a7a-4376-9a17-6d5fcf6b9fa2.png)
