### ISSUE TITLE
Proposed changes to reminder function

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1943]
Here are some refinements needed for the reminder function on applications.

* TIme, make the hh:mm:ss not required. If not set, default to 00:00:00 UTC.

Replace the actions drop-down with the following fields:
* Title: A required field. A plain-text field, max char of 60 chars.
* Assign: A required field. Options (multi-select): Applicant, Partners, Lead, Reviewers, Team.
* Description: Not-required field. A plain-text box.

Changes to notifications:

TBD

Later tasks:
* Ability to click a reminder in the reminders box and view/edit full reminder
* In the admin panel, a place to define default reminder templates that auto-populate the above fields
* A small/light buttons on the reminder interface to choose templates
* Allowing rich-text in the description field

**Comment by danblah** [comment]
@georgiamoon and @bumbleblue for ui/ux  thoughts.

**Comment by Parbhat** [comment]
@frjo Is this ready to work on? Or need UI/UX and requirements updates.

**Comment by bumbleblue** [comment]
I don't have data from the research on the reminder function, but I can second @danblah's suggestions. I would prioritize having default reminder templates (at all) over adding the admin interface for creating new templates.

Is the description field for finding the reminder ("full proposal late - first reminder") or the actual text in the email/notification ("Dear ..., We have not yet received you full proposal ..."). I haven't seen it in action yet!

**Comment by saoun** [comment]
@ei8fdb @bumbleblue are any of you working on this?

**Comment by fourthletter** [comment]
Please remove the **clock** from the reminder function. We only need the date. Thank you.

Program Managers are sending reminders to applicants regarding upcoming application deadlines and potentially setting reminders for other colleagues.

<img width="579" alt="Screen Shot 2021-04-23 at 1 49 42 PM" src="https://user-images.githubusercontent.com/20019656/115866992-c54abc80-a43a-11eb-9d46-e2fd99057bc8.png">

**Comment by ei8fdb** [comment]
We're closing this ticket as it is being handled in #2247
