### ISSUE TITLE
A single application with fields exposed at later stages of review workflow

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1951]
We'd like a single application to be completed at multiple stages of review workflow, rather than have multiple applications. On the public-facing apply page, we'd like a sub-set of specified fields to be visible (initially, those marked required). At a later stage, the applicant would have the ability to complete any remaining fields (initially, in any stage the submission workflows already allow them to edit).

Here's the proposed workflow:

1. Create an application, mark fields required
2. Edit/create a fund page.
3. In form declaration box (where it says Form and Stage), there is a new option "Minimize Form (or whatever)", Yes/No
4. If Yes, rendered form on public application form only displays Required fields
5. After submission, rendered application only displaces completed fields when viewed
6. Upon editing, all fields are available for editing and completion.

**Comment by Parbhat** [comment]
This will help to reduce the application form size significantly and less overwhelming for applicants. Is anyone working on it?

**Comment by frjo** [comment]
@Parbhat No one is working on this. We also have https://github.com/OpenTechFund/hypha/issues/1961 that also is ment to make the forms more manageable for users.

**Comment by Parbhat** [comment]
@frjo We will need more planning for #1961 from the implementation perspective. We will start with this issue.

**Comment by frjo** [comment]
This can be tested on test now, see more info at https://github.com/OpenTechFund/hypha/pull/2162

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Removed from milestones 'horizon 1' https://github.com/HyphaApp/hypha/milestone/24
* Removed priority needed label
* Removed open/close label
* Needs design QA review
* Added to forum post for Ideation meeting topics: https://we.hypha.app/t/candidate-topics-for-ideation-sessions-for-pinning/341
* Recommend review in Q2 rebasing for priority level.

* @frjo did this issue get done in part by OTF PR: https://github.com/OpenTechFund/hypha/pull/2162

**Comment by fourthletter** [comment]
This sounds like 'Group Fields' and related to #2378 
https://test-apply.opentech.fund/cpf-test-fund/

![image](https://user-images.githubusercontent.com/20019656/172020845-ddcd5a89-2f35-4636-9c17-62e3ba4e254d.png)

![image](https://user-images.githubusercontent.com/20019656/172020778-ee441bf4-1abd-404a-b1b7-8a2c5b77f332.png)
