### ISSUE TITLE
[Meta] Add the ability to split an application into multiple pages & conditionally direct a user to specific pages

### ISSUE THREAD

**Issue by georgiamoon** [HyphaApp/hypha#1961]
# Is your feature request related to an existing functionality? Please describe.

As part of the SimSec research on the application experience, we believe that it would be beneficial to be able to split the application into multiple pages and provide navigation to the user.

Closely linked to pagination is the ability to direct an applicant to different pages based on their answers to particular questions.

We're discussing both these functionalities in this meta issue as they are closely linked.

**Terminology**
There are many terms to describe conditional logic - the terms conditional logic, skip logic, and branching are interchangeable.

We'll try to use only **skip-logic**.

## Pagination
Pagination allows the form creator to break show the the application form is displayed to the applicant over multiple pages.

### Minimum viable product
Form creators (i.e. programme managers) need a way to:
- indicate where another page begins (this could be create page breaks in an application, similar to creating a section header)
- "move" questions from one page to another

When the applicant views this application:
- they navigate between sections
- the data they create needs to be stored (in the browser session or something along those lines) to make sure that the users doesn't lose data in the event of an Internet issue (e.g. low bandwidth situation or outage)

### Prior examples of pagination functionality
Most form creation software support pagination.

**Survey Monkey**
[Here's their documentation to adding pages](https://help.surveymonkey.com/articles/en_US/kb/Adding-and-Managing-Pages)

**CrowdSignal**
[Here's how Crowdsignal does pagination and moving questions](https://user-images.githubusercontent.com/1899506/118614990-32dad600-b7b8-11eb-94e8-43567809b2b4.mov) between pages. 

**Google Forms**
Here's [how Google Forms does it](https://user-images.githubusercontent.com/1899506/118615368-92d17c80-b7b8-11eb-9b93-c6de769e4f16.mov)

**Nextcloud Forms**
Here's a [similar discussion](https://github.com/nextcloud/forms/issues/357) for implentation of pagination.

## Skip-logic
Skip-logic allows the form creator to create branches where the applicant can be sent to different pages based on their answer to a question.

### Minimum viable product
When the Hypha form creator user creates the application form, they need a way to:
- choose which question is selected for skip-logic
- they could create a rule to direct an applicant to question located on a different page, based on how they interact with previous question

When the applicant views this application:
- depending on how they interact with the question they are directed to the next question, or to a specific question on a different page
- they are able to navigate forward and backward through the pages

Example of skip-logic form:
![image](https://user-images.githubusercontent.com/1899506/118633901-e0a2b080-b7c9-11eb-98b7-d9b5f7466ca4.png)

## Prior examples of skip-logic

**wagtail-advanced-form-builder**
There is a Wagtail module called ["wagtail-advanced-form-builder"](https://wagtail-advanced-form-builder.readthedocs.io/en/latest/). It contains skip-logic functionality. This module may be able to be reused. @frjo is investigating this.

**CrowdSignal**
Here's how Crowdsignal does skip-logic:
![image](https://user-images.githubusercontent.com/1899506/118634440-71798c00-b7ca-11eb-8357-9eb76ba57c97.png)

**Google Forms**
Here's how Google forms does skip-logic
![image](https://user-images.githubusercontent.com/1899506/118635084-1ac08200-b7cb-11eb-8add-4aa41bbd4407.png)

**SurveyMonkey**
Their [help documentation describes how skip-logic works](https://help.surveymonkey.com/articles/en_US/kb/What-is-Skip-Logic).

## Sub issues
These issues are for technical dscussion of implementation.

- Add pagination to application forms #2378
- Add conditional logic to application form creation [to be opened]

## Describe alternatives you've considered
This is a new idea, feedback/critique/comments/alternative ideas welcome!

**wagtail-advanced-form-builder**
There is a Wagtail module called ["wagtail-advanced-form-builder"](https://wagtail-advanced-form-builder.readthedocs.io/en/latest/). This module may be able to be reused. @frjo is investigating this.

## Additional context
Example from the wireframe:
<img width="772" alt="Screen Shot 2020-04-29 at 4 17 31 PM" src="https://user-images.githubusercontent.com/941210/80642752-fd403f00-8a34-11ea-9ecc-4cd62502cac8.png">

## Affected roles
- Staff
- Applicants

**Comment by frjo** [comment]
My suggestion would be to implement this in JavaScript.

The form would then in reality be one page as now but behave like a multipage form for the user.

A bit like the submission detail pages work today with the three tabs, "SUBMISSION DETAILS"
"COMMUNICATIONS" and "ACTIVITY FEED". That is really one page but it feels like three for the user.

**Comment by danblah** [comment]
Could we create a streamfield that would indicate the split?

**Comment by frjo** [comment]
A "split/break form" stream form would be needed so the staff can specify where the form should break.

@Parbhat What do you think would be the best solution?

**Comment by Parbhat** [comment]
JavaScript to handle the multi-step form in Frontend + A multi-step field in application forms streamfield to add step title and defines a break, looks like a good solution. It will help to not change anything in backend for the form submissions code and its side effects. And helps to retain the current standard form submission.

Wagtail docs also list one customization to create multi-step [forms](https://docs.wagtail.io/en/stable/reference/contrib/forms/customisation.html#multi-step-form) from standard Wagtail forms. It divides the form in the backend into steps with the help of paginator.

This issue is slightly related to the improve the file upload widget issue https://github.com/OpenTechFund/hypha/issues/1440. As it may change how the form submission works currently (standard way) or submitted via Ajax.

**Comment by bumbleblue** [comment]
Flagging that we'd love to have pagination for the review form as well!

**Comment by frjo** [comment]
The first part now has an issue #2378.

The second part about redirecting I do not know how to implement. The admin UI for it can easily become a UX mess.

**Comment by fourthletter** [comment]
@katiewilson21 thank you for [sharing your designs](https://www.figma.com/file/KfKVDbpRRofnu6CA8Wbk5V/Hypha-Pagination-%2B-Skip-Logic?node-id=0%3A1) with us. I'm adding @frjo in case there are any questions. 

Later this week I will share some example or potential application questions and forms we might create in the future based on pagination and skip logic. However, I think your design are great and don't want to delay the development of this github issue further.

**Comment by fourthletter** [comment]
Related to #2378
