### ISSUE TITLE
[Meta] Encryption at rest, how?

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#1966]
How could we do this in the core app? What recommendations do we have for implementations?

**Comment by danblah** [comment]
Bumping this.

**Comment by frjo** [comment]
I would have liked to use a transparent full db encryption but that feature is not implemented yet, do work are being done. See. https://wiki.postgresql.org/wiki/Transparent_Data_Encryption

The standard method seems to be to use PgCrypto and encrypt specific fields. The key would be stored as an environment variable in Heroku. 

The fields I believe OTF and Reset are mainly interested in are `form_date` field in tables like `funds_applicationform` and `review_review`. i.e. user submitted data.

@danblah Is that assumption correct, about the `form_date` field (user submitted data)? Anything else you really would like to have encrypted at rest.

@Parbhat Do you have experience using PgCrypto or another more suitable method? How hard/time consuming is it to implement?

**Comment by frjo** [comment]
https://github.com/dcwatson/django-pgcrypto

**Comment by Parbhat** [comment]
@frjo I have not used pgCrypto before. `django-pgcrypto` package seems good but does not support JsonField which is used for [form_data](https://github.com/OpenTechFund/hypha/blob/39d88dc5eca53164b4612111212db08aad961536/hypha/apply/funds/models/submissions.py#L417). So, the actual blockers will have to see during implementation.

**Comment by frjo** [comment]
See #2192

**Comment by frjo** [comment]
There is at least 6 fields that needs to be encrypted, likely more. Most of them are json fields.

I think this application really needs full db transparent encryption but that seems to be some time until postgres implement that. See https://wiki.postgresql.org/wiki/Transparent_Data_Encryption.

Amazon has there own implementation running ut then we are tied to AWS. I would really like to avoid that.

**Comment by fourthletter** [comment]
On June 6 FJ + DL discussed this is a difficult issue to tackle at this juncture. Closing this issue becuause it is an issue here https://github.com/HyphaApp/hypha/issues/2192
