### ISSUE TITLE
A way to accept extra submissions to a closed round

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#1970]
Staff from time to time needs to allow a submission to a closed round. An applicant had maybe really good reasons for being late and staff want to allow then to apply.

**Comment by fourthletter** [comment]
We currently use filters as a work around. For example, we reassign the 'Lead' because we can not reassign the 'round date' field. We use the filter to only include the 'Lead' we want.

**Comment by ei8fdb** [comment]
As there is no longer a hard closing date is this ticket still needed? @fourthletter @frjo? if not can it be closed?
