### ISSUE TITLE
Word limit error prevention

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#1988]
## Problem

There is no error message when the form can't submit if the user exceeds the word count in any question.

## Possible solution

Need UI element (warning message) to indicate that submission is impossible due to word limit.

**Priority**

- Medium

**Affected roles**

- Applicants

**Ideal deadline**

By June?

**Comment by frjo** [comment]
Exceeding the word limit to not stop people from submitting a form. The word limit is a soft one, it just display the earning, nothing else.

**Comment by ei8fdb** [comment]
We can close this as going over the word-limit does not stop the applicant from submitting.
