### ISSUE TITLE
Submit application even when applicant has exceeded word limits in narrative questions

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#1989]
Related to #577 and #1988 

## Issue

Exceeding the word limit should throw off a warning, but submission should still be possible.

## Possible implementations

Options:

1. Remove word limit requirement, i.e. exceeding word limit will throw off a warning, but applicants can submit with any word count.
2. Make it a "soft word limit": allow submission with 110% of the word limit, e.g. for a word limit of 600, allow all submission up to 660 words to account for special characters etc.

**Describe the solution you'd like**

OTF team prefers (2).

**Priority**

- Low priority

**Affected roles**

- Applicants
- Reviewers

**Ideal deadline**

By June

**Comment by frjo** [comment]
So a hard word limit, or at least the possibility of, is a feature request?

**Comment by bumbleblue** [comment]
I guess what I mean by "soft word limit" is communicating a word limit but allowing 10% leeway -- so yes, there is an actual word limit, just not the one that's on screen. Does that make sense?
