### ISSUE TITLE
Input field size should match word limit

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#1992]
The text input field smaller where the word limit is shorter, this would make it more indicative of the word limit.

Applies to application form, but potentially also review form.

**Priority**

- Low priority 

**Affected roles**

- Applicants
- Reviewers

**Ideal deadline**

By July

**Comment by ei8fdb** [comment]
@frjo is this possible to implement? This idea makes a lot of sense - the size of the input field gives the person an indication of how much they have to write.

The size of the field doesn't have to be exact, just an approximation.

**Comment by frjo** [comment]
Possible, but it would it would be far from exact since text size depends on font used, browser settings etc.

I would most likely make e.g. three fixed sizes and set these for different spans of allowed characters.

**Comment by fourthletter** [comment]
TinyMCE (WYSIWYG HTML editor) in rich fields increase the scope of this issue behind our current capacity.
