### ISSUE TITLE
Link or URL is not visible and accessible when added to website project page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2025]
On website's project pages, when you add a link to a website, it shows up as this inscrutable purple button with a Win95 mouse pointer, any way we can change that to something more noticeable, like the actual link? 

Example: https://www.opentech.fund/results/supported-projects/seaglass-imsi-catcher-detection-latin-america/

**Comment by frjo** [comment]
@fourthletter The Purple arrow icon is not that clear to me either. I would suggest a purple button that say "Homepage", "WWW" or something like that.

What do  @ei8fdb and @bumbleblue think?

**Comment by fourthletter** [comment]
I think nothing should be there since a link/url is already provided below the description. Another option is if the user can select the icon or image they prefer.

**Comment by frjo** [comment]
@fourthletter If you don't want a link to show up then just delete it. But the point of having the contact details in a separate field is that they will show up the same for all projects, consistency.

My suggestion is to delete the link at the end of the body and then we make the url look a way that you like in the contact details section.

https://apply.opentech.fund/admin/pages/802/edit/

**Comment by fourthletter** [comment]
The purple arrow is misleading and the heading title "Get the word out" does not indicate that the purple arrow will take you the project's website. The public is **consistently** confuse by this UI.

**Comment by frjo** [comment]
@fourthletter Then let the designers redesign it so it becomes good.
