### ISSUE TITLE
As a user reviewing an application, I want all links to youtube, twitter, and Instagram, etc to be replaced with privacy preserving links 

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2029]
see https://framagit.org/tom79/nitterizeme for an app based example....

Youtube –> Invidious
Twitter –> Nitter
Instagram –> Bibliogram

I do this now manually for all links. I'd like the app to render these links while preserving the original in the actual field.

**Comment by frjo** [comment]
I think a Javascript solution with a toggle button that is on by default for none applicants is the best solution. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>
