### ISSUE TITLE
Drag & Drop Text Snippets

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#2041]
### The problem

Determination messages take up a long time to write and are not standardized in content or tone across different round leads.

When round leads write a determination message, they often copy & paste standard texts from a shared document. This additional step can be frustrating and time-consuming.

These standard texts ("templates") could also be better grouped/tagged.

### Possible solution

An interface element that allows round leads to drag and drop standard texts and then edit them in the input interface.

![SOAR IFF Review Form (2)](https://user-images.githubusercontent.com/14316263/84179779-c3784480-aa86-11ea-9c1f-f85cf55bd900.jpg)

**Requirements**
- Drag and drop, perhaps preview of full-text upon hover
- Allows for some form of grouping (colors, dropdown filter etc.)
- Has to paste into input field and allow for editing

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Reviewers

**Ideal deadline**

New review and determination forms ship on July 1, but this doesn't need to be part of that release.

**Comment by bumbleblue** [comment]
(Just to be sure: this is only a murky idea, we think it could greatly benefit determination message writers, but want to hear what you all think!)

**Comment by fourthletter** [comment]
Related #2080 #721 #1948

**Comment by fourthletter** [comment]
@ei8fdb potentially applicable to your current work. Thanks!
