### ISSUE TITLE
Structured Questions in Determination Messages

### ISSUE THREAD

**Issue by bumbleblue** [HyphaApp/hypha#2042]
### The Problem

Round leads have to manage a lot of communications with applicants and reviewers, and it can be hard to track which questions have been answered and resolved, and which questions are still open.

### A Solution

Having a structured way to indicate, reference, and open/close questions in a "request for more information" would go towards streamlining internal discussions.

One UI possibility is the following.

![SOAR IFF Review Form (7)](https://user-images.githubusercontent.com/14316263/84181672-8c576280-aa89-11ea-9c90-47818984c070.jpg)

And as responses from applicants come in, it should be possible for round leads to mark a question as (e.g.)
* resolved/closed
* unresolved/open
* waiting for response [default state]

![SOAR IFF Review Form (6)](https://user-images.githubusercontent.com/14316263/84181606-73e74800-aa89-11ea-9307-04753e79329d.jpg)

**Requirements**

- Round leads have to be able to add many questions (at least up to 10)
- Questions should be numbered for future reference

**Open questions**

- Is it more like a GitHub issue (open/closed) or more like a Google Doc comment thread (resolved or unresolved)?
- Are questions anchored to the text in the application (think: editor flow, peer reviewing, Hypothes.is-style annotation) or are there general questions?
- Should their status be internal-only or also visible to the applicant?
- How to display the change history?

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers

**Ideal deadline**

New review and determination forms ship on July 1, but this doesn't need to be part of that release.

**Comment by bumbleblue** [comment]
This is a rough idea and I'm curious to hear if it could be useful for reviewers.

**Comment by saoun** [comment]
i like that a lot! thanks for putting this together.

**Comment by fourthletter** [comment]
Related to #711

**Comment by fourthletter** [comment]
Closing because related to https://github.com/HyphaApp/hypha/issues/2809
