### ISSUE TITLE
[Meta] Salesforce Integration for applicant lookup and Project management

### ISSUE THREAD

**Issue by maxpearl** [HyphaApp/hypha#2055]
This is an issue which will reference other specific issues related to Salesforce Integration.

First feature for Salesforce integration: Create a new opportunity in Salesforce based on a Project in Hypha. This requires:

- Adding django-salesforce to requirements 
- Including a Salesforce Database option in hypha/settings/base.py 
- Adding a SF integration setting in admin #2054 
- Add a model for opportunity in hypha/public/projects/models
- Creating a "create opportunity" button in Project view 
- Providing a "view opportunity" button in Project view if a matching opportunity has been created.

**Comment by frjo** [comment]
@maxpearl I have created a branch for this at https://github.com/OpenTechFund/hypha/tree/feature/salesforce-integration

**Comment by maxpearl** [comment]
First three of these handled by this pull request: https://github.com/OpenTechFund/hypha/pull/2056
