### ISSUE TITLE
Ability to perform a batch action on all matching applications, not just the current paged list (ie more than 25 shown applications)

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2106]
At the moment on submission all table, a max of 25 submissions is listed, there's a pager at the bottom.

If you want to do batch actiions, you can click top box - but only the first 25 will be batchable.

We want to be able to do it for all search results.

**Comment by ei8fdb** [comment]
@ei8fdb had a simple design for showing 

Show items per page: 25 | 50 | 100 | 200
