### ISSUE TITLE
Tasks needed when Hypha repo is moved to Hypha organisation

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2145]
- [x] Set up all needed access for developers and admins on new Hypha organisation.
- [x] Test instance on Heroku for main Hypha
- [x] Set up Hypha fork for OTF
- [x] OTF Heroku uses GitHub for deploys, need to relink
- [x] Make sure Circle CI work for both OTF Hypha and main Hypha
- [x] Slack integrations
- [x] Sentry integrations
- [x] Scout integrations
- [x] …
- [x] …
- [x] …

**Comment by frjo** [comment]
@saoun Is OTF on board with moving the Hypha repo to the Hypa.app organisation at https://github.com/HyphaApp/hypha ?

Moving the repo will also move all the issues etc. We would create a new OTF Hypha repo as a fork of https://github.com/HyphaApp/hypha, this is how Reset is set up.

**Comment by frjo** [comment]
We now have the all clear to do this. Will try to get it done next week.

**Comment by frjo** [comment]
@Parbhat Any input, things to be aware of, on this.

**Comment by Parbhat** [comment]
@frjo The list of updates looks good. I had a doubt about the forks from this project like Reset. Looked for it and it seems that forks are also associated with the new location.

>If the transferred repository has any forks, then those forks will remain associated with the repository after the transfer is complete. - [docs](https://docs.github.com/en/github/administering-a-repository/transferring-a-repository#whats-transferred-with-a-repository)

**Comment by frjo** [comment]
The repo is moved now. Working through the list of tasks above…
