### ISSUE TITLE
Screening applications in 3 panel view

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2158]
## What is this ticket about?
This ticket shows the design and interactions for a Hypha application review to carry out an application screening, in Hypha 3 panel view.

I'll tag @fourthletter, @danblah @saoun and @frjo first to start discussion.

## Related issues
#1948
#[2148](https://github.com/OpenTechFund/hypha/pull/2148) (PR)
#[2154](https://github.com/OpenTechFund/hypha/pull/2154) (PR)
#2080 

## Purpose of this view
Screening (potentially hundreds of) applications can take a lot of time. Because of this, its important that the user is able to screen these applications efficiently.

The user needs to:
- be able to review the answers to the most important questions
- be able to make annotation on application extracts 
- be able to quickly accept or reject an application
- be able to add optional reasons for their screening decision
- be able to move the application to the next stage of the process

## Designs
These wireframes show the designs and interactions involved in the screenign process. The notes in yellow are to communicate design reasons, or parts of the designs I think need more explanation.

In the design, I've included 2 terms - "Minimum" and "Stretch". Minimum means the minimum functionality that the user needs. Stretch means it'd be great if this functionality could be included, if there is time, etc. 
@frjo is that OK?

### How to get to the 3 panel view
![0  list view](https://user-images.githubusercontent.com/1899506/97863786-76c82b00-1cff-11eb-84a9-415eac78f824.png)

The table view is the current default view when a user chooses a fund ([example fund](https://test-apply.opentech.fund/apply/rounds/824/)). 

To get the 3 panel view, the user clicks on the 3 panel view icon on the right-hand-side. (This already exists)

### The 3 panel view for an application in screening
![1  review - application](https://user-images.githubusercontent.com/1899506/97862802-df160d00-1cfd-11eb-8b9a-27cf49c799a6.png)

This view shows the 3 panel view for an application in screening. Here the user reads the application, etc.

#### Minimum
[ ] the user can view the responses to the 4 questions:
- What problem will your project address? 
- How will you address this problem?
- Give a brief overview of the activities in this project.
- Who is the intended user of your project, and how will they benefit from it?

### Making an annotation
![2  snippet - highlight](https://user-images.githubusercontent.com/1899506/97862811-e210fd80-1cfd-11eb-94d0-63dfa3673654.png)

It is important for the uset to be able to make annotations about the application. How to make an annotation is explained here.

#### Minimum
[ ] The user is able to highlight a portion of the text and click a pop-up to create the note

#### Stretch
[ ] The "Screening reasons" show all the possible reasons - both In and Out, until the user chooses an option.

### Write annotation note
![3  snippet - saved (Alternate 177c)](https://user-images.githubusercontent.com/1899506/97862814-e3422a80-1cfd-11eb-96be-ef17b060871c.png)

When the user clicks `annotate` the right hand panel view changes to notes.  Here the user can write their annotation note.

### Multiple annotations 
![4  snippet - multiple snippets (Alternate 943b)](https://user-images.githubusercontent.com/1899506/97862820-e3422a80-1cfd-11eb-8187-387a62839d08.png)

It is common for users to be able to create multiple annotations. When the user views the notes tab, they will see all the notes created about that application there.

The notes will be organised in chronological order - newest to oldest. 

#### Minimum
[ ] the user can see all of there notes

#### Stretch:
[ ] If the user clicks on different notes in this view, the middle pane showing the application text will scroll to the location in the application showing that annotation. It would work like [this recording of how hypothes.is currently works](https://imgur.com/Fkep5ZF).
[ ] the user can see notes written by other users @fourthletter @danblah any thoughts on this?

### Final step - make screening decision and change application stage.
![5  review-screened in](https://user-images.githubusercontent.com/1899506/97862822-e3dac100-1cfd-11eb-9f4b-ca41c260ce88.png)

When the user has finally decided the screening outcome for this application, they can make ther screening decision. How to make the decision and assign screening decision reasons is explained here.

**Comment by sks444** [comment]
Defaults screening statuses are the texts which appears for thumbs up/down. And can be set for a submission by clicking on them. More context regarding this can be found at https://github.com/OpenTechFund/hypha/issues/1948 discussions.

- Should the defaults for yes/no screening statuses be changed **OR** Should they be constant and can only be set once for a project?
   - If yes, What should happen for the submission which has been screened by old default?
      - One idea is to get all those submissions and replace their default screening status set with the new one.

Note that if the defaults are not set: first screening statuses created for yes/no would be set as default.

---
One more point that I would like to discuss is: What should happen for the old submissions(submission which has been screened by old screening system):
 - When they have a screening status set which is not default. 
    - This already invalidates our validation of "Other statuses(reasons) can only be set after setting the default by thumbs..", so for these submissions, I believe it would be better to just the show the screening status without thumbs and not allow to change it.

@ei8fdb, @frjo, let me know your views on this.

**Comment by ei8fdb** [comment]
> Defaults screening statuses are the texts which appears for thumbs up/down. And can be set for a submission by clicking on them. More context regarding this can be found at #1948 discussions.
> 
>     * Should the defaults for yes/no screening statuses be changed **OR** Should they be constant and can only be set once for a project?

To make sure I understand your question:

You mention that screening statuses[already exist in #1948](https://user-images.githubusercontent.com/191392/96550603-5d5fc180-12b1-11eb-9fa7-899fff6934af.png)

Are you asking should these screening statuses be used where the wireframe says `screening reasons`?

If so, then yes you're right - they should be constant.

Does that answer your question?
       
>         * One idea is to get all those submissions and replace their default screening status set with the new one.

The ideal situation is that the screening statuses are configured [in the view mentioned](https://github.com/OpenTechFund/hypha/issues/1948#issuecomment-712645588) in #1948.

These screening statuses are then displayed in the "Screening reasons" part of the UI as shown above.  

> Note that if the defaults are not set: first screening statuses created for yes/no would be set as default.
> 
> One more point that I would like to discuss is: What should happen for the old submissions(submission which has been screened by old screening system):
>     * When they have a screening status set which is not default.
>      
>       * This already invalidates our validation of "Other statuses(reasons) can only be set after setting the default by thumbs..", so for these submissions, I believe it would be better to just the show the screening status without thumbs and not allow to change it.

I'm not sure I follow what you mean here. @sks444 would it help to have a quick call this morning? I am happy to.

(Also I will update these wireframes to make the labellign consistent - screening statuses, instead of screening reasons)

**Comment by frjo** [comment]
@sks444 Really good questions!
1. The default statuses should be able to change. The default is simple on of many screening statuses so if the default change it should not effect existing submission screening statuses I think.
2. I'm keen to make as little changes as possible to submissions that already have a final determination.
3. For current submission that still are being processed I see no problem migrating them from the old to the new default. We just need to inform OTF and Reset that this is how it's going to work.

**Comment by ei8fdb** [comment]
@sks444 @frjo 

For 1. above, just to confirm it will support this behaviour:

When the application is first viewed:
- no screening outcome is set
- no screening reasons are visible (i.e. blank)

When the user clicks `In`:
- the accept screening reasons are visible
- the user can click none/1/all of these reasons

If the user then clicks `Out`:
- the reject screening reasons are visible
- the user can click none/1/all of these reasons

(If possible: if the user had clicked any `accept` reasons they are "remembered" but "hidden")

The same applies vice-versa (if the user first clicks In, then Out).

Can you confirm that?

**Comment by sks444** [comment]
@ei8fdb, yes that is correct.

I think the only point that you're missing is, `In` and `Out` that you mentioned are also screening statuses. So they can be changed:

- Any number of screening statuses can be created from admin for both yes and no. And out of those, two screening statuses should be set as default. One is for `yes` and the other one is for `no`. Default `yes` screening status should be shown for thumbs up and the Default `no` should be set for thumbs down. (E.g. in the wireframes, the `In` and `Out` below the thumbs are the default screening statuses for yes and no.)
