### ISSUE TITLE
Add automation options within a fund to define conditions for automatic status changes

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2167]
Right now an application automatically moves from "External Review" to "Ready for discussion" after two reviews are submitted from Reviewers. Applications in the state "Ready for discussion" can not receive additional reviews. This is a system-wide behaviour. See https://github.com/OpenTechFund/hypha/issues/1096.

This is not ideal default behaviour for Reset. Reviewers who are excited to review a specific application within the deadline but after two others submit a review, can not submit a review :-/

On a fund-by-fund basis, I would like to define how many reviews and/or after how many days before an application transitions from "External Review" to "Ready for discussion". For example, managers should have the ability to transition applications automatically if: 
* 3 reviews were received or after 14 days from the time the application entered the "External Review" state
* only after 14 days from the time the application entered the "External Review" state, no matter how many reviews received

**Comment by fourthletter** [comment]
Related to #2516
