### ISSUE TITLE
Changes to Reviewer Settings and expected behavior 

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2168]
First off, this settings page is awesome... dunno how I missed it was there. Even so, the settings are a challenge to understand and not producing expected behaviour.

One misunderstanding I have just realized from https://github.com/OpenTechFund/hypha/issues/1182 is that the state "Dismissed" is considered higher than "External Review". As a result, an unintended outcome is reviewers have access to all applications once they have been dismissed, regardless of if the application was ever in the state "External review" or not. That would also mean these applications would list in submissions/all listing, also not intended.

With these settings:
* Submission: All Submissions
* State: Only External review or higher
* Outcome: All outcomes
* Assigned: Unchecked
* Use settings: Checked

I expect:
* If a submission has not been in the state "External review", no reviewer access, regardless of the state, regardless if assigned
* If a submission has been in the state "External review", yes reviewer access, regardless of the state, regardless if assigned

What's wrong with current behaviour:
* Reviewers have access to "Dismissed" applications that have never been in the state "External review".

How do we best get to the expected behaviour?

**Comment by Parbhat** [comment]
Good find, @sks444 can pick it next to have the desired behaviour.

**Comment by frjo** [comment]
@danblah The higher/lower concept for statuses is based on the order they are listed in the workflows. You see this order in e.g. the status bar above submissions on the submission detail page. Left/lower and right/higher. Lowest is draft and highest is accepted/dismissed.

@Parbhat @sks444  I do not think the system has any concept of status history. I think we might in the future use the existens of external reviews as a marker. If a submission have external reviews then it will be considered to have been in "external review". Using “has been in external review status” seems fragil, what if the status was set by mistake.

**Comment by Parbhat** [comment]
@frjo Yeah, we need to track changes to the status field. Or we can simply have a check to not show dismissed submissions to reviewers. Along with checking if the reviewer has also submitted the review. If only state check is required ("External review") then we need to track the changes made to status field.

**Comment by sks444** [comment]
@frjo, for now only solution that I can think of is adding another option in the `Outcome`: `All outcomes except dismissed`. Should I go-ahed with that?

**Comment by frjo** [comment]
@sks444 Yes, please do.

For the next step I think we should check if a submission has one or more reviews by external reviewers (none staff) and if it has we consider it to have been in "external review". What do you think about that approach?

**Comment by sks444** [comment]
@frjo, approach sounds good.

Although there may come some submissions which have been in external review but didn't get any reviews from external reviewers? I guess we can accept that edge case to solve this problem and not list those submissions at `/submissions/all`?

**Comment by sks444** [comment]
There is also a [package](https://github.com/gizmag/django-fsm-log) to track status history for the [FSMField](https://github.com/OpenTechFund/hypha/blob/345f3ab782e08d86dc1c0fa2d428a345926182bf/hypha/apply/funds/models/submissions.py#L454). But I think we can neglect that considering following scenario:
 > Using “has been in external review status” seems fragil, what if the status was set by mistake.

This is very valid argument as the status history will define the access permission of a submission. And if it is set by mistake then that is a problem.

Considering this scenario, edge case at https://github.com/OpenTechFund/hypha/issues/2168#issuecomment-735569834 can also be ignored at some level. So it seems https://github.com/OpenTechFund/hypha/issues/2168#issuecomment-734734060 is the best possible approach.

**Comment by fourthletter** [comment]
## Description

As a manager I need to add 'only External review' as an option to State field in  EDITING Reviewer Settings to limit the Reviewer group's access to applications they have submitted a review for. 

Active users in the Reviewer group will have limited access to applications they have reviewed. We will have a process to share information with this group.

![Screenshot 2022-04-11 11 23 37 AM](https://user-images.githubusercontent.com/20019656/162710593-f658a3c2-921f-4337-87ca-1c4cf2dd2431.png)
