### ISSUE TITLE
Encrypt sensitive fields in db

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2192]
List of fields that most likely need encryption:

* activity_message.content
* application_projects_project.form_data
* application_projects_project.form_data.contact_address
* determinations_determination.form_data
* funds_applicationsubmission.form_data
* review_review.form_data

Possible to make the encryption optional? This would, I assume, be something a new organisation need to decide on setting the system up.

Encryption is a hassel and some organisation might not want to deal with it.

**Comment by wes-otf** [comment]
Closing via the discussion in #4075.
