### ISSUE TITLE
Changes/enhancements to the all submissions react page

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2203]
- [x] In the middle pane, show the top of the application, when selecting a new application in the left pane. Right now, I have to scroll back to the top because the position is carried over from where ever I left off in the previous application.
- [x] Change the title in the middle pane to be the actual title of the application, right now it says "RequestExt Information"
- [x] Ability to view/edit/add staff and individual flags
- [ ] If a screening status has already been set, show the sub reasons and collapse all other available screening reasons underneath. Only show them all expanded when none are set.
- [x] Ability to view/edit/add meta terms
- [x] Ability to adjust the 3-panes and show/hide collapse/expand the right and left ones fully
- [ ] Ability to show/hide the filters bar while preserving set filters
- [x] Ability to show/hide all of the top headers/banners to maximize reading space in the window
- [ ] An indication that a new note has been posted that the user hasn't seen/viewed yet
- [x] Keyboard shortcut that allows the user to move to the next application or go back to the previous application
- [x] Ability to set reminders
- [x] Ability to share the current filtered view with others (ie copy a link and send it so they see what I see)
- [x] Ability to change top-level screening status w/o undoing any of the sub/reasons first. Right now I have to unselect any reasons before I can change it from Not Competitive to Competitive.
- [ ] Ability to bookmark my progress reading through a list of applications, so I can come back to it
- [x] Possible to make the right-side panel load faster? Why does it take a second?
- [x] Ability to filter applications based staff or user flag
- [x] Ability to filter for applications that have no screening status set
- [x] Ability to filter by a category question (from dev call)
- [x] When I set a filter for more than 1 round and for a screening term, I get "No submissions available". What I expect is to see is a list of submissions from all those rounds that have those screening terms set. If I select a single round, I do see a list of all submissions in that round with that screening term.
- [x] Bold the text on the selected top-level screening term to better indicate it is selected (ie bold Competitive)

 

@frjo and @Parbhat, can y'all make individual issues for all of these and update this issue with links to said issue as you create them. I'll keep adding more here as they come to me.

**Comment by fourthletter** [comment]
An indication that a new note has been posted that the user hasn't seen/viewed yet (related to #2225 #2161 because it's providing users with additional information within the Hypha)

**Comment by fourthletter** [comment]
Closing this issue because a vast majority of the react page has been created and is functional.
