### ISSUE TITLE
Ability to filter by staff and personal flags in the submissions all page

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2215]
Description:
I need to share it and do something about this later designed to work similarly to flagging email in an email client

Pupose for the flags:
Staff can add a flag to the application, and at later stage discuss them together in a meeting

This shoud work in both
- [ ]  react
- [ ] non-react interface

Design:
- move the for me/staff flgas in the same UI element
- filter position

**Comment by fourthletter** [comment]
Related to #2221 and #2104
