### ISSUE TITLE
Staff flag requires two clicks to undo and undo isn't actually undoing

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2221]
I have to hit the staff flag button twice for the UI to indicate it has been removed. Upon reload of the page, the flag is back to set :-)

I'll share a gif privately to show.

**Comment by ei8fdb** [comment]
Does this apply to hypha-core as well?

**Comment by fourthletter** [comment]
Program Managers are currently not using this feature. Related to #2215 #2104

**Comment by frjo** [comment]
I can not reproduce this unfortunately.
