### ISSUE TITLE
Automatically generate summary text for an application

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2222]
MVP
Find a maintained python/django library that already exists
Create an able to be enabled function to pre-fill the upcoming summary field with this library

Additional features
Ability to specify which fields should be used to generate a summary
Ability to specify a summary max length
Ability to edit, remove, and regenerate a summary

**Comment by danblah** [comment]
Alternatively, just build in support for https://quillbot.com/apiaccess... thoughts?

**Comment by Parbhat** [comment]
Using a good third party tool to summarize will be quick. We will look into the options once the summary field is created in #2214

**Comment by ei8fdb** [comment]
Some questions for discussion:

- What fields should be used for this summary?

**Comment by fourthletter** [comment]
Related to https://github.com/HyphaApp/hypha/issues/2214

https://user-images.githubusercontent.com/4817493/113407864-d79d8180-93cb-11eb-9f39-7e8b4627b964.mov
