### ISSUE TITLE
What task based views of submissions is needed and what should they show?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2224]
The submission/all table is getting overloaded. Can we instead of adding things to it create a number of task based views?

Each view could then show just the info needed for that task and have the filters needed making it faster and easier to use.

When switching between the views the filtering should be remembered. Even when filtering on items that do not exist on all views. When applying new filters on a view it's ok that the filtering on non existing items are lost.

**Comment by frjo** [comment]
@Parbhat Is it feasible to maintain filtering when switching from a Django view to a react view?

**Comment by Parbhat** [comment]
By task based views, do you mean seperate Django views? Can you also give an example of task? Not sure if I get it correctly.

@vimal1083 will look into feasibility of maintaining filtering between Django and React app if same filters exist at both places. I think the issue may be different set of filters in Django views and React app.

**Comment by fourthletter** [comment]
Closing because related to filters https://github.com/HyphaApp/hypha/issues/2501
