### ISSUE TITLE
How to best show notification in the app?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2225]
## Summary
We now send e-mail notifications to applicants and reviewers, and Slack notifications to staff.

## Suggestion
Add in app notifications would allow users to see the info in the app as well without the need to dig through Slack/e-mail.

A view that list the logged in users notification would be a good start.

Having a read state for the notification in app would be nice.

## Associated notification issues
[User notification(slack/email?) on invoice transition in finance flow](https://github.com/HyphaApp/hypha/issues/2704)

**Comment by Parbhat** [comment]
It will be good to have in-app notifications. It will be a new feature with a model named Notification and code to handle actions.

**Comment by fourthletter** [comment]
Related to #2161

**Comment by fourthletter** [comment]
related to #2161

**Comment by ei8fdb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Hypha notifications](https://trello.com/c/If6nzQ59/21-hypha-notifications)

**Comment by fourthletter** [comment]
Closing because of new epic https://github.com/HyphaApp/hypha/issues/2812
