### ISSUE TITLE
Make React app filter do OR instead of AND search

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2238]
This filter should work the same in the:
- [x] React app (#2203)
- [x] Django app.

When filtering for e.g. to funds or two leads etc. you get "No submissions available".

We would like the filter to find e.g. all submission that belong to any of the funds selected.

**Comment by sandeepsajan0** [comment]
@frjo Is something pending in this issue? I think it should have fixed with PR #2519.
