### ISSUE TITLE
Make it possible to set reminders in the React app

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2247]
Make it possible to set reminders for the PM and applicant to action some task.

The reminder is sent by email, default at a time the system chooses.

Related #2203

**Comment by fourthletter** [comment]
Is this reminder feature related to  #1943 ? Thanks.

**Comment by Parbhat** [comment]
@vimal1083 This PR #1865 adds reminder support on the submission detail page. Issue #1943 proposed some changes to it. While implementing it in React app (3-panel view), you can take these into consideration.
