### ISSUE TITLE
Automatically create new rounds

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2259]
For rounds with end dates, create a new duplicate round automatically if none exist.

1. When should the round be created? The day before the end date?
2. Can we look at the current rounds start and end date and take the same numbers of days for the new round?

**Comment by danblah** [comment]
Could the round be created upon the close of the current round? 
1. Round goes to close, checks fund if auto-create flag exists
2. If exists, run function to create new round, wait for confirmation that the new round was created successfully
3. If success, close round

Could we add a round duration into the fund settings?

**Comment by fourthletter** [comment]
related to #2160

**Comment by fourthletter** [comment]
Thank you for creating this issue. We are considering a different approach.
