### ISSUE TITLE
Rebuild the submission/all table in React

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2265]

**Comment by frjo** [comment]
@Parbhat How much work would this be?

We would like it to look more or less the same but be a Reast app, then when you switch to the three panel view the filters can be maintained easily etc.

**Comment by Parbhat** [comment]
@frjo Do you mean the Django Table view with django-filters on All submissions? The requirement is to convert this to a React view.


<img width="1262" alt="Screen Shot 2021-03-03 at 2 50 52 PM" src="https://user-images.githubusercontent.com/4817493/109783330-e27bbf80-7c2f-11eb-93c5-0328f9903027.png">

**Comment by frjo** [comment]
@Parbhat Yes. The toggle that now switch between a Django Table view and a React view would then switch between two React views instead.

I assume this would make it possible to have the same filters on both and keep the filtered state when switching between them.

The batch functionality is maybe hard to do in React? We could, at least initially, keep the Django Table for that task.

(I do not think we should actually delete the Django Table view, just move it to another URL for now.)

**Comment by Parbhat** [comment]
Sounds good. The implementation should not take more time as we already have all submissions listing in React 3 column app. And filters are working on it.

We should look into the permission side also as currently React app is only for admin. But the all submissions django table is for staff and reviewers. We can also have it currently for admin only. And also look into the possibility of opening React app to other user groups.

**Comment by frjo** [comment]
We kan keep React staff only for now, while keeping in mind that in the future some more permission will likely be needed.

We keep the Django Table view for other users for now.
