### ISSUE TITLE
Different review forms for staff and reviewers

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2273]
### Description 

There is currently one review form associated with one proposal. We need separate review forms, one for staff reviewers and another for external reviewers. 

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by ei8fdb** [comment]
@fourthletter Right now, are the Community prototype fund, Community Lab, IFF review forms the same or different? i.e. do they ask the same questions?

**Comment by fourthletter** [comment]
@ei8fdb We plan to have different proposal questions for digital sec, research, CPF, CL, and IFF. These different proposal question may necessitate different review form questions.

**Comment by ei8fdb** [comment]
Understood! 👍 

A few thoughts on how to handle this:

### Use 1 review form, with sections for each category
- the questions that apply to all categories are displayed by default
- have a section for each category
- reviewers "ignore" the sections that don't apply to the application 

### Create separate review forms for each category

My suggestion is to wait until after the next time the fund opens to see if the review form needs to be changed/adapted.

**Comment by fourthletter** [comment]
I agree with your suggested next steps. This issue could be divided into two different issues within github. 

1st issue: UX/Design for 1 review form, with sections for each category - Sim Sec?

2nd issue: Create separate review forms for each category - will #2277 & #2276 impact the design and code for review forms?

**Comment by fourthletter** [comment]
This issue will become moot if we can complete #1961

**Comment by fourthletter** [comment]
@frjo I'm lifting up this issue again. We created a unique AC review form that is more specific and better align with External Reviewers' expertise. It would be helpful if AC receive their own review forms rather than completing Team/Staff review forms.

**Comment by fourthletter** [comment]
carried over from https://github.com/HyphaApp/hypha/discussions/2277#discussion-3250469


Applicants can then be invited to do a proposal in any of the existing funds

This would be used for OTFs "one button" workflow.

This discussion was created after a call about possible future complexity in Wagtail/Hypha with the move from funds to categories.

Issue
The issue seems to be that Wagtail and Hypha was built on the idea of having FUNDS and ROUNDS. Now that the multiple funds are being replaced by 1 FUND and multiple CATEGORIES, this could cause complexity in Hyph if others are using FUNDS and ROUNDS instead of 1 FUND and multiple CATEGORIES.

Proposal
If we had conditional logic working in Wagtail forms, this would mean OTF can use 1 fund and multiple categories model while keeping within the fund and round model. See below:

![110305156-546b5480-7ff4-11eb-8985-5062422a63c0](https://user-images.githubusercontent.com/20019656/140509820-73d6ab03-d8dc-4a21-b2e2-b80bf3d9e0cd.jpg)

**Comment by frjo** [comment]
From standup 2022-05-17:

1. On Wagtail Admin Fund form rename "Review forms" to "Internal Review forms".
2. Add section to set "External review forms". Not required. If not set use forms from "Internal Review forms".
3. "External review forms" are only relevant to some workflows but no harm if they are set in any case so we can ignore that for now.

**Comment by fourthletter** [comment]
I'm currently not able to edit external review forms

Here is the Fund on test: https://test-apply.hypha.app/admin/pages/933/edit/?next=/admin/funds/round/%3Fform-state%3Dopen%26o%3D-3

![image](https://user-images.githubusercontent.com/20019656/170003232-52763369-1639-4c87-a081-23d4ef5081c4.png)

**Comment by frjo** [comment]
@fourthletter  You are on a Round, you need to go to the Fund and add a external review form first.

**Comment by fourthletter** [comment]
Thank you all! This works. 💥
