### ISSUE TITLE
Stop making "project duration" field required by Wagtail system

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2274]
Right now the Wagtail system enforces the "project duration" field to be incuded (along with application title, applicant name, and applicant email address).

If a user tried to create a form, and does not add this field, their work cannot be saved.

It is possible that the way the project duration question is asked in the future will need to be changed, so we're making this field no longer a Wagatil system enforced required field.

**Comment by fourthletter** [comment]
I tested, but the concept note won't save https://test-apply.opentech.fund/admin/funds/applicationform/edit/23/


<img width="1046" alt="Screen Shot 2021-04-12 at 7 25 01 PM" src="https://user-images.githubusercontent.com/20019656/114435730-c8d17e80-9bc4-11eb-8111-fac0ec130b73.png">

**Comment by frjo** [comment]
Thanks for the report, must have missed a part of the code. Will fix that and then we can retest.

**Comment by frjo** [comment]
@fourthletter Please try on the new Hypha test site instead. It has the test, content and the same user accounts etc.

https://test-apply.hypha.app/admin/funds/applicationform/edit/23/

I will specify the test address clearly moving forward.

**Comment by fourthletter** [comment]
@frjo Thank you, please release it. I no longer have the administrative access to change the labels.

**Comment by frjo** [comment]
This is now on test again.

**Comment by fourthletter** [comment]
I was able to delete the duration field from forms. Works great!
