### ISSUE TITLE
Automatically add Wagtail system required field when creating new application forms

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2275]
### What is the background for this ticket?
Hypha needs a number of fields to be present in each application form created in Wagtail. These will be applicant email address and applicant name. Without these fields the form cannot function. This is for historial reasons.

While Wagtail does provide some explanation that these fields are required, it is not also seen by users, leading to a usability issue. Especially new users. If users do not know these fields are required by the system, and they do not add them, they will be unable to save their work, meaning wasted time.

After a discussion with Bernard, Fredrik and Di, the decision has been made that these 2 fields are added to any new application form automatically by the system. This will make it clearer that these fields are required to be included.

### Proposed UI design
When the user creates a new application form instead of seeing UI elements to add the required fields, displayed like this:

![image](https://user-images.githubusercontent.com/1899506/110130135-9ca23100-7dc0-11eb-8f23-4af2347d0014.png)

they see them already included in the form, with sample Label and Help text, as shown below:

![image](https://user-images.githubusercontent.com/1899506/110131474-138bf980-7dc2-11eb-8401-5e131342449d.png)

### Feedback
@frjo @fourthletter has this captured our discussion correctly?

**Comment by fourthletter** [comment]
related to #2460
