### ISSUE TITLE
[Meta] Ability to mark data sensitive or private and hide it from views and users

### ISSUE THREAD

**Issue by saoun** [HyphaApp/hypha#2292]
With the current access, AC members can view the entire application that they are assigned to. 

I would like to remove PII form their view. As in, hide:
- telephone number
- email
- address
- legal name, when there is a redundancy between a person's name (to be removed) and an organization's name

This is an effort to increase privacy and security, and protect applicant information.

**Comment by saoun** [comment]
Not sure if this is something  you are also interested in @danblah

**Comment by fourthletter** [comment]
Relate to #1863

**Comment by danblah** [comment]
I've "meta'd" this issue, making it a little more encompassing.

I think this covers this as well: https://github.com/HyphaApp/hypha/issues/2361

@ei8fdb and @katiewilson21 can y'all scope out and work with @frjo to make issues for these:

* Ability to hide specific fields from AC members
* Ability to hide specific fields from staff as well

**Comment by fourthletter** [comment]
Closing this issue because I created a new issue here Remove PII from AC view #2482
