### ISSUE TITLE
Add setting to turn on/off the "invited to proposal" e-mail to applications

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2302]

**Comment by fourthletter** [comment]
Thank you!

**Comment by fourthletter** [comment]
Our preference would be to have a single email.  But If that is not possible or tough we need to distinguish the two emails: 1) We are inviting you to start you proposal, 2) directing applicant to OTF's determination

**Automated Email**
- remove or delete the "You can find more information about we we'd like to see in your proposal here:" 
- Add a line saying "you will receive a second email linking to a determination message with detailed feedback"

**Manual Determination**
- Remove portion of the determination
- Only show "the outcome is approved" and "Read the full determination here"

**Comment by frjo** [comment]
This is the template for the invite for proposal e-mail, what would you like to change? (I have already removed the "more info" line).

~~~~
{% block content %}We’ve reviewed your Concept note and think it could be a good fit for {{ ORG_SHORT_NAME }} funding. We would like to invite you to submit a Proposal with more details about your project.

The system will allow you to save a draft of your Proposal as you work on it. When you feel it is ready for our review, please click the “Submit” button and we’ll know to take a look at it. We’ll reply to you with feedback on your Proposal as quickly as possible.{% endblock %}

{% block more_info %}
Here is the link to start creating your proposal: {{ request.scheme }}://{{ request.get_host }}{{ source.get_absolute_url }}
If you have any questions, please submit them here: {{ request.scheme }}://{{ request.get_host }}{{ source.get_absolute_url }}#communications

Link to our guide: {{ ORG_GUIDE_URL }}

If you have any issues accessing the submission system or other general inquiries, please email us at {{ ORG_EMAIL }}
{% endblock %}
~~~~

**Comment by fourthletter** [comment]
> ```
> {% block content %}
> We’ve reviewed your Concept note and think it could be a good fit for {{ ORG_SHORT_NAME }} funding. We would like to invite you to submit a proposal with more details about your project. You will receive a second email linking to a determination message with detailed feedback. 
> 
> The system will allow you to save a draft of your proposal as you work on it. When you feel it is ready for our review, please click the “Submit” button and we’ll know to take a look at it. We’ll reply to you with feedback on your Proposal as quickly as possible.
> {% endblock %}
> 
> {% block more_info %}
> Here is the link to start creating your proposal: {{ request.scheme }}://{{ request.get_host }}{{ source.get_absolute_url }}
> If you have any questions, please submit them here: {{ request.scheme }}://{{ request.get_host }}{{ source.get_absolute_url }}#communications
> 
> Link to our guide: {{ ORG_GUIDE_URL }}
> 
> If you have any issues accessing the submission system or other general inquiries, please email us at {{ ORG_EMAIL }}
> {% endblock %}
> ```

**Comment by frjo** [comment]
The determination message part in the determination e-mail is from a specific field. If you do not want to have a message simply do not add anything to this field.

**Comment by fourthletter** [comment]
Let me elaborate further. 

In regards to the manual determination/Email 2, if possible please remove the portion that displays the **text of the determination** so that the email basically is just, "The outcome is approved" and "Read the full determination here"

I think we decided to not include determination text in emails because of data privacy concerns.

**Comment by frjo** [comment]
The only field that is included in the e-mail is the determination message. That is what the field is for. So if you do not want any extra text in the e-mail leave that field blank and only fill in the other fields.
