### ISSUE TITLE
Provide way to share files between successful funding applicants and organisation 

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2327]
**Is your feature request related to an existing functionality? Please describe.**
When an application has gone through application and review stages, but a grant agreement/contract has not yet been signed, there is often a need for the applicant to share documentation with the funder, and vice-versa.

This request is to provide a way for this exchange to happen within the Hypha webapp.

**Describe the solution you'd like**
It would work as follows:

1. The applicant is able to login to their account, navigate to their project, and upload documents for their funding point of contact. They can add a short description to each document. (e.g. "our certificate showing our official status as an NGO"). The point of contact then receives a notifcation saying there are documents waiting for them.

2. The funding point of contact can login to their account, navigate to the project they are managing/responsible for, and upload documents for the project contact. They can add a short description to each document. (e.g. "W9 tax form to be completed"). The project contact then receives a notifcation saying there are documents waiting for them.

**Describe alternatives you've considered**
Currently this happens in email, signal, other communicatins tools, dropbox, file cloud sharing which can be insecure, lead to unintended leakage information, and is another thing to manage and secure.

**Additional context**
This request came from an Hypha user during a research interview.

**Is this a common need?**
Based on research with other funding organisations, I think this is a common request.

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Applicants

**Ideal deadline**
Cannot say.

**Comment by fourthletter** [comment]
Related to #2365?

**Comment by fourthletter** [comment]
Related https://github.com/HyphaApp/hypha/issues/2634

Applicants are currently able to upload and save documents and files in the Project Page for contracting.

**Comment by fourthletter** [comment]
Related to #2492
