### ISSUE TITLE
Create a funding recommendation summary for funding decision makers

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2328]
**Is your feature request related to an existing functionality? Please describe.**
In a funding process where the Final Funding Decision is made by a designated group of people, there is a need to provide them with a summary of applications and a way to make a their decision.

**Describe the solution you'd like**
Provide a way to create and share:
1. an overall summary of applications
  - this could be (in beginning) free-text input field 
2. different combinations of applications to be funded
  - this could be organised by e.g. theme 
3. each application including
  - funding recommendation (Y, N)
  - budget information
  - funding amount requested
  - reviewer assessments
  - a link to the full application, and each review step
4. the reviewer could then make their decision - I agree / I don't agree.
5. the reviewer can then add a short note explaining their decision (optional)

**Describe alternatives you've considered**
Creating and sharing a document/email with each of 1, 2, 3 included manually.

**Additional context**
This request came from an Hypha user during a research interview. I'm not sure if this funding workflow is currently fully supported in Hypha. I think not. @danblah? 

**Is this a common need?**
I am unsure if this is a common need, but it is similar to @danblah's request for creating a summary list of applications for the Reset advisory panel.

The main difference is, in the case of this request - there is a need for this group to be able to record their decision I agree / I don't agree (with the funding recommendation).

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Reviewers

**Comment by danblah** [comment]
Related #2214 and #2222

**Comment by frjo** [comment]
A summary field is already implemented in the React app. It will be added to the Django side as well.

**Comment by fourthletter** [comment]
Related to https://github.com/OpenTechFund/apply-app/issues/3 and https://github.com/OpenTechFund/apply-app/issues/57

**Comment by fourthletter** [comment]
Related to #2214

**Comment by fourthletter** [comment]
This issue sounds like designing an 'output' that is easy to read and exported from Hypha. The main goal and similar objectives of this issue already exist in other issues.
