### ISSUE TITLE
Duration Bug on Form

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2341]
IFF concept notes, they all say "1 day" "7 days" etc but it seems off/doesn't align with the concept note description. If an applicant does not answer the question, the default answer appears on the application. 

**As a reviewer, this information should not appear on the application because it does not align with what the applicant has intended to submit.** 

<img width="718" alt="Screen Shot 2021-04-21 at 9 52 25 AM" src="https://user-images.githubusercontent.com/20019656/115517324-51b47e00-a287-11eb-838c-95b98f41c43f.png">

**Comment by frjo** [comment]
Until we can make the duration field optional there is no fix for this.
