### ISSUE TITLE
Upload button does not like me

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2342]
(\__/) 
(•ㅅ•) 
/ 　 づ🐞 

I regret to inform you that I found a bug in the upload button that appears sometimes. Perhaps during a full moon?

**Describe the bug**

An error message appears when the **applicant** attempts to upload a document to their proposal.

**To Reproduce**

1. Go to a proposal
2. Click on 'upload'
3. See error

**Expected behavior**

The error message should not appear when the user upload a document.

**Priority**

- High (keeping you from completing day-to-day tasks)

<img width="931" alt="Screen Shot 2021-04-06 at 12 23 26 PM" src="https://user-images.githubusercontent.com/20019656/115524525-8546d680-a28e-11eb-8608-8ffcb1843531.png">

**Comment by ei8fdb** [comment]
What are the steps to replicate this issue @fourthletter?

**Comment by vimal1083** [comment]
@fourthletter couldn't reproduce the issue in test site. Could you share the django log If you get the error in your live site?

**Comment by fourthletter** [comment]
@vimal1083 Please let me know if you have other questions. I don't see it in the django log, here is my Chrome browser log (`Version 90.0.4430.85 (Official Build) (x86_64) `):
```
DevTools failed to load SourceMap: Could not load content for https://apply.opentech.fund/static/tinymce/js/tinymce/skins/lightgray/skin.min.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE
file_form.3305d00fcaaf.js:7 PATCH https://apply.opentech.fund/upload/upload/06d4f8af-424a-4069-9257-18a603c431b6 410
(anonymous) @ file_form.3305d00fcaaf.js:7
value @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
Promise.then (async)
zp @ file_form.3305d00fcaaf.js:7
value @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
Promise.then (async)
value @ file_form.3305d00fcaaf.js:7
value @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
Promise.then (async)
value @ file_form.3305d00fcaaf.js:7
value @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
Promise.then (async)
value @ file_form.3305d00fcaaf.js:7
value @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
l @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
ha @ file_form.3305d00fcaaf.js:1
a @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
l @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
ha @ file_form.3305d00fcaaf.js:1
a @ file_form.3305d00fcaaf.js:1
Promise.then (async)
ha @ file_form.3305d00fcaaf.js:1
a @ file_form.3305d00fcaaf.js:1
Promise.then (async)
ha @ file_form.3305d00fcaaf.js:1
a @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:1
(anonymous) @ file_form.3305d00fcaaf.js:7
(anonymous) @ file_form.3305d00fcaaf.js:7
c @ rocket-loader.min.js:1
```


<img width="1232" alt="Screen Shot 2021-04-28 at 10 13 04 AM" src="https://user-images.githubusercontent.com/20019656/116370343-96ea2a00-a80a-11eb-9f7d-eb7a775d14d9.png">

**Comment by vimal1083** [comment]
@fourthletter 

Most probably there is an issue in the cloudfare CDN where we upload the files. Kindly open the server django log, at the same time try upload a file in the application. you would see some error log, post that log here.

**Comment by Parbhat** [comment]
@frjo Can you please take a look into the bug if it is reproducible?

**Comment by fourthletter** [comment]
@frjo I created this just for you. @Parbhat I hope things are well with you and your team.

https://user-images.githubusercontent.com/20019656/118459372-fd70b280-b6fb-11eb-91e0-2e3489ebe4d0.mp4

**Comment by Parbhat** [comment]
@fourthletter Are you experiencing it on live or test site?

I and my team are safe from the second wave till now. Hope things become better soon. Thanks.

**Comment by fourthletter** [comment]
@Parbhat I'm glad to hear you are safe. I'm only experiencing this error on the live site because it's a database issue https://github.com/HyphaApp/hypha/issues/2342#issuecomment-828287804

**Comment by fourthletter** [comment]
This is a not an upload issue, this is a UI issue. The upload button is able to successfully upload a document, but the UI presents the message 'Upload fail' in red. I'm closing this issue because it's related to #2462
