### ISSUE TITLE
Timestamp for Upload Documents

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2344]
Please add a timestamp (a date and time0 next to each document uploaded to the application. As a manager, I would like to know when these documents were uploaded.

**Comment by ei8fdb** [comment]
- The timestamp could be prepended to the filename. 
- When the user uploaded it, they would see the prepended timestamp on the filename in the UI.

### Questions
- @fourthletter - what timestamp should be used for the time portion of stamp?
  - If there is no preference it should probably be UTC?
  - Or possibly the time of the user's computer? There's a possibility for leaking of information about the users location. Is this a risk?

### Design
In this example, the applicant has uploaded 2 files - `sample.pdf` and `sample.doc`.
When they upload the files, the filename is prepended with the date and time of when they uploaded them. 

![image](https://user-images.githubusercontent.com/1899506/116228282-fd107780-a74c-11eb-982e-5b83d5e055fb.png)

**Comment by Parbhat** [comment]
@ei8fdb Is this issue ready for development?

**Comment by ei8fdb** [comment]
> @ei8fdb Is this issue ready for development?

Lemme check with Di.

**Comment by fourthletter** [comment]
@Parbhat It's ready for development. Please reach out if you have any questions. Is it possible to have only the 'date' and exclude the 'time'? I'm also fine with keep both the date & time if that is easier. Thanks.

**Comment by Parbhat** [comment]
A quick question: Do we need to only show timestamp (separately next to the filename mentioned in issue [description](https://github.com/HyphaApp/hypha/issues/2344#issue-863607198)) while checking the submission Or add to filename as well as mentioned in https://github.com/HyphaApp/hypha/issues/2344#issuecomment-827506249? Yeah, we can only show the date and exclude time. Thanks.

**Comment by fourthletter** [comment]
@Parbhat Please add to filename as mentioned in #2344 (comment). Thank you!

**Comment by Parbhat** [comment]
Sounds good, thanks.
