### ISSUE TITLE
[PATCH] Update wiki for recent move of hypha repository (from OpenTechFund -> HyphaApp organization).

### ISSUE THREAD

**Issue by kfogel** [HyphaApp/hypha#2345]
A bunch of links in the wiki associated with this repository are currently broken because they still point at the old OpenTechFund `hypha` repository URL, and that now redirects to the OpenTechFund `apply-app` repository, which doesn't have any associated wiki content.

I've prepared [a commit that fixes all those links](https://github.com/OpenTechStrategies/hypha-wiki/commit/0935ac11bb6bc35243afa6c1fd0241950e3dfef7).  I can't submit it as a PR, because there's no way to submit a PR against a GitHub wiki, but the commit should be easily mergeable.  I just cloned the wiki repository, created branch `updates/adjust-for-repository-move` (from the latest commit, f99895fd0747a, on `master`), and put the commit on the new branch.

**Comment by frjo** [comment]
@kfogel Excellent, will get that merged in.

**Comment by kfogel** [comment]
Great; thanks, @frjo.

**Comment by frjo** [comment]
Done

**Comment by kfogel** [comment]
Whups, [one more commit](https://github.com/OpenTechStrategies/hypha-wiki/commit/0d7f9bab51eed8aeccaab8c142d184782f2e85d2) to complete the link updates in the wiki, @frjo.

(These involved a slightly different set of transformations; sorry for not catching them the first time around.)

**Comment by frjo** [comment]
Done, thanks!
