### ISSUE TITLE
Fund manager wants to know applicants post-application experience

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2349]
As a fund manager I want to know an applicants post-application experience.

### Questions for implementation
- what topics do you want to learn about?
- should it be sent to all applicants? A sample?
- can be it localised?

When a funding applicant has received their final funding request answer (be it positive or negative), automatically send them a survey asking for the overall experience. 

Connected to this closed ticket: https://github.com/HyphaApp/hypha/issues/835

**Comment by fourthletter** [comment]
@ei8fdb Please feel free to edit this [draft survey](https://docs.google.com/document/d/1tLvzigd0X4U6qPN3HiIql4n9Cpc_aLKJ2JklRzaZrsc/edit)

**Comment by fourthletter** [comment]
@ei8fdb The survey is still available to applicants after they've submitted a concept note. Should we take it down? Replace it with a different survey? Thanks, D

<img width="1011" alt="Screen Shot 2021-06-30 at 2 44 40 PM" src="https://user-images.githubusercontent.com/20019656/123962397-b5f36c80-d9b1-11eb-8117-d4c2d627e2eb.png">

**Comment by ei8fdb** [comment]
Oh yes please do take it down @fourthletter. Apologies I should have taken that down. About putting up a new survey, I can't say. Do you think one is needed?

**Comment by fourthletter** [comment]
I took down the survey. There's no need to apologize, hope you got what you needed from the survey. 

I do not see a need for launching another survey at this time.
