### ISSUE TITLE
[Meta] Ability for funded project to submit invoice and have it paid

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2352]
## User story
As a funded project leader, I want to get paid for work done as part of my project, so that I can pay bills, employees, etc."

## Description
When a successfully funded project ("project") has finished a portion of the work agreed, they need to be able to submit a request to get paid, the programme manager and finance accountant need to approve the invoice, and the accountant then needs to pay the invoice.

This meta story will focus on the minimum viable product of a **fixed price contract**. Other contracts will be added later.

## Process

**Declining invoice**
[Only PMs ](https://github.com/HyphaApp/hypha/issues/2704#issuecomment-1033547205)can decline invoices

## Associated stories
These associated stories are needed:

1. The project leader provides funder with contract, tax and banking information (#2379)
2. The contractor needs to submit a fixed price project invoice (#2354)
3. Create a new "Finance" user role with their own Hypha view (#2389)
4. Create files tab view for finance user in hypha (#2414)
5. The Programme Manager needs to approve the fixed price invoice (#2383)
6. Finance level 1 user needs to approve a fixed-price invoice (#2444)
7. PM can request modifications to fixed-price invoice (#2453)
8. Finance level 1 can request modifications to a fixed-price invoice (#2454)
9. Finance level 2  can request modifications to a fixed-price invoice (#2457)
10. Add Finance level 2 user ()
11. Finance level 2 user can review and approve a fixed-price invoice. (#2445)
12. The contractor can modify a fixed-price invoice (#2619)

## Priority
- High (keeping you from completing day-to-day tasks)

## Affected roles
- Staff
- Applicants

## Ideal deadline
Approx. June 2021

**Comment by sks444** [comment]
@ei8fdb, Do we have an issue created for task number 12: The contractor can modify a fixed-price invoice ?

**Comment by ei8fdb** [comment]
@sks444 I have missed a design for case. Apologies. I am working on it at the moment. I'll upload it and tag you here.

**Comment by sks444** [comment]
No problem. I was searching for the issue and was just confirming. Thanks!

**Comment by ei8fdb** [comment]
> No problem. I was searching for the issue and was just confirming. Thanks!

I'm almost finished this. One question for you - on standup this morning when you did the screenshare - did I see that when the contractor uploads the PDF, you are showing it to them embedded? Am I right? I want to know so I can show that in the design. If you're not showing them the embedded PDF, no problem. Just to check.

**Comment by sks444** [comment]
While creating/editing the invoice we are not showing the embedded pdf. That is just when you view the invoice..i.e Invoice detail page.

**Comment by ei8fdb** [comment]
@sks444 There you go: https://github.com/HyphaApp/hypha/issues/2619

Any questions, please just ask. 😄
