### ISSUE TITLE
Update project invoicing

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2354]
This story is part of epic #2352.

## User Story

> As a funded project leader, I want to submit an invoice for my fixed-price contract project, so that I can receive payment.

### Demo
**NB:** This demo needs to be updated with new designs. This simple demo explains how the contractor would create and submit an invoice request. 
https://user-images.githubusercontent.com/1899506/121354966-b14a1400-c92f-11eb-89e9-54c97e172026.mp4

#### 2.1
When the contractor wants to submit an invoice they will log into Hypha, and go to their in-progress project.
This contractor is working on the Maya Summit Project. They want to add an invoice so they click on Add invoice. This starts the invoice creation process. 

![](https://share.balsamiq.com/c/aNNmk6DEXYQsAxRVBwLRy.png)

#### 2.2 
They have to add the required dates, invoice amount, and the currency. Right now we are only required to support US Dollars, but in the future possibly other.
![](https://share.balsamiq.com/c/kKVoQtdcFXpFEnbSTumxm9.png)

#### 2.3
They upload the invoice file - which must be a pdf.
![](https://share.balsamiq.com/c/hA2szjufg9SZxBoWC1XtDY.png)

#### 2.4
Then the contractor can add the supporting documents, these are files that are related to the invoice. They could be xls, microsoft office documents, open office documents, pdfs, txt files. They can add multiple files. They can delete each file if they need to.
![](https://share.balsamiq.com/c/ur7Q4jczSbgqHKxfD93x9X.png)

#### 2.5
The contractor can add an optional note to the invoice. When they are ready they can submit the invoice. 
![](https://share.balsamiq.com/c/u3NeST3DRUvjtJ7jyTVjd1.png)

#### 2.6  
When the invoice is successfully submitted, they can confirmation it’s submitted.
From here they can go back to the project detailed view.
![](https://share.balsamiq.com/c/wSCaiSq6wPT3fvbtEp71TE.png)

#### 2.7
On the project detailed view, they can see the submitted invoice.
![](https://share.balsamiq.com/c/9iXvv6Tr1ya7BwvYfDE7ri.png)

**Minimum-viable story**

This minimum viable story works for OTF's instance, and for Hypha-core. For the fixed-price contract the project needs to submit the following minimum information:

- date from covered in the payment request
- date to covered in the payment request
- the total amount of money requested (in dollars)
- upload multiple files (spreadsheet, pdf, doc, txt file, png, jpg)
  - this is to provide files for 1) their invoice, and 2) the evidence the work has been completed
- free text comment

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants

**Ideal deadline**

Approx. June 2021

**Comment by sks444** [comment]
@frjo, this looks like a good task to start with after vendor setup.

Working on this would automatically solve https://github.com/HyphaApp/hypha/issues/2400. We can add/remove/rename anything that is required from `Payment Requests` to have the new `Invoice` workflow that is mentioned in the design.

**Comment by sks444** [comment]
@ei8fdb, thanks for the detailed issue descriptions, design and the video!

I have a few doubts related to deliverables:

I think we will be storing deliverables in Hypha as well?

Is the Amount(third field in the invoice form) suppose to be sum of all deliverables price?

Is it possible to add invoice without adding deliverables?

As mentioned, deliverables would be predefined list coming from IntAcct. What would happen for an organization not using IntAcct?

Given that Hypha payment system should be working irrespective of organisation using Hypha has integrated a third party payment system.

**Comment by ei8fdb** [comment]
> @ei8fdb, thanks for the detailed issue descriptions, design and the video!

You're most welcome! :)

> I have a few doubts related to deliverables:
> 
> I think we will be storing deliverables in Hypha as well?

Are you referring to what I said at 2:24 ("these come from Intacct"?). I think it's better to ask @frjo for a more definitive answer. (My understanding is that yes the deliverables will be stored/cached in Hypha as well but **please** check with @frjo about the technical details.)

> Is the Amount(third field in the invoice form) suppose to be sum of all deliverables price?

You mean this:
![Screenshot 2021-07-01 at 13 28 14](https://user-images.githubusercontent.com/1899506/124117328-498b7280-da70-11eb-8f93-e4d5e6a5c690.png)

Yes your right - this is the invoice total amount  - sum of all deliverables price. My sums do not add up, my mistake! It should be $3,500.00.

> Is it possible to add invoice without adding deliverables?

I got final answer - the contractor does not need to choose the deliverables - I need to update the designs and the video to reflect this.


~~Good question. I have 1 answer from the programme manager who says without the deliverables they cannot review the invoice. I am waiting for the finance user to reply. (My _guess_ is that should not be possible. i.e. to submit an invoice the contractor needs to choose at least 1 deliverable.)~~

> As mentioned, deliverables would be predefined list coming from IntAcct. What would happen for an organization not using IntAcct?
> Given that Hypha payment system should be working irrespective of organisation using Hypha has integrated a third party payment system.

This is another good question! If an organisation is using a finance system (Intacct, Quickbooks, etc) then the deliverables come from there.

If they are not, then I am not sure.

Just as a suggestion: the deliverables are written into a contract, and uploaded to Hypha (as happens now). Once the finance work is finished, the next piece of work is to work on the contract creation phase, and how those deliverables are added to the contract. Maybe they could come from there?

@frjo do you have some suggestions?


Do my answers help with your questions? If you have others @sks444 let me know.

**Comment by sks444** [comment]
Thanks @ei8fdb!

>I got final answer - the contractor does not need to choose the deliverables - I need to update the designs and the video to reflect this.

Sure. Let me know when the design has been updated will plan the implementation accordingly.

>Just as a suggestion: the deliverables are written into a contract, and uploaded to Hypha (as happens now). Once the finance work is finished, the next piece of work is to work on the contract creation phase, and how those deliverables are added to the contract. Maybe they could come from there?

Sounds good.

**Comment by frjo** [comment]
@sks444 You can simply scrap the deliverables section (Invoice items) from the invoice creation step.

The deliverables will be added by staff/pm when they review/approve the invoice.

**Comment by sks444** [comment]
Thanks @frjo, I will start working on this then!

**Comment by ei8fdb** [comment]
> Sure. Let me know when the design has been updated will plan the implementation accordingly.

@sks444 [Designs above](https://github.com/HyphaApp/hypha/issues/2354#issue-875399090) updated. Any questions please ask.

**Comment by sks444** [comment]
@ei8fdb, with Payment requests we had something called `payment receipts`, so user can upload multiple receipts for that request.

with Invoice, is that also being handled with `Supporting Documents`?

**Comment by frjo** [comment]
@sks444 "Supporting Documents" is just a renamed "Payment receipts".

**Comment by fourthletter** [comment]
QA
- [x] date from covered in the payment request
- [x] date to covered in the payment request
- [x] the total amount of money requested (in dollars)
- [ ] upload multiple files (spreadsheet, pdf, doc, txt file, png, jpg). This is to provide files for 1) their invoice, and 2) the evidence the work has been completed
- [x] free text comment

1) The upload multiple files button has a bug. As a user I would like to delete the file I've uploaded. I am currently unable to delete the file I want.

![Kapture 2021-10-15 Project Page Multiple Files](https://user-images.githubusercontent.com/20019656/137457155-c743164e-13a9-411b-9986-a470fe240c59.gif)

2) Text entered into 'free text comment' does not render or stored in Hypha
