### ISSUE TITLE
[Meta] Ability for a manager and applicant to share an application with other external people

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2365]
Ability to create a unique link for the application w/o any of the internal details exposed
Ability to email / export a pdf of the application to someone

Related to #289

**Comment by fourthletter** [comment]
Related #1934 

Feature already exists in the Projects page [Simplify Project Page #1399](https://github.com/HyphaApp/hypha/issues/1399) (closed issue)

Example

![Screenshot 2022-06-04 7 27 19 PM](https://user-images.githubusercontent.com/20019656/172018685-d5cb617d-b965-4283-b2bf-70790e0a4c54.png)
