### ISSUE TITLE
Programme manager approves submitted contractor fixed-price invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2383]
## Additional context
This is part of epic #2352.

## User story
> As a programme manager I need a way to approve a contarctors invoice, so that the accountant can then review the invoice.

## Describe the solution you'd like in Hypha
In Hypha the Programme Manager needs to:
- view uploaded invoice file
- view uploaded report (optional)
- approve the invoice

## Notifications
When the PM approves the invoice the:
- contractor gets notified the invoice is approved by PM
- finance gets notified that a new invoice needs to be reviewed
- invoice gets sent to Intacct

### UI Demo
**NB:** This demo video needs to be updated to new designs based on change of scope.
  
https://user-images.githubusercontent.com/1899506/125267614-4792a080-e307-11eb-8c1d-7a63241f44f1.mp4

### UI Wireframes

**3.1**
![3 1](https://share.balsamiq.com/c/7Yy7Z8PkS5E3r6NUK4CA2i.png)

The PM logs in and see the list of invoices to be reviewed. **By default** the table is filtered to show the invoices for PM review.

In this case the PM chooses to review “Invoice HP-000-079" for the SPAAAM project.

**3.1 unfiltered**
![3 1 unfiltered](https://share.balsamiq.com/c/gGoE6jVt2wPHuymppT75W5.png)

If the PM wants to see *all* invoices they can cilck on show all - this will unfilter the table. 

**3.2**
![](https://share.balsamiq.com/c/vTmyz296FazBgnjwDzXYy9.png)

Invoice reference Maya Summit (58) is opened. The invoice file - which is a PDF - is embedded in the page so the PM doesn’t have to download the file, and open it in a PDF viewer.

However if the PM wants to open the invoice in a separate window they can - they click on “open invoice in new window”. This can be used if there is an issue with displaying the invoice in the window.

They then review the invoice. If everything is in order, the PM can choose which deliverables this invoice covers under the “Actions to take” column.

**3.3**
![](https://share.balsamiq.com/c/faMGzRJdonsrvYBbCsnpwJ.png)

If everything is OK with the invoice, the PM then clicks “Update invoice status”. This then opens the modal Update invoice status. 

**3.4**
![](https://share.balsamiq.com/c/nXn6E8dRepuEjANyupKTZW.png)

From here they choose “approved by staff”. The finance related approvals are unavailable to them as they do not have those permissions. The other options available are “Request changes” or “Declined”.

**3.11**
![](https://share.balsamiq.com/c/ppfeNYLfKubX5JYp4bTZok.png)

The invoice is now approved so it is not displayed in the invoices to be reviewed table. If the user clicked on “Show all invoices” they’d see it there, along with all other invoices. 

## Priority
- High (keeping you from completing day-to-day tasks)

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

**Comment by sks444** [comment]
Thanks for designs @ei8fdb!

As submitting an invoice is now done and deployed on testing. https://github.com/HyphaApp/hypha/issues/2354

This looks like good issue to start with next.

@frjo @ei8fdb, are the design final for this issue? I see, it is dependent on deliverables, but that was scrapped in https://github.com/HyphaApp/hypha/issues/2354#issuecomment-872785656; Do we need implement the deliverables creation process before this?

**Comment by ei8fdb** [comment]
> @frjo @ei8fdb, are the design final for this issue? I see, it is dependent on deliverables, but that was scrapped in [#2354 (comment)](https://github.com/HyphaApp/hypha/issues/2354#issuecomment-872785656); 

Hiya @sks444 You're right it is dependent on deliverables.

 The **contractor** adding the deliverables In #2354 was scrapped in favour of the programme manager adding the deliverables when they review the invoice.

> Do we need implement the deliverables creation process before this?

I guess so, but I'll defer to @frjo.

**Comment by frjo** [comment]
@ei8fdb @sks444 The deliverables are essential for OTF so yes I think these should be implemented first. This brings us to the API calls for IntAcct. https://github.com/HyphaApp/hypha/issues/2409

**Comment by sks444** [comment]
Thanks @frjo, @ei8fdb

So when we have IntAcct integration the deliverables will be fetched from there..and stored in Hypha. 

We would need a db model with name and price to store all deliverables for a project..then from that list we can choose a few to add on an invoice.

Would be good to have a form where PM can add deliverables manually for a project in case third party payment integration is not there.

@frjo @ei8fdb, what do you think? Could you shed some light on the design of that form and where would it belong? Thank you.

**Comment by frjo** [comment]
@sks444 I do not think the deliverables are useful without a finance system integration. My first thought was that they would simply never show up unless you had an API call to fetch them from somewhere.

@ei8fdb Do you now how the other organisations using Hypha thinks about this?

**Comment by frjo** [comment]
@sks444 In my scenario only a the id of the selected deliverables would need to be stored with the invoice, and sent with the API call that created an invoice in the finance system.

**Comment by sks444** [comment]
>@sks444 I do not think the deliverables are useful without a finance system integration. My first thought was that they would simply never show up unless you had an API call to fetch them from somewhere.


@frjo, In that case, the deliverables would have to be optional, to be able to approve an invoice for an organization not using them/have not integrated a payment system from where they can be fetched.

**Comment by sks444** [comment]
>@sks444 In my scenario only a the id of the selected deliverables would need to be stored with the invoice, and sent with the API call that created an invoice in the finance system.

@frjo, As in the design we would need to show more details for the list of deliverables when choosing them on an Invoice(I.e. name and price).

Storing just an id would require us to make api calls directly on user interaction.

**Comment by frjo** [comment]
@sks444 If we store more than the ID we need to sync the info if/when it's updated in IntAcct. Viewing invoices is not done often and only by a few people. I think doing an API call every time is ok.

Or maybe some type of "cache" layer? If the "cache" is > 1h (or something like that) we do an API call otherwise use the values from the "cache".

**Comment by sks444** [comment]
Thanks @frjo. Caching layer sounds good. It should also be generally implemented when we communicate with third party systems to get/update data. We might be using the same concept at other places.

>@ei8fdb Do you now how the other organisations using Hypha thinks about this?

Let me know, when there is an update on this. Until then I will test things out with dummy deliverables manually added to db.

**Comment by frjo** [comment]
@sks444 Lets go with the assumption that deliverables are only interesting when an API for them exist. If there is none, do not expose them at all.

If it turns out I'm wrong we can deal with that later.

**Comment by sks444** [comment]
@frjo, https://github.com/HyphaApp/hypha/pull/2556 adds the feature to add deliverables on an invoice. Some styling and cleanup needs to be done but this will help in starting the work on SageIntAcct Integration.

We can deploy it to test for feedback. 

Deliverables on a project needs to be added from Django shell for testing: 
```python
project = Project.objects.get(id=project_id)

Deliverable.objects.create(name='Deliverable 1', available_to_invoice=1, unit_price=8000, project=project)
Deliverable.objects.create(name='Deliverable 2', available_to_invoice=5, unit_price=8000, project=project)
Deliverable.objects.create(name='Deliverable 3', available_to_invoice=2, unit_price=8000, project=project)
Deliverable.objects.create(name='Deliverable 4', available_to_invoice=1, unit_price=8000, project=project)
```

**Comment by fourthletter** [comment]
QA

The PM logs in and see the list of invoices to be reviewed:
- [x] submitted and the date it was submitted
- [x] invoice requested payment amount 

Add Invoice:
- [x] drop-down contains all the deliverables the contractor can invoice
- [x] PM can add as many deliverables as is relevant. 
- [x] PM can use the “remove” link.
- [x] open invoice in new window 

I found a minor issue with the deliverables drop-down. Attempting to add the SAME deliverable twice creates an error message. (cc: @ei8fdb )

![Kapture 2021-10-15 at 11 58 17](https://user-images.githubusercontent.com/20019656/137470060-5ea73c68-9b89-4a3c-8f06-cd1fc4a58475.gif)

**Comment by sks444** [comment]
@fourthletter, I assumed, invoice can't have the same deliverables twice. That basically means updating the quantity of an existing deliverable. Which means quantity of the deliverable added earlier was incorrect. In that case we can remove and add that deliverable again with correct quantity.

OR we can also update the quantity of that deliverable internally without raising the error. Let me know if you'd like me to implement that.

**Comment by frjo** [comment]
Deliverables removed but otherwise nothing changes.

**Comment by Erioldoesdesign** [comment]
@frjo is deliverables as a whole not being developed for the finance work then?

**Comment by frjo** [comment]
@Erioldoesdesign It is put on ice for now. Big part of it is already inte the code but does not look like it is going to be used until later on.

**Comment by ei8fdb** [comment]
@fourthletter we need to review the dashboard for this user:

**3.1**
![3 1](https://share.balsamiq.com/c/7Yy7Z8PkS5E3r6NUK4CA2i.png)

**By default** the table is filtered to show the invoices for PM review.

**3.1 unfiltered**
![3 1 unfiltered](https://share.balsamiq.com/c/gGoE6jVt2wPHuymppT75W5.png)
