### ISSUE TITLE
Statuses filter in All Submissions has an error

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2392]
**Describe the bug**

When a manager use a filter on 'All Submissions' they expect to narrow down or hone in on a particular item from the filter. When they select the 'Status' filter, they should be able to filter down to one of the items on the list like 'External Review.' This only occurs when I use 'Statuses,' other filters are working.

I am reporting that selecting ANY status in the 'Statuses' filter will yield no results. 

**To Reproduce**

1. Go to https://test-apply.hypha.app/apply/submissions/
2. Click on 'Filter' and go to 'Statuses'
3. Select any option in the 'Statuses' filter

**Expected behavior**

A manager should be able to narrow down or hone in on the specific items from the list. I used other filters and they work.

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff

**Screenshots**
get the 🍿 , I have video evidence!

https://user-images.githubusercontent.com/20019656/119603409-67b8df80-bded-11eb-82eb-ccf6f35524d0.mp4

**Desktop (please complete the following information):**

 - Browser: Chrome 
 - Version 90.0.4430.85

**Additional context**

I tested this on the live site and the test site. This bug appears in both sits.

**Comment by frjo** [comment]
The query seems to get mangels for status:

`WHERE (NOT ("funds_applicationsubmission"."status" = 'draft') AND NOT ("funds_applicationsubmission"."next_id" IS NOT NULL) AND "funds_applicationsubmission"."page_id" = 224 AND "funds_applicationsubmission"."status" IN ('d', 'i', 's', 'm', 'e')) `

This is search for status "Dismissed"

**Comment by frjo** [comment]
@Parbhat Can you please take a look at this. Sometime ago this filter broke.
