### ISSUE TITLE
Successfully funded projects want the ability for multiple accounts to access their project area.

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2396]
When a project is successfully funded, they will need to start providing legal or contractual information, submitting invoices, and other things.

Some organisations will have dedicated people for these tasks - e.g. a finance person who will submit the invoices/provides banking information, a legal or admin person who will post information important for contracts.

As a result, it would be helpful for projects to be able to have multiple users access project area in Hypha, so that the person responsible for those tasks can complete them.

The responsibilities are at least: 
- finance
- project progress

As we are implementing the finance workflow for OTF, we should investigate how multiple user accounts could be added to the project area to carry out certain tasks.

**Is your feature request related to a problem? Please describe.**

It is related to the finance workflow.

**Describe the solution you'd like**

Give permissions to a user account to view all/part of the funded project area. They would have permissions to carry out certain tasks - e.g. create invoices.

**Describe alternatives you've considered**

The only workaround is to share the details of the account that created the project during the application submission process. This is not a good practice.

**Priority**

- Medium (slowing you down)
- Low priority (annoying, would be nice to not see)

**Affected roles**

- Applicants

**Comment by frjo** [comment]
We have "Partner" user role who's users can be attached to submission and then receive the same permissions as applicants. This can be extended to Projects, if that is not already so.

**Comment by fourthletter** [comment]
I agree with @frjo suggestion. 

- [ ] Allow the contractor/vendor/applicant to add partners to their submission/funded project page
- [ ] Allow partners to create their own user account?
- [ ] Partner is able to see the funded project or application on their dashboard, etc (similar to AC reviewers)
- [ ] List all partners or collaborators in the selection box (similar to AC reviewers)
- [ ] Allow OTF staff or contractor/vendor the ability to remove partners 

The user interface for this functionality needs a refresh. It will also become more difficult in the future to search and select the correct individual from an increasingly long list of vendors/contractors marked as 'Partner' once we implement the Projects page. 

<img width="575" alt="Screen Shot 2021-10-01 at 5 58 44 PM" src="https://user-images.githubusercontent.com/20019656/135651477-a1334cd1-4255-4e1b-86b1-55004b18beb0.png">
