### ISSUE TITLE
Update invoice table on dashboard and add a invoice/all page

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2399]
An invoice table exist on staff dashboard. We want to change the columns a bit according to the designs below.

This table will be used on the new finance dashboard as well.

I think it would be good to add an invoice/all page as well. Similar to how we have a submission/all page.

A "Show all" linking the invoice table on dashboard would take user to it. Likely not used often but good to have this option. Same columns etc as on dashboard but with some filtering.

**Comment by fourthletter** [comment]
@frjo Redesigning invoice dashboards on the project's page is a great idea. I will add this to next year's scope of work/design & development roadmap.
