### ISSUE TITLE
Pipeline workflow tests-be failing on main branch

### ISSUE THREAD

**Issue by sks444** [HyphaApp/hypha#2403]
Noticed it on https://github.com/HyphaApp/hypha/pull/2402: [build log](https://app.circleci.com/pipelines/github/HyphaApp/hypha/1854/workflows/3d55869e-835c-40c3-8bef-40ceb643ee52/jobs/11134)

Then tried building the pipeline against main branch just to confirm and it failed there as well: [build log](https://app.circleci.com/pipelines/github/HyphaApp/hypha/1850/workflows/e9160236-645c-42f5-9eef-29c0a96997d0/jobs/11141).

cc: @frjo

**Comment by frjo** [comment]
@sks444 Good catch!

I just run all the test in my local setup and there I see no errors.

**Comment by sks444** [comment]
@frjo, yes, this seems like a problem with python itself. https://bugs.python.org/issue44061

Let me take it ahead.
