### ISSUE TITLE
IntAcct API information

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2409]
https://developer.intacct.com/api/

Here are some question I have asked and gotten answers for.

### Vendor:
 
1. _Does the vendor object in IntAcct have fields for banking information? Even international versions with IBAN etc?_ Yes, Vendor records have banking information fields. I don’t believe international banking information fields are available but could be added as custom fields. Below are the standard ACH fields.

![Unknown](https://user-images.githubusercontent.com/191392/120601169-e810bd80-c449-11eb-921a-13b8579e567a.jpeg)

2. _If Hypha create a vendor object in IntAcct and gets an OK response. Is it safe for us to delete the information in Hypha and rely on it being in IntAcct? We will most likely only save sensitive information like bank accounts temporarily in Hypha._ Yes, once a vendor record is added, it will not be deleted unless a delete API call is made or a user manually deletes the record.
3. _Can Hypha ask IntAcct if a vendor has a contract or not? The plan is to via a cron job update vendor status in Hypha (maybe twice daily)._ Yes, you would use the “List Purchasing Transactions” API call and set the filter to be the vendor ID: https://developer.intacct.com/api/purchasing/purchasing-transactions/#list-purchasing-transactions
 
 
### Invoices:
 
1. _Is it possible for Hypha to ask IntAcct for all deliverables belonging to all contracts of a specific vendor? OR do we need to make call for each contract?_ Yes, you can get all purchasing transaction lines for all contracts belonging to a vendor using this API call: https://developer.intacct.com/api/purchasing/purchasing-transactions/#list-purchasing-transaction-lines
2. _Can we add one or more of these deliverables when we create an invoice from Hypha in IntAcct?_ Yes, you can add multiple lines per purchasing transaction.
3. _Can Hypha update an already created invoice in IntAcct?_ Yes, you would want to update the purchasing transaction. Here is the update call: https://developer.intacct.com/api/purchasing/purchasing-transactions/#update-purchasing-transaction-legacy
4. _Does the invoice become locked when it has been approved/paid or do we need to handle that scenario in Hypha?_ Once an invoice has been approved, it can be edited before payment however would require re-approval. Once an invoice has been paid, coding can be reclassified but amount may not be changed. Once a period is closed reclassification cannot occur nor can the invoice be edited unless the period is re-opened.
5. _Can we attach a PDF to an invoice created from Hypha in IntAcct?_ Yes, however if the attachment is in Hypha and will remain there then most integrations utilize a custom link back to the source document. In order to create an attachment in Intacct the file’s binary data must be Base64 encoded. More information on the dev site: https://developer.intacct.com/api/company-console/attachments/#create-attachment-legacy (Edit: Hypha will most likely keep the files and only add links to them in IntAcct)
6. _If Hypha updates an IntAcct invoice and has a new PDF file can it overwrite the existing PDF?_ You would have to first delete the existing attachment then use the above create call to replace.
7. _Can we have one or two link fields on an IntAcct invoice so Hypha can send along links back to the Hypha project and a link to the original invoice (if we can't save that in  IntAcct, see 4.)_ Yes, we can add custom link fields on the Intacct purchasing invoice.
8. _Can Hypha ask IntAcct about invoice status? What status are available? We plan to update invoice status in Hypha via a cron job (maybe twice daily)._ Yes, you would use the “List Purchasing Transactions” call and request the field: STATE. The available values for purchasing transaction state are: S for Submitted, A for Approved, X for Partially Approved, R for Declined, I for Draft, O for Pending, D for Closed, G for In Progress, C for Converted, P for Partially Converted. https://developer.intacct.com/api/purchasing/purchasing-transactions/#list-purchasing-transactions
9. _We want to show the status of an invoice, in Hypha, when it has been paid via IntAct.
Can we query the status of the invoice to see if it is paid (via the AP module)?_ Yes, you would use the List Bill API call requesting the STATE field and a filter for RECORDID (Bill Number on AP Bill) = VENDORDOCNO (Purchasing Vendor Invoice Bill Number). Or you could filter on DESCRIPTION2 (Document ID on AP Bill) = DOCID (Purchasing document ID). Both fields are required on the vendor invoice and propagate through to AP. The first is usually the Vendor’s Bill #, the second is a system generated document # (from Purchasing).

**Comment by frjo** [comment]
@sks444 It seems to be time to start the IntAcct API work. My goal is as follow:

* Have all IntAcct API code in a separate app/directory.
* Make it possible to add other API integrations in their own separate app/directory. Maybe have them all in a common subdirectory? "projecttsapi"?
* Hava a setting where Hypha using organisations can select which api to use, none should be an option as well.

Is this feasible? Ideas how to implement?

**Comment by frjo** [comment]
Asking @Parbhat for input here as well, see above comment.

**Comment by sks444** [comment]
Yes @frjo, I will start looking at the IntAcct APIs spec and plan out the implementation.

In the meantime, my plan is to complete the basic payment flow before starting out the api integration implementation:

- Add vendor details
- Create Invoice
- Add deliverables to project and invoice
- Approve an invoice/request changes/decline

I think once this issue(https://github.com/HyphaApp/hypha/issues/2383) is done. We would have the flow completed at a basic level. And we could move on to API integration.

Completion of the flow would make sure that we have the data at Hypha that needs to updated on IntAcct and db models at Hypha that can store the data fetched from IntAcct. This would make it easier for us to test things.

**Comment by Parbhat** [comment]
Using a directory say services inside projects app seems good. There can be separate file for each external service Or directory for each external service if code needs to be arranged further.

**Comment by sks444** [comment]
@frjo, I wanted to understand a[ few fundamentals](https://admin.viewcentral.com/events/uploads/intacct/SageIntacctFundamentals.pdf) about IntAcct..dashboard..i.e: How to create vendor/managing and processing invoices..etc.


Looks like I would need to have a [separate account at learning centre](https://www.sageintacct.com/training) to get access of such documents.

I am logged in to my account at https://www-p02.intacct.com/ia/acct/frameset.phtml?.sess=bfGNtg5qgTbbqAeXz7N-yTr4NtqoYg..# but there I can't find any info related to adding vendor/invoices etc.

**Comment by frjo** [comment]
@sks444 I could link a new account to my IntAcct account. Let me know if the following work for you as well:

1. Go to https://www.sageintacct.com/training
2. Scroll down to "Getting started is easy" and click the "Sign in" link.
3. In the login box top right you see a button "Sign in with Sage Intacct". Use that with your IntAcct account.

**Comment by sks444** [comment]
Thanks @frjo, I am logged in to training centre with my Sage IntAcct account. 

It shows: **Contact your admin to give you permissions to Sage Intacct connections - Learning Center in the Company application.**

**Comment by frjo** [comment]
I have reviews our accounts and we should have the same level of access.

Did you see this login box and clicked the button the red arrow points to?

![1](https://user-images.githubusercontent.com/191392/129008522-e95526db-afdf-4d78-bb90-c7e509775969.png)

And then this page?

![2](https://user-images.githubusercontent.com/191392/129008533-1622a58d-a1a3-42d0-b019-8cdfeb8b4ea5.png)

That leads me to this page.

![3](https://user-images.githubusercontent.com/191392/129008547-9afc3e3f-c8af-4d12-91ce-268562e13053.png)

**Comment by sks444** [comment]
Yes I logged in the same way but nothing shows up on the page except: 

<img width="1326" alt="Screenshot 2021-08-11 at 5 04 57 PM" src="https://user-images.githubusercontent.com/22263040/129022210-cbc44315-deb6-4d28-8940-d252cfa30ec3.png">

**Comment by frjo** [comment]
@sks444 I think I finally found a difference between our accounts. It should hopefully work now.

**Comment by sks444** [comment]
Yes it works now! Thanks @frjo

Let me know if there is any recommendations/suggestions on the courses best suited for us.

I am thinking of browsing through the Sage IntAcct fundamentals..looking through concepts according to our need.

I guess our main importance for now would be Vendor and Invoicing.

**Comment by frjo** [comment]
We also have access to an IntAcct specialist at claconnect.com that we can ask questions. She knows here stuff and are easy to communicate with. Will send here an e-mail, adding you and Parbhat as CC.

**Comment by sks444** [comment]
Thanks @frjo.

Just wanted to make sure that if it's okay to update/add info/entries at the opentechfund-sandbox instance of Sage Intacct that I have access to.

**Comment by frjo** [comment]
Yes, in the sandbox we are free to play around as needed.
