### ISSUE TITLE
Error when deleting user account in WagTail

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2411]
**Describe the bug**

I get an error message when I attempted to delete an account for a user with five accounts in WagTail on the LIVE site.

**To Reproduce**

![Kapture bug_delete_user_account](https://user-images.githubusercontent.com/20019656/120787522-bbcf6c80-c52f-11eb-8e95-259bdaab99ac.gif)

**Expected behavior**

I should be able to delete the account without an error message.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Desktop (please complete the following information):**

OS
Google Chrome is up to date Version 91.0.4472.77 (Official Build) (x86_64)

**Comment by frjo** [comment]
@fourthletter Hypha should show the real error. The user account is linked to content and can therefor not be deleted.

So Hypha is right when it refuses to delete the user but it fails on showing the reason.

**Comment by sks444** [comment]
I believe work related to this is already in progress at Wagtail https://github.com/wagtail/wagtail/issues/1602.

However, I added a middleware in an another project which catch the error and displays a warning message.

If required, could be used here as well in the meantime.

```python
from django.contrib import messages
from django.db.models.deletion import ProtectedError
from django.http import HttpResponseRedirect


class HandleProtectionErrorMiddleware:
    def __init__(self, get_response):
        self.get_response = get_response

    def process_exception(self, request, exception):
        if isinstance(exception, ProtectedError):
            messages.error(
                request,
                "The object you are trying to delete is used somewhere. Please remove any usages and try again!.",
            )
            return HttpResponseRedirect(request.path)

        return None

    def __call__(self, request):
        response = self.get_response(request)
        return response
```
