### ISSUE TITLE
In all submissions, when selecting 2 or more filters, the filter button is no longer clickable

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2432]
have to manually zoom out of the page to actually click the button.
![Screenshot 2021-06-15 09 15 17](https://user-images.githubusercontent.com/620336/122059320-7ece6a00-cdba-11eb-99ac-e7563a5f6cd3.png)

Dont know what is the best expected behaviour :-/

cc @ei8fdb and @katiewilson21 for design review

**Comment by fourthletter** [comment]
This was a bug that existed for awhile now. #2278 is to re-design filters. Since we're on this topic, it's not only the "All Submissions" filter, specific "Fund" or "Lab" filters could use a similar refresh.

**Comment by sandeepsajan0** [comment]
![Peek 2021-06-18 17-31](https://user-images.githubusercontent.com/23638629/122557797-e0146880-d05a-11eb-8e5a-9fd37d24ff07.gif)

@danblah How is it, Is it looks okay to you? Now, the filter button can easily get by scrolling horizontally.
