### ISSUE TITLE
Error at Determination

### ISSUE THREAD

**Issue by saoun** [HyphaApp/hypha#2440]
As I select "Update Status" I receive this red error immediately. Happened twice, but not sure how to recreate it. 

![Screenshot 2021-06-24 5 01 32 PM](https://user-images.githubusercontent.com/11432628/123332441-80143b00-d50e-11eb-95b7-a297eb5b4408.png)

**Comment by Parbhat** [comment]
@frjo Are you working on the fix?

**Comment by frjo** [comment]
I will look at this.

**Comment by fourthletter** [comment]
No longer an issue on the live and test sites.
