### ISSUE TITLE
Finance level 1 user approves fixed price invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2444]
## Additional context
This is part of epic #2352.

## User story
> As a finance user I need to approve a contractors invoice, so that the head of finance can then approve the invoice and it can be sent to the finance system.

## Describe the solution you'd like in Hypha
In Hypha the Finance Level 1 needs to:
- view uploaded invoice file
- (if necessary) change the deliverables assigned by the PM
- show that the necessary checks and documentation is on file
- approve the invoice

## Notifications
When the Finance level 1 user approves the invoice the:
- finance level 2 gets notified that a new invoice needs to be reviewed

## Priority
- High (keeping you from completing day-to-day tasks)

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

### Demo
Need to add.

### Wireframes

![5 1](https://user-images.githubusercontent.com/1899506/124143363-5b2e4380-da8b-11eb-96f8-7ae60cba91c3.png)

When the finance level 1 user first logs in first they see their dashboard - by default showing the invoices to be reviewed. These invoices have all been approved by the PM users. The finance user chooses to review the invoice “Maya Summit number 58, and clicks on it.

![5 2](https://user-images.githubusercontent.com/1899506/124143532-7d27c600-da8b-11eb-8973-443f4d8caf87.png)

When the invoice “Maya Summit number 58” opens they see the invoice information, they see the invoice embedded in the hypha page. They can if they need, open the invoice in another window by clicking on Open invoice in new window”.

On the right hand side in the actions to take panels, they see the deliverables that the PM has already assigned to the invoice. If they agree with what the PM has done, they don’t have to do anything with the deliverables.

If they don’t agree with the deliverables the PM has assigned, they can remove them, and choose different deliverables from the drop-down.

The next thing is the Required checks. A valid OFAC and SAM check needs to be on file for the project. The finance user will need to check these files exist, and are valid, in different systems.

If there is a valid OFAC and SAM check, and valid W8 or W9 document on file they press the radio button “Valid OFAC, SAM W8/W9 on file. This radio button is mandatory. They cannot press the “Update invoice status” button without pressing this radio button.

![5 3](https://user-images.githubusercontent.com/1899506/124143863-c24bf800-da8b-11eb-9a5a-663248b6c8f7.png)

Once they have done the checks in the different system, they paste the link to the OFAC, SAM, W8 or W9 files.

![5 4](https://user-images.githubusercontent.com/1899506/124143925-d1cb4100-da8b-11eb-8342-2b99cdc5aa6f.png)
If everything is OK they press “Update invoice status” button.

![5 5](https://user-images.githubusercontent.com/1899506/124146786-6767d000-da8e-11eb-9f4a-4718c01a1586.png)
When the finance level 1 user has pressed “Update invoice status” the modal opens and here they can choose what state to update the invoice to.
If they want they can write a short comment. This is optional.

![5 6](https://user-images.githubusercontent.com/1899506/124146828-6f277480-da8e-11eb-8ea2-e9c3cd33cbba.png)
If everything is OK they can then choose “approved by finance 1”. (They cannot choose Approved by finance 2 as they are not at the right level of permissions)

![5 7](https://user-images.githubusercontent.com/1899506/124144236-122abf00-da8c-11eb-8062-83180a7379b6.png)
The invoice for Maya Summit is now approved and so is not displayed in the list of invoices to be reviewed.

If the finance user wants to see the invoice, they can click on All invoices.

**Comment by frjo** [comment]
@sandeepsajan0  I have merged in https://github.com/HyphaApp/hypha/pull/2438 to main so we can build on that.

I think approval "Financial level 1" should simply be "Finance approval".

Not all organisations will have a need for the level 2 step.

**Comment by ei8fdb** [comment]
> I think approval "Financial level 1" should simply be "Finance approval".

How will this look in the UI? Will it be "Finance level 1" or "Finance approval"?

**Comment by fourthletter** [comment]
1) This is my favorite thing to look at on the internet right now

<img width="205" alt="Screen Shot 2021-07-08 at 9 12 37 AM" src="https://user-images.githubusercontent.com/20019656/124878795-ca94bd80-dfcc-11eb-9b57-b76b258b4786.png">




2) Will approvals from finance 1 (maker) and finance 2/approver (checker) be tracked and recorded in the activity feed for reporting requirements/audits? Like this 👇 

<img width="1049" alt="Screen Shot 2021-07-08 at 9 12 27 AM" src="https://user-images.githubusercontent.com/20019656/124878856-d97b7000-dfcc-11eb-9b75-3e2b812a24cb.png">

**Comment by frjo** [comment]
@fourthletter Each change of status is tracked.

**Comment by ei8fdb** [comment]
> @fourthletter Each change of status is tracked.

Speaking with @fourthletter on Friday, once I explained what we were proposing, she's OK with the journey of each invoice being tracked.

**Comment by sks444** [comment]
Hey @ei8fdb, just wanted to remind about the design of submitting/viewing required checks that we discussed on standup.

**Comment by frjo** [comment]
There are two ways of solving this, I leve it up to @sks444 to pick the solution.

1. We reuse the standard Hypha pattern of opening a popup with a form to enter the checks.
2. Add a save button to the checks that does an AJAX call to save them, much like how the deliverables work.

**Comment by fourthletter** [comment]
Hiya @ei8fdb:  @sks444 asked yesterday if Finance 1 should be able to "Decline" after they have "Requested changes." We decided Finance 1 could carry out both activities without restrictions because it was easier to develop. We will look into a better design when we refine this feature in the future.

**Comment by frjo** [comment]
Deliverables will be removed (deactivated) but other than that things will look the same I think.

**Comment by ei8fdb** [comment]
@fourthletter we need your and finance users review of these designs for the finance 1 dashboard

**By default the Invoices ready for Finance 1 review are shown**
![](https://share.balsamiq.com/c/jJWCgamwpdcP6dH7KMyVzx.png)

**The Finance 1 user can see all invoices relevant to them by clicking All invoices**
![](https://share.balsamiq.com/c/dnS27Bb88F6WDjtw1E2jJu.png)

**Comment by fourthletter** [comment]
On March 29 I reached out to Finance staff for feedback on the new dashboard designs. I am still waiting for their input.

Current dashboard on the project's page for Finance 1 users:

![image](https://user-images.githubusercontent.com/20019656/162160565-43fc1c5d-b888-4b0e-8a4b-cd7f47b9c3e0.png)
