### ISSUE TITLE
Finance level 2 user can review and approve invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2445]
## Additional context
This is part of epic #2352.

## User story
> As a finance level 2 user I need a way to approve a contractors invoice, so it can be sent to the finance system to be paid.

## Describe the solution you'd like in Hypha
In Hypha the Finance level 2 needs to:
- view uploaded invoice file
- (if necessary) change the deliverables assigned by the PM
- see that finance level 1 user has checked the necessary checks and documentation are on file
- approve the invoice

## Notifications
When the Finance level 2 user approves the invoice the:
- finance level 1 gets notified that the invoice has been sent to Intacct and can be processed there

## Priority
- High (keeping you from completing day-to-day tasks)

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

### Demo
Need to add.

### Wireframes

![9 1](https://share.balsamiq.com/c/qr4gLt6HkzP5vvVrPBdPc7.png)
When the finance level 2 user first logs in first they see their dashboard *by default* showing the invoices to be reviewed. 

It shows them the invoices that are ready for finance level 1 *and* finance level 2 to approve. This is because, the finance level 2 user may need to do the finance level 1 approvals if the finance level 1 user is, for example, on holiday.

The finance level 2 user chooses to review the invoice “HP-000-079" for project SPAAAM, and clicks on it.

*9.1 invoices ready for entry into IntAcct filtered list*
![9 1 invoices ready for entry into IntAcct filtered list](https://share.balsamiq.com/c/syNc6eNmHZiLLBJLSZoc94.png)

*9 1 Show all invoices - unfiltered*

![9 1 show all invoices](https://share.balsamiq.com/c/j1SYfwoibhD4pYvr8mffW2.png)

![9 2](https://user-images.githubusercontent.com/1899506/124147656-2fad5800-da8f-11eb-92dd-027613c67790.png)
When the invoice “Maya Summit number 58” opens they see the invoice information, they see the invoice embedded in the Hypha page. They can if they need, open the invoice in another window by clicking on "Open invoice in new window”.

On the right hand side in the actions to take panels - they see the deliverables that have been already assigned to the invoice. If they agree with what the PM and finance level 1 user has done, they don’t have to do anything with the deliverables.

If they don’t agree with the deliverables the PM or finance level 1 user have assigned, they can remove them, and choose different deliverables from the drop-down.

Finance level 2 user also sees that the finance level 1 user has pressed the “valid OFAC, SAM check and W8 or W9 on file” radio button, and if they want, they can click on the link to verify the files. This verifying will happen in another system.

If they have no problems with invoice, they press “Update invoice status”.

![9 3](https://user-images.githubusercontent.com/1899506/124147657-2fad5800-da8f-11eb-9c9d-0792a06705aa.png)
When the finance level 2 user has pressed “Update invoice status” the modal opens and here they can choose what state to update the invoice to.

![9 4](https://user-images.githubusercontent.com/1899506/124147660-3045ee80-da8f-11eb-9964-6bfcb633360c.png)
They choose approved by finance 2 which then sends the invoice to Intacct. (They cannot choose Approved by finance 1 as this already has been done)

![9 5](https://user-images.githubusercontent.com/1899506/124147662-3045ee80-da8f-11eb-8fd6-2853a501cf6e.png)
When they press update status, they are brought back to the list of invoices to be approved by finance. The invoice for Maya Summit is now approved and so is not displayed in the list of invoices to be reviewed.

If the finance user wants to see the invoice, they can click on All invoices.

![9 6](https://user-images.githubusercontent.com/1899506/124147663-30de8500-da8f-11eb-9074-39034e86a22e.png)
On the all invoices list, they can see all invoices with all statuses - synched to intacct, paid, etc.

**Comment by frjo** [comment]
@sks444 My idea was to use the role "Finance" plus the role "Approval" to be what is here called "Finance level 2" Users with both these roles would then be able to do the level 2 stuff. What do you think?

In practice the second finale approval will send the invoice to the third part system via an API call, in OTFs case IntAcct.

**Comment by sks444** [comment]
Sounds good @frjo

I was also looking at https://github.com/HyphaApp/hypha/issues/2444#issuecomment-874068687

So when there is just one level of finance, user with both the permission can do all at once.

But when there are two level of finance, user with finance permission will do the first step and user with both the permission will do the second..?

**Comment by frjo** [comment]
1. Staff role need to review and approve an invoice, status "Staff approval"
2. Finance role need to review and approve an invoice, status "Finance approval"
3. Finance + Approval role  (senior accountant) nend to review and approve the invoice, status "Send to IntAcct"

The words Staff, Finance and IntAcct can be taken from Group names plus a new wagtail setting, something like "Third party service name". Or maybe better to set the name in the separate IntAcct API call app. Ideas?

The current status "Under review" seems to work very mush like I assume "Staff approval" will work. I do not think we need that anymore, or just rename it.

Invoices can not skip steps, it should not be possible to move from "Staff approval" directly to "Send to IntAcct".

Or in other words "Send to IntAcct" should only be available on invoices in status "Finance approval".

**Comment by ei8fdb** [comment]
@fourthletter we need your and finance users review of these designs for the finance 2 dashboard

**By default the table shows the invoices to be reviewed by finance 2**
![](https://share.balsamiq.com/c/qr4gLt6HkzP5vvVrPBdPc7.png)

**To see the invoices ready for entry into IntAcct filtered list**
![](https://share.balsamiq.com/c/syNc6eNmHZiLLBJLSZoc94.png)

Can we combine this view with the previous view?

**Show all invoices - unfiltered**
![](https://share.balsamiq.com/c/j1SYfwoibhD4pYvr8mffW2.png)

**Comment by sandeepsajan0** [comment]
@frjo This can also be closed as Finance 2 can review and approve the invoices and infact Finance2 is not even in use right now.

**Comment by frjo** [comment]
Thanks for cleaning up!
