### ISSUE TITLE
Allow projects to be created without an application

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2447]
Partners that have projects but has not applied via Hypha could then be administered in Hypha.

- [ ] Add a way to create new project form with:
  - [ ] title, contact name and e-mail
  - [ ] project summary for if the project is made public
  - [ ] (maybe) some questions to justify why it's being funded, e.g.
    - [ ] why it's important
    - [ ] how it will be impactful 
- [ ] If the users (e-mail) exist attach to that account, if not create a new user account.

How does a user add a project, without an application? Maybe a  "Create project" button? On "/apply/projects/"?

**Comment by danblah** [comment]
Using the new terms/workflow, would it be more apt to say this will be to create a new partner setup form > partner page w/o an existing submission/application? cc @ei8fdb

**Comment by fourthletter** [comment]
## User story
As a Funder I need to make payments to vendors through an IDIQ  contracts (Indefinite Delivery, Indefinite Quantity contract vehicles). IDIQ are work or task orders often associated with OTF's Labs. 

The IDIQ workflow is unique from the typical application review process. One vendor could be associated with numerous forms/applications/tasks orders on Hypha's Submission tab.

## Describe the solution you'd like in Hypha
Add a "Create project" button to every "Approved" application? On "/apply/projects/"? 

OR 

Enable a "Create project" button on the Project side. 

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff

**Ideal deadline**
March 2022

**Comment by fourthletter** [comment]
During a standup, we discussed creating a form for contractors/vendors on the Submissions side. This "application form" could be converted to a project for contracting and invoicing purposes. 

- [ ] Create form for vendors in WagTail
- [ ] Select a workflow for vendor/contract workflow, or it could be any workflow
- [ ] Vendor could be converted into a "Project" page like any other funded application
- [ ] Does the application need to come from a published Fund/Lab/Round? Could this Form be for internal use only?


### Next Steps:
Create documentation for these steps, and share with adopters
