### ISSUE TITLE
PM can request modifications to fixed-price invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2453]
## Additional context
This is part of epic #2352.

## User story
> As a Programme Manager I need to request changes to a contractors invoice when it's incorrect, so that I can approve a valid invoice, and the contractor can get paid.

## Describe the solution you'd like in Hypha
- PM opens the invoice
- reviews it
- PM decides the invoice needs to be modified
- PM updates the invoice status and sends a message to the contractor requesting changes to the invoice
- the invoice is then put on hold until the contractor resubmits the invoice

## Notifications
When the PM updates the invoice status to "request changes":
- the contractor receives a notification requesting they update the invoice

## Priority
- High (keeping you from completing day-to-day tasks)

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

### Demo
https://user-images.githubusercontent.com/1899506/125316942-e4b9fd00-e338-11eb-99de-c78a308d7116.mp4

### Wireframes

**6.1**
![6 1](https://user-images.githubusercontent.com/1899506/125317131-0e732400-e339-11eb-9e37-28ecdd493fa5.png)
The PM logs in and sees the table of invoices to be reviewed. This table shows:
- the date of the status and the status 
- the invoice reference - made up of the project name and the reference number generated by Hypha, and
- the total value amount

The PM chooses to review “invoice maya summit 58”.

**6.2**
![6 2](https://user-images.githubusercontent.com/1899506/125317133-0fa45100-e339-11eb-9ab9-488142c834d9.png)

Invoice reference Maya Summit (58) is opened. The PM reviews the invoice. 

The contractor has invoiced for “Designing a website” (Deliverable 1) and “Hosting a website” (Deliverable 2). They have invoiced $6,000 for Deliverable 1 when it should it $5,000. (The PM knows this from the drop-down of deliverables, but also from the contract)

This is incorrect and so the PM cannot approve the invoice. To fix this they will update the invoice status to “request changes” and the invoice will be sent back to the contractor with a message.

**6.3**
![6 3](https://user-images.githubusercontent.com/1899506/125317135-0fa45100-e339-11eb-8b90-84259da9a582.png)

This then opens the modal "Update invoice status" window.

**6.4**
![6 4](https://user-images.githubusercontent.com/1899506/125317138-103ce780-e339-11eb-9193-97ea01da1e97.png)
From here they choose “request changes”.
(The finance related approvals are unavailable to then as they do not have those permissions.)

The other options available are “Approved by PM” or “Declined”.

**6.5**
![6 5](https://user-images.githubusercontent.com/1899506/125317142-103ce780-e339-11eb-9cb0-ed470f8a6046.png)
Then the PM writes a message explaining what is incorrect with the invoice, and how the contractor needs to fix it. This message written here will later be shown in the Activity feed.

When finished writing the message, they click update status.

**6.6**
![6 6](https://user-images.githubusercontent.com/1899506/125317144-10d57e00-e339-11eb-8d1b-a0207f0dbb94.png)
The invoice status is then updated to Requested changes, with the date the status change happened.

If the PM wants to see the message they’ve written to the contractor, they can navigate to the project, and click on activity feed and see the message there.

**6.7**
![6 7](https://user-images.githubusercontent.com/1899506/125317146-10d57e00-e339-11eb-9257-22f1be5c3108.png)
From the all projects list the PM can navigate to the Maya Summit project page.

**6.8**
![6 8](https://user-images.githubusercontent.com/1899506/125317148-116e1480-e339-11eb-89f5-0355a5b1b91d.png)
Once the PM has opened the project page, they can click on the activity feed.

**6.9**
![6 9](https://user-images.githubusercontent.com/1899506/125317149-1206ab00-e339-11eb-9d23-512d99b1fd4d.png)
In the activity feed, the PM can see that the status has been updated, and they can also see the message which has been sent to the contractor.

**Comment by sks444** [comment]
@ei8fdb @frjo,

There are two [types of activities](https://github.com/HyphaApp/hypha/blob/0d65f73f5ef7bc051ddf9cfa3a46ef4d4fb9032c/hypha/apply/activity/models.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L13), 1. Comment 2. Action.

All `action` goes at the `Activity` tab.

All `comment` goes at the `Communication` tab.

Now, with respect to this issue, we have both kind of activities happening together, action(invoice status update) and comment(message sent while invoice status update).

To display this together we developed [this method](https://github.com/HyphaApp/hypha/blob/a7e17ec056d126e8754eda2b4e4f11c4d86f1a9e/hypha/apply/activity/messaging.py?_pjax=%23js-repo-pjax-container%2C%20div%5Bitemtype%3D%22http%3A%2F%2Fschema.org%2FSoftwareSourceCode%22%5D%20main%2C%20%5Bdata-pjax-container%5D#L375): which combines both the string messages together..e.g [as shown in the design](https://user-images.githubusercontent.com/1899506/125317149-1206ab00-e339-11eb-9d23-512d99b1fd4d.png). 

I'm thinking to display this combined message at the communication tab, this way context of the message will also be there in the communication tab. And in the activity tab only display invoice status update message, as the activities are just a log of things.

**Comment by ei8fdb** [comment]
> I'm thinking to display this combined message at the communication tab, this way context of the message will also be there in the communication tab. And in the activity tab only display invoice status update message, as the activities are just a log of things.

That sounds a perfectly sensible approach @sks444. When you have something working locally on your machine can you send a screenshot/video?

**Comment by chaitu210** [comment]
@ei8fdb Implemented above changes, Please check the screencast 

https://user-images.githubusercontent.com/5557179/142149375-3ad19195-2a50-4cb1-96ac-d98f86d9bcd8.mp4

**Comment by ei8fdb** [comment]
Hi @chaitu210 displaying the request modifications message in the communications tab and the activity tab looks really good. 👍 💯 

*One* small request I'd make is - in the communications tab the "chaitanya kattineni left this message" text shown below: 

![image](https://user-images.githubusercontent.com/1899506/142171405-af3118c0-51df-47e3-a567-cc61d80d137c.png)

can you remove this?

The reason being - the username is already displayed in the header "chaitanya kattineni (Staff) (Reviewer) - 2021-11-17 06:12".

Is that clear? Any questions, just let me know! Thanks.

**Comment by fourthletter** [comment]
This looks amazing! Thank you SO much. 

QA

The PM can review the invoice:
- [X] updates the invoice status and sends a message to the contractor requesting changes to the invoice
    - drop down menu Requested changes, Approved by staff, Declined
- [X] opens the modal "Update invoice status" window.
- [X] the invoice is then put on hold until the contractor resubmits the invoice 
- [X] When the PM updates the invoice status to "request changes" on the invoice dashboard (image 1)

Notifications/Communication
- [X] then the PM writes a message explaining what is incorrect with the invoice, and how the contractor needs to fix it.
- [X] A status update is shown in the Activity feed (image 2)
-  [X]  PM's message will also be there in the communication tab

Image 1: When the PM updates the invoice status to "request changes" on the invoice dashboard

<img width="835" alt="Screen Shot 2021-11-23 at 2 17 46 PM" src="https://user-images.githubusercontent.com/20019656/143031168-3e5aa9e6-3e2b-4abd-8214-142f2c07a3ae.png">


Image 2: A status update is shown in the Activity feed
<img width="596" alt="Screen Shot 2021-11-23 at 2 21 58 PM" src="https://user-images.githubusercontent.com/20019656/143031667-5418a6e6-7a0f-4400-aa56-f423e57e8ac1.png">
