### ISSUE TITLE
Finance level 1 can request modifications to fixed-price invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2454]
## Additional context
This is part of epic #2352.

## User story
> As a finance user Level 1 I need to request changes to a contractors invoice when it's incorrect, so that I can approve a valid invoice, and the contractor can get paid.

## Describe the solution you'd like in Hypha
In Hypha the Finance Level 1 needs to:

## Priority
- High (keeping you from completing day-to-day tasks)

### Demo
https://user-images.githubusercontent.com/1899506/125954777-56529004-40d2-4334-9a68-fa554f398340.mp4

### Wireframes

**7.1**
![7 1](https://user-images.githubusercontent.com/1899506/125954857-f6d93fcc-37a4-4667-9957-335d7e8b35fc.png)

When the Finance Level 1 user logs in, they’ll see the list of invoices ready for approval. In this case, they want to approve Maya Summit 58 invoice.

**7.2**
![7 2](https://user-images.githubusercontent.com/1899506/125955004-9fd9edf7-3a1c-43a6-ade3-ab7fb3f8e272.png)

When the invoice “Maya Summit number 58” opens they see the invoice information, they see the invoice embedded in the Hypha page.

On the right hand side in the actions to take panels, they see the deliverables that the PM has already assigned to the invoice. If they agree with what the PM has done, they don’t have to do anything with the deliverables.

They review the rest of the invoice, and see the Total amount in the top area of the invoice says $1,111.00, whereas the PDF invoice says $8,000. This error needs to be corrected before they can approve the invoice. 

So finance user must update the invoice status to “request changes”.

**7.3**
![7 3](https://user-images.githubusercontent.com/1899506/125954862-d11b466b-304d-4a9d-8200-1dced0059249.png)

When the finance level 1 user has pressed “Update invoice status” the modal opens and here they can choose what state to update the invoice to. They can also write a message to explain what change they’re requesting. This message will be sent to the PM. 

The PM will then communicate with the Partner to request the changes.

**7.4**
![7 4](https://user-images.githubusercontent.com/1899506/125954864-d907097c-064f-4a9c-a4e5-fca0b13c0309.png)
/user-images.githubusercontent.com/1899506/125954859-37c770f9-1e7f-4913-b241-415647f6c0da.png)

Because there is a mistake in the invoice, they choose Request changes. There are other options - “Approved by finance 1, and Declined” which are available to them.

Approved by Staff and Approved by finance 2 are not available to them as they do not have those permissions.

**7.5**
![7 5](https://user-images.githubusercontent.com/1899506/125954866-ab418b08-963c-49e6-902a-9250e653258d.png)

Once they’ve chosen Request changes, they can then write their message.

**7.6**
![7 6](https://user-images.githubusercontent.com/1899506/125954867-de841a49-add7-4046-bfa3-96d537e11f27.png)

The message they write is addressed to the PM - listed in the “OTF Lead” field in the upper portion of the invoice tab. The message explains what changes they are requesting.

**7.7**
![7 7](https://user-images.githubusercontent.com/1899506/125954868-6b642a48-5c8c-4ece-b1e4-52ac1a9ea1dd.png)

Once they press update status, the message is sent to the PM. The finance level 1 user then sees the invoice status updated to “requested changes”.

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

**Comment by sks444** [comment]
@frjo @ei8fdb,

This is to confirm what happens after finance 1 requests the changes addressing pm and they receive the notification.

E.g. How do they(pm) communicate with the contractor?

Assuming this would follow the same initial flow b/w the PM/contractor. Where PM will have to again request changes addressing the contractor and when contractor resubmits, PM approves..and the invoice again shows up as review for Finance1.

To conclude the complete process has to be reversible..unless Finance approves the invoice..i.e. even when a pm has approved an invoice, once they are asked by finance 1 to request changes, they should have the possibility to request changes again.

**Comment by fourthletter** [comment]
@sks444 I agree with the workflow you described here (https://github.com/HyphaApp/hypha/issues/2454#issuecomment-998347051) 

Finance 1 & 2 have the knowledge and training to identify issues with the invoice that the PM might have missed when they initially approved the invoice. PMs should have the possibility to request additional changes from the contractor again.

**Comment by frjo** [comment]
When Finance 1 or 2 ask for changes to an invoice it goes to the PM. The PM can fixit themselves if possible or sent it on to the applicant.

When the changes are done I think we should let the invoice go through the work flow again, just as if it was a new invoice.

This makes it easy to implement and it is a safe bet for now. Everyone will need to approve stuff all the time, no one left out.

I imagine that people with time will find this cumbersome. When we have pin pointed the issues we can fix them by making the workflow smarter. But for now stick with the easy and safe option.
