### ISSUE TITLE
Determination Templates Not Implemented

### ISSUE THREAD

**Issue by hawkinsw** [HyphaApp/hypha#2455]
**Describe the bug**

There is functionality for the user to add determination message templates but those templates are not imported when the user creates a determination for an application. 

**To Reproduce**
1. Create determination template messages.
2. Add a determination to an application.

**Expected behavior**

I expect that those determination template messages would populate the text editor. 

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers

**Additional context**
Patch inbound.

**Comment by danblah** [comment]
Related to https://github.com/HyphaApp/hypha/issues/2080

**Comment by Erioldoesdesign** [comment]
This should probably be in the backlog for the [OTF's Ye Olde Bug & Refinement Shoppe](https://github.com/HyphaApp/hypha/projects/14) board?

**Comment by sandeepsajan0** [comment]
I think it is fixed with issue #2809.

**Comment by frjo** [comment]
Correct, closing now.
