### ISSUE TITLE
Finance level 2 can request modifications to fixed-price invoice

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2457]
## Additional context
This is part of epic #2352.

## User story
> As a finance user Level 2 I need to request changes to a contractors invoice when it's incorrect, so that I approve it and the contractor can get paid.

## Describe the solution you'd like in Hypha
In Hypha the Finance Level 2 needs to:
- log into review invoices
- choose an invoice to review
- review invoice, find it needs to be modified
- send a message to the PM requesting they contact the contractor to make changes

## Priority
- High (keeping you from completing day-to-day tasks)

### Demo
- to be added

### Wireframes

**10.1**
![10 1](https://user-images.githubusercontent.com/1899506/126188335-c7cdce13-ad74-4633-a01b-d25a6eeb8fa7.png)

When the Finance Level 2 user logs in, they’ll see the list of invoices ready for approval. In this case, they want to approve Maya Summit 58 invoice.

**10.2**
![10 2](https://user-images.githubusercontent.com/1899506/126188376-737e51a2-38d1-4c8b-b108-657bb88f0496.png)

When the invoice “Maya Summit number 58” opens they see the invoice information, they see the invoice embedded in the Hypha page. 

On the right hand side in the actions to take panels, they see the deliverables that the PM has already assigned to the invoice. If they agree with what the PM and Finance Level 1 user has done, they don’t have to do anything.

In this case they see the dates on the invoice are different than the dates on the top half of the web page. This error needs to be corrected before the  invoice is approved.

The finance level 2 user must update the invoice status to “request changes”.

**10.3**
![10 3](https://user-images.githubusercontent.com/1899506/126188388-72df43d3-f916-42c7-b5e8-3ee428fe2bc1.png)

When the finance level 2 user has pressed “Update invoice status” the invoice status modal opens and here they can choose what state to update the invoice to.

They can also write a message to explain what change they’re requesting. This message will be sent to the PM. 

The PM will then communicate with the Partner to request the changes.

**10.4**
![10 4](https://user-images.githubusercontent.com/1899506/126188419-9afb26b2-1f31-44e1-980c-1df347932d1f.png)

Because there is a mistake in the invoice, they choose Request changes. The other options available are - “Approved by Finance 2”, and Declined”.

“Approved by Staff” is not available to them as they do not have those permissions.

**10.5**
![10 5](https://user-images.githubusercontent.com/1899506/126188442-64b33a7e-653e-4a5e-bf3c-e3dd084858f3.png)

Once they’ve chosen Request changes, they can then write their message.

**10.6**
![10 6](https://user-images.githubusercontent.com/1899506/126188491-389962c6-ae67-40e6-bcdb-d25f9f25fc22.png)

The message they write is addressed to the PM - listed in the “OTF Lead” field in the upper portion of the invoice tab. The message explains what changes they are requesting.

**10.7**
![10 7](https://user-images.githubusercontent.com/1899506/126188520-f78eaddf-8f2d-405e-97de-98c099f44bee.png)

Once they press update status, the message is sent to the PM. The Finance level 2 user then sees the invoice status updated to “requested changes”.

## Affected roles 
- Staff
- Applicants
- Finance

## Ideal deadline
June 2021

**Comment by frjo** [comment]
Deliverables removed but otherwise nothing changes.
