### ISSUE TITLE
Update information displayed in project Activity feed

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2458]
## Describe the solution you'd like
The project activity feed needs to be updated as a result of the new payment request/invoice submission work. The activity feed needs to show information about the new statuses for payment requests. It needs to follow the same UI patterns. 

## UI Design
![](https://share.balsamiq.com/c/gDv63aH5r7RpjP9BBeiaD9.png)

### UI Wireframes

![Proposed update to Activity Feed view with annotations](https://share.balsamiq.com/c/wivfzrAuLj1jUm868yGa8.png)

**Priority**
- Medium (slowing you down)

**Affected roles**
- Staff
- Applicants
- Partners

**Ideal deadline**
When the OTF Finance work is being delivered, ideally this update would be ready when the OTF Finance updates are ready.

**Comment by sandeepsajan0** [comment]
@ei8fdb   I am bit confused about what we need to hide/remove. Can you please clear a few of my queries.

> 1. Already displayed information.

We don't want to create activity for actions like Project creation, Approval, Contract Approval. Do we only want to have payment/invoice related things in activity feed?

Regarding the UI pattern, We want to show request change's messages(comment) in activity feed. right?

Conclusion: We want to reduce the project feed from left side of image(all previous action) to lower right side of image(only payment related actions). Am I right?

**Comment by ei8fdb** [comment]
> @ei8fdb I am bit confused about what we need to hide/remove. Can you please clear a few of my queries.

👍 

> Conclusion: We want to reduce the project feed from left side of image(all previous action) to lower right side of image(only payment related actions). Am I right?

Ah, I understand - I think the designs were confusing. Apologies.

We want the activity feed to contain:

- activity for actions like Project creation, Approval, Contract Approval, **PLUS**
- paymet/invoice related actions, **AND**
- request change's message summary, with a link to the message in the communications tab

@sandeepsajan0 I've updated the designs. Please let me know if that explains better.

**Comment by fourthletter** [comment]
@ei8fdb please move this issue to https://github.com/OpenTechFund/apply-app/issues -- thank you!

**Comment by ei8fdb** [comment]
I've looked thru the issue management UI but I can't see how to move this. 

You'll have to do it @fourthletter

**Comment by fourthletter** [comment]
@ei8fdb I moved it to https://github.com/OpenTechFund/apply-app/issues/24.
