### ISSUE TITLE
Applicant Activity Feed 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2461]
**Describe the bug**

Applicants can see when a reviewer has submitted a review. This should not happen.

**To Reproduce**

1. Submit a review as a staff or reviewer
2. As an applicant, go to the activity feed to see update

<img width="1232" alt="You shouldn't be able to see when a reviewer has submitted a review in the activity feed  Hard to scan data formatting  Quickly finding messages from different people is harder when all comments are the same colour even if from different pe" src="https://user-images.githubusercontent.com/20019656/126893015-ba5717aa-359d-4e60-b4fc-38318e379cb0.png">

**Priority**

- Low priority 

**Affected roles**

- Applicant
- Staff
- Reviewers

**Comment by sandeepsajan0** [comment]
@fourthletter  Applicant should not be able to see the timestamp for any Activity or only for the Reviews?
Other Activity might be like Determination, or any kind of update.

**Comment by fourthletter** [comment]
Hi @sandeepsajan0 Thank you for following up! 

The applicant should not be able to see the entire activity or action (image below).

An applicant should not have permission to see 1) whether a reviewer has 'submitted a review' and 2) when this activity has occurred. 

<img width="751" alt="Screen Shot 2021-07-26 at 9 11 22 PM" src="https://user-images.githubusercontent.com/20019656/127045235-8b88aff4-bede-400e-b26a-1d3d5cc3ec27.png">

**Comment by frjo** [comment]
@fourthletter This is now on test.

**Comment by fourthletter** [comment]
Thank you -- it worked! 💥 

Same application, two different point of views/levels of access:

As an applicant, I should not be able to see any activity associated with the review process 
<img width="677" alt="Screen Shot 2021-08-12 at 8 42 55 AM" src="https://user-images.githubusercontent.com/20019656/129150008-22989945-8ba3-4dde-b8a0-ca421b69cc13.png">


As staff, I should be able to see the activity feed to track all activities, including reviews
<img width="1093" alt="Screen Shot 2021-08-12 at 8 31 13 AM" src="https://user-images.githubusercontent.com/20019656/129148746-b19c126f-a6d0-402c-9039-c9e266a8a754.png">
