### ISSUE TITLE
The Review Agree button

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2464]
## User story
Currently a reviewer clicking on "agree" with an existing review prevents them from drafting and submitting another review. 

**Reviewers should be able to 1) summit a review and 2) have opinions on other reviews for each submission.**

The current user interface misleads users into thinking they can do both. There is not rationale for this restriction.  

## Describe the solution you'd like in Hypha
- Add text to describe the limitation

Example
<img width="278" alt="Screen Shot 2021-08-13 at 9 49 58 PM" src="https://user-images.githubusercontent.com/20019656/129411472-ed90c080-a2d2-49b7-8c70-d4b75a4e8ef0.png">

<img width="525" alt="Screen Shot 2021-08-13 at 9 49 47 PM" src="https://user-images.githubusercontent.com/20019656/129411489-da7bd0dd-7863-4072-9cd8-b605dd576e8c.png">

## Priority
- Low (keeping you from completing day-to-day tasks)

## Affected roles 
- Staff
- Applicants

**Comment by frjo** [comment]
I do not think this is a bug. This is how it was supposed to work. A reviewer could submit a review by writing their own agreeing with someone else's. In Hypha it's called an "opinion".

Hypha counts an opinion as a review, so a review plus an opinion is counted as 2 reviews.

Do OTF want to rebuild this feature so reviewers both can summit a review and have opinions on other reviews for each submission?

Whats is the use case for a reviewer submitting both an opinion and a review for a submission?

**Comment by fourthletter** [comment]
@frjo Yes, OTF want to rebuild this feature so reviewers both can summit a review and have opinions on other reviews for each submission

The user interface (UI) misleads users/reviewers into thinking they can do both. There is not rationale for this restriction.  Removing this limitation would give reviewers the option to do both, this works for other funders as well.

**Comment by frjo** [comment]
What benefits is there with an "opinion" if the reviewer also write a proper review. What does it contribute?

Could we instead make it clear in the UI that reviewer can do one or the other?

**Comment by fourthletter** [comment]
@frjo Sorry for the delay. Here is the text:

_An opinion will replace your review. You will no longer be able to submit a review for this application._
