### ISSUE TITLE
Sort and date in determination sidebar list

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2468]
The latest piece of determination information appears at the bottom, not the top. This goes against convention. Users may not realize 1) which piece of determination is the most recent and that 2) they have to scroll down to see the message. Applicants will not reply quickly because of the current UI. 

Please see the right side of the screen in the box **DETERMINATION**

<img width="1235" alt="It's hard to spot when your project has been approved as the feedback is not distinct enough from other stages in the process  Latest updates are also not listed at the top of the determination section as expected" src="https://user-images.githubusercontent.com/20019656/128667972-14532013-f3fc-45c3-bc61-a5300e9239ad.png">

**Comment by frjo** [comment]
They are in chronological order, you want them to instead be in reversed chronological order?

**Comment by fourthletter** [comment]
@frjo Thank you for clarifying. Please change the order so the determination that is newest or most recent appears at the top.

**Comment by killapop** [comment]
Suggest we change the date format in the determinations list to show `x days ago` as opposed to "2020-02-19".
Additionally add a button to toggle sorting determinations chronologically ascending/descending.

for eg:
![determination_panel](https://user-images.githubusercontent.com/668908/129745953-76cb2171-f068-4b1c-8c03-b11eddb02e81.png)

**Comment by fourthletter** [comment]
Thank you everyone for your input. The crux of the issue is for the applicant to quickly/efficiently identify the most relevant information related to their project, in particular the most recent correspondence or **final determination** (ultimate outcome) of their application. 

<img width="311" alt="Screen Shot 2021-08-18 at 10 50 00 PM" src="https://user-images.githubusercontent.com/20019656/129970356-df42cf24-a1d4-4aac-b39a-afce6e1a7358.png">

**Comment by fourthletter** [comment]
@frjo You decided to implement it even though it goes against every fiber of your being. 👏 

<img width="233" alt="Screen Shot 2021-08-23 at 1 22 57 PM" src="https://user-images.githubusercontent.com/20019656/130439406-167687b2-ae3b-4059-8ef4-ae078d2da446.png">
