### ISSUE TITLE
Implement "environs" package for nice env parsing of settings

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2471]
https://github.com/sloria/environs

I like the look of this package. Looks like we could use it to make the base.py settings a bit cleaner and easier to read. Would also allow Hypha on a standard server to pick up .env files automatically.

```
if env.get('EMAIL_USE_TLS', 'false').lower().strip() == 'true':
    EMAIL_USE_TLS = True

```

Could be rewritten as:

`EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", False)`

as an example.

**Comment by frjo** [comment]
@Parbhat @sks444 What do you think?

**Comment by Parbhat** [comment]
[environs](https://github.com/sloria/environs) looks good and can be [used](https://github.com/sloria/environs#usage-with-django) with Django. Another option is using [django-environ](https://github.com/joke2k/django-environ) which is more widely used in Django projects.
