### ISSUE TITLE
Always show the submission table filters

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2473]

**Comment by fourthletter** [comment]
Specific Funds and Labs always show submission filters without the Filter button (image 1). However, this is not the same for the All Submissions (image 2). BT created something for [ALL Submissions here ](https://github.com/HyphaApp/hypha/discussions/2278)


Image 1
<img width="1079" alt="Screen Shot 2021-08-11 at 9 59 50 PM" src="https://user-images.githubusercontent.com/20019656/129095120-f7cf4e1a-11fb-46f9-bbc8-05324aea0407.png">

Image 2
<img width="1067" alt="Screen Shot 2021-08-11 at 10 03 18 PM" src="https://user-images.githubusercontent.com/20019656/129095495-011d6663-0fcc-4de8-8b5f-fa463e6947f6.png">

**Comment by frjo** [comment]
@fourthletter  I set it so filters always show on view like https://test-apply.hypha.app/apply/submissions/all/ and https://test-apply.hypha.app/apply/projects/all/.

The overview pages that contains multiple tables have not been changed, e.g. https://test-apply.hypha.app/apply/submissions/ and https://test-apply.hypha.app/apply/projects/

Does staff ever use the overview views or to they always head straight for the "*/all" views?
