### ISSUE TITLE
No information about the next steps to take in the 'determination' section

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2480]
## User story
There's no information about the next steps to take in the 'determination' section. As a user I may be unsure what to do next and so are either slow to take action or end up emailing OTF staff with questions. (image 1)

## Describe the solution you'd like in Hypha
Please change the text from 'Awaiting determination' to 'There are no new determinations' (image 2)

image 1: Example
<img width="1238" alt="No info about the rough time it takes for a determination to be made" src="https://user-images.githubusercontent.com/20019656/129381722-4b67621a-89ac-4aee-9787-efeea04458d6.png">

image 2: Example
<img width="183" alt="Screen Shot 2021-08-13 at 5 26 02 PM" src="https://user-images.githubusercontent.com/20019656/129382300-178fa8e6-8265-4557-b3ac-49cc78f23b69.png">

**Comment by frjo** [comment]
@fourthletter The text "Awaiting determination" show when zero determinations exist for the submission.

Should we maybe hide the box altogether for applicants in this situation? 

Or maybe a longer text, something like "Awaiting determination by OTF staff."

**Comment by fourthletter** [comment]
Hiding this box makes sense. The period between the Concept Note and Proposal is a waiting room or purgatory. Applicants often think it's a bug and all their determinations disappeared.

**Comment by fourthletter** [comment]
@frjo Works like a charm! 🌈 


<img width="1218" alt="Screen Shot 2021-09-27 at 12 53 19 PM" src="https://user-images.githubusercontent.com/20019656/134895231-5f7b6851-1c42-4791-a500-9e79511c580e.png">
