### ISSUE TITLE
Remove PII from AC view

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2482]
## User story
As an AC member, I should NOT be able to view PII within to applications associated with my account. This is an effort to increase privacy and security, and protect applicant information.

## Describe the solution you'd like in Hypha
PII should not appear on applications for the AC role. Please hide:

- [ ] telephone number
- [ ] email
- [ ] address
- [ ] legal name, when there is a redundancy between a person's name (to be removed) and an organization's name

<img width="1210" alt="Screen Shot 2021-08-15 at 8 10 02 AM" src="https://user-images.githubusercontent.com/20019656/129469068-0134259a-632f-49d7-9f26-e51b06eacead.png">

**Comment by frjo** [comment]
@Parbhat @sks444 Would it be possible to add a "pii_status" (PII = personally identifiable information) to fields like address and e-mail address like this:

```
 class AddressFieldBlock(ApplicationSingleIncludeFieldBlock):
     name = 'address'
     description = 'The postal address of the user'
     pii_status = True

```

And then check for that when the field is rendered?

```
try:
      pii_status = field.block.pii_status
except AttributeError:
       pii_status = False

```

The best would be if we can get this in to Wagtail group permissions, then each organisation using Hypha can set what groups/roles should be able to view fields with personally identifiable information.

If the last is complicated we can just have a setting in base.py that is a list of groups. The default should be the same as how the system works today, that anyone who can view the submission can also see PII fields.

**Comment by Parbhat** [comment]
@frjo All these options sound good. Sorry for the late response.
