### ISSUE TITLE
Export project bundle

### ISSUE THREAD

**Issue by killapop** [HyphaApp/hypha#2492]
**Is your feature request related to a problem? Please describe.**

Auditors, Reviewers and some other individuals/roles at our funders, because of their existing systems and processes require to have a *Dossier* of each completed application. 

These individuals will not have access to the hypha system and while the application is approved the information still has to go through some processes further upstream in the organisation.

**Describe the solution you'd like**

We'd like to be able to extract/export all information relating to a *Project* in one zip archive that contains
1. generated PDFs of the concept note and proposal
2. all attached documents
3. communication/messages
4. reviews
5. determinations

**Describe alternatives you've considered**

Manually extract this information by printing  or screen-shooting webpages, downloading documents.

**Additional context**

NA

**Priority**

- Medium.

We will need to have the dossier for each project. We are still in early stages of using hypha and will probably need it in 6 - 8 weeks.

**Affected roles**

- Staff (Assigned lead)

We understand that there are different visibility levels set for reviews and determinations and assume that the Lead will redact wherever necessary.

**Ideal deadline**

Mid - End September 2021

**Comment by fourthletter** [comment]
Related to #2327
