### ISSUE TITLE
Add image, description, landing url and ordering fields to Funds and Labs.

### ISSUE THREAD

**Issue by killapop** [HyphaApp/hypha#2506]
**Is your feature request related to a problem? Please describe.**

On the apply landing page that lists funds and labs, we'd like to display an image, a paragraph of text, a link to a guide or more info (this exists) and possibly order the listing.
Currently clicking on the Apply button arrives at a text only listing.
For Orgs that have existing websites that might have this info already, its still quite difficult to be able to link back to their website every time someone wants to get to a list of available funds.

We'd also like to be able to control the order of the list when mixing both funds and labs and promote some over others from time to time.

**Priority**

- Medium

**Affected roles**

- Staff
- Applicants
- General public

**Comment by frjo** [comment]
This information is set in the public site in Hypha but only OTF uses that and they also plan top build a separate public site.

So adding these fields directly on the fund/lab is a good addition. They should also be part of the API call that list open rounds/labs.

**Comment by fourthletter** [comment]
As discussed on June 6 FJ + DL

As OTF moves to a different external website not associated wtih Hypha, this issue will support our new apply page for open calls.

**Comment by fourthletter** [comment]
Related to #2707
