### ISSUE TITLE
Error: webpack-stats.json not being generated with gulp:watch in dev

### ISSUE THREAD

**Issue by killapop** [HyphaApp/hypha#2513]
Running a dev setup with 2 terminals
1. running `./manage.py runserver`
2. running `gulp:watch`

the page `/apply/submissions/all/` to view all submissions breaks with the error 
```
Error during template rendering

In template <path_to_hypha>/hypha/templates/base-apply.html, error at line 9
Error reading <path_to_hypha>hypha/static_compiled/app/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?
```

EDIT:
I realise this is as the `gulp app` set of tasks are not being run. adding `app` to the parallel tasks in the 'gulp:watch` task fixes it.

**Comment by frjo** [comment]
Yes, you need to run `gulp watch:app` as well as `gulp watch`.

**Comment by killapop** [comment]
it works. thanks @frjo . closing this
