### ISSUE TITLE
Design and build a dynamic listing for the Alternate funding sources page on fund.otf, where the user can filter based on defined criteria

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#252]
To clarify - in addition to being searchable we'll want clear separation of the different categories as seen in the google sheet (https://docs.google.com/spreadsheets/d/1-IdAKtOjxUE4MSM9ICp_OTe5qB6VXlUtAuuhJ6tDo8M/edit#gid=0). For backend features: Ability to add new categories, as well as the five fields mentioned below

**Comment by saoun** [comment]
@frjo this seems relatively easy to implement. Would it be possible or is it a bit more complex?

**Comment by frjo** [comment]
@saoun There is work to implement and get it looking nice but it's not hard.

I suggest skipping the "Application Window/Deadline" column, if it's to much work to keep updated in an Google doc it will never be touched in the web app, and that will then just look bad/outdated.

**Comment by saoun** [comment]
I would even skip all the following: Application Window/Deadline | Funding Amount | Funding Duration | Notes

I would just have a search functionality (by name) and filters by categories (rapid response, etc.). We can possibly add more categories. Like "journalism," etc.

What do you think?

**Comment by frjo** [comment]
Simple is good.

**Comment by fourthletter** [comment]
This issue is particularly relevant now.

**Comment by fourthletter** [comment]
Closing this issue because there is a functional source of alternative funding https://guide.opentech.fund/appendix-iv-alternative-sources-of-support
