### ISSUE TITLE
There's no clear link back to the submission from determinations and reviews.

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2526]
## User story
There's no clear link back to the original concept submission from the determination section. There is no obvious next step from the determination detail page. 

## Describe the solution you'd like in Hypha
Please create a quick link back to the submission page, or make any existing links clearer

<img width="1221" alt="No obvious next step from the determination detail page  Make the link back to the submission page clearer" src="https://user-images.githubusercontent.com/20019656/131515146-b608567f-d256-4954-b63f-b01e35f73979.png">

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Applicants

**Ideal deadline**
December 2021

**Comment by sandeepsajan0** [comment]
@fourthletter There is a blue text "Test" can be used to go back to submission. 
Although it can be used but just for better understanding I tried to add a "Back" button on top of it.  

@fourthletter @frjo Let me know if it looks okay to both of you.

![image](https://user-images.githubusercontent.com/23638629/138281458-1fce0a02-53bb-4ad5-9e22-a4f61128544e.png)

**Comment by frjo** [comment]
@sandeepsajan0  On projects we have a "Back to project" link so name this "Back to submission"

Then also remove the link from the submission title and add a colon after "For" to make it look the same as on projects etc.

**Comment by fourthletter** [comment]
@sandeepsajan0 Thank you for following up. I agree with Fredrik that 'Back to Project' is more specific. I see both versions on Project

**Version 1: Back to Project**
<img width="431" alt="Screen Shot 2021-10-21 at 4 21 31 PM" src="https://user-images.githubusercontent.com/20019656/138297261-ee6c1ceb-66fe-4265-81fa-0ab9ea14cdc9.png">

**Version 2: Project**
<img width="878" alt="Screen Shot 2021-10-21 at 4 17 02 PM" src="https://user-images.githubusercontent.com/20019656/138297463-7a69fb48-ab15-4005-bf97-bc192ac167b6.png">

**Comment by frjo** [comment]
@fourthletter Then I have missed to update this there, it should be "Back to project" everywhere.

@sandeepsajan0 Can you add a fix for that to this PR please. Also add the same pattern to reviews so it looks the same everywhere, thanks!

Updated the title to cover this.
