### ISSUE TITLE
Remove default from determination forms

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2533]
## User story

As a user I would send out the wrong determination type because the default is either 'dismiss', 'accept', or 'need more information' depending on the workflow status. 

## Describe the solution you'd like in Hypha

I would like to select the determination type  I need (dismiss, accept, need more info) before sending out the determination to minimize human error.

<img width="1107" alt="Screen Shot 2021-09-03 at 3 29 36 PM" src="https://user-images.githubusercontent.com/20019656/132013494-ff14c398-03e6-450b-8092-5550879091f8.png">

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Applicants

**Ideal deadline**
December 2021

**Comment by fourthletter** [comment]
This is what they call a 'Rider' in Congress when one tries to add a provision to a piece of legislation.

## User story

As a user I may send the incorrect proposal form to ab applicant. 

## Describe the solution you'd like in Hypha

I would like to select the proposal 'category' type I need before sending out the proposal  to minimize human error.

<img width="930" alt="Screen Shot 2021-09-13 at 2 35 56 PM" src="https://user-images.githubusercontent.com/20019656/133084558-200b45b9-3edc-4b4a-9dd7-742bb355882b.png">


Priority

Low priority (annoying, would be nice to not see)
Affected roles

Applicants
Ideal deadline
December 2021

**Comment by frjo** [comment]
@sandeepsajan0 Can www add an "empty_value" to these fields to force users to make a choice before submitting the form?

For reviews we use "-- No reviewer selected --" as the empty value, follow the same format here.

**Comment by sandeepsajan0** [comment]
@frjo  I checked, we cannot add a simple empty value to determination form, because it is directly connected with [workflows/transitions](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/workflow.py#L1101). It is a ChoiceField, that doesn't allow simply an empty value. If we really wants to do this, I think we will need to change our transitions for determinations or need to add "empty_value" as initial step. Let me do more research, I'll update if I'll find any other good way to implement this.

**Comment by frjo** [comment]
@sandeepsajan0  The filed is required and an empty value should not be allowed when submitting the form.

We only need the field to have no value initially thereby forcing the user to make a conscious choice before submitting.

Today staff users from time to time forget to set the right value and submitting with whatever is the default/top value for this field.
