### ISSUE TITLE
Create a new contracting role

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2557]

**Comment by Erioldoesdesign** [comment]
Can I help with the testing of this in some way?

**Comment by frjo** [comment]
@Erioldoesdesign All issues with the testing label are on https://test.hypha.app. This link shows all of them https://github.com/HyphaApp/hypha/labels/Status%3A%20Needs%20testing. 

This particular issue has not so mush to test. Just confirm that the group/role exist and can be assigned to users.

**Comment by fourthletter** [comment]
tack! 💥 

<img width="784" alt="Screen Shot 2021-09-28 at 6 31 16 PM" src="https://user-images.githubusercontent.com/20019656/135128215-ac8e090a-31ff-47fa-8dcf-d7a50c5dfd85.png">

**Comment by Erioldoesdesign** [comment]
Awesome - I also tested and see it there and it saved all ok
<img width="807" alt="Screenshot 2021-09-29 at 10 29 05" src="https://user-images.githubusercontent.com/11681324/135242341-874293fb-e284-4ec1-92d4-a65ae9f2685f.png">
<img width="819" alt="Screenshot 2021-09-29 at 10 29 26" src="https://user-images.githubusercontent.com/11681324/135242345-01894ec4-e1d9-4e8a-84d1-6b7b6c7dce14.png">
