### ISSUE TITLE
Applicants see 'edit' button but can't edit

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2566]
As an applicant I see no information to explain why I can't edit the submission when there is an edit button.

<img width="841" alt="No details explaining why the 'edit' button is locked" src="https://user-images.githubusercontent.com/20019656/134973293-e940a836-8a40-485a-bf73-552ddb4a1500.png">

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Applicants

**Ideal deadline**
December 2021

**Comment by sandeepsajan0** [comment]
@fourthletter It depends on the phase of application, applicant don't have edit permissions in some phases.  Do you want to hide that `Edit` button instead of making it inactive?

**Comment by fourthletter** [comment]
@sandeepsajan0 That's a great idea. Please hide the `Edit` button from **applicants** when it is appropriate. Thank you!

**Comment by frjo** [comment]
@sandeepsajan0 @fourthletter I think the greyed out link with a padlock is quite clear. If there is a need to make it even more clear I would prefer a popup on hover with an short explanation. We use this in other places already.

![Skärmavbild 2021-10-19 kl  08 51 05](https://user-images.githubusercontent.com/191392/137858348-a1289574-ee90-4dd7-9fc2-b881d9414b12.png)

**Comment by sandeepsajan0** [comment]
@frjo I agree. @fourthletter  let's confirm this first, then I'll make the changes in draft PR.

**Comment by Erioldoesdesign** [comment]
I'm concerned that a popup/mouse-over help text is not accessible for users not using a mouse (using a touch device). Is there a way in our current UI styles to do non-hover help text? even if it's a hover-over that requires a 'x' close button.

I think generally help text should be contextual next to buttons/inputs and if no achievable in UI then it should not be there so my design perspective votes for not having an unusable button/link present on the screen until it is usable. Especially if there is no space to put contextual help text.


Just flagging as well that this grey #E5E5E5 is not WCAG accessible on a white background
![Screenshot 2021-10-28 at 11 36 17](https://user-images.githubusercontent.com/11681324/139240198-6f8507f7-59f1-4f78-bc9c-304bc73b96fc.png)
d:

**Comment by Erioldoesdesign** [comment]
Just an additional comment before someone says 'But hypha isn't touch/mobile/ipad friendly anyway' - I know that this is common knowledge but doesn't mean we can't start making it more non-mouse friendly with these smaller bugs/UI/UX improvements, as long as folks agree it's worth the effort.

**Comment by fourthletter** [comment]
Hello @sandeepsajan0, thank you for following up. Fredrik and I had a discussion and we agree the `Edit` button should not appear for applicants when they can not use it.
