### ISSUE TITLE
Unify base and base-apply templates

### ISSUE THREAD

**Issue by killapop** [HyphaApp/hypha#2573]
**Is your feature request related to a problem? Please describe.**

For an adoption that requires only the apply site of hypha there are still many interfaces like the login screen and open call listings that use the public site template (base.html). I know there are others that do as well but these are the ones to come to mind.
These templates also load different css bundles and its a little cumbersome to pick out which ones use them and don't while themeing a new deployment.

I know that there are plans to do away with the public site completely but until then some fixes to the current code to address this issue would help.

**Is your feature request related to an existing functionality? Please describe.**

As above.

**Describe the solution you'd like**

- to provide a setting `USE_UNIFIED_BASE_TEMPLATE = True | False` that allows adopters to decide to do this.
- in `base.html` check if the setting above is `True` and `{% extends "base-apply.html" %}` if not load the current contents.
- in `base-apply.html` put in conditions for authenticated user to load navs and user buttons.

**Describe alternatives you've considered**

currently modifying both templates independently + their included style bundles.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Developers

**Ideal deadline**

End 2021

**Comment by frjo** [comment]
We will soon scrap the public part of Hypha so closing this.
