### ISSUE TITLE
Unclear workflow language 'closing' or 'complete' on project page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2574]
## User story
> As a user I need to automate the filling of contract forms with PAF information. This would minimize human error and increase efficiency. 

## Describe the solution you'd like in Hypha
It's not clear what the process is to progress a project to 'closing' or 'complete'.

<img width="1174" alt="It's not clear what the process is to progress a project to 'closing' or 'complete'" src="https://user-images.githubusercontent.com/20019656/136102448-30587295-3f4d-49bc-9024-14ef58408a7c.png">

**Comment by frjo** [comment]
@fourthletter  I think this was never implemented.
