### ISSUE TITLE
Hypha will only create invoices in IntAcct, what info is needed from IntAcct?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2578]
After the walk-through of how OTF uses IntAcct in practice it has become clear that that a lot of the vendor and project set up must be done in IntAcct manually by OTF finance people.

Bank information does not need to be in either Hypha or IntAcct since payments are done in a completely separate system.

My suggestion is that we provide a nice view for finance that display all the needed vendor and project information. Making it easy to copy and paste information from Hypha into IntAcct.

Finance then add the following data to Hypha:

* Vendor ID
* Project ID
* Contract amendment number

Hypha can use this information for two purposes:

1. Create invoices in IntAcct via API calls.
2. Create the contract number since it is <project-id>-<vendor-id>-< amendment-number>

Tasks:

1. We need to decide in what step Finance will add the information.
2. We need to make banking information fields optional so OTF can turn them off.
3.  ?

**Comment by sks444** [comment]
Thanks for drafting this issue @frjo!

>My suggestion is that we provide a nice view for finance that display all the needed vendor and project information. Making it easy to copy and paste information from Hypha into IntAcct.

Good Idea!

>We need to make banking information fields optional so OTF can turn them off.

We can disable form steps for the multi step form based on some configurations. We can add fields at project settings or vendor form settings to disable steps where we ask for banking information.

Let's also schedule a call with Finance to understand Project Deliverables and Invoicing in Sage Intacct. Once understood the complete SageIntAcct flow that finance follows, we can discuss and decide things accordingly. cc: @fourthletter

**Comment by sks444** [comment]
A small summary of the yesterday's call with Finance.

Finance will put the Contract Project ID in Hypha(This is the final project for which they generate invoices). I am hoping this ID can also be used to get deliverables of the project. I will check with the APIs doc.

While creating an invoice in Hypha..we will generate a unique Invoice Identifier. (Finance will let us know about the format of this identifier)

We will use contract project id provided above to generate an invoice in SageIntAcct, also updating unique invoice identifier there in a field Finance will let us know about.

Now the SageIntAcct invoice generated above will go through different processes for it to be paid. In this process, entity of the originally generated invoice also gets changed. According to finance the originally generated invoice won't be related in any way to final entity which is getting paid.

We need something constant throughout this process..to be able to update the invoice status back to Hypha. Finance will use the Hypha's unique invoice identifier throughout the invoicing process. 

We will have a cron job which checks all the final paid invoicing entity in SageIntAcct(We also need to know what is that entity called in SageIntAcct). Using the unique invoice identifier we will find out the related Hypha invoice and update the status.
