### ISSUE TITLE
Clean out paymentrequest code in favour of invoice

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2579]
There are models/views/templates etc for paymentrequest. They should all be removed. If parts of the code still is relevant rename all funktions etc. to "invoice*".

- [ ] On the project overview page "/apply/projects/" there is a table "Payment Requests". Rename to "Invoices and list invoices with links to invoice views."
- [ ] On the staff dashboard there is a table "Active requests for payment". Rename ot "Project invoices" and rebuild "active_payment_requests" funktion to list invoices.

**Comment by frjo** [comment]
@sks444 Maybe a good issue for the new dev to get started with?

**Comment by sks444** [comment]
Yes, thanks @frjo
