### ISSUE TITLE
Remove all parts of Project approval forms model

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2583]
This is a left over from earlier unfinished development. It will never be used and should be removed.

**Comment by sks444** [comment]
@frjo, does this mean removing [all occurrences of ProjectApprovalForm](https://github.com/HyphaApp/hypha/search?q=ProjectApprovalForm)? Even for the funds, labs etc?

**Comment by frjo** [comment]
@sks444 Yes.
