### ISSUE TITLE
Applicant should not have access in any way to Approval form

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2584]
It can stay in the list to show the checkmark but applicant should not have any access to view or edit it.

![Skärmavbild 2021-10-13 kl  12 32 48](https://user-images.githubusercontent.com/191392/137296038-4048c97e-49f0-4f37-abdc-d07642dd09cb.png)

**Comment by frjo** [comment]
@sandeepsajan0 There are some attentional things needed for this. Easiest if I take it over letting you concentrate on the other issues.

**Comment by sandeepsajan0** [comment]
@frjo okay, I'll continue on other tasks.
