### ISSUE TITLE
Help text links are below the fold and not close to the application question

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2597]
## User story
Links to open new windows with useful contextual info are hidden below the fold and not close to the question. Users start writing their answer only to realize there was a link to useful help information below the fold. This wastes the users time and could lead to poorer quality answers.

## Describe the solution you'd like in Hypha

![Useful information hidden below the fold part 2](https://user-images.githubusercontent.com/20019656/137721407-55c3731d-8b7a-437a-8f0c-644a9b293bcf.png)

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Applicants

**Ideal deadline**
December 2021

**Comment by frjo** [comment]
This does not look like an application form, is it maybe a Review form?

**Comment by fourthletter** [comment]
I think this issue was already resolved. The help link is no longer below the fold.
