### ISSUE TITLE
Invalid activation template instructs user to "test to reset password"

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2601]
**Describe the bug**

An [instruction](https://github.com/HyphaApp/hypha/blob/44013c3c7aa5b1550ae97c10aa5e8d82f1da3d83/hypha/apply/users/templates/users/activation/invalid.html#L16) on the invalid activation account page is:

> "First test to reset your password. If that fails please contact %(ORG_SHORT_NAME)s"

**Expected behavior**

A more natural-sounding instruction might be:

> "First try to reset your password. If that fails please contact %(ORG_SHORT_NAME)s"

**Priority**

- Low priority (annoying, would be nice to not see)

Can submit a PR. We're overriding this with a translation, but in general we'd prefer to use defaults when possible.

**Comment by frjo** [comment]
That is my broken English, I will make a PR to fix it directly. Thanks for noticing it!
