### ISSUE TITLE
Add fields to enter IntAcct ProjectID, VendorID and amendment number in to Hypha

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2611]
Project ID is needed to retrieve the list of deliverables for a project.

Vendor ID together with Project ID seems to be needed to create invoice, more on that later.

The amendment number is needed together with the other two to construct the contract number. Amendment
 number start with "00" for the first contract and then the first amendment is "01" etc.

Contract number is: `<projectid>-<vendorid>-<amendment>`

In the database we can name these fields something like `external_projectid` etc. Then they can be reused by other integration and future devs can easily understand what they are.

The OTF staff member needs enter these 3 strings ( `<projectid>-<vendorid>-<amendment>`) into Hypha during the contracting and compliance phase - when the contract is being created.

**Comment by frjo** [comment]
@ei8fdb We need a place for these fields so OTF staff can fill them in.

**Comment by sks444** [comment]
### Query to get deliverables

As discussed on the API integration call: we could use `Program Project ID` to get all deliverables across contract for that project.

Question: **What is that field called in the APIs?**

A single line item has fields: `PROJECTID`, `PROJECTKEY`, `PROJECTDIMKEY`, `PROJECTNAME`: but from the response these basically seem to be returning GRANT information: `<PROJECTID>1001</PROJECTID>` `<PROJECTKEY>1</PROJECTKEY>` `<PROJECTDIMKEY>1</PROJECTDIMKEY>` `<PROJECTNAME>USAGM OTF Grant FY 2020</PROJECTNAME>`; and are same for all the line items(deliverables) returned by `List Purchasing Transaction Lines` APIs without any filters.

A line item is also related to something called `PODOCUMENT` which from the response seem to be the contract attached to line item.

A `PODOCUMENT` has several fields: `RECORDNO`, `DOCNO`, `DOCID`..I am able to use any of these as filters to list line items for that specific `PODOCUMENT`: E.g. to get deliverables for a project contract with document number: `CNTR-99`: [sandbox link](https://www-p02.intacct.com/ia/acct/frameset.phtml?.sess=6dsRV_Bp-3T85sLwXY88qDmGdP3mpw..#3164786360) I can successfully execute this query and get only three line items:

```xml
        <query>
          <object>PODOCUMENTENTRY</object>
            <filter>
                <equalto>
                    <field>PODOCUMENT.DOCNO</field>
                    <value>CNTR-99</value>
                </equalto>
            </filter>
          <select>
            <field>ITEMID</field>
            <field>ITEMNAME</field>
          </select>
        </query>
```

**But none of these fields seem to be the `Program Project ID` that we discussed yesterday.**

cc: @frjo 

### Update

Line items has field `DEPARTMENTID` which is `Program Project ID`.

**Comment by ei8fdb** [comment]
@frjo @sks444 I'm working on the contract creation designs at the moment so can't give you a full design **however** the compliance user will add them at the point their using the contract template  - https://github.com/HyphaApp/hypha/issues/2485

**Comment by fourthletter** [comment]
On 2022 March 2 during standup we discussed this issue. 

Developers suggested we add the contract number `<projectid>-<vendorid>-<amendment>`  and Project Contract CNTR-XXX (this is the contract request number generated by Intacct) directly into the PAF. These ID numbers will need to be on the a) contract and be used for b) invoicing.

**Comment by ei8fdb** [comment]
> On 2022 March 2 during standup we discussed this issue.
> 
> Developers suggested we add the contract number `<projectid>-<vendorid>-<amendment>` and Project Contract CNTR-XXX (this is the contract request number generated by Intacct) directly into the PAF. These ID numbers will need to be on the a) contract and be used for b) invoicing.

From this morning's standup discussion, we decided this wasn't a good idea as until the PAF has been approved by all required the contract creation step doesn't happen, and so the contract id won't be created.
