### ISSUE TITLE
Contractor edits submitted Fixed-Price invoice, makes changes and resubmits it.

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2619]
## Additional context
This is part of epic #2352.

## User story
> As a contractor I need to be able to modify a submitted invoice when requested so that I can be paid for the work completed.

## Describe the solution you'd like in Hypha - Design requirements

In Hypha the contractor:
- logs into after receiving an email notification from the PM
- reads the email requesting changes to a submitted invoice
- navigates to their project and chooses the invoice to be edited
- sees the invoice displayed and can edit the invoice, and make the required changes
	- these changes could be any/all of the following:
		- changing figures, dates in input fields
		- deleting uploaded invoice pdf file
		- uploading a new invoice pdf file
		- deleting uploaded supporting documents
		- uploading new supporting documents 
- can write a new message/comment
- saves the changes to the invoice

## Affected roles 
- Applicants

### Demo
Need to add.

### Wireframes

![12. 1](https://share.balsamiq.com/c/jLe3NVttjozNZrpHV6NZkf.png)

12.1 - The contrctor navigates to their project area and chooses the invoice to be edited. In this case invoice 09.

![12.2](https://share.balsamiq.com/c/6ZRvAwUbB9dCWuCEEVDWxv.png)

12.2 - The contractor sees the invoice displayed and can edit the invoice to make the required changes. These changes could be any/all of the following:
		- changing figures, dates in input fields
		- deleting uploaded invoice pdf file
		- uploading a new invoice pdf file
		- deleting uploaded supporting documents
		- uploading new supporting documents 

![12.3](https://share.balsamiq.com/c/ieoxeho5ENx8v1RxQTnQgW.png)
12.3 - here the contractor has changed the amount (from 3900.50 to 2900.50), they have also deleted the invoice pdf, and will upload another.

![12.4](https://share.balsamiq.com/c/kLBp6S7JdzADP8QLET6fdH.png)
12.4 - here the contractor has uploaded a new invoice pdf file - project-name-Invoice-june-2021-correct.pdf

![12.5](https://share.balsamiq.com/c/3iLX2b8HWHnVBE1XnvfDDr.png)
12.5 - The contractor has also written a new message for the OTF PM. The contractor then presses "submit changes" and the invoice has been submitted.

![12.6](https://share.balsamiq.com/c/jkuWaHhj8QFx9WvFFUk241.png)
12.6 - The contractor now sees the invoice file embedded on the page. They can now close the browser window, or navigate back to the project area.

![12.7](https://share.balsamiq.com/c/wPQJYT6ExJWqMjJpZBpYR8.png)
12.7 - The project page now shows the invoice with the resubmitted status. 

### What happens next?
The invoice will now be visible in the PM's list of invoices to review with the _resubmitted_ status.

**Comment by sks444** [comment]
Thanks @ei8fdb;

One question that was also kind of pending from https://github.com/HyphaApp/hypha/issues/2354#issuecomment-944074994

> Text entered into 'free text comment' does not render or stored in Hypha

Where are we displaying the `Message for PM`..I believe that will go in the communications tab?

**Comment by ei8fdb** [comment]
> Where are we displaying the `Message for PM`..I believe that will go in the communications tab?

Yup agreed, it can go in the communications tab. Let's see how that works.

**Comment by fourthletter** [comment]
QA

In Hypha the contractor:
- [ ] logs into after receiving an email notification from the PM (pending)
- [ ] reads the email requesting changes to a submitted invoice (pending)
- [x] navigates to their project and chooses the invoice to be edited
- [x] sees the invoice displayed and can edit the invoice, and make the required changes
	- these changes could be any/all of the following:
		- [x] changing figures, dates in input fields
		- [x] deleting uploaded invoice pdf file
		- [x] uploading a new invoice pdf file
		- [x] deleting uploaded supporting documents
		- [x] uploading new supporting documents 
- [x] can write a new message/comment
- [x] saves the changes to the invoice

Notifications/Communication
- [x] then the Contractor writes a message explaining what is incorrect with the invoice, and how the contractor needs to fix it.
- [x] A status update is shown in the Activity feed 
- [x]  Contractor's message will also be there in the communication tab
