### ISSUE TITLE
Slack integration doesn't work directly with Slack

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2630]
**Describe the bug**

Hypha has a `SlackAdapter` for messaging and it counts on this channel to deliver messages to staff (in lieu of email), but what's called a Slack integration appears to depend on a [Hubot webhook intermediary](https://github.com/OpenTechFund/botf) and doesn't appear to work directly with the Slack API (or the Zulip Slack compatibility API).

**To Reproduce**

1. Add a Slack API endpoint URL and some channels to the environment
2. Change workflow states in a way that should message Slack
3. No message is sent

**Expected behavior**

Hypha could either work with Slack's API directly or better document the Hubot requirement.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Developers

**Additional context**

Unknown is whether the formatting of the messages would have to change if it sent to Slack directly, how to deal with authentication (a key? pre-authed per-channel webhook?), whether sending to multiple channels would require one call per channel and whether there'd be an important loss of functionality without Hubot. But I'm willing to create a PR.

**Comment by chriszs** [comment]
To clarify, if I were to PR this, it'd create a separate Hubot adapter that might inherit from the Slack one or vice versa.

**Comment by frjo** [comment]
Yes, this definitely needs documentation. OTF uses this https://github.com/OpenTechFund/botf running on Heroku.

We intend in the future to make all notifications be e-mail be default and then allow each organisation (or user) to make their choices. The current Slack integration will be one option.

**Comment by chriszs** [comment]
Makes total sense and is exactly what ARDC is asking us for. Would be willing to provide PRs toward that end, too.

**Comment by chriszs** [comment]
Okay, so far I've written a Zulip adapter that inherits from the Slack one. My plan is to open a separate issue for that as a feature, inherit from an abstract chat messaging adapter for Zulip and Hubot, and add a Slack webhook or REST API integration (which shouldn't be hard to do). _Edit:_ I wonder if the general case here is entirely chat, or if it's webhooks in general.

**Comment by Erioldoesdesign** [comment]
@chriszs Can you expand on this: "Edit: I wonder if the general case here is entirely chat, or if it's webhooks in general."

**Comment by chriszs** [comment]
@Erioldoesdesign Sure, I can try. Right now Hypha sends an event to a URL specified for Hubot. I'm proposing expanding that to cover Zulip and Slack directly. Each works similarly by receiving an event message at a URL. But in addition to those chat applications, there may be other types of systems that could benefit from event notifications. IFTTT and Zapier come to mind as popular ways to integrate systems using those events, for instance. Through those, one could theoretically do things like add a line to a spreadsheet or update a card on a Trello board. If the base adapter for this was a webhook adapter, from which the chat apps extended, there may be other integrations like those we might be able to get without much additional work.

**Comment by frjo** [comment]
@chriszs Excellent ideas! Defintly webhooks in my mind, anything that can receive notifications for users. 

That we now happen to have Slack integration is because OTF use it for all internal communication.

My end goal is to have all notifications default to e-mail. Then an organisation can set their own defaults, like OTF would set that staff notification be default goes to Slack. Each user then would have the option to pick among the available options. Hypha should also have in app notifications that are always active.

We now only have a Slack field in the user account and would need to add a Zulip field etc. but that is easily done.

**Comment by Techslammer** [comment]
I think this is a feature that OTF would like to put resources towards later this year.  Addilng a slack integration for Django that @frjo suggested: https://pypi.org/project/django-slack/

**Comment by frjo** [comment]
We are working on this in https://github.com/HyphaApp/hypha/issues/2852 so closing this issue.

**Comment by Techslammer** [comment]
thanks
