### ISSUE TITLE
Require password on account e-mail address change

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2643]
**Is your feature request related to a problem? Please describe.**

As a user, when I am logged into my account on a device that I trust and I would like to change my email associated with my account. I will be required to enter my current correct account password in order to confirm the change of email process.

Makes it harder for bad people to take over the account by e.g. session hijack.

**Is your feature request related to an existing functionality? Please describe.**

Not existing functionality but existing section in the /account area

**Describe the solution you'd like**

A solution that includes the logged in users current correct account password on request of email change would also include error pathways for users including:
- If a user enters their password incorrectly
- A user enters an invalid email as a new email (could also include an email that does not have accepted organisational affiliation in the email address)
- If a user spends to long on the page session and 'times out'
- Compatible with any existing 2-factor processes on that account and instance

**Describe alternatives you've considered**

- Alternative to password entry on email change might be using any current 2-factor process.

**Additional context**

This was part of the recommendations given by the security audit team circa Aug 2021.

**Priority**

- Low priority (annoying, would be nice to see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners

**Ideal deadline**

End of Q1 2022

**Comment by fourthletter** [comment]
This works! 100 points to Gryffindor! 🌈 

Please change text from 'Email change requires you to put password' to **Please re-enter your password to verify your account.**


QA

- [X] Changing the user's name does not trigger a verification module
- [X] Changing the user's email triggers a verification module (image 1)
- [X] Verification module asks the user to enter their password to verify email change (image 2)

Image 1
<img width="575" alt="Screen Shot 2021-12-03 at 8 38 31 AM" src="https://user-images.githubusercontent.com/20019656/144563854-ee9cfbc6-82a2-403d-b880-70b8d04bccc1.png">

Image 2
<img width="838" alt="Screen Shot 2021-12-03 at 8 38 18 AM" src="https://user-images.githubusercontent.com/20019656/144563851-31aeb2a3-a9fc-44f0-bb38-5f86f54d410c.png">
