### ISSUE TITLE
Require password on account 2FA change

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2644]
**Is your feature request related to a problem? Please describe.**

As a user, when I am logged into my account on a device that I trust and I would like to change my 2 factor authentication associated with my account. I will be required to enter my current correct account password in order to confirm the change of 2 factor authentication.

**Is your feature request related to an existing functionality? Please describe.**

Not existing functionality but existing section in the /account area

**Describe the solution you'd like**

A solution that includes the logged in users current correct account password on request of 2 factor authentication change would also include error pathways for users including:

* If a user enters their password incorrectly
* A user enters an invalid 2 factor authentication process (this may need to be agreed at an organisational level e.g. this organisation approves use of google authenticator app and Microsoft's authenticator app but not others etc.)
* If a user spends to long on the page session and 'times out'

**Describe alternatives you've considered**

N/A

**Additional context**

This was part of the recommendations given by the security audit team circa Aug 2021.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners

**Ideal deadline**

Date when you'd like to see this accomplished and a reason, if appropriate.
End of Q1 2022

**Comment by ei8fdb** [comment]
@sks444 @frjo 

To answer your questions:

1. where should the user be prompted when disabling/changing 2FA?

Here is the proposed userflow showing where the user is prompted for their password:

![hypha#2644.1 - Require password on account 2FA change](https://share.balsamiq.com/c/gLdMj6RqeyJDLawUbRzgtu.png)

2. where should the user be prompted when requesting to view the 2fa backup codes?

![hypha#2644.2 - Require password to view backup tokens](https://share.balsamiq.com/c/8NFA5XQAsVu4K1bka33LqA.png)

**Comment by sandeepsajan0** [comment]
@ei8fdb We don't need password when user is enabling the 2FA for the first time on their account?

**Comment by frjo** [comment]
@sandeepsajan0 No, I do not think we need a password for first time setup.

**Comment by ei8fdb** [comment]
@sks444 I've updated [the design](https://camo.githubusercontent.com/4c4ff6e4c0c4dff3a9c7712cae71b55a1c9eba27a614ad55fbc051304879fa01/68747470733a2f2f73686172652e62616c73616d69712e636f6d2f632f384e464135585141735675344b31626b6133334c71412e706e67)for requiring the user password to show the backup codes.

Can you review it and tell me if this is the design you were suggesting?

@Erioldoesdesign on the OTF standup today we discussed about opening an epic issue to improve the usability of the account section. Included in this would be to implement some of the improvements I suggested in the designs above. (They will not be implemented as part of the OTF security audit work) We can talk about what needs to be included.

**Comment by sks444** [comment]
@ei8fdb, yes, that looks good for the current implementation. Thanks!

**Comment by frjo** [comment]
This is deploying to test. Will be available to test in a few minuts.

**Comment by fourthletter** [comment]
@sks444  I was NOT led to a screen that requested me to enter a new password. Missing steps 3, 4, and 5 in the above design.

Step 1:
<img width="884" alt="Screen Shot 2021-12-06 at 8 14 55 PM" src="https://user-images.githubusercontent.com/20019656/144907937-8774a1b9-4011-438b-b9dc-7caf3b74341c.png">

Step 2:
<img width="898" alt="Screen Shot 2021-12-06 at 8 17 58 PM" src="https://user-images.githubusercontent.com/20019656/144908222-556b0295-b714-46e7-ac4e-999342ea2b28.png">

Step 3:
<img width="878" alt="Screen Shot 2021-12-06 at 8 15 00 PM" src="https://user-images.githubusercontent.com/20019656/144907927-8f27ff10-be1c-4a9c-a2c7-02f5dec0f67c.png">

**Comment by sks444** [comment]
Hi @fourthletter, can you test this again, this works fine for me on test.

**Comment by fourthletter** [comment]
@frjo @sks444 Looks great! Please deploy on live.

**Comment by Erioldoesdesign** [comment]
Sorry for the delay - I also tested the 'remove 2fa' and got the enter password process!

Understand this has been closed but just noting that the language token (which is the 6 digit number on 2fa apps) might be worth referring to as token/number when setting up 2fa... @ei8fdb did we set up that epic to capture improvements to the settings page? or should I create it?

**Comment by Erioldoesdesign** [comment]
Noting there's conversation re. improving usability and UX of settings happening here: https://github.com/OpenTechFund/apply-app/issues/31 but it's on hold pending critical OSS governance conversations.

**Comment by ei8fdb** [comment]
> @ei8fdb did we set up that epic to capture improvements to the settings page? or should I create it?

We've not yet creted an epic, but this is getting confusing now as we're talking about 2FA here in Hypha-Core and also in OTF repo under https://github.com/OpenTechFund/apply-app/issues/31.

**Comment by Erioldoesdesign** [comment]
> > @ei8fdb did we set up that epic to capture improvements to the settings page? or should I create it?
> 
> We've not yet creted an epic, but this is getting confusing now as we're talking about 2FA here in Hypha-Core and also in OTF repo under [OpenTechFund#31](https://github.com/OpenTechFund/apply-app/issues/31).

Yup I went digging for it and found it

**Comment by ei8fdb** [comment]
> Noting there's conversation re. improving usability and UX of settings happening here: [OpenTechFund#31](https://github.com/OpenTechFund/apply-app/issues/31) but it's on hold pending critical OSS governance conversations.

Right, I have no preference where it should be put. If they are different pieces of work can we define them well, or else put them in the same issue. Otherwise it'll get confusing.
