### ISSUE TITLE
Vendor document number and Transaction type for creating invoices in IntAcct

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2652]
Vendor document number: HP######

Transaction type "Contract Invoice Release"

**Comment by fourthletter** [comment]
We thinking the vendor document number: HP###### in Intacct could be the **Invoice Number** in Hypha (see image below)

<img width="976" alt="Screen Shot 2021-11-24 at 1 13 48 PM" src="https://user-images.githubusercontent.com/20019656/143236489-a33febfb-4cee-4886-a356-e9b6c981e1b6.png">

**Comment by ei8fdb** [comment]
The invoice number takes the format HP000000. 

This format is difficult for humans to read. To make this text easier to read we will use chunking. [Chunking is a concept](https://www.nngroup.com/articles/chunking/) of breaking text into smaller chunks to help users process, understand, and remember it better.

Assuming @fourthletter has no objections, @sks444 @frjo ⭐️Golden rule⭐️: whereever the invoice number is displayed, it is chunked into the following format:

HP-3 digits-3 digits, i.e.: HP-000-001

Designs for how the Invoice number should look for each user view:

![image](https://user-images.githubusercontent.com/1899506/159463423-aec75687-4d86-4a1a-883d-acfeaf596146.png)

![image](https://user-images.githubusercontent.com/1899506/159463548-b7bfda82-52d1-4890-bd34-f8866f6c0dd3.png)

![Invoice number chunked](https://share.balsamiq.com/c/exzPU7Hh18Bx3euEhsTDZ4.png)
