### ISSUE TITLE
A banner/notification in hypha that lets users know there is a new version of hypha available and/or a security related update that should applied asap

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#2656]
**Is your feature request related to a problem? Please describe.**
As an adopter of Hypha I want a way to know that an update/version has happened to the main Hypha repositories code without having to hear from a synchronous meeting, email or channel comms or looking in releases in the (this) github repository.

This applies to feature release large and small and also security updates but both of these (and other new types of updates) may require different actions or information for adopters to 'follow up on'

e.g. For a security update the adopters may want to be able to assign a developer/person with specific code and domain knowledge in order to assess that adopters Hypha instance is ready to 'receive' that update and be able to 'bank' the update message as a reminder.

The hypha adopters may also want to view a history of updates/notifications of this nature in a section of settings (for example) and when/if they were actioned/updated by someone in their organisation.

**Is your feature request related to an existing functionality? Please describe.**
Wagtail may already have existing functionality that allows for notifications and banners to be shared in across instances of use. @frjo may investigate this at a later date.

Possible wagtail implementations: 
https://docs.wagtail.io/en/latest/reference/settings.html?highlight=email#wagtail-update-notifications 

Wagtail audit log might be needed if adopters are 'actioning' on updates to hypha main: https://docs.wagtail.io/en/v2.14.2/advanced_topics/audit_log.html

A user of wagtail in the wagtail repo has asked about Wagtail updates in a similar fashion here: https://github.com/wagtail/wagtail/issues/5541

**Describe the solution you'd like**
Using existing styles in wagtail, when a hypha adopter logs into their Wagtail admin back end (or/and their instance of hypha via wagtail) they see a dismissible notification banner at the top or bottom of the page (the section that doesn't interrupt critical call to action buttons/operations etc.

Notifications would stack (on top of each other if applicable e.g. there was a release on Dec 1st 2021 and then on Dec 10 2021 and the hypha adopter user did not log in until the 12th Dec 2021 they would see both notifications stacked on top of each other) and be dated in connection to the associated release number and date.

**Describe alternatives you've considered**
It's possible to remove the functionality of an audit log or history of notifications. This is not MVP for this feature.
It is possible that the notifications can link directly to release notes in Github instead of having any explainor text explaining the update due to time constraints for constructing specific messaging. e.g. A hypha update is available [LINK TO RELEASE] vs. 'There has been an update to [section of hypha] and affects [this part] and [this art] and he nature of the update is both feature releases and security update'. etc.

**Additional context**
It might be useful in the future to know which adopter developers worked on a release in this notification.

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**
- Staff

(Possibly)
- Reviewers
- Developers

**Ideal deadline**

End of 2022

**Comment by frjo** [comment]
We can see how Wagtail implements this feature.

**Comment by Erioldoesdesign** [comment]
Gave this issue more detail and flavour according to what I think an adopter user needs from this and what kinds of actions post notification might be needed to do.

Also did a little bit of Wagtail digging to try and find relevant info but unsure If I was on the right track.
