### ISSUE TITLE
Remove Hypha styleguide available "/styleguide/"

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2685]
Add all commonly used elements to this page.

**Comment by fourthletter** [comment]
Let discuss during a Maintainers' call if we need additional support and resources for this initiative. Thanks!

**Comment by theskumar** [comment]
Torchbox has a really neat library that will allow us to maintain it in a really neat way. Worth exploring

https://github.com/torchbox/django-pattern-library
