### ISSUE TITLE
[META/EPIC] Reporting 

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2708]
# Reporting

## Is your feature request related to a problem? Please describe.

As a funder managing applicant projects and fund in Hypha, I want to be able to report across the lifecycle of a project on a number of key metrics, deliverables and details so that I might be able to better understand 'at a glance' how well certain organisational KPI's and goals are happening across projects being managed in Hypha

A clear and concise description of what the problem is. Ex. I'm always frustrated when 
Currently reporting is done via existing functions in Hypha/Wagtail Admin and outside tools (e.g. google sheets, airtable, forms, sms, slack human labour etc.) we'd like to bring that effort inside of Hypha.

## Is your feature request related to an existing functionality? Please describe.

Connected to project workflows through Hypha and deliverables. Reporting 'touches' multiple places within Hypha.

## Describe the solution you'd like

Scoping of implementation feasibility happens here in this Google Spreadsheet:
https://docs.google.com/spreadsheets/d/1-anh9NM8CyChGX2IjpJjl81P-wdLVYJHlJr3Q0J0X4Q/edit#gid=1610025234

Individual feature pieces will be sub-epics and issues within this epic.

### Describe alternatives you've considered

Currently reporting across the various context is service with tools outside of Hypha and with hacks within Hypha. We'd like to bring in cohesive, usable reporting inside of Hypha as an alternative to the hacks and external tools already being used to report on Funder work.

### Additional context

Scoping of implementation feasibility happens here in this Google Spreadsheet:
https://docs.google.com/spreadsheets/d/1-anh9NM8CyChGX2IjpJjl81P-wdLVYJHlJr3Q0J0X4Q/edit#gid=1610025234

Design Miro's: https://miro.com/app/board/o9J_l5LQgJ0=/

Feature discussion on forum: https://we.hypha.app/t/reporting-functionality-discussion-and-clarity/162/23

Original Adopter request: https://we.hypha.app/t/evolving-existing-reporting-capabilities/101

Deliverable/Objective/Milestone = same terminology for same 'thing' used across different Adopters

### Priority
- High (Roadmap priority for Reset Adopter)

### Affected roles

**In part 1: Project updates from fundees to funders - High Priority**
- Staff
- Reviewers
- Applicants

**In part 2: Funders reporting to funders (govt. public etc.) - High Priority**
- Partners
- General public

**In part 3: Funders reporting internally comms - Medium Priority**
- Staff
- Reviewers
- Applicants
- Partners

**In part 4: System performance of Hypha - Lowest priority**
- Developers

### Ideal deadline

TBC - will follow sprint cycles of 2-3 weeks

**Comment by fourthletter** [comment]
I will be closing issues related to Reporting META/EPIC https://github.com/HyphaApp/hypha/issues/2708 as part of the quarterly rebasing process and [current priorities](https://github.com/HyphaApp/hypha/wiki/Roadmap).

Please reach out if you have any questions or concerns.
