### ISSUE TITLE
Inconsistent design of 'Assign' user interface

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2723]
There are currently three dropdown menus to assign new users on the submissions interface. Each dropdown menu is different. As a user I would like to see consistency across these features. 

### Case Study: Reviewer

"No user selected"

![Screenshot 2022-06-04 6 57 08 PM](https://user-images.githubusercontent.com/20019656/172017480-e0f14650-2013-4fb3-a49d-15b0bf51074a.png)

### Case Study: Partner

The default is the word "Partner." Does not contain a "no user selected" option

![Screenshot 2022-06-04 6 57 34 PM](https://user-images.githubusercontent.com/20019656/172017500-903e6782-f24f-4269-b4df-75b1917a980d.png)

### Case Study: Lead

Does not say "no user selected" only dashes

![Screenshot 2022-06-04 6 57 46 PM](https://user-images.githubusercontent.com/20019656/172017510-e073f874-92e0-40e8-bd3f-0c5a11eb31d9.png)

**Comment by frjo** [comment]
There are two styles of dropdown. The difference is that one is for single select and the other is for multi select.

**Comment by fourthletter** [comment]
@frjo Thanks for following up. I updated the issue because of the "no user selected" option in each of the dropdown menu.
