### ISSUE TITLE
"No directory" warnings when running tests on a new clone

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2725]
**Describe the bug**

When I run tests on a fresh "from scratch" installation: `python manage.py test --settings=hypha.settings.test`

I receive hundreds of warnings similar to this:

```
./Users/slifty/.local/share/virtualenvs/hypha-mBDD0kdH/lib/python3.10/site-packages/whitenoise/base.py:115: UserWarning: No directory at: /Users/slifty/Maestral/Code/personal/hypha/static/
  warnings.warn(u"No directory at: {}".format(root))
```

It is possible I missed a key step (or a step failed unrelated to this issue) that would create this directory; but wanted to raise the issue in case.

**To Reproduce**

1. Follow the "From scratch" guide
2. Run tests: `python manage.py test --settings=hypha.settings.test`
3. See error

**Expected behavior**

The tests should run normally

**Priority**

- Low-Medium: This does not impact the end user, but it is an issue that new contributors may face.

**Affected roles**

- Developers

**Screenshots**

N/A

**Desktop (please complete the following information):**

 - OS: MacOS 12.1
 - Browser N/A
 - Version N/A

**Additional context**

Manually creating the `static` directory fixes the issue and allows tests to run as expected.

**Comment by frjo** [comment]
The `static` directory should be created when running `collectstatic`. Tested it on a fresh install myself just now and it worked there (macOS 12).

I have found it is best to run `collectstatic` like this:

`python manage.py collectstatic --noinput --settings=hypha.settings.dev`

I really need to update these docs pages, thanks for reminding me of this!

These two doc pages needs updating:

https://github.com/HyphaApp/hypha-docs/blob/main/contributing/localdevelscratch.md
https://github.com/HyphaApp/hypha-docs/blob/main/deployment/stand-alone.md

**Comment by slifty** [comment]
Just a heads up that it looks like these warnings are appearing in the CI tests as well:

<img width="1076" alt="image" src="https://user-images.githubusercontent.com/208884/154291246-cb9769c6-7399-4fcf-8ce5-17fadb2eb5f5.png">

I wonder if it would be worth making sure the directory exists as part of the test command too

(or adding a `static/.gitkeep` so it's just there as part of the repo)

**Comment by frjo** [comment]
I fixed that earlier today in https://github.com/HyphaApp/hypha/pull/2727. 

Does `collectstatic` create the `static` dir in your local  environment or are there more issues at play?

**Comment by slifty** [comment]
Oh nice -- and yes it does; my issue / the original issue is resolved.
