### ISSUE TITLE
Consistent table headers on submissions tab and dashboard tab

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2734]
**Is your feature request related to a problem? Please describe.**

The "My dashboard" (`/apply/dashboard/`) page has a table that lists past reviews.
The "Submissions" (`/apply/submissions/`) page has a very similar table (the "Role" field is removed)

The content is almost the same, but the order of the columns is different.  One of our users requested that the order be consistent between the two interfaces to create a more predictable user experience.  I wanted to raise the issue in case this would be of interest to the Hypha team as well.

![image](https://user-images.githubusercontent.com/208884/154750964-fbf807de-afed-4350-9f5b-b05ba6a58d80.png)

![image](https://user-images.githubusercontent.com/208884/154750978-aa0fa363-753d-45c2-a2b9-713f261ef357.png)

**Describe the solution you'd like**

The same order of columns between both tables.

**Describe alternatives you've considered**

The alternative would be to leave it as is, or make the column for each table order completely customizable by the local instance.

**Additional context**

I'd be happy to open a PR with this for the team's consideration.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers

**Ideal deadline**

None.

**Comment by frjo** [comment]
Good to make them look the same, as much as possible.

**Comment by fourthletter** [comment]
@slifty Thank you for flagging this. At the moment we will select one column order and ensure this design is consistent throughout the platform.

**Comment by Erioldoesdesign** [comment]
Would love this UX bug fixed :) we'll happily receive that PR

@slifty quick question, as we don't yet have points sizing (or any sizing or S/P rank priority process yet) would you say this is a very low points? like a 1 or a 3 on the agile points scale? We may end up using tshirt sizes too so I would say this is XXS (xtra xtra small)

**Comment by slifty** [comment]
This is super small (XXS) and I do have the local fix (we actually diverged which columns to render on both these tables in our local instance -- adding ID and removing one of the columns).

Ultimately it comes down to:

1) One of the table explicitly specifies the sequence of ALL columns.
2) The other uses the Django table's `"..."` magic sequence key to specify sequence.  Unfortunately the field order Django calculates doesn't match the specified sequence.

The solution is to explicitly specify the order on *both*.

I'll open that PR shortly.
