### ISSUE TITLE
Support localization for reviewer toggle labels

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2736]
**Is your feature request related to a problem? Please describe.**

We would like to change "All Assigned Advisors" to "All Assigned Reviewers" in the reviewer sidebar, since the term advisor isn't used elsewhere in our application flow.

Normally I would use localization to translate the string, however this particular line is hard coded [in the javascript](https://github.com/HyphaApp/hypha/blob/47ed4ff6168905ff05d540190897410faea764a0/hypha/static_src/src/javascript/apply/toggle-reviewers.js#L17)

![Advisorlabel](https://user-images.githubusercontent.com/208884/155377726-581f9a32-3042-4975-8285-58cc0c3e17d2.gif)

**Describe the solution you'd like**

It would be helpful to define the `Hide All Assigned Advisors` and `All Assigned Advisor` strings in a way that supports localization.  This would prevent a code-level diff on those lines.

One implementation solution could be to define both labels in the template (where localization already exists) and change the frontend logic to hide / show the server-rendered DOM elements, instead of injecting text directly from a line defined in the javascript.

**Describe alternatives you've considered**

I was going to originally open this issue as a question -- in particular, I'm not sure if this is *already* possible through localization tooling.

For the Django template side I have the following in my :

```
msgid "All Assigned Advisors"
msgstr "All Assigned Reviewers"

#: hypha/static_src/src/javascript/apply/toggle-reviewers.js:14
msgid "Hide All Assigned Advisors"
msgstr "Hide All Assigned Reviewers"
```

The first line does modify the template as expected.
The second line was a shot-in-the-dark attempt (which didn't work)

The translated line is overwritten when the user presses the toggle button.

**Additional context**

I would be happy to open a PR for this if the above approach sounds reasonable; if another approach is preferred I should also be able to but would need direction on that preferred approach.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Developers

**Ideal deadline**

I have a local fix, so this is not time sensitive.

**Comment by frjo** [comment]
The default text should be "reviewers" and not "advisors", we are using "reviewers" everywhere else. This is a very quick PR.

Hardcoded strings in javascript is not nice. Definitely should have them in DOM and just swap them with javascript.

**Comment by chriszs** [comment]
There's a couple places where there's hardcoded stuff in JS. Dealt with this somewhere else. There's a Django way to translate JS, but I don't know if it makes sense to do in Hypha or not.

**Comment by frjo** [comment]
I would like to replace all of them. Maybe let Django place the translatable string in a data-* attribute that javascript then easily can pick up.

**Comment by fourthletter** [comment]
Could we please also change "All Assigned Advisors" to "All Assigned Reviewers" in Hypha Core's reviewer sidebar? The term _advisor_ isn't used elsewhere in Hypha's application flow. Thank you. 

The individuals on the "All Assigned Advisors" list are referred to as **Reviewers** in the WagTail admin:

<img width="551" alt="Screen Shot 2022-02-24 at 8 45 29 PM" src="https://user-images.githubusercontent.com/20019656/155596532-31bc229b-5ad8-4861-96ea-6c27adaafc1a.png">


**External Review** on the workflow status bar
<img width="1270" alt="Screen Shot 2022-02-24 at 9 01 19 PM" src="https://user-images.githubusercontent.com/20019656/155598636-063a3071-dd61-4599-bf92-00a75423741f.png">

**Reviewers** in Actions to take 
<img width="348" alt="Screen Shot 2022-02-24 at 9 01 36 PM" src="https://user-images.githubusercontent.com/20019656/155598758-44574f26-842c-4b5d-abe5-1418f6a4be5d.png">

**Comment by Erioldoesdesign** [comment]
Sounds like the 'quick fix' for @slifty is to change hard coded word to '...reviewers' but the preferable PR would be adding these to the translations and assuming that's more effort.

I think the quick fix was done here: https://github.com/HyphaApp/hypha/pull/2737

So does this issue want to capture the want for this to be in translations @frjo ?

**Comment by frjo** [comment]
@fourthletter That is already done in PR https://github.com/HyphaApp/hypha/pull/2737

**Comment by frjo** [comment]
A new more general issue about removing all hardcoded ( and therefor untranslated) strings from JavaScript would be the best.

**Comment by Erioldoesdesign** [comment]
Added a new issue https://github.com/HyphaApp/hypha/issues/2752

**Comment by Erioldoesdesign** [comment]
I think this one can be closed 👍
