### ISSUE TITLE
0.0 - Hypha can store 'organisational areas of focus and goals/mission'. Build 'tags' or 'categories' within Hypha/Wagtail.

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2742]
0.0 - Hypha can store 'organisational areas of focus and goals/mission' as a way to 'define' or 'categorise' an  application for funding and subsequent report information from a fundee. Build 'tags' or 'categories' within Hypha/Wagtail.

**Is your feature request related to a problem? Please describe.**

As a part of the Reporting META/EPIC https://github.com/hyphaapp/hypha/issues/2708 Hypha users need a way to 'create' categories and/or 'tags' that can later be connected to deliverables. These categories and/or 'tags' must be a 'flat list' as in the 'Core areas of funding' never have 'nested' 'children' tags or terms inside them -> this is where we encourage Adopters to use 'destructible' meta terms to further define criteria if wanted. Advised they don't make things too complicated.

Ideally 'Core areas of funding' as a section within Wagtail would be able to be changed in translations if a Hypha user has different terminology they use to describe a 'tag' for categorising deliverables in terms of 'Core areas of funding' that they would later like to build any reporting from.

This new section in Wagtail would not 'replace' meta terms or using screening options as a way to better define and categorise funds to build reporting from but be a more 'fit for purpose' method of doing this work within Hypha.

Design investigation on Miro: https://miro.com/app/board/o9J_l5LQgJ0=/?moveToWidget=3458764516819905383&cot=14
Option 2 in the Miro board was the preferred way of implementing this work.

**Is your feature request related to an existing functionality? Please describe.**

Linked to the existing way that Meta Terms work but also linked to funds/projects by way of (still in development from OTF Finance work) deliverables section.

**Describe the solution you'd like**

As a user i want to follow these steps:

1. A member of the funding organisation that manages Hypha and has access to the Wagtail admin through appropriate permissions (named as 'user' after this) goes to the Wagtail admin screen.
2. The user visits the 'Apply' section of Wagtail admin and sees in the menu structure a menu item 'Core areas of funding'
![Screenshot 2022-02-25 at 15 24 57](https://user-images.githubusercontent.com/11681324/155741361-8393dd77-b324-4d83-b7db-783c30ac1737.png)
3. The user clicks here to open up a new page section where they can add terms from a button in the top right of the screen:
![Screenshot 2022-02-25 at 15 26 17](https://user-images.githubusercontent.com/11681324/155741577-623cc500-1b3d-4234-ae50-9f79da794b79.png)

4. From here they can fill out form fields that name the core are of funding 'tag', assign a parent (unless they are creating a parent tag) and add whether that tag should be archived, appear on dashboard filters, be available to applicants, and add descriptive help text for that tag. They can then save the tag.
5. The user can edit this tag from the main list page.
![image](https://user-images.githubusercontent.com/11681324/155743558-b75482f0-af99-43d5-b98a-d66b3175c8f6.png)

**Describe alternatives you've considered**

Alternative implementations options were:
1. Use Meta terms as a base to create the parent to child tree tags/categories for goals and areas of focus.
2. Screening options can be used for area of focus/goals.
3. A new way of tagging via UI that does not follow existing similar functions.

**Additional context**

Bigger context for the reporting feature can be found here: https://docs.google.com/spreadsheets/d/1-anh9NM8CyChGX2IjpJjl81P-wdLVYJHlJr3Q0J0X4Q/edit#gid=936698147

And in the META/EPIC: https://github.com/hyphaapp/hypha/issues/2708

**Priority**

- High (keeping you from completing day-to-day tasks) in regard to the reporting feature development generally.

**Affected roles**

- Staff
- Reviewers
- Partners

**Ideal deadline**

March 21st

**Comment by Erioldoesdesign** [comment]
OTF calls there 'Core areas of Funding' 'Focus areas' this would need to be covered in the user documentation.

Tagging @emlini re. docs

**Comment by fourthletter** [comment]
> Is your feature request related to an existing functionality? Please describe.
Linked to the existing way that Meta Terms work but also linked to funds/projects by way of (still in development from OTF Finance work) deliverables section.

OTF is not a suitable use case for this feature because we have not collected information on 'Focus areas' from applicants in several years. 

While there is value in 1) collecting progress reports (image 1) and 2) data visualizations of results (image 2), our efforts will focus on improving existing functionalities before developing new features. 

Image 1: Collecting Progress Reports
![image](https://user-images.githubusercontent.com/20019656/161550435-c4daa2d8-5819-4f28-a11a-00a29252a8e2.png)

Image 2: Data Visualizations/Results
![image](https://user-images.githubusercontent.com/20019656/161550576-4680c20c-f5f3-4015-9814-bb9e8a862650.png)

**Comment by fourthletter** [comment]
I will be closing issues related to Reporting META/EPIC https://github.com/HyphaApp/hypha/issues/2708 as part of the quarterly rebasing process and [current priorities](https://github.com/HyphaApp/hypha/wiki/Roadmap).

Please reach out if you have any questions or concerns.
