### ISSUE TITLE
After a user updates their email address, editing an application with the old email address might associate it with a new account

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2759]
**Describe the bug**

After updating an email address in the user's profile, a subsequent edit to the application which does not update the email creates a new account.

**To Reproduce**

1. Submit an application
2. Log in as the user associated with the application
3. Update your email address in the user profile
4. Now edit the application without changing the email
5. The application will no longer appear in your account

**Expected behavior**

The application to remain tied to that account.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Applicants

**Additional context**

One possible solution would be to update the email on applications tied to the user when they update an email in their profile (or when an admin updates it for them).

Related to #2758.

**Comment by frjo** [comment]
If this is so it is clearly a bug, the submission should definitely follow the account.

When I test this I can not replicate it.

The function in question is:

https://github.com/HyphaApp/hypha/blob/6997240cebc84fe539dd3986d363aaad9ed3a77a/hypha/apply/funds/models/submissions.py#L526-L547

The issue we have had is when updating the e-mail address on an account the submission still show the old address until it is resaved. This has confused a very small number of users.

**Comment by chriszs** [comment]
Ah, right. Okay. Not an upstream issue.
