### ISSUE TITLE
Anyone can associate an application with a user if they know their email

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2760]
**Describe the bug**

If I know the email of an applicant, I can submit an application and have it show up in their account with no confirmation.

**To Reproduce**

1. Submit an application with the same email as a user
2. Log in to that user's account
3. You should see the application 

**Expected behavior**

I'm personally fine with this behavior, but others on the project consider it an issue and believe it's a risk to enable anonymous users to put applications in to another user's account.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Applicants

**Additional context**

This isn't a high priority for ARDC, but it was surfaced in conversations about the account creation UX.

**Comment by chriszs** [comment]
One alternate flow we discussed would detect if the applicant had an account based on their email during the submission process, and then prompt them to login to continue. That would create an issue in that it would allow someone to confirm a user's email, but in that event it would stop an anonymous user from associating applications with an existing account.

**Comment by frjo** [comment]
Allowing anonymous users to submit applications was an early requirement for Hypha. This made this feature a requirement as well, at least it was the only way we could come up with to make it work.

Having multiple accounts with the same e-mail adress was not something we wanted to tackle.

With more and more organisations using Hypha we maybe should add the possibility to demand users to create accounts and be logged in to submit applications.

A feature switch would then allow organisations to choose how they want it to work.

**Comment by killapop** [comment]
> With more and more organisations using Hypha we maybe should add the possibility to demand users to create accounts and be logged in to submit applications.
> 
> A feature switch would then allow organisations to choose how they want it to work.

Thanks for this :heart:  It would be quite useful for us (DDP).

I would also love to see this settable at the Lab/Round level for organisations that have some completely open grants and some that need registration.

**Comment by frjo** [comment]
Yes, adding it as a Fund/Lab setting, e.g. "Require applications to login" checkbox, make sense.

A UX task to make the workflow nice for applicants.

**Comment by Techslammer** [comment]
Sorry to be so late in responding.  I see that the applicant receives an email verification notifying that they have submitted an application. That email is sent to the account that is associated with the email address provided. Is there another way of confirmation that was expected? For me this seems fine but i do like adding a setting to require applications to login if a fund wants that.
