### ISSUE TITLE
Unclear to users that applications will be associated with an existing account based on email

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2761]
**Describe the bug**

Users (and by users I mean project stakeholders) have expressed to us surprise that the email they enter will matter for associating the application with an account, or that it will create a new account automatically for the user if they don't have one. In particular, the question of how to prevent a user with multiple emails from unwittingly creating multiple accounts or what happens when you enter an incorrect email has been raised.

**To Reproduce**

1. Submit an application with one email
2. Submit an application with a second email
3. You now have two accounts, each with one application

or

1. Create an application with an incorrect email 
2. You won't receive a confirmation

**Expected behavior**

It's unclear to me what exactly the expected behavior here should be, but this and some related issues (#2758, #2759, #2760) have led to talk about putting a registration step before applications.

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Applicants

**Additional context**

As a proposed fix we configured help text on the email field, noting that it would be associated the email with an account or create one, and then after the user submits (on the confirmation screen) we added text mentioning they should be receiving a new account email, or if they were logged in, we added a link to their dashboard (that's related to a separate yet-to-be-filed issue).

This issue is somewhat loosely defined, and one solution basically amounts to a won't-fix, but conversations that came out of this, related issues and separate user feedback have evolved to potentially prefer a different application creation flow.

**Comment by chriszs** [comment]
The underlying issues still exists, but so far we haven't decided to require accounts first.

**Comment by frjo** [comment]
It should be made clear that an account will be created when submitting an application as an anonymous user. Should be easy to add a short text explaining this to the application form.

Shout we add it above the form, next to the e-mail field? What is the shortest way to formulate this so it clear to the user?

**Comment by fourthletter** [comment]
I reccomend several methods:

1) Informing applicants via the automated email sent to them after they've submitted an application. 

2) Using 'Application Settings' to create a message on the landing page that appears right after an applicant has submitted their application:

![Screenshot 2022-04-06 9 56 40 AM](https://user-images.githubusercontent.com/20019656/161925151-444e8ea3-41db-4ee5-8ba1-dcb615e4284a.png)

![image](https://user-images.githubusercontent.com/20019656/161925349-4f16c15f-a9d8-413d-8a76-62a26955b624.png)

3) Include it in the applicant's guidebook that exists outside of Hypha

**Comment by frjo** [comment]
Is this not fixed with https://github.com/HyphaApp/hypha/pull/2772 ?

**Comment by fourthletter** [comment]
> It should be made clear that an account will be created when submitting an application as an anonymous user. Should be easy to add a short text explaining this to the application form. Shout we add it above the form, next to the e-mail field? What is the shortest way to formulate this so it clear to the user?

## How to add help text explaning this on the application form in WagTail Admin
![image](https://user-images.githubusercontent.com/20019656/162676585-098648ce-f5a2-4b4e-ab81-f4569786b1ec.png)

## Application form help text example
![Screenshot 2022-04-11 8 25 08 AM](https://user-images.githubusercontent.com/20019656/162677310-df517ff7-5bd1-4f6c-a94f-dcc2e033164c.png)

**Comment by frjo** [comment]
I believe this issue has been addressed in recent releases.
