### ISSUE TITLE
Applications with submitted reviews still appears on 'Waiting for your review' dashboard

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2766]
**Describe the bug**

A review was submitted for an application, but still appears on the staff's 'Waiting for your review' dashboard.

**To Reproduce**

1. Go to a fredrik's dashboard 'https://test-apply.hypha.app/dashboard/'
2. Click on 'https://test-apply.hypha.app/apply/submissions/11/'
3. Scroll down to 'reviews', and you will see two completed or submitted reviews

**Expected behavior**

Once a review has been submitted, the application should no longer appear on the staff's 'Waiting for your review' dashboard.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Screenshots**

his may only associated with applications in the 'More information requested' workflow status.

<img width="1173" alt="Screen Shot 2022-03-07 at 9 57 49 AM" src="https://user-images.githubusercontent.com/20019656/156999589-126b8a38-2480-4afe-9468-271a4d372b2a.png">

**Comment by frjo** [comment]
Thanks for setting up this test, will investigate. Definitely looks like a bug.

**Comment by frjo** [comment]
Is this not a duplicate of https://github.com/HyphaApp/hypha/issues/2767 that has been fixed?

**Comment by fourthletter** [comment]
It's a duplicate, and has been fixed. Thank you.
