### ISSUE TITLE
For logged in users, populate "E-mail" and "Full name" on new submissions and disable input

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2770]
Related #2758

We should also disable editing "E-mail" and "Full name" on any existing submissions.

Now users can edit the fields but they get reverted on save to whatever the values are in the user account. This is a bit confusing. Better to disable editing and direct users to edit these values in their user account.

**Comment by frjo** [comment]
@sandeepsajan0 You can take this one when there is no other issues to work on. So not urgent, but good to get done at some point.

**Comment by killapop** [comment]
Thanks for this. This really clears up a lot of confusion for repeat applicants.

Is it possible to *not* store the email and full_name in submission but rather fetch it each time from the applicant's user info? 
It would help in some fringe cases we've encountered where submissions have had to be reassigned or moved to a different applicant that this information had to be changed manually by editing the submission.  
I understand though that this might cause data versioning issues when an applicant changes their profile info and that change is reflected in older submissions.

**Comment by fourthletter** [comment]
Test worked! 😄 

![Screenshot 2022-04-04 10 21 23 AM](https://user-images.githubusercontent.com/20019656/161503736-21fd97ed-f74c-4250-aa37-5d1ab1a56f6e.png)
