### ISSUE TITLE
Improv handling of required fields on stream field form creation in Wagtail admin

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2774]
These include Application forms, Review forms and Determination forms.

1. The best solution would be to prepopulate all required field when e.g a new application form is created. See #2275 #2460 

2. The second best solution is to improve the error messages given when a user try to save a form without a required field. See #2771.

Number 2 should be in place regardless in case a user by mistake removes a required field that has been prepopulated.

**Comment by fourthletter** [comment]
Group field is currently a **required** section. This requires the applicant to select an option even when the section is not applicable to their proposed scope of work.

<img width="1053" alt="Screen Shot 2022-03-16 at 5 52 49 PM" src="https://user-images.githubusercontent.com/20019656/158644599-5425420a-20e7-4c13-b12d-fbbb0e01ad41.png">

**Comment by fourthletter** [comment]
Heading Text field does not render on website

<img width="1049" alt="Screen Shot 2022-03-16 at 6 02 56 PM" src="https://user-images.githubusercontent.com/20019656/158646582-1cda1d6a-8fcd-40d6-8826-1514e3fb9380.png">

**Comment by frjo** [comment]
@fourthletter These are separate issues, please create them and we can start working on them.

**Comment by fourthletter** [comment]
This is beautiful -- 💯 for Gryffindor!


![Screenshot 2022-04-06 8 00 09 PM](https://user-images.githubusercontent.com/20019656/162038797-c6ccac65-af76-4e7e-891e-f9adf44eee6d.png)

![Screenshot 2022-04-06 7 59 35 PM](https://user-images.githubusercontent.com/20019656/162038803-0a711b6a-8c3f-41a8-a210-9d7f9acecc1d.png)

![Screenshot 2022-04-06 7 57 23 PM](https://user-images.githubusercontent.com/20019656/162038804-a604ff1d-0945-4765-9bdb-22e8d9de4546.png)

![Screenshot 2022-04-06 7 54 54 PM](https://user-images.githubusercontent.com/20019656/162038805-f2acc427-9aa6-4c94-8e92-a27001f51fd4.png)
