### ISSUE TITLE
Implement a EMAIL_SUBJECT_PREFIX setting

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2775]
The existing setting `EMAIL_SUBJECT_PREFIX` is a standard Django setting. Adding a subject prefix is a common praxis to make it easy to identify e-mails for users.

https://docs.djangoproject.com/en/4.0/ref/settings#email-subject-prefix

It is not used anywhere in Hypha. It was added early on and just stuck around. The default value is "None".

Lets implement it on all e-mails sent out from Hypha.

It could get inserted here:

https://github.com/HyphaApp/hypha/blob/6554683d5756d1932418282ea2d225aa22c9b5ce/hypha/apply/activity/tasks.py#L10-L20

Setting it as empty string should mimic how it works today, no prefix at all. But any organisation using Hypha can decide to add any prefix they like.

**Comment by fourthletter** [comment]
![image](https://user-images.githubusercontent.com/20019656/174055023-86d8d847-fb6d-4bb2-b278-a28024cb8a25.png)

**Comment by frjo** [comment]
@fourthletter The subject line of the e-mail had the "[Hypha] " prefix?

**Comment by fourthletter** [comment]
Yes! [Hypha] Your application to Hypha Test App: Beatrice

It used to look like "Your application to Hypha Test App:..."
