### ISSUE TITLE
Changing email on non-staff accounts creates non-null constraint violation

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2784]
**Describe the bug**

When a non-staff user attempts to edit their email account they ultimately reach a non-null constraint error related to the `slack` field.

**To Reproduce**

1. Log in as a non-staff user
2. Click on profile link (upper right)
3. Note that the "Slack" field is not in the form (this should be the case if it is not a staff user)
4. Change the email address
5. Enter the password confirmation
6. See error

**Expected behavior**

The error should not appear.

**Priority**

- Medium-High (this seems like a significant issue as it is broken functionality to all applicants, reviewers, and partners)

**Affected roles**

- Applicants
- Reviewers
- Partners

**Screenshots**

<img width="888" alt="image" src="https://user-images.githubusercontent.com/208884/159750476-e198754a-ad9a-4937-b403-c00b6fa6dd15.png">

**Desktop (please complete the following information):**

 - OS: MacOS 12.2.1
 - Browser Firefox
 - Version 98.0.1

**Additional context**

@chriszs pointed out this is related to https://github.com/HyphaApp/hypha/issues/2714

The problem comes from the fact that the slack field does not exist in the password edit form for this type of user (it isn't immediately obvious to me where the logic that determines fields in a form lives, since the form view is doing some fancy footwork in rendering fields).

I should note: it isn't clear to me yet why the EmailChangePasswordForm references slack *OR* full_name in the first place, or why `self.user.save` exists in this context since the email is the item being saved and is also the only item that isn't explicitly saved in this logic.  Isn't save already handled in the `ProfileForm`?

One solution would be to only set the slack field if a value is passed.  Another is to remove reference to slack (and full_name) entirely from `EmailChangePasswordForm`.

I will open a PR.

**Comment by slifty** [comment]
I see now why the save logic exists in the EmailChangePassword form -- the `ProfileForm` does NOT handle save in the case of an email change.

I'll just add the conditional around the setting of slack.

**Comment by frjo** [comment]
Thanks for reporting this, definitely needs fixing. Have tasked one of our devs to take a lock.

**Comment by slifty** [comment]
Sorry for jumping the gun!  I've issued a potential patch (cc @sandeepsajan0 so you don't spend time on debugging this in case the PR is good enough!)

**Comment by frjo** [comment]
@sandeepsajan0 We are deleting the Slack field for none staff here:

https://github.com/HyphaApp/hypha/blob/f4b3cec839f868423c534611673eb84588de1283/hypha/apply/users/forms.py#L52-L53

This creates the error @slifty is reporting.

The `users_user` -> `slack` column is set to not be nullable. Can we simply change it to be nullable?
