### ISSUE TITLE
Docker for local development not working: permission error

### ISSUE THREAD

**Issue by ramojo** [HyphaApp/hypha#2788]
**Describe the bug**

I cannot get docker-compose up to run at all. Whenever I try to spin up the containers, the django container (py) always stops on this error:
PermissionError: [Errno 13] Permission denied: '/usr/local/hypha/media'

**To Reproduce**

1. Go to '/path/to/hypha/docker'
2. Type 'docker-compose build'
3. Type 'docker-compose up'

**Expected behavior**

To see the container spin up successfully

**Priority**

- High (keeping you from completing day-to-day tasks)

**Screenshots**

![Screenshot- Thu Mar 24 03:41:38 PM EAT 2022](https://user-images.githubusercontent.com/9459879/159918406-e0a75f99-528f-411d-be67-5a8474b83977.jpg)

 - OS: Linux (Tried on Ubuntu 20.04, 21.10 and also Arch Linux) and MacOS Monterey on a MacBook Air M1

**Comment by frjo** [comment]
I think your issue is solved by creating a `media` directory in hypha root. Please let us know if that fixes it.

I have added it do the docs now.

**Comment by ramojo** [comment]
Thanks for the extremely quick response! Yes, that did fix it (had to create `media/temp_uploads` as well). Thank you for adding it to the docs as well.
