### ISSUE TITLE
Not able to save a draft, “Community convening” options are required but not selectable

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#2791]
## Bug Description
When saving “as draft" an existing draft application, impossible to save because “Community convening” options are not selectable, but selecting one is required.
## Effect
Unable to complete my draft and apply for funding.
## Proposed Solution

- [ ] Design user workflow for creating and saving a **draft** on Hypha (is this workflow different than for submitted applications?)
- [ ] User updated application form and user documentation 

## Tech specs
Mac OS (latest)
Tried both Chrome (latest) and Firefox (latest)
## Steps to reproduce
Step 0: no account on MyOTF
open new IFF application
enter project name, person name, person email (I don’t remember if I filled in anything else — I am pretty sure the form didn’t ask to select an option for “community convening”)
save as draft
Access My OTF through the email link, set up new profile
open draft from MyOTF Dashboard
Save as draft again —> doesn’t work, requires selection of one of “Community convening” options, options are not selectable
## Troubleshooting
I noticed in the inspector that both radio buttons have the `disabled` value. I tried to manually change one to `enabled` and I’m able to select the radio button, but the information isn’t recognized when clicking “Save.” I also tried to remove the value instead of changing it, same result

cc @fourthletter 

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by fourthletter** [comment]
Users are unable to save applications as draft when a question is nested in a group field. Options are not selectable because both radio buttons have the `disabled` value. The user is unable to manually change one to `enabled` and the selection isn’t recognized when clicking “Save.” Related to #2800

**Comment by fourthletter** [comment]
Issue was fixed https://github.com/HyphaApp/hypha/tree/enhancement/gh-2798-group-field
