### ISSUE TITLE
Staff role deleting submissions should be aware of the parameters 

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#2792]
## Description
When the staff user role deletes an application from the platform, they are not informed of the potential consequences of also deleting associated links, e.g., determinations and other applications on the platform. An application (concept note - 1st stage) is associated with determinations and oftentimes a proposal (2nd stage). 

The applicant role is currently not given permission to delete any applications. 

## Solution
The staff user role see a warning or message informing them of the consequences of deleting an application associated with determinations and other proposals. 

## Priority
Low

**Comment by frjo** [comment]
Who can delete is controlled by permission set on user roles.

**Comment by fourthletter** [comment]
On April 6 standup we discussed:

Managing persmissions in the WagTail Admin:
WagTail Admin - go to settings/groups
![Screenshot 2022-04-06 2 46 09 PM](https://user-images.githubusercontent.com/20019656/161977620-4b5d8ccf-7e81-4ba3-a77c-a76eab92ae08.png)

Select a user role
![Screenshot 2022-04-06 2 44 59 PM](https://user-images.githubusercontent.com/20019656/161977405-bc058625-f100-42a6-ab67-1d7bdaeb3c23.png)

Warning message for deleting an application

![image](https://user-images.githubusercontent.com/20019656/161979211-92003b1d-97fd-4b49-9820-549ea3cfe558.png)

**Comment by frjo** [comment]
So a warning is given already, good.

As I mentioned before, I think the permission to delete submission might not be good to give to all staff. Maybe something for Team admin role?

**Comment by fourthletter** [comment]
As I recall from our conversation, we should consider a message that includes information on the potential deletion of supporting documents and other dependencies. A user might delete an application but neglects to delete associated documents that could potentially lead to errors.

**Comment by fourthletter** [comment]
I am closing this issue and adding it to the Epic https://github.com/HyphaApp/hypha/issues/2814
