### ISSUE TITLE
Improve filters for user roles in WagTail Admin

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2793]
## Description

As a sys admin I would like to quickly sort, search, and manage user accounts in the WagTail Admin. 

1) I am able to sort by Name, Email, Status, but not by **Role**

2) Sorting by Name, Email, Status is cumbersome and does not easily filter or hone in on the user accounts I am searching for.

3) Some user accounts are not assigned to a role, making it difficult to understand their permissions (level of access to information) on the platform. 

![image](https://user-images.githubusercontent.com/20019656/161540252-cf460672-b77f-4010-ad01-a91970896d73.png)

**Priority**
- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Ideal deadline**
October 2022

**Comment by frjo** [comment]
@fourthletter What do "Search field should not be required" mean more exactly?

**Comment by fourthletter** [comment]
@frjo there is white text under the search field stating "x this field is required" -- the search field is not required. I went to the user role page again and the text is no longer there https://test-apply.hypha.app/admin/users/

Search field should not be **required**

![image](https://user-images.githubusercontent.com/20019656/161538745-e62a806d-9d7a-4c34-adc7-7ebbec39f6c6.png)

**Comment by frjo** [comment]
That text only show up if you try to do a search without entering any text to search for.

**Comment by fourthletter** [comment]
On April 6 standup we discussed installing new functionalities for managing user accounts in the WagTail Admin. Click here for WagTail documentation: [https://docs.wagtail.org/en/stable/editor_manual/administrator_tasks/managing_users.html#managing-users-and-roles]

As an administrator, a common task will be adding, modifying or removing user profiles. This is done via the ‘Users’ interface, which can be found in the Settings menu, accessible via the left-hand menu bar.

![screen36 5_users_bulk_actions](https://user-images.githubusercontent.com/20019656/161976939-182a8874-aa22-4665-a0ba-b5ddacd1889a.png)

**Comment by fourthletter** [comment]
April 7 standup we discussed several methods for increasing the efficiency of how we could do a search and get the results we need.

## Description 
While the current user interface shows a count of search match results, improvements to filters and search will provide more granular information. Example: "5 matches"

![image](https://user-images.githubusercontent.com/20019656/162408394-f92e342b-baf2-4fdf-bbe3-687ef8fe7eb4.png)


## Filters
- Filters should be able to have a tally of user accounts 1) associated with a specific role and 2) total amount of all user accounts
- Sort by Role (not 'Level')
- Filter for a **combination** of fields, e.g., Role and Active accounts

## Search 
- Search terms are currently only available for Name and Email fields. Example 4,000 gmail accounts

**Comment by fourthletter** [comment]
On April 11

> @ei8fdb's design suggestion: Moving filter control location to page top, how to clear the filters, selecting multiple roles

@sandeepsajan0 : You mean on the top in just one row like we have filters for submissions and all? Actually, I used this design because we already have the same design in wagtail's other pages(like site history). In order to clear the filters you have to just select the '-------'. selecting multiple roles 

video shared on slack:
![image](https://user-images.githubusercontent.com/20019656/162929424-ce6b5bde-b391-42fc-b894-019751f06678.png)
