### ISSUE TITLE
Greyed out name and email on application form - info to help user update these details

### ISSUE THREAD

**Issue by Erioldoesdesign** [HyphaApp/hypha#2794]
**Is your feature request related to a problem? Please describe.**

Recently (April 2022) a [PR was merged](https://github.com/HyphaApp/hypha/pull/2772)  (issue #2770 captures the need pre-PR) where applicants that are already logged into their Hypha account will not be able to edit their name/email in an application to a fund and these fields are 'greyed out' logic being that users should want to use existing accounts/names for all applications ongoing.

This doesn't account for the possible case where an applicant might have changed name (either legally or otherwise) since their last application but still wishes to use their existing account and starts an application before checking in on 'account settings'. This may trip up and confuse users who want to change that before submitting a fund application. The solution being, go to the account details section and update name and/or email (which would then be reflected in the applicant fund form)

**Is your feature request related to an existing functionality? Please describe.**

See above

**Describe the solution you'd like**

Best guess is that either help text or a link to docs on how applicant users can change their account info will solve this problem

**Describe alternatives you've considered**

Simply not doing this and relying on people figuring it out or asking for help/support.

**Additional context**

![image](https://user-images.githubusercontent.com/11681324/161829659-1557b7f4-f8bb-4fad-9833-a2145cb6dc73.png)

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Applicants
- General public
- Anyone in a help/support role

**Ideal deadline**

Review in Q3 rebasing project.

**Comment by fourthletter** [comment]
This issue has been resolved here:

![Screenshot 2022-06-04 7 55 30 PM](https://user-images.githubusercontent.com/20019656/172019730-84b70d75-5fc6-4d53-aeff-5a47e496c7e1.png)
