### ISSUE TITLE
Group field is buggy

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2798]
Group field is currently a **required** section. This requires the applicant to select an option even when the section is not applicable to their proposed scope of work. I propose this section does not need to be marked as **required**

<img width="1053" alt="Screen Shot 2022-03-16 at 5 52 49 PM" src="https://user-images.githubusercontent.com/20019656/158644599-5425420a-20e7-4c13-b12d-fbbb0e01ad41.png">

**Heading Text field** and **Section Text field** when nested within Group Fields do not render or published on the website.

<img width="1049" alt="Screen Shot 2022-03-16 at 6 02 56 PM" src="https://user-images.githubusercontent.com/20019656/158646582-1cda1d6a-8fcd-40d6-8826-1514e3fb9380.png">

**Comment by sandeepsajan0** [comment]
>Heading Text field and Section Text field when nested within Group Fields do not render or published on the website.

It is still not fixed yet. I am working on it in PR  #2800.

**Comment by fourthletter** [comment]
Related to https://github.com/HyphaApp/hypha/issues/1355 and https://github.com/HyphaApp/hypha/issues/1259

**Comment by fourthletter** [comment]
Thank you for pushing this through! 💥
