### ISSUE TITLE
Update django-bleach and bleach to latest versions.

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2803]
Version 5 of bleach is not yet compatible with django-bleach 2.x so keep tabs on that.

bleach is a Python module that takes any HTML input, and returns valid, sanitised HTML that contains only an allowed subset of HTML tags, attributes and styles. django-bleach is a Django app that makes using bleach extremely easy.

**Comment by sandeepsajan0** [comment]
@frjo The `django-bleach` has a [new release to 3.0](https://github.com/marksweb/django-bleach/releases/tag/3.0.0) that supports Bleach >=5. I think a simple update should work just fine now.
