### ISSUE TITLE
Add 'External Reviewer' picklist to batch action 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2805]
## Summary

As a manager I need to assign reviews to the Reviewer group as a batch action. 

## Description

When an application is in the 'External Review' workflow status, or in any workflow status, I can't rely on the user interface to select anyone from the Reviewer group because the third drop down menu is not available.

## Suggested Solution
![Screenshot 2022-04-12 9 58 43 AM](https://user-images.githubusercontent.com/20019656/162910740-a0b6040f-3211-45fc-a3cb-42bae4df9ae3.png)

## What UI looks like now
![image](https://user-images.githubusercontent.com/20019656/162909996-25d4ad71-26ba-4033-b460-346bf466b458.png)

---
## Internal Approval Process
- [ ] @OpenTechFund/design to add designs to issue
- [ ] @OpenTechFund/devs to review designs for implementation
- [ ] Di to help organise testing/feedback session with OTF users
- [ ] @OpenTechFund/design do testing/feedback session with OTF users
- [ ] OTF to sign-off
- [ ] @OpenTechFund/design to make sure most up to date designs designs are attached to issue

**Comment by fourthletter** [comment]
Standup April 21 -- thank you @sandeepsajan0 for your question today.

When a user attempts to select a individuals from the reviewer group to a Fund/Lab with a workflow that does not accomodate external reviewers (individuals with the reviewer role), they should receive an error message.

Error Message: "Unable to select reviewer based on the current application workflow" OR "Reviewer cannot be selected because of the application workflow"

**Comment by fourthletter** [comment]
I tested @sandeepsajan0 and it works great! 💯 

I am no longer able to 'become' on the test site so I am unable to see whether the External Reviewer is able to see the application on their dashboard. It is important that when an application is assigned to an 'External Reviewer', the application appears on their dashboard.

**Comment by frjo** [comment]
If a reviewer is assigned they are assigned and everything else will follow as it always do.

Have reactivated the hijack function (and disables enforce 2FA) on the test site now. We where testing the PR that allows orgs to disable hijack.
