### ISSUE TITLE
[Epic] In-app notifications

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2812]
## Summary

OTF needs to inform the users involved in the process of invoice transition through the webapp.  This is so they can be kept up-to-date of the invoice status, and be notified if they are required to do anything.

## User Story
We now send e-mail notifications to applicants and reviewers, and Slack notifications to staff.

## Suggestion

In-app notifications enable users to view a list of comments and messages associated wtih the Lead (staff) without the need to dig through Slack, e-mail, and the comment tab.

<img width="588" alt="Screen Shot 2022-06-04 at 10 05 52 PM" src="https://user-images.githubusercontent.com/20019656/172023970-8a13fb7e-5db0-4aca-99ba-00538fa9db88.png">

**Comment by sks444** [comment]
@di, I thought this is one of the TO Dos in current month..

I have been doing some research on this, we could take a lot of ideas from https://github.com/django-notifications/django-notifications, one of the key points that I noticed is about recipient(a user or a list of user) to whom the notifications are being sent on an event.

And the other is about [real time updates](https://github.com/django-notifications/django-notifications#live-updater-api).

**Comment by fourthletter** [comment]
@sks444 Thanks for your research and  new ideas. I thought you preferred to work on the email default before starting this one. I put it back on the TO DO list.

I propose "event(s)" could be 1) new comments in the communication tab and 2) when the applicant revised/submitted a revision to their proposal. I'm opening to hearing other ideas for defining "events."

**Comment by sks444** [comment]
On June 9 standup, for MVP purposes, we discussed to list all the activities on all the submissions and on all the projects at one place..

**Comment by sks444** [comment]
There are two types of objects involved in an activity. [Source](https://github.com/HyphaApp/hypha/blob/f1c1afb5df207735b4660215db17d22275fb51c3/hypha/apply/activity/models.py#L93) and [Related](https://github.com/HyphaApp/hypha/blob/f1c1afb5df207735b4660215db17d22275fb51c3/hypha/apply/activity/models.py#L106).

Source are the core objects in Hypha. I.e ApplicationSubmission and Project.
Related are the other objects that are related to core objects. I.e. Determination and Reviews for ApplicationSubmission **and** Invoice and contract for Project.

There are two type of activities that is performed: Comment and Action. I'm thinking to have the list of notifications displayed in a generic way.

### For action:

**[Link to source object]: Activity Performed [Link to related object if it exist]**

So a notification from [this submission](https://test-apply.hypha.app/apply/submissions/506/) might look like:

[Submission](https://test-apply.hypha.app/apply/submissions/506/): Progressed from More information required to Need screening
[Submission](https://test-apply.hypha.app/apply/submissions/506/): Sent a determination. Outcome: More information requested. [Determination](https://test-apply.hypha.app/apply/submissions/506/determination/312/)

And notifications from [this project](https://test-apply.hypha.app/apply/projects/43/) might look like:

[Project](https://test-apply.hypha.app/apply/projects/43/): Approved contract. [Contract](https://test-apply.hypha.app/apply/projects/43/contract/42/)
[Project](https://test-apply.hypha.app/apply/projects/43/): Updated Invoice status to: Changes Requested by Staff. [Invoice](https://test-apply.hypha.app/apply/projects/43/invoices/17/)

### For comment:

**[Link to source object communications tab]: Username made a comment.**

So a comment notification from [this submission](https://test-apply.hypha.app/apply/submissions/439/) might look like:

[Submission communications](https://test-apply.hypha.app/apply/submissions/439/#communications):  Shrikrishna Singh made a comment.

And a comment notification from [this project](https://test-apply.hypha.app/apply/projects/43/) might look like:

[Project communications](https://test-apply.hypha.app/apply/projects/43/#communications): sks made a comment.

---

Notification view will list all these in an order of recently performed. I'm thinking maybe we could also have a filter based on source object. I.e only list notifications for submissions or projects.

@frjo let me know your views on this.

**Comment by frjo** [comment]
@sks444 Make sense to have a more compact display in the notifications than in the communication/activity feed tabs for each submission. Should not the link text be the objects title? Maybe truncated since some are quite long. We do this in the submissions table already.

https://github.com/HyphaApp/hypha/blob/67999482694f8ad43819d545bbc7e0d4ce71d867/hypha/apply/funds/tables.py#L56-L61

**Comment by sks444** [comment]
On June 10 standup, we discussed to display two tabs in the notification view. One for communication and other for actions, similar to what we have on one submission. But keeping the notification format same as described [above](https://github.com/HyphaApp/hypha/issues/2812#issuecomment-1153788752) with displaying the [truncated title](https://github.com/HyphaApp/hypha/issues/2812#issuecomment-1154782976) of the source.

**Comment by fourthletter** [comment]
On June 16 standup, sandeep demo an iteration of two tabs in the notification view. 

Di asked if we could include indications when a notification or activity is NEW so the user knows there are notifications they haven't read yet.
FJ suggested shortening the messages/notifications and giving more details when the user clicks on (as in expand) the notification (ie Discourse). The start of each notification is repetitive and potentially unnecessary? 
sks suggested showing top 10 on a pop-up, and the user going to the notification view for more details. This could be version 2.0

![Screenshot 2022-06-16 10 24 51 AM](https://user-images.githubusercontent.com/20019656/174052370-c3c56240-8e97-4889-ba53-efb48858162c.png)
