### ISSUE TITLE
Streamline user roles and their permissions

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2814]
## Description 

Streamline user roles by better defining level of access and functionalities associated with each role

### Admin
- [ ] As an admin, I need the capacity to disable 2fa on user accounts to better manage users' access to the platform. The staff admin role overseas user accounts and troubleshoot technical glitches via the WagTail admin in Hypha.  

### Staff Admin
- [ ] Staff admin is little used at the moment but we have talked about using it more. Removing stuff from staff so they see less and have a cleaner UI.
- [ ]  As a staff admin, I need the capacity to disable 2fa on user accounts to better manage users' access to the platform. The staff admin role overseas user accounts and troubleshoot technical glitches via the WagTail admin in Hypha. Staff admin role has permission to disable 2fa for all user accounts except for Admin 
- [ ] [Role could delete submissions](https://github.com/HyphaApp/hypha/issues/2792)

### Staff/Lead

- [ ] Staff should receive all the same permissions as Lead, including [adding reviewers to proposals](https://github.com/HyphaApp/hypha/issues/2832)
- [ ] Lead is not a role but permissions to select Reviewers, receive notifications

### Reviewer
- [ ] Combine 'Community Reviewer' with 'Reviewer'

'Community Reviewer' and 'Reviewer' is quite different so can't be merged. I do not think anyone is actually using community reviews so we might simply remove that feature.

### Approver
- [ ] 'Approver' and 'Partner' roles are not well defined AKA the Dr. Bronner's of user roles 🧼 
- [ ] "Approver" give users with staff/finance/contracting roles the ability to approve things like projects/invoices/contracts. Without it we would need at least three new roles.

<img width="711" alt="Screen Shot 2022-01-24 at 2 42 59 PM" src="https://user-images.githubusercontent.com/20019656/150793875-f51bdae3-1252-43e1-9fa9-2738c18b2e04.png">

**Comment by wes-otf** [comment]
@frjo going through and cleaning out old issues assigned to me, I think this is pretty much set right? It seems like all the issues presented here have been mostly resolved.
