### ISSUE TITLE
Giver Staff Admin role permission to disable 2fa on user accounts

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2821]
## Description

As a staff admin, I need the capacity to disable 2fa on user accounts to better manage users' access to the platform. The staff admin role overseas user accounts and troubleshoot technical glitches via the WagTail admin in Hypha. 

## Solution

Staff admin role has permission to disable 2fa for all user accounts except for Admin

**Comment by ei8fdb** [comment]
From research so-far into 2FA management processes, these are the 2 workflows I've seen:

## 1. Disable 2FA for user affected
![Screenshot 2022-04-26 at 13 45 59](https://user-images.githubusercontent.com/1899506/165293084-781d9712-bb1a-43de-b28e-31b3fb0694ab.png)

Possible design approach [documented in Miro board](https://miro.com/app/board/uXjVO8_szdM=/?moveToWidget=3458764524024014367&cot=14). 

## 2. Generate one-time use TOTP code for user affected to allow them regain access
![Screenshot 2022-04-26 at 13 47 12](https://user-images.githubusercontent.com/1899506/165293287-85e56ad2-b4ae-4683-bd39-27fd5ba0d42d.png)

Possible design approach [documented in Miro board](https://miro.com/app/board/uXjVO8_szdM=/?moveToWidget=3458764524028179328&cot=14).

**Comment by ei8fdb** [comment]
Decision taken on today's OTF standup was to go with option 1: Disable 2FA for user affected.

Next steps are to work on designs and test with Hypha adopter staff who have required permissions.

**Comment by ei8fdb** [comment]
@sandeepsajan0 Here's the design for this issue:

![Two-Factor Authentication Improvements - Frame 1](https://user-images.githubusercontent.com/1899506/166663216-1521e705-f6b0-456c-88e4-2a692ec2b0d8.jpg)

(You can see it [in the Miro board](https://miro.com/app/board/uXjVO8_szdM=/?moveToWidget=3458764524024014367&cot=14))

The only part I've not designed fully is the step where the staf member has to enter their password before the 2FA is disabled. This should keep the user on the page, the staff member should enter their password, and then the 'disable 2FA' button should be disabled (as they cannot reenable the user's 2FA)

If you have questions let me know here.

**Comment by fourthletter** [comment]
During standup on May 5 we discussed attributes associated with the "user" category (as seen in settings below). Attributes for the "user" currently includes email, ID, and other criteria. The proposed approach is to customize user attributes to include 2FA disabling. Only Admin and Staff Admin roles will be able to disable 2FA for all user groups.

Developers will research the implications of using this interface for 2FA disabling. If we choose this approach, Hypha OSS maintainers will need to document this approach for developers and other adopters of Hypha.

### User Settings
![Screenshot 2022-05-05 10 53 42 AM](https://user-images.githubusercontent.com/20019656/166891731-f17879e5-5ab0-414a-93b9-46aa3004ea52.png)

### Good to have in the distant future? 

[https://docs.wagtail.org/en/latest/editor_manual/administrator_tasks/managing_workflows.html#creating-and-editing-tasks]
![image](https://user-images.githubusercontent.com/20019656/166895479-0824e654-4bc6-45fe-af7b-b5e4ab7c5393.png)

**Comment by sandeepsajan0** [comment]
@fourthletter @frjo @sks444 @ei8fdb What do you all think about using "Reset 2FA" instead of "Disable 2FA"?

**Comment by frjo** [comment]
I prefer "Disable 2FA". That is what technically is happening.

**Comment by ei8fdb** [comment]
@sandeepsajan0 agreed. _Disable 2FA_ is the action the user (staff) is doing here.

**Comment by fourthletter** [comment]
Looks amazing -- you rock! 👨‍🎤 🎸 

### User with 2FA
![image](https://user-images.githubusercontent.com/20019656/167675576-67756bfa-bc9d-4ae4-b32d-f25b70f91b45.png)

![image](https://user-images.githubusercontent.com/20019656/167676307-07fd057d-159f-439a-92fc-f69bdc710f54.png)


### User without 2FA
![image](https://user-images.githubusercontent.com/20019656/167675739-3479dff6-b95a-46b3-a0b6-568ab93e6f66.png)
