### ISSUE TITLE
[Epic] 2FA workflow usability improvements for 2FA use cases

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2828]
# Description

This issue documents usability improvements to the workflow for OTF applicants to configure Two-Factor authentication by:
- improving instructions and explains what users are required to do to enable 2fa
- removing unnecessary, and confusing pages from the current process
- putting creation of 2FA backup codes in the 2FA configuration process
- providing support for OTF applicants who do not have a smartphone and so cannot configure 2FA

# Related Issues
#2836 Add documentation to support users who don't use smartphones
#2821 Give staff admin role to disable 2FA
#2824 Email sent to new applicants with information about 2FA
#2829 hi-jack function
#2830 show error message when you use hi-jack function when 2FA is enforced
#2846 Add a can't scan QR code funcation
#2898 Replace django-two-factor-auth with something that support WebAuthn

# Is your feature request related to an existing functionality? Please describe

It is related to current 2FA implementation.

# Describe the solution you'd like

### OTF Enable App Based Two-Factor Authentication - ENFORCED - Userflow

Here is the userflow and design for OTF who have enforced 2FA:
![Two-Factor Authentication Improvements - OTF Enable App Based Two-Factor Authentication - ENFORCED - Userflow](https://user-images.githubusercontent.com/1899506/166665077-cbf3ee31-6cf2-4220-abcc-025714e4e587.jpg)

This video walks through the steps of setting up 2FA for an OTF user.

https://user-images.githubusercontent.com/1899506/165336378-2a257703-eb13-460f-b7b3-0854dfd9a413.mp4

### Hypha Core: Enable App Based Two-Factor Authentication - NOT ENFORCED - Userflow

Here is the userflow for an adopter who does not have 2FA enforced for users:
![Two-Factor Authentication Improvements - Hypha Core_ Enable App Based Two-Factor Authentication - NOT ENFORCED - Userflow](https://user-images.githubusercontent.com/1899506/166664870-d429b089-f045-4543-a9c8-c58980b468d3.jpg)

### Hypha Core: Enable App Based Two-Factor Authentication - ENFORCED - Userflow

Here is the userflow and designs for an adopter who does have 2FA enforced for users:
![Two-Factor Authentication Improvements - Hypha Core_ Enable App Based Two-Factor Authentication - ENFORCED - Userflow](https://user-images.githubusercontent.com/1899506/166664976-a45248f8-bd50-4d86-8ed7-b03d5fbd2fbc.jpg)

# Priority

- Medium

# Affected roles

- Applicants
- Reviewers
- Partners

**Comment by fourthletter** [comment]
@ei8fdb   In the proposed design, a sys admin would need to insert the url/guidance into image 1 and image 2. This requires the sys admin to add guidance for 2FA  in several places and maintain these links indefinitely. My proposal is to minimize this admin burden with a single message.

### NEW message:

2FA is an extra layer of security used to make sure that people trying to gain access to an online account are who they say they are. We recommend using either a security key as your second factor, and/or using an authenticator app such as[ Authy](https://authy.com/). 

Here is additional information on how to set up your 2FA in the Applicant’s Guidebook [https://guide.opentech.fund/application-platform-guidance/login/two-factor-authentication-2fa]. 

**If you have technical difficulty enabling 2FA, please contact [insert email]**

### Image 1:
![image](https://user-images.githubusercontent.com/20019656/167593177-24c053fc-2600-4d48-8e42-dfa2290f1b31.png)



### Image 2: I've installed 2FA (I don't have a smartphone)

<img width="850" alt="Screen Shot 2022-05-08 at 5 05 51 PM" src="https://user-images.githubusercontent.com/20019656/167302492-050ef8b1-095b-4de8-a6dd-38cb91ce7b24.png">

**Comment by fourthletter** [comment]
Accessibility note from a recent user: "I think this is not a really accessible way to do it because it depends on sight and you have a really small time limit period to do it (impact on blind users and cognitive disabilities)."

**Comment by frjo** [comment]
https://miro.com/app/board/uXjVO8_szdM=/

**Comment by fourthletter** [comment]
@sandeepsajan0  Great job - the new flow works great! 💥 

My only question is with the "regnerate codes" comes right after "save codes." End-users unfamiliar with backup codes will click on regenerate codes right after save codes, rendering save codes pointless. 

![Screenshot 2022-06-04 6 30 25 PM](https://user-images.githubusercontent.com/20019656/172016650-84ecca09-de5f-4740-898e-215d08e88452.png)

The suggested design was a gray regenerate codes button sitting side-by-side with save codes. I don't know if this is better for users. 

![image](https://user-images.githubusercontent.com/20019656/172016763-18e51a66-1f73-40d2-93ea-2e5f90c56178.png)

**Comment by frjo** [comment]
A new version of the PR is now on test with some minor improvements. Mostly for Apple device users.

**Comment by fourthletter** [comment]
I ran another test on ios, and it worked fine. No major issues. 

There are slight differences in the workflow for test.hypha and test.opentech.fund for saving backup codes.

**Comment by frjo** [comment]
test.opentech.fund does not have the new code. That site is only used for deployment testing for OTF.

**Comment by fourthletter** [comment]
I completed a new run through, and was able to set up my 2FA and log in via backup codes & tokens. 💥 

Nothing happened when I clicked on **Alternative otpauth set up link**

![Screenshot 2022-06-16 11 04 19 AM](https://user-images.githubusercontent.com/20019656/174035562-43e2af1d-ccbe-452f-a97a-de5cd67bc96d.png)

**Comment by frjo** [comment]
@fourthletter It seems your computer does not have an app that can handle the otpauth link. On my computer the system keyring opens up and I can safe 2FA stuff.

I have changed the design a bit to hide the link behind a "Advanced" toggle so not to confuse users. People who want the link will know where to look.

![Skärmavbild 2022-06-16 kl  14 00 17](https://user-images.githubusercontent.com/191392/174065290-1b7441a1-aa5c-4695-80cc-ee48301d9016.png)

**Comment by fourthletter** [comment]
Could we please release the 2FA workflow with increased usability without #2846 for now? Thanks.
