### ISSUE TITLE
Add global env variable to turn hijack/become feature on/off

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2829]
HIJACK_ENABLE = env.bool('HIJACK_ENABLE', False)

https://github.com/HyphaApp/hypha/blob/4e8e4d1c5b9ae2e7d81393fc6a39297585394b51/hypha/apply/users/views.py#L160-L172

**Comment by fourthletter** [comment]
As a staff admin on test.hypha.app, I am no longer able to access the hijack/become feature.

**Comment by frjo** [comment]
Perfect, so it works then. I have no reenabled the hijack funktion on test.
