### ISSUE TITLE
Staff user group should be able to assign 'External Reviewers' to submissions

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2832]
### Description
Staff user group should be able to use batch action to select reviewers and assign them to submissions. Currently on the Lead user group associated with a particular Fund could do this. 

Staff needs to select 'External Reviewers' in the:

- [ ] detailed submission view;
- [ ] batch action

### Related Issue

https://github.com/HyphaApp/hypha/issues/2805

**Comment by frjo** [comment]
See https://github.com/HyphaApp/hypha/blob/55acc7ab7ef4faba5456909fc05ffb34a0fece75/hypha/apply/funds/forms.py#L253-L254

**Comment by fourthletter** [comment]
Works great! Thank you!
