### ISSUE TITLE
Add documentation to support users who can't use smartphone device for 2fa

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2836]
**Is your feature request related to a problem? Please describe.**

Right now, if a fund has enforced device-based 2FA and an applicant doesn't have a smartphone, they are unable to log in. There should be documentation created to support that user.

**Is your feature request related to an existing functionality? Please describe.**

Current hypha adopters who enforce use of 2FA.

**Describe the solution you'd like**

The solution should be to support multiple 2FA implementations Until that happens, there should be documentation to explain to these users what is recommended.

**Describe alternatives you've considered**

There is no usable alternative.

**Priority**

- High (keeping users from completing day-to-day tasks)

**Affected roles**

- Applicants who can't use a smartphone to generate 2FA codes
- Reviewers who can't use a smartphone to generate 2FA codes
- Partners who can't use a smartphone to generate 2FA codes

**Comment by fourthletter** [comment]
Hello @sandeepsajan0 The new recommended workflow is great, but I made some slight revisions to the messages. Thank you for your work on this: https://miro.com/app/board/uXjVO8_szdM=/

### We agreed to have to the disable function on OTF's platform
![image](https://user-images.githubusercontent.com/20019656/169304506-5c673977-6cb1-4284-90ef-1e2ca7502284.png)

### Update message on Permissions Denied page (see comment box)
![image](https://user-images.githubusercontent.com/20019656/169303643-d73c3f3b-2000-47e5-9b2c-3ff1efa06233.png)

### We will not embedd a url to the guidebook, but a new message with email (see comment box)
![image](https://user-images.githubusercontent.com/20019656/169303895-02c78cd8-8c59-4dc5-a686-996d70e27519.png)

### Update message with message from comment box
![image](https://user-images.githubusercontent.com/20019656/169304010-a53acfb9-6535-4cc0-9a0d-d868e71022f6.png)

**Comment by fourthletter** [comment]
guidance on 2FA setup: https://guide.opentech.fund/application-platform-guidance/login/two-factor-authentication-2fa
