### ISSUE TITLE
Support alternative 2FA methods

### ISSUE THREAD

**Issue by ei8fdb** [HyphaApp/hypha#2837]
**Is your feature request related to a problem? Please describe.**

Hypha supports only 2FA OTP generation by a smartphone app. This requires users to have a smart device. 

Hypha should support 2FA using different methods for example; SMS, email, telephone call, others.

**Is your feature request related to an existing functionality? Please describe.**

Related to current Two-Factor Authentication implementation.

**Describe the solution you'd like**

An easy way for adopters to add support for 2FA methods alternative to smartphone OTP.

**Describe alternatives you've considered**

**Priority**

- High (it is keeping *some* users from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers
- General public

who don't have access to / can't use a smart device.

**Comment by frjo** [comment]
Implementing e-mail, SMS etc. lower the overall security benefits of 2FA quite a bit.

I believe a better solution is to enforce 2FA on a role by role basis.

Then OTF can enforce it on e.g. reviewers that I assumes all have smartphones etc.

For applicants, who only have access to their own applications, strongly suggesting activating 2FA is a good compromise I think.

**Comment by ei8fdb** [comment]
This isn't OTF related @frjo, it's for any adopter.

**Comment by fourthletter** [comment]
We could discuss this alternative approach for other adopters during the Maintainers call. Thanks.

**Comment by fourthletter** [comment]
Related to #2898
