### ISSUE TITLE
Enhance project reporting with yearly and none options

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2841]
## User Story

As a user I need to submit a report once a year during the completion of a grant. Managers are unable to adjust the Reporting user interface for this requirement. Currently a manager could "skip" this requirement by selecting month-by-month. 

A manager needs to:

- [ ] select **'annual'** 
- [ ] no report required 
- [ ] submitted reports interface does not need to record _'skipped reports'_
- [ ] notification for contractors? 

### Image 1: Report Upload Page
![image](https://user-images.githubusercontent.com/20019656/166901089-474dfd38-c616-46fc-a8d5-0c7f23541c35.png)

### Image 2: Reporting Frequency Setting
![image](https://user-images.githubusercontent.com/20019656/166901137-ed0d810f-bb2e-40f0-a183-7505cfd49852.png)

### Image 3: Submitted Reports
![image](https://user-images.githubusercontent.com/20019656/166901768-19b3d5d3-494f-497e-a588-0c852bea36c5.png)

**Comment by frjo** [comment]
@fourthletter So in practice you want to add "Year" as an option in the "Frequency" select field?

**Comment by fourthletter** [comment]
@frjo Adding "Year" as an option in the "Frequency" select field is correct. If it's feasible, we could also add **no report** as an option. For example, if a contractor is funded to submit a security audit or a tool (open source code), they are not required to submit a report.

**Comment by sks444** [comment]
Current default reporting frequency is set to Month, which automatically schedules the next report.

With having no-report as an option now, would be good to set that as a default and if a report is required on a project we can set specific frequency accordingly.

**Comment by fourthletter** [comment]
On May 12 standup we discussed adding 'reporting' as a status change in the 'Actions to Take' box. This feature is potentially connected to the PAF creation process. However, in this iteration we will focus on refining the frequency and due dates (?). As sks444 suggested, no-report as a default is the best approach moving forward.

**Comment by fourthletter** [comment]
Revise reporting form:
1. Does this project need to submit reports? 
2. When will this project start to collect reports?
3. How many reports will be submitted? Will it repeat?
4. How often will this report repeat (frequency)?

Bug:
- There is currently a bug on the form because we removed the start and end date from projects, form does not allow user to select a future date to submit reports. Needs to remove validation
- replace jquery with Alpine
