### ISSUE TITLE
Add a "Can’t Scan a QR Code?" feature to 2FA

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2846]
This is a quit common feature. You display the QR information as a code string enable the user to paste it it to there password manager. 

Related to #2828

**Comment by fourthletter** [comment]
Users need more instructions regarding how to setup alternative otpauth. 'Advance' could mean 'go further', or it could mean someone with expert knowledge. 

I clicked advance but wasn't able to go very far...

<img width="990" alt="Screen Shot 2022-06-17 at 6 59 04 AM" src="https://user-images.githubusercontent.com/20019656/174228385-7e13545a-0561-4f9c-85a0-a8fb12802a7a.png">
