### ISSUE TITLE
Remove draft submission from API calls

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2850]
Draft submission should not appear in any lists anywhere in Hypha.

**Comment by ghfakev** [comment]
Note that this removal of draft exposure is [being discussed in chat](https://chat.hypha.app/#narrow/stream/1-general/topic/Anyone.20using.20the.20React.20app.3F/near/10220) as of today.

**Comment by kfogel** [comment]
Note that this removal of draft exposure is [being discussed in chat](https://chat.hypha.app/#narrow/stream/1-general/topic/Anyone.20using.20the.20React.20app.3F/near/10220) as of today.
