### ISSUE TITLE
Add ability to send Slack messages directly from Hypha

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2852]
Hypha can now use an Hubot endpoint to sent messages to Slack. Hubot has not been updated for 3 years https://www.npmjs.com/package/hubot and it would be nice to have this built in to Hypha.

Current endpoint: https://github.com/OpenTechFund/botf

Packages like e.g. https://pypi.org/project/django-slack/ maybe can be of use.

**Comment by frjo** [comment]
@sks444 @sandeepsajan0 Any ideas or reflexions around this?

**Comment by fourthletter** [comment]
Perhaps this github issue would address our current situation? https://github.com/HyphaApp/hypha/issues/2630

**Comment by sandeepsajan0** [comment]
Yeah, It would be better to have it inbuilt for hypha. I'll do a bit of research about it.

**Comment by fourthletter** [comment]
@sandeepsajan0 Thanks for tackling this. ⚡

**Comment by fourthletter** [comment]
slack message was sent! Thank you! 💥 

![image](https://user-images.githubusercontent.com/20019656/175235070-6dd1d80c-4b0a-473f-9fc0-01338157fc82.png)
