### ISSUE TITLE
The "/django-admin/activity/event/" detail view crash with TypeError

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2855]
TypeError: has_add_permission() takes 2 positional arguments but 3 were given, see:

https://sentry.io/organizations/otf/issues/3288636037/?project=1268368&query=is%3Aunresolved

Removing "has_add_permission" from below resolves the issue but might have side effects. 

https://github.com/HyphaApp/hypha/blob/e560578d087b73cd923f01592b6e74cc953c81bf/hypha/apply/activity/admin.py#L6-L25

**Comment by sandeepsajan0** [comment]
Yeah, I see they have used `obj` as a mandatory argument. https://github.com/django/django/commit/6079ed82f43d8cc4b2c07eb36bc14efa0a1a5c17#diff-e77dfa6935de3fac94356ffd1029a679f8aa23f2979fe9b31aea7f93e1dccad3L2129.

Let me create a quick PR for this one.
