### ISSUE TITLE
Add search to select dropdown with many items like reviewers and partners

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2868]
For the become dropdown on the account page we have a search field on top to quickly find a specific user. (A side note, this fields should not have checkboxes since it is not multi select.)

This would be useful on more select dropdown like the reviewer and partner input fields found on the submission detail view.

![Skärmavbild 2022-06-02 kl  15 20 32](https://user-images.githubusercontent.com/191392/171639472-4c4de9db-93a6-4b7d-b8d4-d68f59c9f321.png)

![Skärmavbild 2022-06-02 kl  15 28 12](https://user-images.githubusercontent.com/191392/171640799-5368ecc6-9a46-4f4e-9eef-e2497ad43339.png)

![Skärmavbild 2022-06-02 kl  15 28 30](https://user-images.githubusercontent.com/191392/171640806-551cbfdf-b203-466d-b1ba-072fcb1deb37.png)

**Comment by fourthletter** [comment]
Related to improve design for assinging reviewers, partners, etc https://github.com/HyphaApp/hypha/issues/2723
and segmenting reviewers https://github.com/HyphaApp/hypha/issues/2783

**Comment by frjo** [comment]
Being done in another issue.
