### ISSUE TITLE
determination form error when creating a Fund

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2870]
### Description

When creating a Fund, the user is required to add a determination form to the Fund.

![Screenshot 2022-06-05 6 18 43 PM](https://user-images.githubusercontent.com/20019656/172094995-2433896c-bca5-4b8c-9813-e230b89ea195.png)

**Comment by frjo** [comment]
Yes, a determination form is required. Without it you can not do determinations.
