### ISSUE TITLE
Update password reset

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2871]
### Enhancement request
Please update https://apply.opentech.fund/account/password/reset/ with additional instructions. 

### Example

Forgot or want to change your password?

Please enter your email address. An email will be sent to your Primary Email address that includes a password reset link. You will have [x] days to access this reset link.

**Comment by frjo** [comment]
Does this look ok? I prefer not to make the days the link is active to public. That info is in the e-mail the user will receive.

![Skärmavbild 2022-06-06 kl  08 55 45](https://user-images.githubusercontent.com/191392/172111048-3388eaaa-abea-435a-a248-fc86d924b2a1.png)

**Comment by fourthletter** [comment]
@frjo - isn't it easier for them to change their platform profile?

please update text:

**Please enter your user account's email address and we will send you a password reset link.**

This looks great. Thank you! 💥
