### ISSUE TITLE
Roles checkboxes aren't aligned with labels

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2874]
**Describe the bug**

The "Roles" 

**To Reproduce**

Go to edit a user's "Roles" -- the checkbox labels are not aligned with the checkboxes.

**Expected behavior**

The labels should appear next to checkboxes.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff

**Screenshots**

<img width="414" alt="image" src="https://user-images.githubusercontent.com/208884/172200684-f485b374-d72b-45aa-b6c0-7967bfa5c540.png">

**Desktop (please complete the following information):**
 - OS: MacOS 12.4
 - Browser: Firefox

**Additional context**

In order to fix this in Hypha we need to add a hook to wagtail admin to load custom CSS on admin pages.

From there I want to note that simply adding float left to the checkbox doesn't do the full trick because of the way Wagtail checkboxes are rendered in Fun and Exciting ways.  In particular they used a `-5px` top which messes with vertical alignment.  That has [since been changed](https://github.com/wagtail/wagtail/commit/5996c5dd29200090948edefafa825c4b7ac43f5a#diff-e1bd478fcf7bc69d113aabd3a6a1cb0e3294cb6bd28aba916f8c21a9c7f9be47L199) though there is still a 2px `top` which might still cause a pixel of net awkwardness.

I'll have a PR for this soon.

**Comment by slifty** [comment]
Just a note that it looks like this interface has been awkward at the Wagtail level for maybe quite some time.

(Wagtail 3 fresh install is quite awkward -- even more so -- out of the box) https://github.com/wagtail/wagtail/issues/8633

I'm gonna throw in the patch here for our purposes.

**Comment by slifty** [comment]
Here's what I have it looking like now:

<img width="734" alt="image" src="https://user-images.githubusercontent.com/208884/172208472-6c4dd5d3-842f-4658-a28e-2d091c4220ac.png">

If folks like it I'll open the patch!

**Comment by frjo** [comment]
This would be good to get fixed, thanks!

**Comment by frjo** [comment]
This how it looks in Wagtail 3 so it will be fixed automatically as soon as we upgrade.

![Skärmavbild 2022-06-08 kl  11 51 38](https://user-images.githubusercontent.com/191392/172587939-03071969-e6db-408f-a823-df60c76328a9.png)

**Comment by slifty** [comment]
Much better -- though I think we'll still want to address the vertical centering of those labels (they're zippered right now instead of aligned).

Should I hold off on the patch in Wagtail 2 and wait until 3?

**Comment by frjo** [comment]
Yes, we will try to get in Wagtail 3 in a couple of weeks.

**Comment by frjo** [comment]
See https://github.com/HyphaApp/hypha/issues/2880

**Comment by theskumar** [comment]
The wagtail 3 feature is [merged](https://github.com/HyphaApp/hypha/pull/2934) and also this particular issue with vertical alignment has been [addressed in it](https://github.com/HyphaApp/hypha/commit/e464e91dd1c8a9badcb06133e10af57afaec9193#diff-a57e700965c351d3d51625e02dcba161a8833583a3f286d057701e08755e198fR12-R17). Closing the issue now.
