### ISSUE TITLE
Let users link arbitrary text in application field help text

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2875]
**Is your feature request related to a problem? Please describe.**

ARDC wants to link to documentation from the text above their application form fields, but the documentation is not in the form of a help guide, so they want to control which words are linked in the help text. Sometimes there are multiple links.

**Is your feature request related to an existing functionality? Please describe.**

Application form fields can define help text and a separate link to a "help guide." This would allow links on arbitrary text as opposed to a separate link.

**Describe the solution you'd like**

To do this, I changed the help text to a rich text field and controversially did away with the separate help guide link:

<img width="593" alt="Screen Shot 2022-06-06 at 1 36 27 PM" src="https://user-images.githubusercontent.com/1103467/172216031-12c4e9b5-20df-4ad1-abb2-496a6323eb1e.png">

<img width="466" alt="Screen Shot 2022-06-06 at 1 36 00 PM" src="https://user-images.githubusercontent.com/1103467/172216036-bb73f887-ba41-4872-a934-25e370b2ab3a.png">

**Describe alternatives you've considered**

ARDC could learn to love the separate link approach and we could rename that link to something other than "help guide" with a locale.

**Additional context**

I have a patch for this.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Applicants

**Ideal deadline**

No deadline.

**Comment by fourthletter** [comment]
This looks amazing, I look forward to testing it out soon.

**Comment by frjo** [comment]
This is how it looks now.

![Skärmavbild 2022-06-07 kl  15 33 33](https://user-images.githubusercontent.com/191392/172394113-a7aabd85-c71b-4a78-aca7-abadaa58ca3b.png)

**Comment by chriszs** [comment]
I assume that link opens in a new tab so as to preserve the user's progress drafting the application, which is presumably what the icon there is supposed to signal. Probably something we should take into consideration if we were to change it to this.

The disconnect between "here" and the link is actually a good example of the problem this tries to solve, though "here" is generally not a descriptive title for a link. But you could link "More information" or "OTF's Rapid Response remit" and that would be more direct than "See help guide."

**Comment by frjo** [comment]
Yes, it does automatically open in a new tab and has rel="noopener noreferrer" etc. Another benefit of letting the system create the links.

You can see them in action at https://apply.opentech.fund/internet-freedom-fund-concept-note/.

You do not see these links in your Hypha setup? They should just work out of the box.

I now notice that I have manage to miss making the string "See help guide for more information." translatieble. Will add an issue about it and get it fixed. Would be easy to make this string configurable as well.

**Comment by chriszs** [comment]
I do see them. I don't know all the reasons ARDC is opting for this instead, but the links they're adding definitely aren't to a help guide (as you say, we could translate) and occasionally there's more than one. Will ask.

**Comment by chriszs** [comment]
I do see them. I don't know all the reasons ARDC is opting for this instead, but the links they're adding definitely aren't to a help guide (as you say, we could translate) and occasionally there's more than one.

Here are the examples I was given:

<img width="980" alt="Screen Shot 2022-06-07 at 8 23 14 PM" src="https://user-images.githubusercontent.com/1103467/172505619-3f5f09e8-e7ae-4874-9eef-632eb7821916.png">

I had previously asked whether translated help guide links would work for this, a conversation was had and this was the preferred outcome. Will ask for further context.

**Comment by chriszs** [comment]
Actually it does seem like the links in these rich text fields have everything we just talked about:

<img width="961" alt="Screen Shot 2022-06-12 at 4 07 10 PM" src="https://user-images.githubusercontent.com/1103467/173251432-ee6233fe-1c79-4c62-ad55-52d1130ea12c.png">

**Comment by fourthletter** [comment]
This issue was completed.
