### ISSUE TITLE
Underlines and links

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2876]
**Is your feature request related to a problem? Please describe.**

We have a few (known) places where the universal lack of underlines in links is causing confusion.  The first is in the footer text -- if the site is configured with a link that link has no indication it is clickable.  For instance in this screenshot "Giving" is a link but you would never know:

<img width="633" alt="image" src="https://user-images.githubusercontent.com/208884/172242434-74e1960a-88ad-4c5d-870f-a3806b38e84a.png">

**Is your feature request related to an existing functionality? Please describe.**

There are existing links across Hypha that appear the same as non-link text; this applies to all of them.

**Describe the solution you'd like**

A lot of links in Hypha would be more legible with an underline.  For instance clickable elements in the submissions table, and even in-page navigation such as "Show All".

Might we consider making underline the default for all links and explicitly removing the underline for `.button` based links (e.g. the log out button)

**Describe alternatives you've considered**

Color alone doesn't do the trick since (A) not everybody can see color and also (B) the blue is used in other places on non-clickable text.

We could instead apply underline just to identified concern points, but I'm worried that will create inconsistency.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- General public

**Ideal deadline**

We'll make this change locally on our own timeline, so no major urgency.

**Comment by frjo** [comment]
The original designer was allergic to underlining I believe :-). As a developer I rather like them, from an accessibility stand point they are good as well.
