### ISSUE TITLE
Make the default notification for all user roles be e-mail

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2882]
## Additional context
This is a sub-issue of #2911 

### User Story

As a staff member, I need to receive email notifications when a contractor has submitted an invoice, when a new application has been submitted, or when I need to approve or review an item in Hypha.

### Description

- [x] List all the Slack notifications that do not have an e-mail version
- [x] Create e-mail templates for all the missing notifications
- [x] Make Hypha send e.mail notification by default.

The staff user roles now get notification only via Slack. For organisations not using slack this is big negative point in Hypha.

We should make all notification be e-mail by default and then keep Slack as an option for staff notifications. This should be controlled by an environment setting.

A neat plus feature would be to allow staff set their preferred notification method if there is more than one.

If an organisation have set that staff notification should go to Slack a staff user would then have the option to say that they want e-mail as well.

**Comment by sks444** [comment]
**Here is a list all slack notifications that doesn't have email version:**

[UPDATE_LEAD](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L431)
[BATCH_UPDATE_LEAD](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L432)
[APPLICANT_EDIT](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L435)
[PROPOSAL_SUBMITTED](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L443)
[NEW_REVIEW](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L445)
[OPENED_SEALED](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L447)
[REVIEW_OPINION](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L448)
[DELETE_SUBMISSION](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L450)
[DELETE_REVIEW](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L451)
[UPDATE_PROJECT_LEAD](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L453)
[EDIT_REVIEW](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L454)
[SEND_FOR_APPROVAL](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L455)
[APPROVE_PROJECT](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L456)
[REQUEST_PROJECT_CHANGE](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L457)
[APPROVE_CONTRACT](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L459)
[CREATE_INVOICE](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L460)
[DELETE_INVOICE](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L462)
[BATCH_DELETE_SUBMISSION](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L465)

**A few email notification that doesn't have slack version:**

[PARTNERS_UPDATED_PARTNER](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L754)
[UPDATED_VENDOR](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L757)
[SENT_TO_COMPLIANCE](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L758)
[SKIPPED_REPORT](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L762)
[REPORT_FREQUENCY_CHANGED](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L763)
[REPORT_NOTIFY](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L764)
[REVIEW_REMINDER](https://github.com/HyphaApp/hypha/blob/b5b013479d6b3093316adf4f0bd42878fa130631/hypha/apply/activity/messaging.py#L765)

**Comment by sks444** [comment]
Here are demo text messages that we send on slack, this could be helpful for designing email templates for them.

**UPDATE_LEAD**: The lead of [submission name](https://test-apply.hypha.app/apply/submissions/439/) has been updated from Di to Shrikrishna Singh by Shrikrishna Singh
**BATCH_UPDATE_LEAD**: Shrikrishna Singh has batch changed lead to Shrikrishna Singh on: [submission 1](https://test-apply.hypha.app/apply/submissions/432/), [submission 2](https://test-apply.hypha.app/apply/submissions/439/)
**APPLICANT_EDIT**: Shrikrishna Singh has edited [submission](https://test-apply.hypha.app/apply/submissions/439/)
**PROPOSAL_SUBMITTED**: 'A proposal has been submitted for review: [submission](https://test-apply.hypha.app/apply/submissions/439/)
**NEW_REVIEW**: Shrikrishna Singh has submitted a review for [submission](https://test-apply.hypha.app/apply/submissions/505/). Outcome: Yes,  Score: NA
**OPENED_SEALED**: Shrikrishna Singh has opened the sealed submission: [submission](https://test-apply.hypha.app/apply/submissions/505/)
**REVIEW_OPINION**: Shrikrishna Singh Agrees with Test Reviewers review of submission(this should be a link)
**DELETE_SUBMISSION**: Shrikrishna Singh has deleted submission
**DELETE_REVIEW**: Shrikrishna Singh has deleted {review_author} review for [submission](https://test-apply.hypha.app/apply/submissions/505/).
**UPDATE_PROJECT_LEAD**: The lead of project [project](https://test-apply.hypha.app/apply/projects/43/) has been updated from sks Staff to Shrikrishna Singh by Shrikrishna Singh
**EDIT_REVIEW**: Shrikrishna Singh has edited {review_author} review for [submission](https://test-apply.hypha.app/apply/submissions/505/)
**SEND_FOR_APPROVAL**: Shrikrishna Singh has requested approval on project [submission](https://test-apply.hypha.app/apply/submissions/505/)
**APPROVE_PROJECT**: Shrikrishna Singh has approved project [project](https://test-apply.hypha.app/apply/projects/43/)
**REQUEST_PROJECT_CHANGE**: Shrikrishna has requested changes for project acceptance on [project](https://test-apply.hypha.app/apply/projects/43/)
**APPROVE_CONTRACT**: Shrikrishna Singh has approved contract for <{link}|{source.title}>.
**CREATE_INVOICE**: Shrikrishna Singh has created invoice for [project](https://test-apply.hypha.app/apply/projects/43/)
**DELETE_INVOICE**: Shrikrishna Singh has deleted invoice from [project](https://test-apply.hypha.app/apply/projects/43/)
**BATCH_DELETE_SUBMISSION**: Shrikrishna Singh has deleted submissions: submission 1, submission 2

**Comment by fourthletter** [comment]
On June 21 standup we discussed the need to have different templates for slack, email, etc. because this feature would split up email from other messaging apps like slack,zulip, etc.

### Next Steps

- user research to hone in on what notifications users need and want
- refine message temaplates

**Comment by fourthletter** [comment]
As a user I prefer to receive an email notification when a new application is submitted to the lab I am managing.

**Comment by fourthletter** [comment]
On August 2 @theskumar is working on this issue to ensure existing slack messages have email equivalents. When implemented this solution would ensure organizations could receive notifications without third party messaging apps like slack, signal, etc. 

The next phase of implementation could potentially include email digests, timed emails that are not sent in real time, and give users more options to select their preferences. To determine user base preferences we would need to determine a standard list of categories. 

![Screenshot 2022-08-02 12 45 43 PM](https://user-images.githubusercontent.com/20019656/182356673-08c555bd-389b-4b11-ba6b-7ba095401953.png)

**Comment by fourthletter** [comment]
Do we still need this functionality in the project settings (image below) after the completion of #2882?

![image](https://user-images.githubusercontent.com/20019656/184145884-7b4c255f-6df4-4fa3-ad1d-055523bf9a09.png)

**Comment by theskumar** [comment]
Hi @fourthletter, In my last discussion with @frjo , I am 100 % not sure if we are keeping this particular setting. Still, for the v1 of the default email notification, we decided to have an alternative email added that should be seen as the equivalent of the slack bot's channel. 

We have a game plan of how the V2 of the notification system could look. At a high level, it would mean that we'll have a broadly classified set of notifications that are a little flexible, and those notifications can be followed by different people or emails. Etc.

**Comment by fourthletter** [comment]
> Hi @fourthletter, In my last discussion with @frjo , I am 100 % not sure if we are keeping this particular setting. Still, for the v1 of the default email notification, we decided to have an alternative email added that should be seen as the equivalent of the slack bot's channel.

@theskumar your approach makes a lot of sense moving forward. Thank you for clarifying.

**Comment by fourthletter** [comment]
Comments in Hypha are currently routed to an email designated by (ie app@apply.opentech.fund). Is this a global setting? Fund?

**Comment by frjo** [comment]
@fourthletter Can you post a copy of one of these comment notification mails ot Slack? I thought we only send e-mails to applicants regarding comments.

**Comment by fourthletter** [comment]
On September 20th standup we discussed Saurabh's implementation approach of making default email into a global setting associated with a particular Fund. The email template will be a digest of similar slack messages in groups. For example, all slack notifications associated with a new submission will be in one email digest.

**Comment by theskumar** [comment]
> The email template will be a digest of similar slack messages in groups. For example, all slack notifications associated with a new submission will be in one email digest.

@fourthletter Correction, the idea here is not the send different emails for different message types. The emails will be sent regularly (say 3 Hours or daily). If any new message comes for the staff/slack, since last sent they all will be sent in a single email. In this email, the message type can be grouped together in different sections. 

e.g. 
```
Summary

# Submissions
- New Submission 1
- New Submission 2
- Reviewer added

# Projects
- Invoice added to project 1

```

**Comment by fourthletter** [comment]
On September 27 standup we received a demo of feature. The same consistent set of messages could be sent via slack and/or email. Other messaging options include Zulip or Signal. Next step is to have a webhook

**Comment by frjo** [comment]
@fourthletter This is now on test, I have set so the e-mail digest goes out to your and mine e-mail addresses. On live I assume you will set some team/list e-mail address(s).

**Comment by frjo** [comment]
I have set the cron job that sends the digest to every 10 minuts for the test site.

**Comment by frjo** [comment]
I have received my first digest from the test site. Seems to work just as intended.

**Comment by fourthletter** [comment]
Thank you for pushing this through!

1) Will emails be part of a continuous thread? 
2) Slack enables certain funds and labs to have unique (separate) slack channels. Is this also possible for emails?
3) What is your proposed 2.0? Could we separate activities into broad categories? 

![image](https://user-images.githubusercontent.com/20019656/196465271-d28d4797-9ffe-4aea-8d6f-aceece6f7c61.png)

**Comment by frjo** [comment]
1. Each e-mail is a separate e-mail.
2. No, not at this point.
3. This PR already separate them into new submissions/comments/reviews/other. This can easily be adjusted based on feedback from users. We saw it as a decent starting point.

**Comment by fourthletter** [comment]
We will need to refine this issue before OTF could use it. However, the feature works. Thank you! 👍 

We need to document the chron job and other details for developers because each organization using it will have specific needs.
