### ISSUE TITLE
Add numbers for submission

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2884]
**Is your feature request related to a problem? Please describe.**

ARDC uses submission numbers or IDs extensively in their current CRP-based grants management process, using them to refer to specific applications in meetings and elsewhere.

**Is your feature request related to an existing functionality? Please describe.**

Our solution for this adds ID numbers to the submissions table, the submission details page and adds ID as a searchable field.

**Describe the solution you'd like**

Here's how we added it:

<img width="312" alt="Screen Shot 2022-06-12 at 3 45 06 PM" src="https://user-images.githubusercontent.com/1103467/173250620-2d29f648-01c4-4e8b-8d55-7fc577b568c3.png">

<img width="284" alt="Screen Shot 2022-06-12 at 3 40 44 PM" src="https://user-images.githubusercontent.com/1103467/173250636-995544fe-df20-4e04-b4ff-1ad2d4bec709.png">

<img width="1325" alt="Screen Shot 2022-06-12 at 3 45 43 PM" src="https://user-images.githubusercontent.com/1103467/173250619-caa0e521-ec1f-4085-8349-d7da2cea4d84.png">

**Describe alternatives you've considered**

There are some implementation details that could vary.

**Additional context**

Could PR.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff

**Ideal deadline**

No deadline.

**Comment by frjo** [comment]
I do not see a problem with accepting a PR that adds this column. Other Hypha users can use the existing SUBMISSIONS_TABLE_EXCLUDED_FIELDS to exclude any columns they do not need.

The same PR, or a separate one, can also fix the ordering of the filters so they sync with the columns. I see you have fixed that in the screenshot above.

**Comment by frjo** [comment]
Adding the number to the header after the title I leave up to other implementer to comment on.
