### ISSUE TITLE
Customizing the recommendation field on review forms

### ISSUE THREAD

**Issue by slifty** [HyphaApp/hypha#2891]
**Is your feature request related to a problem? Please describe.**

The "Recommendation" field is currently a required field, and its answers are restricted to "yes / no / maybe"

There is a user desire for this field to be more akin to score, providing a 0-5 range of values (along with a "need more information" and "n/a" option).

**Is your feature request related to an existing functionality? Please describe.**

This is related to the current "recommendation" field.

**Describe the solution you'd like**

I don't know if there is an ideal upstream solution but wanted to raise the question here.  Some possibilities:

1. Provide a way to define the values for this field in the wagtail admin interface.
2. Provide a way to override the values for this field via site setting.
3. Remove the requirement for this field entirely, thus allowing the user to just create the field they want with existing functionality.

Something else?

**Describe alternatives you've considered**

I don't have a specific solution yet, so all ideas are intended as being considered.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Reviewers

**Ideal deadline**

None -- for now we'll just override the `options.py` to set the values we want in our instance, but ideally we could modify this without diverging from upstream.

**Comment by slifty** [comment]
I realize this field drives the red / yellow / green lights as well, so this is a more complex conversation than just text.  In our case we'll be mapping a series of "strong / weak / accept" to "yes" and the same for reject

**Comment by bickelj** [comment]
@frjo I don't think I submitted a PR for this one, but is it resolved elsewhere?
