### ISSUE TITLE
Customize review score range, e.g. 0-3, 0-5, 1-10

### ISSUE THREAD

**Issue by chriszs** [HyphaApp/hypha#2897]
**Is your feature request related to a problem? Please describe.**

ARDC has different scoring for different questions in the review process, so one question might have a maximum score of 10 and another 3. To accomplish this, they've been using the dropdown field and inputting a list of numbers, e.g. 0, 1, 2, 3, 4, 5, 6, 7, ... etc. but that's cumbersome and doesn't total into an overall score.

**Is your feature request related to an existing functionality? Please describe.**

In a review form, you can add a score block and then it appears when reviewers review.

**Describe the solution you'd like**

What we've done so far is to add options for up to 0-10 and maximum and minimum fields to Score Without Text block, like so:

<img width="120" alt="Screen Shot 2022-06-27 at 7 55 29 PM" src="https://user-images.githubusercontent.com/1103467/176058569-e43c6289-c234-4b34-94fe-58a59191bfe0.png">

<img width="236" alt="Screen Shot 2022-06-27 at 7 56 02 PM" src="https://user-images.githubusercontent.com/1103467/176058630-63630278-8895-4c95-b0d6-6adb2d743335.png">

**Describe alternatives you've considered**

This design was arrived at after considering a coupe other options, including a dropdown in which could select which range (it was requested to add a minimum value also, in case people want to start at 1 not 0).

**Additional context**

This current implementation isn't perfect. The implementation doesn't require a value in the min or max fields because a default of 0 was detected as false. It does allow the user to specify a negative range, e.g. 8 - 5, though the way it handles that is just to set the min to the max silently.

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Reviewers

**Ideal deadline**

No deadline.

**Comment by fourthletter** [comment]
This issue was completed.
