### ISSUE TITLE
Replace django-two-factor-auth with something that support WebAuthn 

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2898]
* [mkalioby/django-mfa2: A Django app that handles MFA, it supports TOTP, U2F, FIDO2 U2F (Webauthn), Email Token and Trusted Devices](https://github.com/mkalioby/django-mfa2/)
* [justinmayer/kagi: WebAuthn security keys and TOTP multi-factor authentication for Django](https://github.com/justinmayer/kagi)

Webauthn is the base of Apple/Googles/etc. new "passkeys" feature ment to replace passwords in the long run. Apple will release "passkeys" in the next versions of macOS/iOS etc. later this year.

Test it here: https://www.passkeys.io

Worth taking a look at I think. Read more: [Why Passkeys Will Be Simpler and More Secure Than Passwords - TidBITS](https://tidbits.com/2022/06/27/why-passkeys-will-be-simpler-and-more-secure-than-passwords/)

Another good article: [Passkeys: Death to passwords](https://arstechnica.com/gadgets/2022/10/macos-13-ventura-the-ars-technica-review/15/#h1)

* https://webauthn.guide
* https://www.hanko.io/blog/passkeys-part-1

**Comment by fourthletter** [comment]
Related to #2837
