### ISSUE TITLE
Re add the PAF stream field form

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2904]
## Additional context
This is a sub-issue of #2911  

## User story

> As a programme manager, I want to create a Project Approval Form so that the project can receive their contract

### Description

The PAF stream field was removed in this PR https://github.com/HyphaApp/hypha/pull/2635 so should be fairly easy to re add.

With the simplification of the contracting and the removing of the IntAcct integration I believe a stream field form will be the most flexible solution.

If this looks good then we will replace the current minimal PAF form with the stream field version.

**Comment by fourthletter** [comment]
@sandeepsajan0 @frjo You're both correct about a process where PM's can only edit the PAF at specific junctures similar. This is similar to invoicing or when applicants could only edit the submission during certain workflow states or given 'permission' to do so.

**Comment by fourthletter** [comment]
I created a PAF in WagTail https://test-apply.hypha.app/admin/application_projects/projectapprovalform/edit/1/

but it has not appeared on the project page https://test-apply.hypha.app/apply/projects/78/

**Comment by sandeepsajan0** [comment]
@fourthletter We also have to assign the PAF to the Fund.
<img width="951" alt="image" src="https://user-images.githubusercontent.com/23638629/178246690-3fe99f2b-85b5-410a-b596-792536c7bd75.png">

 I checked that project "PAF Workflow"(the link you provided) based on Bernard's Internet Fund(https://test-apply.hypha.app/admin/pages/938/edit/) and attached the Approval form to it and now you can see it is getting appeared there on project page https://test-apply.hypha.app/apply/projects/78/edit/.

**Comment by fourthletter** [comment]
Hi @sandeepsajan0 I completed the PAF form, but am not able to save the PAF https://test-apply.hypha.app/apply/projects/78/edit/

![image](https://user-images.githubusercontent.com/20019656/178250172-dc232c01-5aec-4bfa-9770-e9b5501c693e.png)

**Comment by sandeepsajan0** [comment]
Yes, I just checked that. Looks like it is somehow related to the BlockFieldWrappers or we can say https://github.com/HyphaApp/hypha/issues/2909. I tried without header and section text in my local and it works. Let me try to fix it in the same PR for the PR's code.
