### ISSUE TITLE
PDF and text/doc output of PAF

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2912]
## Additional context
This is a sub-issue of #2911  and output of #2904 Re add the PAF stream field form

## Description

Compliance needs to provide contractors and auditors with a contract and the SOW. The SOW contains part of the information in the PAF, and can be generated by the WebApp. 

![](https://share.balsamiq.com/c/aUxtq9tx1MLPYjxVrUJrxY.png)

![Design option for Scope of Work PDF output](https://share.balsamiq.com/c/oowAKSKVe8TdPcRyo45Ps4.png)

## Summary

A bundle of information could be exported as pdf files for external stakeholders as a batch action.

## Possible workflows

(Bestest) Option 0. Generated at the same time as the contract:
- Amended to the contract template information
- CA can create a contract with the SOW incorporated into the template (related to #8 )
- CA can export both contract and SOW templates into their document editor
- Contract and SOW will be stored in the system of record/relevant google drive folder

Option 1. The manual process could be something like:
- Finance user goes to Hypha and identifies the projects they need to export as a pdf output
- Finance user asks the Lead Dev for these projects to be exported
- Lead Dev does the export, which creates a number of pdf files
- Finance user downloads/receives pdf files from Lead Dev

Option 2. A more self-service process could be:
- Finance user goes to Hypha and identifies the projects they need to export as a pdf output
- Finance user goes to Hypha to highlight/select the projects 
- Finance user then "exports" the information bundle (contract and scope of work) and downloads the pdf files

## What is required?

0. Generated at the same time as the contract
- Validation that the contractor and auditors get the same SOW - needs OTF to answer
-design: include SOW creation into the contract creation process
-technical: to figure out how to generate the contract template at the same time as the SOW template

2. Minimum process
- design: the Scope of Work output file
- technical: @frjo to figure out how the pdfs get exported

3. Self-service process (images below)
- design: the process so the user can select the projects in Hypha and export the Scopes of Work
- design: the Scope of Work output file
- technical: @frjo and devteam figure out how the pdfs get exported

## Priority
- High (keeping you from completing day-to-day tasks)

## Ideal deadline
October 2022

**Comment by frjo** [comment]
Also add a plain text, or even better, a doc format output with the same content as the PDF.

**Comment by fourthletter** [comment]
> Also add a plain text, or even better, a doc format output with the same content as the PDF.

@sandeepsajan0 this issue will only focus on what frjo mentioned above. I'm sorry for the confusion. I was hoping we would have a designer on board to refine the design of the output, but this is not the case.

**Comment by fourthletter** [comment]
The test version looks amazing! 🍾 🥂   

![image](https://user-images.githubusercontent.com/20019656/203173106-b5933583-d707-46d0-aff4-7b88f6dc22ac.png)
