### ISSUE TITLE
Add feature flag to make Finance 2 user workflow optional 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2918]
## Description

Add a feature flag (in base.py) to set if finance 2 needs to approve invoices or if finance 1 can do it themselves.

Name it ´INVOICE_EXTENDED_WORKFLOW´, default too false.

## Priority
- High (keeping you from completing day-to-day tasks)

## Ideal deadline
October 2022

## Dev Tasks

- [ ] Add new wagtail settings to make `Finance 2` optional, with help text - `All the permissions of Finance 2 will be transferred to Finance 1.`
- [ ] ❓ where in the admin should we have this setting?
- [x] If Finance 2 is optional, hide the UIs related to the `Finance 2` role and update the logic to upgrade the permission of `Finance 1` position.
- [x] Add Tests - Settings Page, workflows.

**Comment by frjo** [comment]
Updated this issue to make it a feature flag not a removal.

**Comment by frjo** [comment]
One second thought an organisation who do not need the two steps (finance 1/2) for invoices can simply make all finance users finance 2. I think this is the cleanest solution.

**Comment by theskumar** [comment]
@frjo Update: I added the dev tasks in this issue.
