### ISSUE TITLE
Approver Role: PAF to approve table

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2923]
## Additional context
This is a sub-issue of #2911 

## Describe the solution you'd like in Hypha
In Hypha the Approver needs to view PAF's awaiting approvals on a table/dashboard 

## Current Dashboard

![image](https://user-images.githubusercontent.com/20019656/189351420-31f9ceea-3428-4788-90b4-ecd954e69e88.png)

## Priority
- Low

## Ideal deadline
February 2022

**Comment by sandeepsajan0** [comment]
@fourthletter I think we discussed that only staff(PMs), finance members, and contracting members will approve the PAF. Right now, the approver doesn't even have permission to PAF.
Do we want to include the approvers to the above list and provide them permission to PAF?

**Comment by fourthletter** [comment]
@sandeepsajan0 Approvers need their own table or dashboard to approve PAF's as well. 

The Approver dashboard should only have PAF's that have been approved by Contracting. Let's discuss more tomorrow! Thank you.

**Comment by frjo** [comment]
No user will ever only have the "Approver" role. It will always be "Staff with Approver", "Contracting with Approver" etc.

The Approver role is ment to extend the permissions of other roles.

**Comment by fourthletter** [comment]
We could be more specific and say the table or dashboard for displaying PAF's awaiting FINAL APPROVAL should only be seen by "Contracting with Approver"

**Comment by sandeepsajan0** [comment]
**Record**: On Oct 18 standup, we decided to show a separate table of PAFs that requires Final approval, on the contracting dashboard.

**Comment by fourthletter** [comment]
This is what the Staff + Approver role sees. Thanks @sandeepsajan0 

![Screenshot 2022-10-23 11 19 58 AM](https://user-images.githubusercontent.com/20019656/197384573-e0c6290a-ad69-4e7b-875c-0c4b57d33b7d.png)

**Comment by frjo** [comment]
@fourthletter  Are we all good here so the issue can be marked approved?
