### ISSUE TITLE
Staff Role: PAF submitted table

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2924]
## Additional context
This is a sub-issue of #2911 

## Describe the solution you'd like in Hypha
In Hypha Staff needs to view PAF submitted on a table/dashboard 

## Priority
- Low

## Ideal deadline
February 2022

**Comment by fourthletter** [comment]
Staff sees projects 1) in progress, 2) committed, 3) contracting, and 4) waiting approval. I no longer remember what "committed" means. Looks great! Thank you @sandeepsajan0 

![image](https://user-images.githubusercontent.com/20019656/197384738-695c889d-80c5-4ce9-92fc-4da86a3a3724.png)

**Comment by frjo** [comment]
If "Committed" is not obvious we should change the name.

It is the first status a project gets after being created. Before staff submit it for approval.

What do you think we should name it?
