### ISSUE TITLE
Add ability to link to PGP key on people pages

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2926]
### User Story

Add 'apply link' field to contact method on public website. PGP fingerprints need to have associated keys.

![image](https://user-images.githubusercontent.com/20019656/178039283-1469d0bf-4ca4-48c3-b8ab-913dcba2671a.png)

**Comment by frjo** [comment]
What is a "Apply link"?

**Comment by fourthletter** [comment]
Maybe **document** is the better option? The goal is to attach the key as a document like a hyperlink. Did you have breakfast yet? 🍳 

![image](https://user-images.githubusercontent.com/20019656/178099957-74c84bf9-71c5-4d49-bfd2-46a707799144.png)

![Screenshot 2022-07-09 11 24 25 AM](https://user-images.githubusercontent.com/20019656/178099936-ce68ae76-443f-48e3-a020-39e6fed4d90a.png)

**Comment by frjo** [comment]
These are field types in stream field forms like application forms etc. Not really relevant for this issue. Changed the title to explain what the outcome should be.

Why is it important to have a link to the PGP key? The e-mail client will automatically retrieve the key from a key server.

The fingerprint is there to confirm that you have the correct key.

If this is something the OTF really wants I suggest you build it in to your new site. This old one we should not spend effort on in my opinion.

**Comment by fourthletter** [comment]
I am closing this issue because a feature to embed links/url already exists.
