### ISSUE TITLE
The same comment show multiple times in in-app notifications

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2929]

**Comment by sandeepsajan0** [comment]
@frjo Can you please share some details for this issue? 
I think it might be the case that the same user has commented multiple times so it might show like " `user` made a comment" multiple times.

**Comment by fourthletter** [comment]
@sandeepsajan0 Thank you for following up, you are correct. The bug is more obvious on the live site

![image](https://user-images.githubusercontent.com/20019656/183958002-a0830c85-8e1f-4362-83b8-6f9a92de272b.png)
