### ISSUE TITLE
Ability to use default/provided workflows, modify defaults, or create new workflows from scratch for funds/labs 

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#294]
As a manager, I want the ability to use default/provided workflows, modify them, or create new workflows from scratch for funds/labs

**Is your feature request related to a problem? Please describe.**

Currently, Hypha only support 4 'hard-coded' workflows for funds/labs. The flexibility in these is limited (but not impossible) however, building fully flexible configurable workflows in Wagtail/Hypha would allow for less reliance on developers to make changes to workflows adhoc and allow for more experimentation for funders when they want to try different funds/labs.

This could also enable adopters to 'share' workflows and rationale for workflows in an 'OSS content' way.

This is a very large 'feature' and is more at the Epic/META level in current description.

**Is your feature request related to an existing functionality? Please describe.**

Related to:
* Existing workflows
* Forms/fund creation in Wagtail
* OSS content sharing
* ...plenty more!

**Describe the solution you'd like**

An idea of how to approach this could be a 'fund/lab workflow builder' in a sort of WYSIWYG way. This would need to be validated by user research that is more exploratory in nature.

**Describe alternatives you've considered**

Another option that is worth scoping is how existing workflows might be 'templates' that can be added to but not 'removed from'. An iterative way to explore this big feature is key. 

**Additional context**
![Screenshot 2022-04-07 at 10 57 53](https://user-images.githubusercontent.com/11681324/162174369-16705e18-6108-481f-8dfc-ce66546ac06f.png)

^^ Current dropdown of 'workflows' in test.hypha.app 

**Priority**

Depending on the adopter:
- Medium (slowing you down)

or:
- Low priority (annoying, would be nice to not see)

This becomes critical when a existing funds/labs do not reflect future planning from a funder - this epic/META could rapidly move from low to high depending on their strategy and whether existing workflows fit those fund/lab strategies.

**Affected roles**

- Staff (they would be using this fund/lab editor)
- Developers (they would no longer need to hard code funds/labs)

**Ideal deadline**

Recommend review in Q2 rebasing for priority level post summit 2022

**Comment by saoun** [comment]
@frjo @fourthletter isn't this how it currently works?

**Comment by frjo** [comment]
The workflows are hardcoded, you can pick on of the four that exist but not change them or add new ones.

This is mayor new development but it would make the system a lot more flexible for different organisations.

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* This is a very large 'feature' and is more at the Epic/META level in current description.
* Added epic label
* This is not a single issue, it's more of an Epic/META. - **PM needed to build out Epic/META details**
* Added the issue template to body with content.
* Recommend review in Q2 rebasing for priority level.
* Updated title of issue to shortened version
* *Priority needed label could be removed - **Adopters needed to confirm strategical need of this** + **Could benefit from user research with reviewers**
* Size estimated at XXL
* Removed from dev backlog board: https://github.com/HyphaApp/hypha/projects/2

**Comment by fourthletter** [comment]
> The workflows are hardcoded, you can pick on of the four that exist but not change them or add new ones.
> 
> This is mayor new development but it would make the system a lot more flexible for different organisations.

Users could currently select from at least four different workflows as noted in the original issue,  options include a single stage workflow or two stage workflow. Users could also change the names of each workflow status via translatable files. 

While I could see the value making workflow selection more configurable, isn't Hypha already offering adopters a great deal of options and flexibility in terms of workflows?
