### ISSUE TITLE
Applicants saving a draft does not receive an email notification

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2940]
### User Story

I submitted a draft submission as an applicant, but received no further instructions on how to access this draft. 

### Suggested Solution

Applicants will be sent an automated email notification similar to when an applicant submits an application with a url to their draft

**Comment by theskumar** [comment]
```
Subject: Your application to Acme Corporation: {{ project.title }}
To: applicant@email.com

Dear {{ user }},

We appreciate your {{ project.title }} application submission to the Acme Corporation.

Please note that it is not submitted for review because it's still in draft. You can access the draft at: http://apply.hypha.test:8090/apply/submissions/36/

If you have any questions, please submit them here: http://apply.hypha.test:8090/apply/submissions/36/#communications

If you have issues accessing the submission system or general inquiries, please email us at info@example.org.

For more information about our support options, review process, and selection criteria, please visit our website at https://www.example.org/.



Project name: Draft Project
Contact name: Admin User
Contact email: f@f.com



Kind Regards,
The ACME Team

-- 
Acme Corporation
http://hypha.test:8090
```

This is a slightly modified version of the copy sent when the final submission of application submission is made (see below).

> Dear {{ user }},
> 
> We appreciate your {{ project.title }} application submission to the Acme Corporation. We will review and reply to your submission as quickly as possible.
> 
> If you have any questions, please submit them here: http://apply.hypha.test:8090/apply/submissions/36/#communications
> 
> If you have issues accessing the submission system or general inquiries, please email us at info@example.org.
> 
> For more information about our support options, review process, and selection criteria, please visit our website at https://www.example.org/.
> 

Let me know if this is okay to move ahead. @fourthletter

**Comment by fourthletter** [comment]
@theskumar Email looks great. Thank you so much! 👍

**Comment by theskumar** [comment]
@fourthletter Cool! 

 @frjo can you please review and merge PR #2948 Thanks.
