### ISSUE TITLE
Add a guide message if PAF is not configured to the fund

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#2960]
For now, I am thinking of showing a message on the same page.

"Approval Form is not configured the fund associated with this project/submission. Please configure it first from [Wagtail Admin]('URL to respective fund')."

**Comment by theskumar** [comment]
I believe this is a non-issue now, as the system can have a functional round/lab without an additional PAF form. @frjo @fourthletter

**Comment by fourthletter** [comment]
I see the message. Looks great! 💯 

![image](https://user-images.githubusercontent.com/20019656/189350267-a5b484d0-8e33-4c72-ab96-929ab0896335.png)
