### ISSUE TITLE
Display of workflow and forms names on rounds in wagtail admin are wrong

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2965]
Display the round name instead of the name of each workflow/form.

**Comment by theskumar** [comment]
![Screenshot 2022-09-06 at 08 10 32](https://user-images.githubusercontent.com/236356/188582980-a1c6a0bf-591e-49b2-8e01-2fd72ebeeaf0.jpg)

**Comment by fourthletter** [comment]
Looks great! 💯 

![image](https://user-images.githubusercontent.com/20019656/190374608-4b942ee9-0631-4042-9f8e-3e6db838baa9.png)
