### ISSUE TITLE
Wagtail admin sidebar is not visible after upgrading hypha to 3.0

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#2967]
**Describe the bug**

- Wagtail admin sidebar is not visible in updated instance of hypha and styling is bit odd.

**To Reproduce**

- Just follow the documentation to setup the project and login as a staff user.

**Expected behavior**

- Wagtail admin sidebar should appear as previous versions

**Priority**

- High

**Affected roles**

- Staff

**Screenshots**
![Screenshot from 2022-08-31 18-20-58](https://user-images.githubusercontent.com/111306331/187694963-be62d898-a997-450c-9c9e-a6cb826dd7fd.png)
![Screenshot from 2022-08-31 18-21-50](https://user-images.githubusercontent.com/111306331/187694995-e6cd87b5-0e75-4a49-a53b-5052ee7acdb8.png)

**Comment by frjo** [comment]
Should be fixes by rebuilding the css and js files.

`npm run build`

or in development environment

`npm run watch`

**Comment by gmurtaza00** [comment]
> Should be fixes by rebuilding the css and js files.
> 
> `npm run build`
> 
> or in development environment
> 
> `npm run watch`

Yes, i have tried rebuilding the css and js files, then running collectstatic command.
Also tried `npm run watch`.
The issue still persists.

**Comment by frjo** [comment]
Try to clear out `/static` dir and `hypha/static_compiled`dir and then rerun the npm command.

**Comment by gmurtaza00** [comment]
@frjo no success.

**Comment by frjo** [comment]
This was tricky. Was pretty sure the above would solve the issue.

Assume you already done the following but just to be sure.

```
python manage.py migrate
pip install -r requirements.txt
or
pip install -r requirements-dev.txt
```

We are running the latest code with Wagtail 3 on a number of environments (live/test/sandbox/dev) without this issue.

**Comment by gmurtaza00** [comment]
@frjo https://sandbox-apply.opentech.fund/ is the sandbox url. right?
I see its using wagtail 2.16.1

![image](https://user-images.githubusercontent.com/111306331/187755770-49713037-2bde-4196-8447-a47151b63a66.png)

**Comment by frjo** [comment]
You are correct, it has been too long since I updated the sandbox, will get that done this week. Thanks for reminding me.

**Comment by frjo** [comment]
Sandbox is now updated.

![Skärmavbild 2022-09-01 kl  18 37 25](https://user-images.githubusercontent.com/191392/187967185-be4b7167-5cc2-4659-80fe-54755e9caa61.png)
