### ISSUE TITLE
Provide finer grained control over email notifications on submission status update

### ISSUE THREAD

**Issue by killapop** [HyphaApp/hypha#2968]
**Is your feature request related to a problem? Please describe.**

I am adopting hypha for a client and they do not have all of the internal workflow steps in their process. So to skip a workflow step they go through them by updating the status to get through the steps they want to skip. This sends notification emails out to the applicant which firstly are quite annoying but more importantly gives the applicant the impression that the submission is going through steps that don't exist for the organisation. Is there a way to avoid this happening.

**Is your feature request related to an existing functionality? Please describe.**

- Email notifications
- Status Updates

**Describe the solution you'd like**

I am wondering if a possible fix for this is to have a checkbox in the update status/determination form that toggles the particular notification for that step on or off to give the fund manager more control at the status change step.

**Describe alternatives you've considered**
**Additional context**
**Priority**
- High

**Affected roles**

- Staff
- Applicants

**Ideal deadline**

**Comment by frjo** [comment]
You could create a new workflow for them with the steps they need.

**Comment by frjo** [comment]
But user/org control over the notification are on the task list.
