### ISSUE TITLE
User e-mail field is not case incentive

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#2985]
This makes it possible to have one user with `test@example.org` and another with `TEST@EXAMPLE.ORG` etc.

Since e-mail is also the username this need to be fixed.

There is a number of accounts today with duplicate e-mails. How should we handle these @fourthletter.

See also https://github.com/OpenTechFund/issues.otf/issues/34

**Comment by fourthletter** [comment]
Let's discuss a technical plan for deleting them. 1) Is it possible to archive these accounts? 2) What happens to associated documents? 3) We need a technical plan that aligns with our data policy/compliance for saving documents. 

Before we remove any accounts from the system, I could send a letter to these individuals to let them know their accounts have been suspended, and that they need to choose only one viable account on Hypha.

**Comment by theskumar** [comment]
@sandeepsajan0 For you to consider, as discussed overall for implementation: 
1. https://github.com/taigaio/taiga-back/blob/master/taiga/users/services.py#L46-L59
2. https://docs.djangoproject.com/en/4.1/ref/contrib/postgres/fields/#django.contrib.postgres.fields.CIEmailField

**Comment by fourthletter** [comment]
On September 20 standup we discussed migrating documents (ie proposals) from disparate accounts and preserving the case inputted by the user.

**Comment by fourthletter** [comment]
Amazing! Thank you 💯 

![image](https://user-images.githubusercontent.com/20019656/193823657-5dc8333c-764b-488a-af26-67bc1edd2fd9.png)
