### ISSUE TITLE
Applicants need to edit approved proposals

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#2988]
### User Story

As a program manager I need to revert an approved submission for applicants to make additional edits. Approved proposals because it may be missing information that is required before proceeding to invoicing.

Example: 
https://test-apply.hypha.app/apply/submissions/480/

Option 1: Applicant could EDIT approved submissions. This would show in the Activity Feed
Option 2: Applicant could revert the approved submission to a workflow status where they could EDIT

**Comment by frjo** [comment]
I believe staff already can edit all approved submissions, including proposals.

**Comment by fourthletter** [comment]
@frjo I updated the issue to applicants, not staff.

**Comment by frjo** [comment]
In an audit how is one to know what was approved if everyone can edit the submission at any time?

**Comment by fourthletter** [comment]
You're right. The last stage of approval should be 'frozen'
