### ISSUE TITLE
Feature: Support archiving of submission

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#2996]
### User Story
Historic submissions and rounds are not relevant and they become noise on the dashboard. Labs doesn't need archiving they are long lived. Mimizing the amount of data on the platform aligns with better data retention and responsibility practices.

### Proposed Solution

MVP: Archive entire rounds, funds, labs
Long-term goal: archive individual submissions

- Archive submission using true/false (no future date based)
- Send staff notification when some
- Should be able to unarchive a submission
- Add "Archive" button; it should behave the same way as "Delete" button.
- If a submission is archived, then:
  - reviews are also archived
  - determinations are also archived
- 'Staff Admin' and 'Admin' would be able to archive. This functionality is not available to other user groups. 

**Additional context**

![Screenshot 2022-10-04 at 09 05 28](https://user-images.githubusercontent.com/236356/193781541-45c096ac-0f6b-4f5b-aef5-b889f481edf9.jpg)

**Priority**
- Medium (slowing you down)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers
- General public

**Ideal deadline**

end of Q4

**Comment by frjo** [comment]
1. Add a setting to decide if staff or only staff admin should see archived/all submissions.
2. Rename All submissions to Active submissions
3. Add another view for "active" submissions. Let all be "all".
4. Test to use tab views for active/archived tables.
5. In "all" view separate out the archived submissions with a different background or something like that.
6. Links in filter section that links to all/archived/active

~~~~
SUBMISSIONS_ARCHIVED_ACCESS_STAFF  = env.bool('SUBMISSIONS_ARCHIVED_ACCESS_STAFF', False)
SUBMISSIONS_ARCHIVED_ACCESS_STAFF_ADMIN  = env.bool('SUBMISSIONS_ARCHIVED_ACCESS_STAFF_ADMIN', False)
~~~~

**Comment by frjo** [comment]
7. I think the addition of a archived table on the submission overview is not needed.

**Comment by fourthletter** [comment]
I'm not able to see the unarchive function. Thanks.

![image](https://user-images.githubusercontent.com/20019656/200851060-b30ad516-42b1-4152-b1a3-9f8c4e42b6c7.png)

**Comment by frjo** [comment]
@fourthletter Can we do the unarchive feature in a separate issue?

**Comment by fourthletter** [comment]
I don't see the "show archived submissions" toggle.

**Comment by frjo** [comment]
@fourthletter You should see them now, I had missed to add the SUBMISSIONS_ARCHIVED_ACCESS_STAFF_ADMIN setting to the test site.
