### ISSUE TITLE
Settings file loaded by django-admin/manage.py

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3004]
This is related to the issues with `EMAIL_BACKEND` in https://github.com/HyphaApp/hypha/pull/2991.

Environment variable `DJANGO_SETTINGS_MODULE` is set to `hypha.settings.dev`.

~~~~
echo $DJANGO_SETTINGS_MODULE
hypha.settings.dev
~~~~

But when I run django-admin/manage.py it is not picked up. According to https://docs.djangoproject.com/en/3.2/ref/django-admin/ it should work.

If I set it explicitly with `--settings hypha.settings.dev` it works just as it should.

Any ideas?

**Comment by theskumar** [comment]
The correct setting is picked for me if the environment variable is provided.
![Screenshot 2022-10-12 at 19 05 33@2x](https://user-images.githubusercontent.com/236356/195428386-882936bd-dcbc-41fe-9c65-273ccbb0e5d2.jpg)

**Comment by frjo** [comment]
Tested now and when I set it explicitly in the venv like above it works for me as well.

I had it set in my "zshenv" so it was set for all terminal sessions I open. That doesn't seems to work for venv environments. I now set it in `venv/bin/actiate`. Looks like that works.

Thanks for testing this!
