### ISSUE TITLE
Add activity e-mail digest for each Fund and Lab

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3017]
### User Story

As a Program Manager (staff user), I would like more granular control over which emails I received from Hypha. Existing categories or sub-headings in the email digest include Submissions, Comments, Other activities. As a user I would like to only receive emails related to submissions.

### Proposed Solution

- [ ] Add an "Digest recipient e-mails" field to each Fund and Lab. Similar to the existing Slack channel field.
- [ ] Create the same type of digest as the global one but filtered for each Fund and Lab.
- [ ] Send out all digest with the same cron command

**Comment by fourthletter** [comment]
This is a different github issue, but could we please plan on next steps for e-mail digest related to invoices and contracts on the Project page? Thank you.

**Comment by frjo** [comment]
Migration conflict so needs to wait a bit.

**Comment by fourthletter** [comment]
It works -- thank you!

![image](https://user-images.githubusercontent.com/20019656/212857777-99867c71-b974-4ea8-9699-1edc6827a998.png)
