### ISSUE TITLE
Upgrade to Wagtail 4.x

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3018]
Wagtail 4.x supports Django 3.2 according to https://docs.wagtail.org/en/stable/releases/upgrading.html#compatible-django-python-versions

Short term we want access to Global settings, see https://docs.wagtail.org/en/stable/releases/4.0.html#global-settings-models

See https://docs.wagtail.org/en/stable/releases/4.0.html#upgrade-considerations

**Comment by fourthletter** [comment]
Looks great!

![Screenshot 2023-01-20 12 09 22 PM](https://user-images.githubusercontent.com/20019656/213681727-587dc6e8-671b-4585-a525-b387a1733793.png)

**Comment by frjo** [comment]
@theskumar Opening/edit a Rounds leads to a server 500 error, https://dev-apply.opentech.fund/admin/funds/round/.

**Comment by theskumar** [comment]
> @theskumar Opening/edit a Rounds leads to a server 500 error, https://dev-apply.opentech.fund/admin/funds/round/.

It fails with the missing template error, looking into it. 
```
TemplateDoesNotExist at /admin/pages/18/edit/
wagtailadmin/panels/single_field_panel.html
```

**Comment by theskumar** [comment]
I've added a fix for it. It looks now on my local machine, using the sandbox db dump. 

The `wagtailadmin/panels/single_field_panel.html` was removed in https://github.com/wagtail/wagtail/commit/5521e3b59f45af830ebac3c5686e092616eb82e4#diff-5f423c8a648872a3fdaced74d5a742a679eb4a6fd858aa6a4643056b7f86bb32

![Screenshot 2023-02-14 at 06 46 06@2x](https://user-images.githubusercontent.com/236356/218660023-38e9b48b-600c-4385-b91b-f8356f95fb03.jpg)

**Comment by frjo** [comment]
@theskumar, @fourthletter  found another issue, creating a round.

~~~~
TemplateDoesNotExist at /admin/funds/round/choose_parent/
modeladmin/includes/header_with_breadcrumb.html
Request Method:
GET
Request URL:
http://apply.hypha.test/admin/funds/round/choose_parent/
Django Version:
3.2.18
Exception Type:
TemplateDoesNotExist
Exception Value:
modeladmin/includes/header_with_breadcrumb.html
~~~~

**Comment by frjo** [comment]
In `hypha/apply/funds/templates/funds/admin/parent_chooser.html` it works to replace the header block with:

~~~~
    {% block header %}
        {% include "wagtailadmin/shared/header.html" with title=view.get_page_title subtitle=view.get_page_subtitle icon=view.header_icon %}
    {% endblock %}
~~~~

But might not be optimal.

**Comment by theskumar** [comment]
@frjo The above works fine and doesn't seem to be create any issue. I've pushed the fix for it to #3045 . I'm not sure if you need to redeploy the test.

**Comment by frjo** [comment]
@fourthletter Deploying a fix to test now.

**Comment by frjo** [comment]
@theskumar In current Hypha we have code to stop staff from using "File Field" (single) since they by mistake used it in place of "Multiple File Field".

On old applications forms where it was already added it should work as normal. But it should not be possible to add to any new forms. And if deleted fron an old form it should not be possible to add it again.

With this PR it is back.

![Skärmavbild 2023-04-21 kl  12 58 05](https://user-images.githubusercontent.com/191392/233620093-6b7cda15-71dd-4baa-ac69-d2e57d658351.png)

**Comment by theskumar** [comment]
ah. This is a good catch, I'll look into this.

**Comment by frjo** [comment]
@theskumar Another issue that I believe is Wagtail 4 related.

We have code to make the category fields use the default value if empty on the field instance.

https://github.com/HyphaApp/hypha/blob/278d8a7dc18e106e924acc7ee9346d46ede5072a/hypha/apply/categories/blocks.py#L88-L95

In line 94 `value['category']` used to return the category object `<Category: Region(s) archive>` but on test now it just return an int, the Category ID.

~~~~
[2023-04-22 07:18:55] DEBUG [hypha:98] StructValue([('field_label', 'Region'), ('help_text', ''), ('help_link', ''), ('required', True), ('category', <Category: Region(s) archive>), ('multi', True)])

[2023-04-22 07:14:20] DEBUG [hypha:96] StructValue([('field_label', 'Region'), ('help_text', ''), ('help_link', ''), ('required', True), ('category', 5), ('multi', True)])
~~~~

See https://otf.sentry.io/issues/4116177815/?project=5823154&query=is%3Aunresolved&referrer=issue-stream&stream_index=0

**Comment by fourthletter** [comment]
> @theskumar In current Hypha we have code to stop staff from using "File Field" (single) since they by mistake used it in place of "Multiple File Field".
> 
> On old applications forms where it was already added it should work as normal. But it should not be possible to add to any new forms. And if deleted fron an old form it should not be possible to add it again.
> 
> With this PR it is back.

@theskumar Could we please change 'File field' to 'Single file field'? We have historical knowledge as to why this field is faded out, but other organizations adopting this platform will not have this historical knowledge.

**Comment by frjo** [comment]
If easy we can hide the "File Field" (single) instead of disabling it, then no confusion.

**Comment by theskumar** [comment]
Right, I looked the internal changes and it feels like hiding might be much easier than disabling it.

**Comment by frjo** [comment]
@theskumar Forgot to mention that the issue in https://github.com/HyphaApp/hypha/issues/3018#issuecomment-1518545818 makes most submission on the test site load with a 500 error.

**Comment by theskumar** [comment]
Update: the disabling/hiding of "Single File Field" is turning out to be harder than a expected, as the core of the wagtail is now react and it's harder to hack around it. I've spent sometime on it today and over the weekend. If I'm not able to solve it by tomorrow. We'll have a make a decision.

For the categories issues, will take a look, have got to that yet.

**Comment by frjo** [comment]
@theskumar Maybe then go with @fourthletter suggestion and rename it to "Single File Field" instead. That will hopefully make it easier to pick the right one.

The code we had in place for Wagtail 3 to disable the field should also be removed if not done already.

**Comment by theskumar** [comment]
Cool. Will push the code with "Single File Field"
