### ISSUE TITLE
2FA refine design

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3019]
### Description

This issue documents usability improvements to the workflow for OTF applicants to configure Two-Factor authentication

### Is your feature request related to an existing functionality? Please describe

It is related to current 2FA implementation.

### Describe the solution you'd like

- [ ] Replace with current text associated with 2FA setup with **text below** 
(This guidance is currently located in a separate document for applicants. Embedding instructions on the platform directly would minimize confusion)
- [ ] More descriptive text on buttons, e.g., **I've installed 2FA**
- [ ] More options for backup codes, e.g., Print backup codes, Copy to clipboard, Regenerate backup codes
- [ ] When user has completed steps, they could return to their dashboard by clicking "Go to Dashboard"

### OTF Enable App Based Two-Factor Authentication - ENFORCED - Userflow

![image](https://user-images.githubusercontent.com/20019656/197417903-e34f00a2-79b3-43f2-a148-312e6c7670e6.png)

![image](https://user-images.githubusercontent.com/20019656/197418242-598cb923-f46b-4212-a3b7-95a96f81d8f2.png)

![image](https://user-images.githubusercontent.com/20019656/197417959-25305f6a-1f3a-4c0f-92a9-393f58995728.png)

![image](https://user-images.githubusercontent.com/20019656/197417975-92da6b51-c996-4a6c-855e-e1d8b6a001b8.png)

![Screenshot 2022-10-23 10 58 37 PM](https://user-images.githubusercontent.com/20019656/197418058-dee1e103-f2af-4718-817c-0c282e60904e.png)

![image](https://user-images.githubusercontent.com/20019656/197418041-d799ed1e-b435-486a-a01b-2955514f0697.png)

**Comment by frjo** [comment]
If these changes needs substantial work I think we should consider going to https://github.com/HyphaApp/hypha/issues/2898 directly.

**Comment by fourthletter** [comment]
On November 1 standup we discuss implementing the proposed designs. In addition, add a confirmation for end-users
potentially as the MVP. The 2.0 version could potentially include adding phone or email as a secondary fall back. This means implementing a security question or one time magic link/setup code sent via text or email

In addition to the above designs, the login page for individuals forgetting their 2FA app and backup codes need improvements.

![Screenshot 2022-11-01 9 53 43 AM](https://user-images.githubusercontent.com/20019656/199209319-9d92553b-d60e-4dae-bf84-569ac6348663.png)

**Comment by frjo** [comment]
I do not think adding phone is a good idea.

1. It lowers the security considerably. 
2. It would force Hypha to store users phone numbers, more sensitive information.

Adding codes via e-mail also lowers the security but that part we at already need store in Hypha.

**Comment by fourthletter** [comment]
On November 3 standup we agreed to use email as we are already collecting emails and not telephone. A magic link or code would benefit user onboarding. Developers will research the overall onboarding process before determining next steps.

We may need to replace the current 2FA library, but this sounds drastic 😥

**Comment by theskumar** [comment]
The fixes with the email verification or email as an additional factor is up here: https://github.com/HyphaApp/hypha/pull/3040

Could you create another ticket to use email verification during login and registration/application submission as a safety check?

**Comment by fourthletter** [comment]
Works like magic -- thank you! 🪄 🐇 

Step 1
![Screenshot 2022-11-21 11 52 27 PM](https://user-images.githubusercontent.com/20019656/203175931-babda9f8-e594-41a2-93d3-c80f170fc770.png)

Step 2
![Screenshot 2022-11-21 11 52 54 PM](https://user-images.githubusercontent.com/20019656/203175930-06b60d75-d555-4f4c-873e-706d79de6984.png)

Step 3
![Screenshot 2022-11-21 11 54 11 PM](https://user-images.githubusercontent.com/20019656/203175927-ce4d1d40-ec07-4c99-bb5b-a1d05b4bfde7.png)

Step 4
![Screenshot 2022-11-21 11 54 21 PM](https://user-images.githubusercontent.com/20019656/203175925-438dee23-0dd9-4e21-bba6-107f6c27bd73.png)

Step 5
![Screenshot 2022-11-21 11 58 11 PM](https://user-images.githubusercontent.com/20019656/203175922-01bbf3ce-307c-4268-be68-d88fe9404f88.png)
