### ISSUE TITLE
Rename Flag app to Bookmark

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3028]
### Description 

The Staff flagged feature/dashboard was developed as a "to-do list" for users. Staff could bookmark/save applications to their own dashboard and on a dashboard for other staff members. 

### Challenges

- [ ] Design has not been user tested and feedback has never been collected on the functionalities. 
- [ ] Determine whether this feature needs to be retired because there has not been a clear use case to refine the design, e.g., usability testing

![Screenshot 2022-11-02 3 12 42 AM](https://user-images.githubusercontent.com/20019656/199379203-2ca04cbc-902d-4a05-afde-5135acc5b0b0.png)

**Comment by wes-otf** [comment]
@frjo Today I learned that some members of the program team use the flag feature pretty frequently. This opened a bit of a wider discussion for those that didn't know what it was or how to use it. It was somewhat agreed that it might make more sense to relabel this as a "bookmark" as it's being saved to return to later. It seemed that all were using individual flags rather than staff flags. Would be curious to hear your thoughts.

**Comment by wes-otf** [comment]
looping @Techslammer in too as I think they'd find this interesting

**Comment by Techslammer** [comment]
hey @wes-otf  I agree renaming makes sense. At our next meeting, lets talk about how this could better fit into the PM workflow or what the use cases could be

**Comment by frjo** [comment]
Have no issues with renamning the feature if that makes more sense to staff.

**Comment by theskumar** [comment]
Thoughts on calling it "Starred"? I believe it's widely used to represent bookmarks/saved items. 

Starred items can easily represented by a symbol (⭐) and also takes less characters/space.

Just my 2 cents!

**Comment by frjo** [comment]
Liking "Starred", shorter. Bookmark for me indicates a a place in an item, not marking several items.

But we go with the term that makes most sense to the staff.

What do you think @wes-otf?

**Comment by wes-otf** [comment]
Ahh yeah! That makes sense to me, the representation for that would also be slick. On Friday I have a 1:1 with a program team member that uses the feature if you'd prefer me get feedback first
