### ISSUE TITLE
Enhance search function

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3036]
### User Story

I would like to use the 'search' function to query for similar submissions. The priority key search terms should be 1) email, 2) name, 3) submission title as these are the same key terms embedded in a majority of submissions. 

### Proposed Solution

- [ ] Research Hugo or similar ML library that could be used for this proposed functionality

**Comment by frjo** [comment]
@fourthletter  Some examples of "when I search for X i want to find submission N" would be helpful.

**Comment by frjo** [comment]
The submission table search are done with https://github.com/carltongibson/django-filter and "icontains" on the "search_data" field.

The "search_data" field is populated for each submission with "prepare_search_values()". The field contains almost all the text from the submission including title, name and e-mail.

My guess is that a search many times return too much and that is a one reason people do not "find things".

Search for author is therefor already possible, see e.g https://test-apply.hypha.app/apply/submissions/all/?query=Fredrik+Jonsson
