### ISSUE TITLE
Change Wagtail Admin setting for STAFF role

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3046]
### User Story

STAFF user group could currently access all settings in the Wagtail admin. We would like to limit this access to 1) user settings, 2) Apply, and 3) Projects. STAFF would be able to carry out their core work within the Wagtail admin with these settings. Access to other settings unrelated to their work is unnecessary, e.g., website.

**Comment by frjo** [comment]
Access to wagtail admin is controlled by the wagtail admin permission settings. Each organisation using Hypha can set this up how they want it for each role.

**Comment by fourthletter** [comment]
In OTF's wagtail admin permission settings, could we please configure so STAFF could only access 1) user settings, 2) Apply, and 3) Projects? This would make onboarding and documentation easier. Thanks.

**Comment by frjo** [comment]
You can change these settings easily yourself inside Wagtail admin.

Go to Settings -> Groups. Clicking on the group name, e.g. "Staff", takes you to the permission page where you set what wagtail permissions staff should have.
