### ISSUE TITLE
Complex comments can break page loading

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3048]
We had a comment with a very long PGP key that broke page loading. The error said jQuery could not be found. Removing the key from the comment fix the issue directly. But this should not happen in the first place.

It was only via Cloudflare the error showed upp, on local it worked fine. Via Cloudflare the script tag on the bottom of the page was ignored so they loaded too early, before jQuery was loaded.

**Comment by sandeepsajan0** [comment]
@frjo I tried it on the test site https://test-apply.hypha.app/apply/projects/43/#communications but it seems to be working fine. I think it might be something in that particular PGP key. I am still researching about it but hard to say anything until we can reproduce it.

**Comment by frjo** [comment]
@sandeepsajan0 I posted my long key there as well and it works. So let's put this issue on hold for now.
