### ISSUE TITLE
Show proposal form select field when needed on add determination form

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3049]
### User Story

OTF enables program managers to select from multiple proposals. This function requires the user to change the status to **invite to proposal**, and select from one of the proposal options. 

Program staff sending out a determination to approve the concept note (first stage) automatically gives applicants the default proposal. In this case, the default proposal is the first proposal associated with the Fund.

### Proposed Solution

Option 1:
Applicants will be required to select a proposal from multiple options when they attempt to 'approve' a concept note by sending out a determination 

Option 2: 
Staff should not be able to 'approve' a concept note by sending out a determination

**Comment by frjo** [comment]
Option 1 is already in place, see screenshots below.

![Skärmavbild 2022-11-16 kl  09 06 23](https://user-images.githubusercontent.com/191392/202122948-1bd0419f-22d2-4d28-9c5f-925cd6a02049.png)
![Skärmavbild 2022-11-16 kl  09 06 34](https://user-images.githubusercontent.com/191392/202122954-e355d881-2fef-4ec0-b6d0-40ad3ae5b244.png)

**Comment by frjo** [comment]
But I believe we have a bug here. The above works when staff use the "Update status" button and select "Invite for proposal" Then the select field for proposal form shows.

If staff instead click "Add determination" no select field for proposal is shown and if staff pick "Approved" then the system picks the first proposal form.

So I think the solution is to make sure it works the same in both situations.

**Comment by frjo** [comment]
The problem is here:

https://github.com/HyphaApp/hypha/blob/90501d5e408571ce4fa4be96b6f98dfde7098570/hypha/apply/determinations/views.py#L356-L369

Just removing the check "action == 'invited_to_proposal'" makes it work. The UI becomes a bit confusing because then you always need to pick a proposal form, even when just asing for more information or dismissing.

How to make this functionality into a nice user experience? Ideas @sandeepsajan0 @theskumar ?

**Comment by frjo** [comment]
@fourthletter Since it all works when you go via the "Update status" button can we simply remove the "Add determination" button.

I think it would also make documentation and training easier since you do not need to explain that you can create determination in two different ways.

**Comment by fourthletter** [comment]
Removing the functionality to create a determination is counter intuitive to Hypha users. It is not possible to send a 'need more info' or 'dismiss' determination via the status update at this stage. https://test-apply.hypha.app/apply/submissions/525/

**Comment by frjo** [comment]
That can easily be added.

**Comment by fourthletter** [comment]
On November 22 standup we discussed several options, including:

- recreating a drop-down/picklist with proposals for the determination button
- making the proposal drop-down available, but bypassing this function for dismiss/need more information as proposals are only assigned for accepted/approved/invite to proposal
- removing the determination button completely because it is duplicative of the status update button

**Comment by fourthletter** [comment]
@frjo As an MVP I propose disabling the function where a **default proposal** is sent when a user has not selected this proposal as a determination. A proposal could only be sent once it has been selected via the 'status change'

**Comment by frjo** [comment]
@fourthletter What is needed for that is to remove the ability to pick "approved" when staff clicks the "Add determination" button. That option should then only show when staff clicks the "Update status" button.

But will this not be confusing?

**Comment by fourthletter** [comment]
Proposed solution: applicant should not receive a proposal when they approve a concept note through a determination

**Comment by frjo** [comment]
Today, the only way to approve (or dismiss) something is to write a determination. Separating the determination from the status would take some work and force staff to change the status manually. The workflow around that sounds confusing.

I would prefer to simply remove the "Add determination" button but if that is not acceptable we need to remove the "Approve" option from "Add determination", at least when the fund have multiple proposal forms.

**Comment by fourthletter** [comment]
This features works great. Thanks 💯 

The email I received as an applicant did not lead directly to the proposal, but this may have been because it's a test email.

![image](https://github.com/HyphaApp/hypha/assets/20019656/9d597594-08ee-4d32-aadf-25b36917fb6a)
