### ISSUE TITLE
Building hypha with docker FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/hypha/hypha/static_compiled'

### ISSUE THREAD

**Issue by tassosblackg** [HyphaApp/hypha#3056]
`git clone` from the main brunch and building by following the instructions given in the docs for build `hypha` with docker

**ERRORs:**

`sh: 1: sass: not found`

`Error: EACCES: permission denied, mkdir '/usr/local/hypha/node_modules'`

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/hypha/hypha/static_compiled'`

**Desktop (please complete the following information):**

 - OS: Ubuntu 20.04 LTS
 - Browser: Brave
 - Version:1.45.27 | Chromium 107.0.5304.110

**Screenshot (not node_modules installed):**

![image](https://user-images.githubusercontent.com/22836483/203020094-8c8d4076-dc27-4706-90a1-5a038ffc9da2.png)

**Steps to solve:**

`docker exec -it django /bin/bash`

execute `npm install` with `sudo` 

![image](https://user-images.githubusercontent.com/22836483/203037112-cb11190d-5cdf-4d91-b5ea-3debeffeebcb.png)

But still I get this error:

`FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/hypha/hypha/static_compiled' `

**Comment by frjo** [comment]
Docker tried to run `npm install` but did not have permissions to do so on your system. The node install goes inside your local code dir.

If you can't find a fix for that you can just run `npm install` locally before you start upp docker. Just make sure you have the same node version locally as docker has.

Would be happy to have a chat if you have any question around Hypha, just give me a ping.

**Comment by tassosblackg** [comment]
Ok, thank you, for your response, I fixed the issue with the `npm install` but how about `FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/hypha/hypha/static_compiled ` how this `static_compiled` folder is created? Because it seems that doesn't exist. I've tried to created manually it works partial but stays empty.

**Comment by frjo** [comment]
The "static_compiled" dir is created by "npm run build". All the css, js, font and images are built to that dir and then moved over to static with Djangos "collectstatic" command.
