### ISSUE TITLE
Enhancement to creating multiple new rounds

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3059]
## User Story

As a user I would like to create multiple rounds that could be published in the future. **End dates** from different funds are currently preventing this functionality.

## Problem
When creating or copying a round to be published in the future, I am unable to because this date overlaps with an existing round.

### I am asked to put an end date on **CIFund-2021**:
![Screenshot 2022-11-22 12 17 38 AM](https://user-images.githubusercontent.com/20019656/203177384-66663a82-b427-42cd-a8d8-5e0fef7e75fc.png)

### When I attempt to put an end date on **CIFund-2021**
![Screenshot 2022-11-22 12 17 55 AM](https://user-images.githubusercontent.com/20019656/203177381-0f9a3056-6dda-4362-ba21-2965fdd5eefb.png)

### I am sent on an endless loop
![image](https://user-images.githubusercontent.com/20019656/203177777-fd94b649-987c-4768-a288-a1188dc6f362.png)

**Comment by frjo** [comment]
Tested locally and it seems to work as expected but it might very well  exist some edge case bugs.

The rules are:

* Rounds from the same Fund can not have overlapping dates.
* A Round with no end date will block you from adding any future Rounds for that Fund.
