### ISSUE TITLE
Magic link in a verification email

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3060]
### User Story
Many web applications require users to verify their email addresses, this is particularly helpful when I have forgotten my password to login or 2FA. As a newly registered user, I would like to receive an automatic email containing an email verification link. 

### Proposed Solution
Add email verification during login and registration/application submission as a safety check

**Ideal deadline**
April 2023

**Comment by theskumar** [comment]
@fourthletter please find the overall flow for the magic link and passwordless implementation. 

![image](https://github.com/HyphaApp/hypha/assets/236356/0956062e-2767-494d-968a-632ff42f7d35)


^^ Click to enlarge [Source](https://www.figma.com/file/rNsp8xTqnofbDlEXb4B6fv/Hypha-Passwordless-Login%2FSignup?type=whiteboard&node-id=0%3A1&t=8p8JmbYyprIVFUyE-1)

I'm done with the implementation on the password-less login. Working on the password-less self-signup in the this PR #3531

**Comment by theskumar** [comment]
As discussed on the call, we want to skip 2FA setup/verification for submission form pages.

**Comment by fourthletter** [comment]
Resolved with this PR https://github.com/HyphaApp/hypha/pull/3531
