### ISSUE TITLE
Add a seperate registration path without application

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3064]
**Is your feature request related to a problem? Please describe.**

Allow registrations without applications.  Add a new workflow for that.  If account with that email address already exists, then just route the person through a regular login screen and then bring them back to the rest of the application.

Furthermore, add a configuration option that forces registrations prior to being allowed to create an application

**Is your feature request related to an existing functionality? Please describe.**

It's an enhancement of the current login process.

**Describe the solution you'd like**

When clicking the Apply button, and not currently logged in, continue as normal.  However, add a new button next to "Log In" at the top titled "Register" that allows account creation.  Then, when logged in, can apply as normal.

When configuration to force registration is set, clicking "Apply" will instead take the applicant to the log in screen, from which they can register if they haven't yet.

**Additional context**

This has been completed for a different client, although with the change that registration is always forced.  We would tweak the code slightly to allow the configuration in the case an admin would prefer to continue to allow registration through application.

As such, this feature request is not as much as a request that a feature be developed, but rather that the feature is an acceptable addition to hypha.  A PR would be forthcoming in that case.

**Priority**

It was a high priority for the end user, but it's not a high priority to be in core hypha.

**Affected roles**

- Applicants

**Comment by frjo** [comment]
We would prefer the default to be as it is today and a setting to allow implementers to activate the new workflow where users need to register an account first.

**Comment by frankduncan** [comment]
Is the best way to do the setting via the settings file?  As in, we should do something like:

```
if getattr(settings, "ENABLE_REGISTRATION_WITHOUT_APPLICATION", False) and settings.ENABLE_REGISTRATION_WITHOUT_APPLICATION:
    # Code here
```

Or is there some other configuration for enabling features and leave `settings` to be about application settings?

**Comment by frjo** [comment]
A setting in `base.py` works well. Something like this:

~~~~
# Enable users to create accounts without submitting an application.
ENABLE_REGISTRATION_WITHOUT_APPLICATION = env.bool('ENABLE_REGISTRATION_WITHOUT_APPLICATION', False)
~~~~

In the code you can then do:

~~~~
from django.conf import settings
…
if settings.ENABLE_REGISTRATION_WITHOUT_APPLICATION:
    # Code here
~~~~

**Comment by ramojo** [comment]
A nice workaround to allow for this is to have it implemented but set to False in the settings. Within the Wagtail Admin, the Staff Admin can set it to True so that the login/registration is required. Those that don't need it can use Hypha as is but it would be a really useful feature to have built-in
