### ISSUE TITLE
OSError at /apply/submissions/all/

### ISSUE THREAD

**Issue by tassosblackg** [HyphaApp/hypha#3069]
**Describe the bug**
There is something wrong with the path and the name of the file see:
`Error reading /usr/local/hypha/./hypha/static_compiled/app/webpack-stats.json. Are you sure webpack has generated the file and the path is correct?`

there is a line that seems that does some kind of renaming and moving the file `"dev:build:js": "npm run build:js && mv ./hypha/static_compiled/app/webpack-stats-prod.json ./hypha/static_compiled/app/webpack-stats.json",` inside the `package.json`

But probably it's not working, 

**Temporary Solution:**

so I had to edit it manually inside the `dev.py` by changing the line 141 `'STATS_FILE': os.path.join(BASE_DIR, './hypha/static_compiled/app/webpack-stats.json')` 

**To Reproduce**

1. Go to /apply/submissions/
2. Click on 'Show All ' under all submissions

**Screenshots**

![image](https://user-images.githubusercontent.com/22836483/204753491-08e1751a-b1e9-4697-8dc4-f768a641d098.png)

**Comment by frjo** [comment]
The React app will soon be removed from Hypha. Until then add this setting to disable it.

`ENABLE_WEBPACK_BUNDLES = False`

See more in https://github.com/HyphaApp/hypha/pull/3052
