### ISSUE TITLE
slug for copy or clone rounds

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3072]
### Description

When copying an existing round to create multiple rounds for the future, the slug needs to be different than the one that currently exists.

What is the best process to copy multiple rounds in advance to ensure each round is published via 'Apply'?

![image](https://user-images.githubusercontent.com/20019656/205599337-3f67efc2-be68-42c4-b446-d9e1557a1acf.png)

**Comment by frjo** [comment]
You need to set a different slug (that will form the URL) for each page. No way around that.
