### ISSUE TITLE
2FA disable button

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3088]
### User Story

User intends to disable 2FA and expected the button text to change.

### Image - 2FA is enabled

![image (1)](https://user-images.githubusercontent.com/20019656/208089801-149f3653-94fa-4cb4-81bd-3bd7ba50e762.png)

### Image - 2FA has been disabled

![image](https://user-images.githubusercontent.com/20019656/208089802-eaad435d-c3b1-4429-a927-a0694113cd32.png)

### Deadline
Low priority

**Comment by fourthletter** [comment]
@Techslammer - what do you think of this ui for Administrators to know whether 2FA has been set up or not?

![image](https://github.com/HyphaApp/hypha/assets/20019656/fbb473d9-fba9-4279-a72f-74a3d4ef81ee)

**Comment by sandeepsajan0** [comment]
We can not enable 2FA from here. It is only to disable 2FA via staff or staff admin on users' request. 
2FA can be enabled only by the user via their account page.
