### ISSUE TITLE
Consider replacing flake8 and iSort with ruff 

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#3101]
Ruff is a replacement for flake8, implemented in rust for performance. It supports many flake8 plugins by default and is compatible with iSort and black.

The downside is that we might use some flake8 plugins, but this project does not use many flake8 plugins or intend to use more.

See: https://github.com/charliermarsh/ruff#how-does-ruff-compare-to-flake8

**Comment by frjo** [comment]
+1 from me, seems to be very popular and blazing fast.

**Comment by theskumar** [comment]
I tried on this project, and it runs insanely fast. I had to introduce an error a few times to see if it was even working. Another good thing is that it has native support for many flake8-plugins; it's just a matter of enabling them.
