### ISSUE TITLE
Tabs are not functioning properly for multiple tables on same page.

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3114]
It can be a use case for the dashboard pages or overview pages where we show multiple tables and wants to have tabs in different tables on the same page.

Ex: I tried to update the Finance dashboard, we want to show the invoice table and project awaiting approval table both with tabs.
But when we load the dashboard page only one table is active by default or only one tab is active among all the tabs on the page.

Current behaviour:
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/23638629/211790056-10d60c27-681b-4cab-9937-ada591e5ce6c.png">

Expected behaviour:
<img width="1247" alt="image" src="https://user-images.githubusercontent.com/23638629/211790108-aa5137ea-f277-4b3b-b9cf-d2374519d597.png">

**Comment by sandeepsajan0** [comment]
@frjo @theskumar I have created a draft PR(#3115) with the changes that can help you to populate the above scenario. Just pull the branch and look into the finance1 dashboard.

**Comment by frjo** [comment]
Looks like the javascript in `hypha/static_src/src/javascript/apply/tabs.js` needs to be updated to handle multiple tab sections. Right now it thinks all the tabs is in one single group.

**Comment by sandeepsajan0** [comment]
Record: @theskumar has already fixed this issue with alpine in PR #3115.
