### ISSUE TITLE
Close/Complete a project manually

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3128]
We have 'Closing' and 'Complete' statuses for a project, but we don't have any way to set these statuses manually for a project. 
Do we really need Closing and Complete as two separate statuses? We may just use them as final status just like Accepted/Declined for Submissions.
We can have a button in 'More Actions'(like submissions) to set the Closing state. And the Complete status button should be available for projects in 'IN Progress' status?

<img width="705" alt="image" src="https://user-images.githubusercontent.com/23638629/214277567-c151b21f-a9b7-4db9-8427-70f050cf8203.png">

**Comment by frjo** [comment]
@fourthletter What are OTFs needs around closing/completed statuses for projects?

**Comment by fourthletter** [comment]
On Jan 31 standup we discussed 'closing' means an accounting process that requires taking funds from a contract, a formal letter, etc. We decided to add an 'update status' button for users to manually move from workflow status to status.

**Comment by fourthletter** [comment]
Staff could manually update the workflow status. This is only allowed in between in Progress, Closing and Complete statuses. It is revertable as well, we used this approach just to achieve closing and complete status and make the project non-editable for those statuses. 

![Screenshot 2023-02-21 10 40 14 AM](https://user-images.githubusercontent.com/20019656/220310929-f2b467d8-001e-4813-bdac-a5520f2c830c.png)
