### ISSUE TITLE
Hypha style guide at "/styleguide"

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3135]
### Description

New adopters would like to know the font/typography and how to change the LOGO on their Hypha instance. The current logo is OTF's logo.

**Comment by frjo** [comment]
The default logo will be changed to the Hypha logo when we rip out the public part.

Documenting it is needed.

It is done in Wagtail admin -> System settings

**Comment by frjo** [comment]
A styleguide exist at "/styleguide/" but it can be extended.
