### ISSUE TITLE
Project Invoice filters are not aligned

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3139]
<img width="1236" alt="image" src="https://user-images.githubusercontent.com/23638629/215687402-b0e5d836-97ab-49c6-8e65-14105170c309.png">

I think we don't need the labels there, just removing the labels should work fine.

**Comment by fourthletter** [comment]
Filters are aligned now -- thank you! 💥 

![image](https://user-images.githubusercontent.com/20019656/215820277-46366804-169a-4767-a3e9-6e383b584866.png)
