### ISSUE TITLE
As a manager, the ability to customize all automated notification templates (confirmation emails/slack/signal for applications, submission responses, etc)

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#314]

**Comment by fourthletter** [comment]
Relates to #1223

**Comment by danblah** [comment]
For emails, see https://www.mailgun.com/blog/transactional-html-email-templates and https://documentation.mailgun.com/en/latest/user_manual.html#templates.

**Comment by fourthletter** [comment]
Could be closed because related to overarching issue of #2161
