### ISSUE TITLE
Remove deadline from public site home page blocks

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3143]
### Description

OTF no longer has deadlines or end dates for rounds. This end date appears on the 'apply' page for applications and confuse applicants. This end date also prevents staff from creating several rounds in advance.

### Related
https://github.com/HyphaApp/hypha/issues/3026

![image](https://user-images.githubusercontent.com/20019656/215720512-657ea72f-e928-4ea8-9b51-2e37c4f45f40.png)

**Comment by frjo** [comment]
I found the last PR by me missed hiding the deadline date on home page blocks.

**Comment by fourthletter** [comment]
Thank you! 👍
