### ISSUE TITLE
Line breaks formating in application forms

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3150]
### User Story

As an applicant I would like to paste a chart or line breaks into the application.

### Example 1

1. Item 1
2. Item 2
3. Item 3

### Example 2
<p is="qowt-word-para" qowt-lvl="undefined" qowt-entry="undefined" qowt-eid="E620" id="E620" class="x-scope qowt-word-para-0"></p><div class="content-wrapper style-scope qowt-table"></div>

Infrastructure | $10,000
-- | --
Tech Staff | $300,000
Programming | $100,000
Marketing | $150,000

**Comment by frjo** [comment]
I assume you by "line breaks" mean tables as in the example above.

If you use richtext fields in your application, applicants can copy from a spreadsheet and when pasting it will become a table.
