### ISSUE TITLE
PAF approval

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3151]
### Description

The PAF needs approvals from several user roles before it could be used to write a contract. These user roles include: Finance, and VP OR IT Director. This PAF https://test-apply.hypha.app/apply/projects/81/#activity-feed on the test site received approvals from Finance and staff + approver, but has advance to the next stage for contracting.

This PAF is still in the 'awaiting approval' phase

![image](https://user-images.githubusercontent.com/20019656/216626296-374208f3-ad97-4cae-89e1-67dff0bd85eb.png)

![image](https://user-images.githubusercontent.com/20019656/216625466-731cc079-d661-4fbc-bb42-daf349df59c4.png)

**Comment by frjo** [comment]
There are "PAF Reviewers Roles" that you configure here: https://test-apply.hypha.app/admin/settings/application_projects/projectsettings/2/

They are different from "user roles" (applicant, staff, reviewers etc.)

The "Spring" projects is not in contracting from what I can see, it is still in "Waiting for approval".

It will not move forward until all "PAF Reviewers Roles" have approved it, just as we decided it should work.

**Comment by frjo** [comment]
A separate issue is that it might be cumbersome for staff to track what "PAF Reviewers Roles" has approved and who has not. Now they need to look in the "Activity feed" and figure it out. I imagine they will need to "nag" people from time to time?

**Comment by fourthletter** [comment]
#### What roles are included on the platform and workflow?

OTF internal title| User Roles| PAF Reviewer Roles | Invoice| 
------------ | ------------- | -------------| -------------| 
 |Program Manager|Staff  | none |  PM
 | VP Tech| staff + approver | VP Tech | none
 | IT Director| staff + approver | IT Director | none
 | Finance Director| finance + approver | Finance Director | Finance?
 | Accountant| finance | none | Finance  |  
 | General Counsel| contracting  | none | none
 | Attorney|contracting  | none |  none
 | CEO|contracting + approver | CEO |  none


####  What roles or approvals are needed during contracting?

Vendor | Program Manager| General Counsel/Contracting User | VP Tech; IT Director; Finance Director| 
------------ | ------------- | -------------| -------------| 
 |Upload banking details|Fills in PAF| Reviews PAF |  Approves PAF (only need two approvals)
 

#### What roles or approvals are needed during invoicing?

Vendor | Program Manager| Finance user | 
------------ | ------------- | -------------| 
 |Upload invoice|Approves or rejects invoice| Approves or rejects invoice| 

### Related
https://github.com/HyphaApp/hypha/issues/2704#issue-1122876524

**Comment by frjo** [comment]
@fourthletter Note that the "PAF Reviewer Roles" are set up by each organisation however they want. To have none is perfectly ok.

They are not mapped to user groups in any way. It is up to the users to pick the roles that is right for them when they approve PAFs. The honour system, plus that it is logged in the activity feed.
