### ISSUE TITLE
Applicant communication tab default

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3152]
### User Story

As an applicant I need to communicate with program managers at the funding organization. The communication tab indicate "Applicant" (as default) and "All." This user interface is not clear.

![image](https://user-images.githubusercontent.com/20019656/216631653-72d1f165-fd5f-4d51-836a-1199ea107ff9.png)

**Comment by frjo** [comment]
@fourthletter Do applicants ever need to write comments to anyone else but staff?

If they only need/should write to staff we could remove the "visible to" option making it nice and clean.

**Comment by fourthletter** [comment]
@frjo removing 'applicant' makes the most sense. Thank you.

**Comment by frjo** [comment]
@fourthletter So "All" should be set as the default then? That means that e.g. reviewers also will see the messages.

**Comment by sandeepsajan0** [comment]
We may show the labels like this(Visible to Applicant and Staff) everywhere, it may help for all user roles.

<img width="1275" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/397be21a-e8ac-4988-9d87-309cb004b54a">

**Comment by fourthletter** [comment]
@sandeepsajan0 - I think adding definitions directly on the UI would be helpful. Thank you for your suggestion.

**Comment by frjo** [comment]
@fourthletter Do you mean that applicant comments always should be visible to everyone? Staff, reviewers etc?

I thought that applicants and reviewers normally never should communicate directly?

**Comment by fourthletter** [comment]
On July 13 we decided applicant user group will have NO options by default. Their comments will only be seen by the staff user group.

**Comment by frjo** [comment]
Moved to https://github.com/HyphaApp/hypha/issues/3486
