### ISSUE TITLE
Reviewer and applicant user accounts

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3153]
### Description

A user account is assigned both a reviewer and applicant role. How does this impact their experience with accessing the applications they submit on the platform? There are parameters preventing a reviewer from submitting and reviewing their own submission. However, will this user account be able to access their own applications  on their dashboard, and have the same functionalities designated to the reviewer user group?

**Comment by frjo** [comment]
Reviewers do not need the "applicant" role but I do not think anything will change if they do.

**Comment by fourthletter** [comment]
A 'Reviewer' that has submitted an application will not be able to view and access their own application.
