### ISSUE TITLE
Project approval e-mail, subject and recipients

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3154]
### Description

This e-mail digest is sent out to all staff (contacting and finance user groups) when  a staff member asks for a project to be approved. Please revise the subject of the e-mail template for users to know this alert is related to project (finance and contract) setup.

Where is the email or user group associated wtih this email digest located? Is it here or hardcoded? https://test-apply.hypha.app/admin/settings/application_projects/projectsettings/2/

![Screenshot 2023-02-06 10 02 50 AM](https://user-images.githubusercontent.com/20019656/216929945-3f5af94a-c833-4905-91be-aa1c09787c4e.png)

### Related
https://github.com/HyphaApp/hypha/pull/2991

**Comment by frjo** [comment]
The message in question is "MESSAGES.SENT_TO_COMPLIANCE".

The `get_subject` function defaults to a subject intended for applicants and it is wrong for this message.

https://github.com/HyphaApp/hypha/blob/d16b671ab3868c327aa3baed8bfc0011ebea310b/hypha/apply/activity/adapters/emails.py#L63-L87

**Comment by frjo** [comment]
Also who should get this e-mail? Right now it goes to staff+finance+contracting.

https://github.com/HyphaApp/hypha/blob/d16b671ab3868c327aa3baed8bfc0011ebea310b/hypha/apply/activity/adapters/emails.py#L225-L226

**Comment by fourthletter** [comment]
> Also who should get this e-mail? Right now it goes to staff+finance+contracting.
> 

staff+finance+contracting is currently correct. I am inquiring about this email because a coworker who has NOT been assigned the roles staff+finance+contracting has also been receiving these emails. We currently have a designer who will map out the commincation/notification necessary for this workflow in the near future.

**Comment by frjo** [comment]
@fourthletter That coworker did belong to the "staff" user group and therefor got the e-mails. I see you now have inactivated the account in question.

**Comment by fourthletter** [comment]
> @fourthletter That coworker did belong to the "staff" user group and therefor got the e-mails. I see you now have inactivated the account in question.

I thought "staff+finance+contracting" meant they needed ALL three roles to receive these emails.

**Comment by frjo** [comment]
No, all of them get e-mails. Users should normally have only one of the roles.

**Comment by fourthletter** [comment]
| | Message to Compliance | ALL Activities ?| Fund | 
------------ | ------------ | ------------- | -------------| 
| Who gets emails? |finance, contracting user groups|Staff  user group| only individuals managing the fund/lab|  
| Who creates emails? |hardcoded|wagtail sys admin selects| wagtail sys admin selects|  
| What is subject heading?||| |  
| What triggers email?||| |

**Comment by fourthletter** [comment]
When a user requested 'approval', this single activity generated several notices in the email. I could replicate this activity and bug again if it would help.

![image](https://user-images.githubusercontent.com/20019656/217249976-80d43429-5b48-42b1-a96d-48670215bfd1.png)

**Comment by fourthletter** [comment]
The subject headings align with the activity. Thank you!

![Image](https://user-images.githubusercontent.com/20019656/222688741-aa0b71c8-8e6f-44ad-8f33-a7f5e0715a90.png)
