### ISSUE TITLE
Add url to 2FA setup user interface

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3158]
### Description

Add a url to the user interface for 2FA setup for users to copy the url so that they can manually add it rather than just scan the qr code

![203175930-06b60d75-d555-4f4c-873e-706d79de6984](https://user-images.githubusercontent.com/20019656/217024666-df916a4f-bc61-4075-bfa9-e097989a62e2.png)

### Related
https://github.com/HyphaApp/hypha/issues/3019
https://github.com/HyphaApp/hypha/issues/2846

**Comment by frjo** [comment]
@fourthletter Check under "> Advanced" and you see it is already in place.

**Comment by fourthletter** [comment]
I propose making the url more explicit and embedd this url directly on the user interface

**Comment by frjo** [comment]
I suggest we change the text "Advanced" to something more descriptive, e.g. "If you cannot use the QR code, click here for otpauth url."

Very few users will need it so best not to clutter the UI.

**Comment by fourthletter** [comment]
Should we also include this as an option? It's an alternative authy provides directly on their app.

https://zxing-js.github.io/library/
ZXing ("zebra crossing") TypeScript is an open-source, multi-format 1D/2D barcode image processing library ported to TypeScript from Java.The library can be used from browser or from node.

**Comment by frjo** [comment]
I do not understand what the library does.

What is the main problem you want to solve?

There are a number of solution for the people in the world that has a computer but no smartphone with a camera.

The "otpauth url" is the most manual one.

Password managers like e.g. 1Password has a QR code reader built in to their desktop apps. You get a transparent window that you drag over the QR code and the app "scans" it.

Built in to macOS is a feature where you just right click a QR code to get the system to "scan" it.

**Comment by theskumar** [comment]
Do you think this looks okay? @frjo @fourthletter IMO, this doesn't clutter the page too much. 

![Image](https://user-images.githubusercontent.com/236356/220281260-bee79240-1a1b-4b8c-94fd-a63813fdb65b.jpg)

**Comment by fourthletter** [comment]
@theskumar the design looks elegant. I want to do some light user research with my coworkers before moving forward with this design. Thank you.

**Comment by frjo** [comment]
I believe very few people will have a need for the link. Can't we keep hiding it under a toggle but make the text more clear then the current "Advanced"?

When I originally added this link I thought it was only for myself and one or two other technical people.
