### ISSUE TITLE
Move Reports permissions to permissions.py file

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3159]
**Description**:

Reports permissions are at multiple places right now and it is different at every place for the same view.

[ReportAccessMixin](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/projects/views/report.py#L34) allows staff members, finance members, and project owner.

[Dispatch method](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/projects/views/report.py#L64) of report update, details, and other views checks for the report status, timeline, and other report-related things.(Its fine for now but better to move to permissions.py)

[Report templates](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/projects/templates/application_projects/includes/reports.html#L60) are checking for apply staff at multiple places.

As in templates we are showing the report edit, skip, and unskip options only to staff members while in ReportAccessMixin finance and project owner also have the permissions for those views, so we need a little clarification on these permissions. 

**Question**:
Who(user roles) can view the reports?
Who can add/edit/update the reports?

**Proposed solution:**:
Let's keep the permissions in permission.py and use the same in templates and in the views, so that if anyone can't see the buttons can't access the view anyhow and vice-versa.

**Comment by fourthletter** [comment]
We haven't changed any permission in that(just collected at a place) but we just want to make sure that these user roles can perform their action for reports. Like staff can update the report config and applicants/staff can update/add reports only when a project is in 'IN PROGRESS' state, these actions should be restricted to 'CLOSING' and 'COMPLETE' states.  Similarly, applicants/staff/finance can 'view' the reports in all three states. Sandeep has updated the [comment there](https://github.com/HyphaApp/hypha/pull/3162#issue-1575577318) as well.
