### ISSUE TITLE
Group testing session

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3164]
**Purpose:**
- To understand and align the design, dev and product teams on the current state of the feature.
- To identify any usability challenges or gaps with the expectation from the feature.

**Outcome:**
- Document the feature as the one source of truth for everyone. Use this document to direct any further design and development.
- A shared understanding of the current state of the feature and areas of work.

**Participants:**
1. Di (role: PM/staff)
2. Frederik (role: applicant)
3. Sandeep (role: contracting?)
4. - (role: finance)
5. - (role: approver)
6. Abhishek (role: observer/notes taker)
@fourthletter could you please suggest names for two other roles? or if we can't find, one of us could impersonate/become?

**Process:**
- A group of 6 people will meet to go through the contract and finance workflow and play the roles defined above.
- We will use zoom to record the session. To identify the different user roles we can rename our zoom user names to the appropriate roles.
- We will start the workflow from the step after creating a project.
- Everyone takes action as per their understanding of the feature without prompting others (at first).
- Participants shall talk out loud what they’re thinking they should do next. Participants can suggest to the observer how they would have wanted something to work.
- As a group we will explore different scenarios and all possible routes available during the workflow for eg. approver can approve, request changes, or reject so we will perform all three options.
- In case we get stuck somewhere:
    - if it’s because of a bug, we make a note and proceed further via some alternate route
    - if it’s a knowledge gap, someone in the group who knows can prompt and suggest the next step

**Remember!**
- This session is not to discuss how a feature should be but to understand how it is right now. Hence, we will avoid any long discussions on how it should work, unless it’s a very simple addition to the session.
    - We will discuss this after the session

**Prerequisites:**
1. Create a user for each of the participants if not already available
2. Set up a project on Hypha
3. Set up zoom meet link

**Comment by frjo** [comment]
I have created users and application on the test site now:

* Application: https://test-apply.hypha.app/apply/submissions/544/
* Users: https://test-apply.hypha.app/admin/users/?q=thursday

Please do not change anything on these until our meeting on Thursday.

**Comment by frjo** [comment]
> Hence, we will avoid any long discussions on how it should work

Very good point indeed! Let's all help keep the meeting on track.

**Comment by fourthletter** [comment]
We spent two hours going over the full compliance/finance workflow in Hypha this morning (with special guest star James as the Program Manager)

We've experienced some confusion over the PAF approval process, notifications were not sent to the intended individual when it was required (ie vendor submitted an invoice to the program manager), dasboards/tables did not always reflect the correct status of the PAF or invoice, etc.

We went through the easy path of only approving the PAF, but didn't test the "decline" and "more info requested" options

We will paste all notifications from Thursday's session on this doc 
https://docs.google.com/document/d/1WOU1jtVtBiICdTDN-w8tWXJQm79OtqTn48PxzW9vzyU/edit# 
Di will organize it by the sequence of the workflow and paste in the Slacck notifications

Next Steps:
Abhishek will document our user experiences, and divide up tasks according to design, development, or clarification from OTF
