### ISSUE TITLE
Contracting, Applicant, Staff, and Finance's dashboard updates for Contracting and In Progress projects

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3165]
- [ ] Contracting should get an email after PAF final approval.
- [ ] Project should be visible on the contracting dashboard to upload the contract.

**Comment by fourthletter** [comment]
All the individuals assigned had the PAF awaiting on their dashboard exept for the the 'contracting' user role.

Contracting has approved the PAF - marked as 'General Counsel' approved
![image](https://user-images.githubusercontent.com/20019656/222690776-addfba49-1c47-4e79-88c6-aa6814d15750.png)

Contracting or the General Counsel never had the PAF on their dashboard
![Screenshot 2023-03-03 10 57 47 AM](https://user-images.githubusercontent.com/20019656/222690921-7e73662b-c419-45e2-a23f-edded15ec83b.png)
![Screenshot 2023-03-03 10 57 35 AM](https://user-images.githubusercontent.com/20019656/222690925-6f9b3296-2046-4912-a584-747f0a4b0b4c.png)
