### ISSUE TITLE
Upload contract doc title preview

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3166]
**Describe the bug**

When uploading the contract as a contracting user, the uploaded doc title doesn't preview. That makes it challenging to know if the doc was uploaded or not.
And then when uploading the signed contract as a PM the same thing happens.

**To Reproduce**

1. Go to a project that is in the contracting stage
2. Click on 'upload contract'
3. Select a file from the computer
4. See error - the file name doesn't show. 

**Expected behavior**

The file name should preview.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Contracting user role
- Project manager role

**Screenshots**
- For contracting user role
<img width="1141" alt="image" src="https://user-images.githubusercontent.com/124244361/217526001-36e0d6ac-8925-42db-8ff3-cbfa8d8e58f7.png">
- For project manager role
<img width="1309" alt="image" src="https://user-images.githubusercontent.com/124244361/217528240-678c421c-f3fb-4c08-87b7-3df9b3e9eb74.png">

**Desktop (please complete the following information):**

 - OS: [iOS]
 - Browser [chrome]
 - Version [Version 109.0.5414.119 ]

**Comment by fourthletter** [comment]
**Will this enhancement impact all document upload buttons throughout Hypha?** 

I see the file name. Thank you! 💥 

![image](https://user-images.githubusercontent.com/20019656/220769010-2b9fff9b-69ec-4a5e-9f64-2818922cce5d.png)

**Comment by sandeepsajan0** [comment]
>Will this enhancement impact all document upload buttons throughout Hypha?

It will not impact all upload buttons but only contract upload for any user role. Most of the upload buttons in Hypha use the same approach and if there are any that don't, we can update that.
