### ISSUE TITLE
Contract document error 

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3167]
**Describe the bug**

After uploading the contract, the Contracting role, PM and Applicant are not able to view the contract doc. The document link throws an error.

**To Reproduce**

1. Go to the contracting stage for a project (as a pm or contracting role)
2. Click on uploaded doc link that goes by a date in contracts block.
3. See error - the new tab throws and error. The contract doc isn't visible.

**Expected behavior**

The doc should show, i believe?

**Priority**

- Medium (slowing you down) - probably high if it's getting in the way of the contracting process.

**Affected roles**

- Staff
- Contracting role
- Applicant

**Screenshots**

<img width="1338" alt="image" src="https://user-images.githubusercontent.com/124244361/217530057-542071e3-492e-4a71-a7e4-5ad0c18a4fb2.png">
Error:
<img width="662" alt="image" src="https://user-images.githubusercontent.com/124244361/217530115-d94b59d0-2389-4f69-9b2b-5cbdfaf5fd7a.png">

Desktop (please complete the following information):

OS: [iOS]
Browser [chrome]
Version [Version 109.0.5414.119 ]

**Comment by frjo** [comment]
The URL is missing the domain "https://projects/43/contracts/test.pdf?………", it should be something like "https://test-apply.hypha.app/projects/………"

**Comment by abhiXII** [comment]
oh okay. is that a user error or we need to fix something on the system? because i simply clicked on the the link (as in the image with the arrow)

**Comment by frjo** [comment]
It is a bug, should be easy to fix.

**Comment by sandeepsajan0** [comment]
I am not able to produce it locally but it is not working on test site for me as well. I think it might be the private media file issue. 
We have a `ContractPrivateMediaView` view, let me use it for this instead using file.url direclty. I am just going to create a PR for this.

**Comment by sandeepsajan0** [comment]
@frjo I just created a PR #3170 to fix this url issue. I think we can put this to test.
