### ISSUE TITLE
Whitespace in project e-mail notification templates

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3173]
The current templating engine can not filter out whitespacing. E-mail templates must contain not indentation extra line breaks etc. They will all be copies as is to the actual e-mail. Not a good look.

https://github.com/HyphaApp/hypha/blob/af62dddd41362b3f4300ef3784d6d3e190196455/hypha/apply/activity/templates/messages/email/contract_uploaded.html#L11-L32

**Comment by frjo** [comment]
Long term we plan to convert all templates to Jinja2.

**Comment by theskumar** [comment]
These emails can be converted to use the markdown-based email. For the majority, it will look great, while for others, we can try updating the formatting to fix the whitespace issue as much as possible. 

Sure, we can think of using Jinja for emails, at least.

**Comment by fourthletter** [comment]
![image](https://user-images.githubusercontent.com/20019656/234939873-dd2a19d9-29bc-4a17-80c4-7e5584e28d99.png)
