### ISSUE TITLE
Hide the “Corrections or amendments to your contract?” when the contract is approved.

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3176]

**Comment by fourthletter** [comment]
I still see it because this update will only impact NEW projects? https://test-apply.hypha.app/apply/projects/78/

![image](https://user-images.githubusercontent.com/20019656/220205624-20aab6ba-0e99-4b62-90c5-17362054a35d.png)

**Comment by sandeepsajan0** [comment]
@fourthletter The above project's contract is not approved yet(even unsigned yet). It is the time when an applicant, staff, or contracting can use this feature to have corrections in a contract. After signing and approval of the contract, it will be gone.
