### ISSUE TITLE
On applicant dashboard remove the Fund allocation column

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3179]
This information is not collected anymore inside Hypha.

**Comment by sandeepsajan0** [comment]
>This information is not collected anymore inside Hypha.

Does it adds any value to the other's dashboard(like staff or finance) or should we just remove it from everyone's dashboard?

**Comment by frjo** [comment]
@sandeepsajan0  Good point. Remove it from all dashboards.

Hypha no longer have a way to enter the allocation so no way to show this info in any case.

**Comment by sandeepsajan0** [comment]
Great, already removed it from all dashboards in PR #3214.
Now, it only shows up on the projects listing page but I think we should just remove it from there as well.

**Comment by frjo** [comment]
Yes, I agree. Remove it from everywhere.

**Comment by fourthletter** [comment]
Looks great! 💥 

![image](https://user-images.githubusercontent.com/20019656/220204749-b03575ce-a751-4e29-9b9a-0bc1d412d644.png)
