### ISSUE TITLE
Replace PAF reviewer roles with function to assign actual user roles to approve a PAF

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3188]
Staff who create the project selects one user from each of these user roles:

1. Staff + approver
2. Finance + approver
3. Contracting

Only staff + approver is required.

Should staff pick the contracting + approver user as well?

**Comment by sandeepsajan0** [comment]
@frjo I think we should include this in MVP issues else we will be reworking on PAF related things.

**Comment by frjo** [comment]
Done

**Comment by fourthletter** [comment]
![image](https://user-images.githubusercontent.com/20019656/222689474-49a7038a-48cb-4475-b06f-80fdd8e476de.png)
