### ISSUE TITLE
Add ability to upload templates for each type of project supporting document

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3189]
Users can then download the template, fill it in and upload the result.

**Comment by frjo** [comment]
@fourthletter This is the issue for the contract and project document categories templates we where discussion in todays meeting.

I think it can be a neat feature and staff will then no longer need to send these over e-mail manually.

If it is not something OTF wants/needs anymore, we can close the issue.

**Comment by fourthletter** [comment]
Thank you for sharing this. I think a central place for applicants is a good idea, but we should map out the full end-to-end user journey for the applicant/vendor first (cc: @abhiXII ). I think it's best when the designs are based on applicants' needs and experience on the platform. There was an activity we plan to pursue after we've completed user testing with staff.

**Comment by fourthletter** [comment]
Step 1: Go to wagtail admin/contract document settings
![Screenshot 2023-06-08 12 11 54 PM](https://github.com/HyphaApp/hypha/assets/20019656/c07de579-defb-4b20-82db-3f98c6b62981)

Step 2: Click on bank details and Upload bank details template
![Screenshot 2023-06-08 12 12 05 PM](https://github.com/HyphaApp/hypha/assets/20019656/b2a1f323-4ccf-45f0-8cac-15e598e50023)

Step 3: The template should appear as a 'template'
![image](https://github.com/HyphaApp/hypha/assets/20019656/81276b5b-0836-4037-88b8-1dcdf49af37e)

@sandeepsajan0 I clicked on the template on this project but it didn't open: https://test-apply.hypha.app/apply/projects/2/

**Comment by frjo** [comment]
@sandeepsajan0 You get a "403 Forbidden" when clicking "View template". The files are in a s# bucket and you need to authenticate with a token. See how other file downloads handle it.

https://github.com/HyphaApp/hypha/blob/b35bf029557d6d2b622310b357de7e6998234aea/hypha/apply/stream_forms/files.py#L72-L74

**Comment by sandeepsajan0** [comment]
@frjo @fourthletter I think it is the view permission issue [here](https://github.com/HyphaApp/hypha/pull/3390/files#diff-621986afc338fab91d81a271b824a081d16293131eca41b542142b9fdfb753f9R902). Because for Project documents, `staff`, `contracting` and `finance` is allowed but for contract documents only `applicant` have the permission.
I tried it by "become" an applicant and it is working fine for the applicant. 
So the question here is, should we open it for every logged-in user or staff + applicant only?

**Comment by frjo** [comment]
@sandeepsajan0 Everyone who can see the project should be able do download the templates.
