### ISSUE TITLE
Improve visibility of PAF fill in 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3191]
### User Story

As a program manager, I need to “fill in” the approval form for approvals from compliance and others within the organization. Visually, this button seems to be lost among other options.

### Proposed Solution
There’s probably also no need to show buttons and information that is not useful to the users at this step like the “submit for approval” button.

### PAF fill-in
![image](https://user-images.githubusercontent.com/20019656/222091429-a85fb6eb-3477-4352-a683-a07adb4b3452.png)

### Contract Upload 
![image](https://user-images.githubusercontent.com/20019656/222092139-f2a6be13-ae38-4b12-ae12-e379808ce1cd.png)

### Pop-up button to approve the contract for invoicing
![image](https://user-images.githubusercontent.com/20019656/222093704-890535be-2c7e-49b7-95b3-25f49a0d297a.png)

**Comment by frjo** [comment]
At the state you are in the screenshot the PAF is approved and the project is in contracting status. At this stage the PAF can not be edited, therefor no edit link.
