### ISSUE TITLE
Make approval form required when creating a fund application

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3192]
### Description
In our testing the approval form had not been set up. Thoughts: Should we think of making “add approval form” a mandatory option when setting up the fund form?

![image](https://user-images.githubusercontent.com/20019656/218988914-1944041b-3297-4a5e-88cc-53e85ec5adff.png)

**Comment by frjo** [comment]
But all organisations will not be using the project part of Hypha.

Maybe we can tie it to the "PROJECTS_ENABLED" setting. If that setting is true the PAF is mandatory for funds and labs.
