### ISSUE TITLE
Front end validation of number fields etc.

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3194]
### Description

While entering the amount in the approval form users tend to use alphabets but it only accepts numerical value. 

### Proposed Solution
Number field on form does accept any alphabetical value since right now it takes one there could also be a tip that pops if uses enter alphabets OR help text OR clearly indicate this in the question on the PAF.

![image](https://user-images.githubusercontent.com/20019656/218999442-03ddeee9-3364-4b42-b15a-139727ccc4c4.png)

**Comment by frjo** [comment]
It will give an error when you try to submit. We can see about adding a front end validation feature.

**Comment by abhiXII** [comment]
yes @frjo the validation has to be instantaneous instead of after submit. If you'd like we can also add instruction with the field.

**Comment by frjo** [comment]
Help text can be added to any field in Wagtail admin since these are stream fields.

**Comment by frjo** [comment]
Related #3213

**Comment by fourthletter** [comment]
Works great! 💯 

![image](https://user-images.githubusercontent.com/20019656/222684082-dd59dd8c-1e7a-42dc-aef8-0c566e146d1d.png)
