### ISSUE TITLE
Add the same fields to PAF as application forms etc. have.

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3195]
### Description
The input field mentions bullet points but there’s no option to add bullet points. 

### Proposed Solution
Either update the support text or provide formatting in the field

**Comment by frjo** [comment]
The PAF is a stream field form that each organisation build themself. Just like application forms etc.

This for uses plain text fields for the input in question. The ricktext field type is not available for PAF forms. At some point is was decided it was not needed but things have changed.

Now I think PAF forms should have the same field types as the other forms.

**Comment by fourthletter** [comment]
I was not able to use group fields on this PAF form as well. We would like to add a group field question to this form as well.

**Comment by frjo** [comment]
@fourthletter That is already fixed if you look at the test site now. Just deployed the linked PR to test.

<img width="953" alt="Skärmavbild 2023-04-12 kl  19 45 06" src="https://user-images.githubusercontent.com/191392/231540999-5d851ebe-394a-475b-874a-92104fb1bccd.png">

All the field types are now available to PAF forms (minus the ones that are specially only for application forms, review forms etc.)
