### ISSUE TITLE
Improve usability of interface and workflow of the Action to Take box with buttons

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3197]
### Description

The greyed out buttons don’t add any value to the interface and workflow. The proposed solution is to show the status of the application for eg. instead of a greyed out submit for approval button, we should “submitted for approval to xyz role/person”

![Screenshot 2023-02-15 11 23 07 AM](https://user-images.githubusercontent.com/20019656/219001725-f04e5523-4f32-475d-b138-5576b7542ddc.png)

**Comment by frjo** [comment]
In actions to take we can just remove/hide the buttons.

Status information will be displayed in other places since they are not actions.

**Comment by fourthletter** [comment]
There was a comment during our group test to have this 'Action to take' box move from top to bottom on the screen so the user has it available after they reviewed the entire contents on the screen.

**Comment by sandeepsajan0** [comment]
Update: It has been fixed in previous PRs.
