### ISSUE TITLE
staff + approver role can not see the approve the PAF button

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3199]
### User Story

For staff + approver (VP of tech) actions to take block doesn’t show the button to approve the PAF when trying to approve by going into the PAF page.

![image](https://user-images.githubusercontent.com/20019656/219003840-bd503ffa-f610-4252-a71e-87689f48b5cf.png)

### Related Issue

#3196 
#3197 
#3188

**Comment by frjo** [comment]
Do you want the button on both the project page and the PAF page or only on one of them?

**Comment by abhiXII** [comment]
@frjo i think it's worth having it in both the places

**Comment by sandeepsajan0** [comment]
As we are rebuilding the PAFReviewerRoles flow, I think we should work on it after that.

**Comment by sandeepsajan0** [comment]
I think it is already fixed. As we checked in testing, every PAF reviewer could see the Update PAF status button?
