### ISSUE TITLE
Add a loader when it takes some time for the file to be uploaded

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3201]
### Description

Add a loader when it takes some time for the file to be uploaded.

**Comment by sandeepsajan0** [comment]
It is already fixed. I have checked it for Submissions and projects (Paf, contracts, and invoices). 
<img width="647" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/11cd598a-0ee5-4922-ac99-0c432420a083">
