### ISSUE TITLE
Contracting should not have access to the project after the contract is approved. 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3205]
### Description
Contracting should not have access to the project after the contract is approved. Their role in the process is complete

**Comment by frjo** [comment]
Is it important that they can not view the project or is it just that they should not show on their dashboard?

**Comment by sandeepsajan0** [comment]
I have created PR #3220 and mentioned there the permissions as well. But I think it will be better if show the project details to finance, contracting, and staff at every stage. And just restrict the actions that a particular user role can make in a particular status. It might help in discussions across the team?
