### ISSUE TITLE
[Applicant] Add invoice table to Applicant dashboard

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3207]
### User Story

Applicant/vendor/contractor sees **In progress** for the project which is fine but there’s no invoice status here. 

- [ ] Create new overview pages for vendor/applicant user role - 'Invoice' and 'Report'
- [ ] Create separate pages for projects and submissions. There will be two tabs to switch between Active and Past projects

![image](https://github.com/HyphaApp/hypha/assets/20019656/bc4a62f2-4f5f-4a56-8783-da117fd73d3f)

<img width="834" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/cf5a294a-0244-4d11-b23a-dda24132801e">

<img width="889" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/aaa42931-3051-49c8-9817-f6013da9ff52">

<img width="842" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/38cf4eb4-2e0d-48ed-9cc8-3f3c6b36669f">

**Comment by sandeepsajan0** [comment]
@frjo @abhiXII I think we can close this one as we already have an invoice table on applicant dashboard and we are not moving forward with multiple pages access to applicant.



![Image](https://github.com/HyphaApp/hypha/assets/23638629/832c7a58-d8b6-4383-9e0e-c924244978c3)
