### ISSUE TITLE
Add an SOW option

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3209]
After the PM has filled out the approval form, OTF wants a 'View SOW' option along with 'View Approval Form' in the table. This SOW will essentially just show a part of the entries filled in the SOW form as per [this doc](https://docs.google.com/document/d/1RIV6DDrbq9q7vMVHHUe9xa9nV1RjYsI0/edit).

<img width="625" alt="image" src="https://user-images.githubusercontent.com/124244361/219011967-19572ac0-8aee-449d-8c9b-799882202085.png">

**Comment by frjo** [comment]
The PAF form is a stream field form that each organisation build themself. There is no way for Hypha to know what part of that form is "SOW" and what is not.

**Comment by abhiXII** [comment]
@frjo is there any way to mark those SOW fields on the form builder? or some other way to identify this information?

cc @fourthletter

**Comment by frjo** [comment]
I'm very hesitant to build that kind of feature. The form fields are overloaded as is making form creation more burdensome.

I would suggest something really simple. E.g that OTF att all the SOW fields at the bottom of the form and then we add a "SOW" link that goes to the PAF with an anchor tag that simply scrolls down.

**Comment by abhiXII** [comment]
Okay sounds fine.
Based on my conversation with @fourthletter, they wanted to download and be able to share SOW with external people. sharing Approval form with all the information wasn't serving the purpose. Could you suggest if this is possible in some way?

**Comment by frjo** [comment]
Then we need to create a completely separate form called "SOW".

**Comment by abhiXII** [comment]
okay. Will users have to fill it again? that will not be best :/

**Comment by frjo** [comment]
There will then be two forms. One PAF and one separate SOW that staff fills in separately with whatever is needed for the two forms.

I do not like this solution since it make the system even more complicated and there is no lack of other things to put dev time on.
