### ISSUE TITLE
Update the flow for collecting banking details

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3212]
Right now banking details are uploaded while filling in approval form. The update required is for it to happen after the contract has been approved.

<img width="631" alt="image" src="https://user-images.githubusercontent.com/124244361/219013846-56b20630-d4cf-415c-8f8b-81e5b5efd53a.png">

**Comment by fourthletter** [comment]
I think you have redesigned for this and resolved this issue.
