### ISSUE TITLE
Add placeholder to all input fields, used for simple front end validation css

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3213]
HTML5 input fields gives us built in validation in browsers. For it to work nicly we need an empty placholder attribute on all input fields.

Then we can add CSS like below to directly show users when input is valid/invalid.

```
    input {
        &:not(:placeholder-shown):valid {
            background-color: lighten($color--correct, 40%);
        }

        &:not(:placeholder-shown):invalid {
            background-color: lighten($color--error, 30%);
        }
    }

```

**Comment by theskumar** [comment]
This indicates the form field is invalid but needs to explain what is wrong. Does using a library or JS solution for client-side validation make sense?

**Comment by frjo** [comment]
With HTML5 the browser will show why for the same fields it set `:invalid` for I believe. You can also use the `pattern` attribute on the input tag to make it more specific.

**Comment by theskumar** [comment]
There are lot of UX concerns on using the number input, so I would want it to be a text input with pattern and proper error message display. I'll look into it. 

https://news.ycombinator.com/item?id=32852643
