### ISSUE TITLE
Help needed in understanding object model

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3217]
(Not sure if this the right place to put)

My goal is to create a django command that goes through all reviews and applications, replacing all data with appropriate anonymized data (lorem ipsum, generic addresses, etc).  The basic script is to do the following:

```
for submission in ApplicationSubmission.objects.all():
    for (key, value) in submission.form_data.items():
        type = determine_type(key)
        sanitized_value = sanitize(value, type)
```

I'm having problems understanding how to implement `determine_type`.  How do you connect a field's key to a specific instance of that field in the correct instance of `ApplicationForm`?  I'm hoping that this answer will port over to the review object model as well.

**Comment by frjo** [comment]
Submission, review and determination forms are all built as stream field forms.

They are messy to work with in the way you want. For organisations using Hypha they do offer a lot of flexibility without the need for a developer.

@theskumar Can you offer @frankduncan any tips regarding this?

Frank helps a couple of other Hypha implementors, he is one of the devs behind PR #3156.

**Comment by frankduncan** [comment]
When investigating, I notice that some `form_data` are keyed by the `form_field.block.id` and some are keyed by `form_block.block_type` (notably title, email, duration, but there are others).  Where is this distinction is defined (I couldn't find it)?

**Comment by frjo** [comment]
It might be controlled here, but other will know for sure.

https://github.com/HyphaApp/hypha/blob/e9e65902e8d9e3d91d5c564beb09b4300ac97310/hypha/apply/utils/blocks.py#L190-L194

It is done for required fields so they easily can be retrived and displayed in various places, not just as part of the application.

**Comment by frankduncan** [comment]
@frjo That makes sense, and yes, that's exactly the place!

**Comment by frankduncan** [comment]
Looks like my best bet is to switch on the `instanceof` check of `form_field.block` as here: 

https://github.com/HyphaApp/hypha/blob/main/hypha/apply/stream_forms/models.py#L64-L117

**Comment by frankduncan** [comment]
I've gotten pretty far on this.  I think I'm ok for now, but I'm keeping the issue open in case I run into more problems.  Once I've finished the script, I'll close it out.

I don't know how much general use it would be.  It turns out that things like "Phone Number" are being implemented as generic Char Fields, so we have to key off of the field_label so that we replace them with `Faker.phone_number` rather than `Faker.text`
