### ISSUE TITLE
Run into ValueError: Missing staticfiles manifest entry for 'js/select2.multi-checkboxes.js' on v3.7.1

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3233]
**Describe the bug**

When upgraded to v3.7.1, from v3.3.0, ran into the following:

```
ValueError: Missing staticfiles manifest entry for 'js/select2.multi-checkboxes.js'
```

**To Reproduce**

1. Update to v.3.7.1
2. Run various update things (npm, pip, python)
3. Run `npm run dev:build`
4. Run `npm run build`
5. Run `python manage.py collectstatic --noinput --settings=hypha.settings.production`
6. Start server
7. Visit home page

**Expected behavior**

Not a 500 error

**Priority**

I guess the priority is High (for me).  Though from searching around online, it looks like it might be something with collectstatic not working like it should?  I can't imagine that something this breaking would have made it into an official release.  It's most likely a configuration error or something related to the upgrade leaving a vestigial file somewhere.

**Comment by frankduncan** [comment]
Also note, I do see the file in `static/js/select2.multi-checkboxes.js` and also `static/js/select2.multi-checkboxes.42b78f172fb5.js` (and gz files).  I also see it in `static/staticfiles.json`:

```
"js/select2.multi-checkboxes.js": "js/select2.multi-checkboxes.42b78f172fb5.js"
```

**Comment by frjo** [comment]
It should be this file `hypha/apply/dashboard/static/js/select2.multi-checkboxes.js`. I do not think the code around that has been touched for a long time.

**Comment by frankduncan** [comment]
I just hit the server again this morning and the error did not show up.  Closing the issue, but I have no idea why it just started working.  I'll reopen if I can end up recreating and understanding why waiting solved the problem.
