### ISSUE TITLE
External Reviewer access to reviewer names, review outcomes, and reviews

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3240]
### Description

External reviewers should not be able to view the staff member WHO has reviewed their application and the OUTCOME of reviews submitted. 

### Related
Reviewer can access any submission by directly visiting the submission detail page #2169
https://github.com/HyphaApp/hypha/pull/2170

**Comment by frjo** [comment]
@fourthletter Is this when an reviewer has submitted their own application?

**Comment by frjo** [comment]
When an reviewer is the author of an application they get the applicant view for that application. There should be no reviews visitable there.

@fourthletter  Can you provide the review user you are testing with and the URL to the application they have submitted?

**Comment by fourthletter** [comment]
@frjo Please have it apply to ALL submissions

Reviewers need to be impartial when they evaluate a proposal. Seeing the outcomes or who have submitted is information external reviewers do not need to see.

**Comment by frjo** [comment]
@fourthletter The reason the reviewer could view the full staff review was that it was explicitly set so in the visibility settings.

![Skärmavbild 2023-02-22 kl  13 51 41](https://user-images.githubusercontent.com/191392/220624772-d36deab6-b34c-4348-bc06-9a3c0e9b74c3.png)

When a review is set to private should we maybe hide it all together?

**Comment by fourthletter** [comment]
Thank you for looking into this.

**Comment by sandeepsajan0** [comment]
@frjo Should we look into it or is it just fine with the `Private` option?

**Comment by frjo** [comment]
@wes-otf Is this still an issue or can we close it?

**Comment by wes-otf** [comment]
Hey I'm going to look deeper into this and ask around - I think the private aspect should be fine but it also shouldn't show names/results in application details if private. I tested locally & as the `Reviewer` role I was able to see the result & staff reviewers of an application even though I couldn't click and see the details:
<img width="945" alt="Screenshot 2024-05-08 at 12 41 09" src="https://github.com/HyphaApp/hypha/assets/145372368/3d4e6f27-26e0-40f2-9ad9-ab50d66c67b5">

I feel like these should only show when visibility is set to `Reviewers and Staff`

**Comment by wes-otf** [comment]
~~also maybe we could rename `Private` to `Staff`/`Staff only` if y'all thought that made sense. To me `Private` vs `Reviewers and Staff` implies staff can't see it when private~~

**edit**: disregard this, in my haste I missed the nice description:
<img width="534" alt="Screenshot 2024-05-08 at 12 51 03" src="https://github.com/HyphaApp/hypha/assets/145372368/94403c5d-d57e-48a6-91bf-5a8942c2b838">

**Comment by frjo** [comment]
This is how it was supposed to work once upon a time. If OTF has other needs now it should not be hard to fix.

**Comment by wes-otf** [comment]
Yeah that sounds good - I have no clue if this is where they currently stand, I was just trying to interpret Di's previous posts. Will ask around and report back!
