### ISSUE TITLE
Old and unused stuff to remove

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3242]
- [x] Stellar conf file, we use dslr now
- [x] Salesforce integration, never used
- [x] django-webpack-loader, we are not using webpack anymore
- [x] Matomo integration, not used for years
- [x] Update locales
- [x] Update pytest duration file.
- [ ] Redis integration, will we ever use this?
- [ ] other stuff?

**Comment by frjo** [comment]
@sandeepsajan0 @theskumar Any objections to remove the stuff above? More stuff we can remove?

**Comment by theskumar** [comment]
What is redis using right now? I would suggest keeping it can recommend using it for sessions and introducing caching where it's needed.

**Comment by frjo** [comment]
We had plans to use Redis but never got around to it, no urgent needs. No need to make the app more complicated than needed.

**Comment by theskumar** [comment]
If redis not used, we can remove it. The latest version of Django now has in-built support for redis after installing redis-py. We can add those in the production deployment docs.

**Comment by theskumar** [comment]
So I would add this to removal when we upgrade Django to 4.x, More about the feature: https://docs.djangoproject.com/en/4.1/topics/cache/#redis
