### ISSUE TITLE
Provide section titles for "Copy questions to clipboard" output

### ISSUE THREAD

**Issue by hpk42** [HyphaApp/hypha#3244]
When using the  "copy to markdown" button on proposals and concept notes, one gets a nicely workable markdown file. Thanks! 
 "
However, the lack of proper section titles with "nouns" leads to difficulties for easily referencing one section from another, or from a text chat.  It would likely help also other future proposal writing teams, to generate numbered sections with a short title/section noun. 

In our case, we split the markdown files into 11 different files,  with a local numbering like below. 
Subsequently, everyone started talking about "working on 05 now", "revising 02 and 04" etc. -- if there is async collaborations between even just a handful of active contributors, brevity and precision of references is helpful.  

![Screenshot from 2023-02-23 01-51-29](https://user-images.githubusercontent.com/73579/220798922-49d0e590-26c8-4912-9cd6-329c22d90252.png)

**Comment by hpk42** [comment]
thanks for the quick handling!

**Comment by r10s** [comment]
wow, that was fast! thanks a lot, @frjo and @fourthletter 👋 :)
