### ISSUE TITLE
Allow applicants to select multiple options in a category question

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3246]
### Description

Category questions on application form only enable a single selection. https://test-apply.hypha.app/admin/categories/category/edit/7/

**Comment by frjo** [comment]
When staff add a category field to a form they can decide if it should be multi-select or not.

![multiselect](https://user-images.githubusercontent.com/191392/221005576-4639fbf7-7738-4c31-9365-3e95b5a8cdda.jpeg)

**Comment by fourthletter** [comment]
Thank you for the reminder!
