### ISSUE TITLE
Roles layout in user add wagtail form

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3247]
**Describe the bug**

Roles check boxes are misaligned with roles text, in user add wagtail form 

**To Reproduce**

1. Check out the following url: https://sandbox-apply.opentech.fund/admin/users/add/#tab-roles

**Affected roles**

- Staff

**Screenshots**

![image](https://user-images.githubusercontent.com/111306331/221297733-89dea845-fc1b-489b-abd6-93e67b566b70.png)

**Comment by theskumar** [comment]
Hi @gmurtaza00, on which browser are you facing this issue? 

I'm on chrome (Mac OS) and don't see the misalignment. I'm using the `main` branch. 

![Screenshot 2023-02-28 at 07 27 58@2x](https://user-images.githubusercontent.com/236356/221783664-ef0aa01d-baca-485e-acd3-b87ce16b0140.jpg)

On Safari: 

![Screenshot 2023-02-28 at 07 29 36@2x](https://user-images.githubusercontent.com/236356/221783939-8a09aff6-a737-4d76-aed2-381cfe68820b.jpg)

**Comment by gmurtaza00** [comment]
@theskumar I have tested it on chrome and firefox on my linux machine.

**Comment by fourthletter** [comment]
This issue will be resolved with this PR https://github.com/HyphaApp/hypha/pull/3636
