### ISSUE TITLE
Request time out issue on both docker and without docker setup

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3250]
When running gunicorn server on my local setup, the request keeps getting timed out. Same goes with the docker setup.

![Screenshot from 2023-02-27 10-49-34](https://user-images.githubusercontent.com/111306331/221612921-57932921-20f3-4cc4-bd99-1fb355b9f970.png)

**Comment by frjo** [comment]
By default gunicorn runs with only one worker. Increase that to three and I think it should work better.

If it does a PR for the docs and Docker would help others.

**Comment by gmurtaza00** [comment]
Increasing the worker solved the **502 Error** but the worker processes keeps getting timed out almost every other minute.
 
 I have the hypha 3.4 version for a client and when i used those static files by editing the nginx config to point the /static/ and /media/ directory of 3.4 version. It worked perfectly but the error reappears when i use the latest version of hypha with necessary changes in nginx config file.

**Comment by frjo** [comment]
Have you tried to increase the timeout setting? The default is 30 I believe, try 120 or something like that.

https://docs.gunicorn.org/en/stable/settings.html#timeout

**Comment by gmurtaza00** [comment]
Yes, i set it to 90 but no improvement.

**Comment by frjo** [comment]
I also see some "WORKER TIMEOUT" on my local machine running gunicorn but Hypha runs just fins any way. Not so for you?

You could try to switch `--worker-class=gevent`, the default is "sync"

You will need to `pip install gevent` for that.

**Comment by theskumar** [comment]
Could you try running the local setup with: 

```
$ python manage.py runserver 0.0.0.0:9001 --settings=hypha.settings.dev
```

Replace the port, with you have configured for the site and you may want to stop nginx and apache.

**Comment by theskumar** [comment]
@gmurtaza00 Take a look at updated local setup guide, i'm working on https://github.com/HyphaApp/hypha/blob/778accb10589bf17144cb15ed86e463ebcb46d68/docs/getting-started/development/manual.md

- https://github.com/HyphaApp/hypha/pull/3264
