### ISSUE TITLE
No email notification goes to a user when admins create an account for them

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3253]
**Describe the bug**

There is no email generated when an account is created by an admin prompting a user to go activate their account and set up their password.  Current workaround is that the user goes to the "Forgot password" page and uses their email to complete the setup process.

**To Reproduce**

1. Create a user via the wagtail admin console

**Expected behavior**

An email goes to the end user so that they can set up their password.

**Priority**

This was a nice to have item for our client, and we resolved it our fork.

**Affected roles**

- All

**Additional context**

The code change we made was small, adding a `send_activation_email` call in `hypha/apply/users/wagtail_hooks.py`

**Comment by theskumar** [comment]
I agree this will be pretty useful while onboarding users.

**Comment by frjo** [comment]
Good addition. Especially in combination with https://github.com/HyphaApp/hypha/pull/3156

**Comment by sandeepsajan0** [comment]
It has been fixed already. It sends activation mail to the user.

![image](https://github.com/HyphaApp/hypha/assets/23638629/c5fa7dd8-19c4-4dac-9d6a-47399e0a2e4d)

**Comment by frjo** [comment]
This has been fixed in another issue.
