### ISSUE TITLE
500 error when editing a review that's had its form changed

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3254]
**Describe the bug**

After submitting a review, if the review form is edited removing a score, a 500 error is raised when editing the review.

**To Reproduce**

1. Create a review involving multiple scores
2. Submit the review
3. Edit the review form, removing one of the scores
4. Submit the edit for that review

**Expected behavior**

That the edit review is successful

**Priority**

It was High for our client, as they had a situation where they ran into this and was preventing them from moving forward, but it's fixed on our branch.

**Affected roles**

- Reviewers

**Additional context**

We have a fix for this case, and a PR will be incoming :)

**Comment by frjo** [comment]
Definitely sounds like a bug. Editing an existing review should rely on the form in the "form_fields" field for that review.

**Comment by frjo** [comment]
@frankduncan When you write "form changed" do you mean:

1. Changing the stream field form in Wagtail admin?
2. Changing the python code of the review form?

**Comment by frankduncan** [comment]
I mean #1, changing the form in the wagtail admin.
