### ISSUE TITLE
Add SOW template to wagtail 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3259]
## Description
Compliance needs to provide contractors and auditors with a contract and the SOW. The SOW contains part of the information in the PAF, and can be generated by the WebApp. 

- [ ] SOW could be created in wagtail similar to forms and PAF
- [ ] PAF and SOW are combined, and could be completed by the program manager as a single document
- [ ] SOW is rendered as a separate document from PAF 
- [ ] Contracting can export the SOW into their document editor

### SOW in Wagtail
![image](https://user-images.githubusercontent.com/20019656/222099853-c6541778-178c-43cb-b123-2baabd071395.png)

### Related
https://github.com/HyphaApp/hypha/issues/3209

**Comment by frjo** [comment]
1. The SOW form(s) will be created exactly like the PAF and all other forms are created today.
2. Staff will then select the SOW for to use for each fund/lab just as in the mockup above.
3. When staff fill in the PAF for a project the fields from the SOW will be automatically added to the end making it look like one form. If needed we can make these fields stand out in some manner.

The point of having them as separate forms in Wagtail admin is that Hypha then easily can output only the SOW fields when needed. To have a separate SOW that did not contain the PAF fields (that has a lot of sensitive information) was an important requirement for OTF.
