### ISSUE TITLE
Submission form questions should display even when value is empty

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3271]
Description

Questions fields do not appear on forms when an answer or response has not been submitted: https://test-apply.hypha.app/apply/submissions/532/

Proposed Solution

When an applicate does not input a response into a question field, program managers should still be able to see the question even when the answer is blank.

![image](https://user-images.githubusercontent.com/20019656/223457504-4932040d-c4ef-49a2-a676-53c74c85012a.png)

**Comment by frjo** [comment]
This was done on purpose so not a bug. Should not be hard to change the behaviour, we already do it for some custom fields.

**Comment by fourthletter** [comment]
Fixed here https://github.com/HyphaApp/hypha/issues/2261
