### ISSUE TITLE
Give 'Paragraph' and 'Section text' fields the same name since they are identical

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3272]
Description

Please add 'Paragraph' field to Apply Forms. This field is currently only available on review forms.

![image](https://user-images.githubusercontent.com/20019656/223466331-3bba7d81-9d7f-451a-ba57-f0788485a4b8.png)

**Comment by frjo** [comment]
You already have this field in Application forms, it just named differently.

Look for "Section text", different name but works exactly the same.

**Comment by theskumar** [comment]
To make this consistent, does it make sense to name both of them the same?

**Comment by fourthletter** [comment]
Thank you, @theskumar This isn't urgent, I will add it to the backlog.

**Comment by theskumar** [comment]
Does this look good? 
![Screenshot 2023-03-16 at 08 38 27@2x](https://user-images.githubusercontent.com/236356/225561025-fbcbee43-7f5f-4270-add5-03edc38c8f53.jpg)

**Comment by theskumar** [comment]
Determination form also has a `section text/headings`, do we want to make it same? @fourthletter @frjo 

![Screenshot 2023-03-16 at 08 39 33@2x](https://user-images.githubusercontent.com/236356/225561545-1a0363cd-f2d5-436b-bc6d-237e3abcd5bd.jpg)

**Comment by fourthletter** [comment]
Updating these particular field names is not a high priority. 

We are increasingly building more custom forms in Hypha (ie Review form, PAF form, etc.). As maintainers, we need to ensure the forms are consistent and intuitive to users. There are some fields that are required, but do not align with user needs. These required fields and lack of clarity over field parameters (how they render on application forms) makes it difficult for current and new Hypha users.

**Comment by frjo** [comment]
@fourthletter This is a very easy fix, the PR is done https://github.com/HyphaApp/hypha/pull/3285. 

Regarding field in general, please add issues for what required field should not be required any longer. AS well as issues for any other things you want changed.

We need specific requests to be able to do anything. Most of them is likely easy fixes, we just need to know what to do.
