### ISSUE TITLE
In "All Rounds and Labs" table, drafts should not be included when calculating % Determined

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3273]
Description 

Drafts are included in the total amount of submissions. Draft submissions should not be included in this count because applicants are still revising their application forms. 

Image 1
![image](https://user-images.githubusercontent.com/20019656/223470057-e23b8337-76a1-467a-8ca7-a84406d251fb.png)

Image 2
![image](https://user-images.githubusercontent.com/20019656/223470224-2f56d75d-9dfc-4589-af4a-0b85d1613395.png)

**Comment by frjo** [comment]
Is it the number one in "CPF January (1)" that you refer to as "total amount"?

That number shows you how many submissions your are currently viewing, i.e. search results count. That should not change.

Or is the number one in "Determined (0/1)"? That number should maybe not include the drafts.

**Comment by fourthletter** [comment]
Example of Fund [https://test-apply.hypha.app/apply/rounds/949/] that counts drafts towards the total amount. This Fund has three submissions total. Two are complete and one is a draft. The percentage indicates 66% determined. I viewed this information as 'Staff Admin' and as 'Staff.' 



![image](https://user-images.githubusercontent.com/20019656/224001792-a4f06433-9d9e-49de-8b99-1d8fc8d4bece.png)

**Comment by frjo** [comment]
So option 2 it is, that should be fixed. Updated the title to more precisely state the issue.

**Comment by fourthletter** [comment]
Thank you! 

![image](https://github.com/HyphaApp/hypha/assets/20019656/aa077a4e-2832-4b99-945a-4890439f6e7d)
