### ISSUE TITLE
Should workflow permissions be handled through wagtail interface

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#3297]
While working on #3296, I realized that our withdrawing code relied on the applicant having edit permissions on the submission.  This was not a result of changing the wagtail permissions for submissions to "edit", but rather on changing workflow.py here: https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/workflow.py#L225

And changing it to `applicant_edit_permissions`.  This seems like something that should be configured through the admin interface, rather than a code change, but I wanted to open up a discussion about the most appropriate place to enable this.

**Comment by fourthletter** [comment]
I'm sorry we didn't get a chance to discuss this during our Tuesday morning call. We will make a point to discuss these items you've raised during upcoming meetings.
