### ISSUE TITLE
Visual enhancement of reviewer/assignee column in all submissions table

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3299]
**Is your feature request related to an existing functionality? Please describe.**

In reviews column, express completed reviews/assigned reviews as a ratio or fraction.

**Additional context**

![image](https://user-images.githubusercontent.com/111306331/227968137-8cb7d781-a9f1-43cd-bea4-6acb39447702.png)

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners

**Comment by fourthletter** [comment]
![image](https://user-images.githubusercontent.com/20019656/234940303-1124d1d3-3889-42e7-9ae7-1736e7678f83.png)
