### ISSUE TITLE
Export users list as .csv file

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3307]
**Is your feature request related to an existing functionality? Please describe.**

Admin/Staff user should be able to download the users list in a .csv file. 

**Additional context**

If no filters are applied, all users should be exported otherwise filtered users should be exported. 

**Priority**

- Medium priority 

**Affected roles**

- Staff

**Comment by frjo** [comment]
Limited to staff admin user role would be best I think.

**Comment by frjo** [comment]
or use Wagtail permissions system to make it configurable per role.

**Comment by gmurtaza00** [comment]
> Limited to staff admin user role would be best I think.
Yes. It is limited to staff admin only.

**Comment by frankduncan** [comment]
This appears to have been reverted by commit b006b96d76b6af37c7807a80d052f371027ebd15

Is this functionality supposed to have been removed?  Or did it get moved and I don't see where?

**Comment by frjo** [comment]
@frankduncan  It was rebuilt a bit I think, the functionality is still there from what I can see.

<img width="873" alt="Skärmavbild 2024-09-11 kl  14 46 08" src="https://github.com/user-attachments/assets/93d33303-249e-4bc2-81cc-cb66715dc4bf">

**Comment by frankduncan** [comment]
Oh great!  Thanks :)
