### ISSUE TITLE
General Counsel picklist during PAF approval should only be contracting user group

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3315]
### Description
When selecting the General Counsel approver, only individuals from the contracting user group should appear. Right now the contracting and 'contracting + approver' user group also appears in the pick list.

![image](https://user-images.githubusercontent.com/20019656/229157332-7f7d4005-3d86-480b-aefe-584c509ebfb4.png)

![image](https://user-images.githubusercontent.com/20019656/229157250-2d95b7dc-ca08-4ef6-80d2-cec55828a5d8.png)

**Comment by frjo** [comment]
@fourthletter Then go Wagtail admin and change it. This is completely configurable by each implementor in Wagtail admin.

**Comment by fourthletter** [comment]
I did configure it as such but there appears to be a bug

![image](https://user-images.githubusercontent.com/20019656/229175757-54df7c34-bd2d-44b1-8123-6a244b93a3d6.png)

**Comment by frjo** [comment]
@fourthletter See "PAF Reviewer Roles" here https://test-apply.hypha.app/admin/settings/application_projects/projectsettings/2/ and you will see you can configure it any way you like.

**Comment by frjo** [comment]
@fourthletter If you pick only the approver role these users should appear in the list: https://test-apply.hypha.app/admin/groups/11/users/

If that is not the case there is a bug.

**Comment by fourthletter** [comment]
I only selected 'contracting' but 'contracting and approver' user group also appears on the picklist. This is a bug.

**Comment by frjo** [comment]
@fourthletter Yes, it will show all users with the role contracting. The users on the list might have more roles as well, the system ignore that.

Do you prefer the selection to be particular and only show users that has the exact roles you pick?

So that if you pick "Staff" only users with that roles and no other roles (e.g. "Staff admin" role) are listed?
