### ISSUE TITLE
Single File Field button

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3316]
### Description

Users should know that the file upload button will upload only one document. Currently the ui shows a gray out field when it should say "Single File field"

![image](https://user-images.githubusercontent.com/20019656/229177877-5c5dca9e-ff41-4f5f-9037-250ccaeecf78.png)

**Comment by frjo** [comment]
@fourthletter  Staff kept using it by mistake and was then reporting it as a bug that only a single file could be uploaded. OTF wanted it completely removed but that was hard since current application forms was using it. The solution was to disable it for all new forms.

**Comment by fourthletter** [comment]
We know the historical reasons for the greyed out file upload field https://github.com/HyphaApp/hypha/issues/2102

Different adopters, other funding organizations, using this platform will not know and intuit that 'file field' means single file upload only. I propose we make it more clear if possible.

**Comment by frjo** [comment]
No one can use the "Field field", it is greyed out for all new forms. Only the "Multiple File Field" can be used.

New implementors might wonder why "File Field" is always disabled (greyed out). Maybe we find a way to hide it completely.

**Comment by fourthletter** [comment]
I remember the historical reason for why file field was gray out. However, other organizations using Hypha will not.
