### ISSUE TITLE
Change Download to View on Contracting documents table

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3319]
### Description

On the Contract Change table change Download to **View**. The user clicks on View, and the form is rendered into another tab.

![image](https://user-images.githubusercontent.com/20019656/229181094-81cf9bf8-fb51-4358-9300-f2c07c1f70c3.png)

**Comment by frjo** [comment]
@fourthletter The contract is a PDF and it will depends on the browser and user settings if the file is opened in the browser or directly downloaded.

You can att code to intrust the browser to always download, but not the opposite.
