### ISSUE TITLE
Change the button to ‘Resubmit’ when someone requests for change and the PM is trying to submit the PAF after editing

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3323]
Change the button to ‘Resubmit’ when someone requests for change and the PM is trying to submit the PAF after editing.

![image](https://user-images.githubusercontent.com/20019656/229183168-accc43e5-4994-48d6-9d3f-6c6e76f157f1.png)

**Comment by sandeepsajan0** [comment]
@abhiXII Do we want to update the next step as well?

**Comment by abhiXII** [comment]
> @abhiXII Do we want to update the next step as well?

Yeah that would be good, thanks!
