### ISSUE TITLE
Revise step to say “Review the contract for all relevant details and approve”

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3324]
### Description 

User didn’t know what ‘Approve contract’ meant. The next step should say “Review the contract for all relevant details and approve”. [Figma update](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE?node-id=432:9757#408228815)

![image](https://user-images.githubusercontent.com/20019656/229183680-4185f0d5-0e74-4e93-8f50-243e78cb7c39.png)

**Comment by frjo** [comment]
Maybe even  "Review the contract and any contract documents for all relevant details and approve"?
