### ISSUE TITLE
Hide Vendor 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3325]
### Description

Hide Vendor (no response) from ui. UI was designed for financial software integration that is still pending.

![image](https://user-images.githubusercontent.com/20019656/229184194-6d228726-f234-41f8-a3a6-460be3ca2851.png)

**Comment by frjo** [comment]
All vendor things should be hidden when "Vendor setup required" is not checked in Projects settings in Wagtail admin.
