### ISSUE TITLE
UI fixes: a thread

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3331]
- [x]  1. Add some space between the body text and `Select lead` as in design
- [x] 2. Make the popup heading left aligned - refer to figma. We need to make this change for all the popupa.
![Image](https://user-images.githubusercontent.com/124244361/229768026-ab41dc7f-7a93-4ea7-94a3-c4d3c533409f.png)

- [ ] 3. As soon as the project is created, the supporting document row shows blue tick, it should be grey. Blue only when documents have been approved, i.e. after PAF approval
- [x] 4. Should we also remove `choose file` since its not doing anything really
- [x] 5. The download option for proposal should either prompt pdf, docx . Else we could probably remove the down icon and use it only when there are options for files
![Image](https://user-images.githubusercontent.com/124244361/229768793-f97776fd-57db-4e86-9054-69ab2f4d9bd6.png)

- [x] 6. When uploading supporting documents, the pop-up header might be better labelled `Upload supporting document`
- [x] 7. We also need to put actual categories in the dropdown for user testing
![Image](https://user-images.githubusercontent.com/124244361/229791957-b4c98a9e-8921-4f88-b3d8-a7202b61d3dc.png)

- [x] 8. After uploading supporting documents, we need same formatting for `Download` button which is bold and icon if there's option to download pdf/doc
- [x] 9. Remove action should be red with cross icon, like this 
- [x] 10. Please also left align the texts as shown by vertical line
![Image](https://user-images.githubusercontent.com/124244361/229794989-423d6a6c-ff7d-47f5-8dc6-cf639b1203fe.png)
Reference image:
![Image](https://user-images.githubusercontent.com/124244361/229793241-eabf528e-8822-41e1-aeaf-f628164feb85.png)

But also! aren't we going with the design where the required documents are listed on the interface and users can directly upload it without having to use the popup dropown?

- [ ] 11. Can we pls make the font size of sow same at 'otf review' it is too big rn
![Image](https://user-images.githubusercontent.com/124244361/229796478-a7ed9da3-e925-4b81-8695-06ef0fa2a963.png)

- [x] 12. There should be a download for the entire Approval form as well, and there should be edit for sow which would just take users to that section in edit mode.
![Image](https://user-images.githubusercontent.com/124244361/229798431-5e9a296e-ad48-49fa-96d9-ecdadca7f867.png)

- [x] 13. Please add some space between VP technology and the body text as marked by red line
![Image](https://user-images.githubusercontent.com/124244361/229798911-cb70a866-fd22-47d1-9b28-046713f4f05c.png)

- [x] 14. Can we please change `Request` to `Submit` so that the terminology is consistent
![Image](https://user-images.githubusercontent.com/124244361/229799370-cbe2e586-2bf4-4f52-bc2a-623f3db64a30.png)

- [x] 15. Once the PAF has been submitted for approval, we shouldn't allow staff to remove the supporting document
![Image](https://user-images.githubusercontent.com/124244361/229800742-94c283e4-e5ac-4966-b152-ae67a7393abf.png)

- [x] 16. Please add date when it gets approved ([refer to design](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=247-3851&t=Y8TPTBlN6NBR1w1b-4))
![Image](https://user-images.githubusercontent.com/124244361/229802301-08fb5f76-b4aa-447c-a175-b2f875cf5592.png)

- [x] 17. We can confirm this with @fourthletter but i think the SOW should show up on the same page as the Approval form, and should be viewed from the same page but lower. Because the problem that may arise is that people will just approve the PAF without looking at the SOW since they are on separate pages and there's no way to separately approve SOW.
![Image](https://user-images.githubusercontent.com/124244361/229804497-ef24f6ed-7aee-4206-b497-81d8414d583c.png)
![Image](https://user-images.githubusercontent.com/124244361/229804931-422ad08c-1f4c-47f4-8a22-8a05ba659585.png)

- [x] 18. We don't need two upload contract buttons. i think the lower one should be sufficient
![Image](https://user-images.githubusercontent.com/124244361/229819678-146ba4a8-7013-4380-ad24-0cdce8089d61.png)

- [x] 19. We need some spacing between the icons and text, everywhere. you can refer to Figma file for this too. We need to check some vertical spacing in few places. Also, check the padding inside Upload button. please check that for all similar buttons.
- [x] 20. If contracting documents are not configured we shouldn't show that row. And the icon shouldn't be blue initially - only after uploading the documents.
- [x] 21. Reupload button should also show once
- [ ] 22. We also don't need to show 'corrections' option when contracting uploads the document? 
- [x] 23. Can we please show the contract date next to the view option([like in the design](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=432-3557&t=Y8TPTBlN6NBR1w1b-4)) instead of the label on the left?
![Image](https://user-images.githubusercontent.com/124244361/229822157-8ac5bcc2-fb3c-4268-83b0-f8a503c5171f.png)

- [x] 21. Please make sure that countersigned is written the same way in all the places. Let's go with "Countersigned" instead of CounterSigned or counter-signed or counter sign etc...
- [ ] 22. When the applicant is uploading countersigned contract, the popup header should be `Upload Countersigned Contract`, instead of Upload we can say `Select contract` and then instead of submit it could be `Upload` to make things a bit more clear.
- [x] 23. I think if there is an option to upload contract documents, the `submit contractor documents` should be made available once contract documents have been uploaded else they will get missed causing unnecessary back and forth. @fourthletter can you please confirm regarding point 23?
![Image](https://user-images.githubusercontent.com/124244361/229826183-998b1e56-718d-4250-8dc4-78ff69d8bc0b.png)

- [ ] 24. Delete action should be in red, hex: #CD3238 
![Image](https://user-images.githubusercontent.com/124244361/229826507-f0e54f94-a3e9-4243-a2f6-9eb0d3014ab8.png)

- [x] 25. Can we please change the label to `Need corrections/amendments to contract?` just to make it explicit and clear?
![Image](https://user-images.githubusercontent.com/124244361/229829155-ee019827-9e0b-416a-81dc-8ec8b688d60a.png)

- [x] 26. Let's please change the Invoice delete button to red, hex: #CD3238 
![Image](https://user-images.githubusercontent.com/124244361/229835555-3b81152b-ffe5-437c-800d-42b45bdc90bb.png)
![Image](https://user-images.githubusercontent.com/124244361/229835710-eabdfbbb-ad3a-4e4f-b2cf-d100762e6e57.png)
Also please remove underline from here for the buttons to keep them consistent.

- [x] 27. For the Staff this next step text should be: `Review invoice and take action`
- [x] 28. Also, staff can't upload invoices
![Image](https://user-images.githubusercontent.com/124244361/229837082-d3f346c2-39f5-47ad-8ddb-f49180c56607.png)

- [x] 29. Once the invoice is approved, the finance person should also get an email to process the invoice.
- [x] 30. Should the finance person be able to see invoice before it is approved by the staff? @fourthletter 
![Image](https://user-images.githubusercontent.com/124244361/229838516-84fceb04-b9b0-4952-9458-ec80d8f4a133.png)

**Comment by abhiXII** [comment]
Update from our meeting today: We're removing `Download` button from the entire flow and relying on `View` option followed by users downloading the doc from their browsers. 

FYI @fourthletter 
Oh and Di, we would need your help on #7 and other informations that make the Test interface look as close to Live as possible.

**Comment by frjo** [comment]
@abhiXII I think the PAG and SOW forms on test have been updated already, looking at them now them look like the real things.

**Comment by sandeepsajan0** [comment]
>As soon as the project is created, the supporting document row shows blue tick, it should be grey. Blue only when documents have been approved, i.e. after PAF approval

It shows blue tick when all required supporting documents are uploaded. If there is none required then it should be already blue. We are using the same behaviour for other places as well.

**Comment by sandeepsajan0** [comment]
>As soon as the project is created, the supporting document row shows blue tick, it should be grey. Blue only when documents have been approved, i.e. after PAF approval

@abhiXII It should be blue as soon as the user uploads 1st file or after approval? Because in yesterday's meetings we finalize it turns blue on 1st file upload but I think it might confuse the user in case of multiple required documents. 
And We are having the same behavior for contracting documents as well.

**Comment by fourthletter** [comment]
> Update from our meeting today: We're removing `Download` button from the entire flow and relying on `View` option followed by users downloading the doc from their browsers.
> 
> FYI @fourthletter Oh and Di, we would need your help on #7 and other informations that make the Test interface look as close to Live as possible.

@abhiXII - sorry I did not reply sooner. I added document categories

![image](https://user-images.githubusercontent.com/20019656/231464481-208a6375-4b93-4a33-b7ad-f679ab99e0b0.png)

**Comment by abhiXII** [comment]
Thanks @fourthletter 
@sandeepsajan0 I believe we're aligned on your [comment above](https://github.com/HyphaApp/hypha/issues/3331#issuecomment-1504983174) right?

Here's some updates from 2nd round of testing :
11 might have got missed. i unticked it.

- [x] 31. Now there's no option to download PAF document. View takes it to the next page and then there's no download. i think we need to add Download button on the next page atleast like how it is for SOW row. 
<img width="939" alt="image" src="https://user-images.githubusercontent.com/124244361/232010828-c161dda7-98fa-4f66-a3cf-5bf7a1226a76.png">

- [x] 32. This is showing twice - maybe in the Parallel approval case?
<img width="813" alt="image" src="https://user-images.githubusercontent.com/124244361/232012643-472076b3-899a-421e-8014-b3db150d71cf.png">

- [ ] 33. Can we please open documents in a new tab for the ones that open directly
<img width="935" alt="image" src="https://user-images.githubusercontent.com/124244361/232013383-ca97d02d-7b35-4098-860b-70d7d01e34a6.png">

- [x] 34. Hovering on the cross shows the arrow cursor, i think we should have hand cursor to show it's clickable.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/124244361/232014500-98df7647-b85f-4642-a5cd-2d5ef5d9ca72.png">

- [x] 35. Minor thing but the button text can appear in one line i think
<img width="530" alt="image" src="https://user-images.githubusercontent.com/124244361/232014730-d2055dcd-ea25-415c-9c07-e353f62ae19b.png">

- [x] 36. Right after Abhishek Finance approved the PAF, i think we should hide the `Update status` button? Since it's not applicable anymore. 
Additional note: Only the CEO doesn't see update status again other approvers continue to see it. Oh! this happening because all the other approvers need to approve it twice. after two times, the option disappears. 
<img width="1123" alt="image" src="https://user-images.githubusercontent.com/124244361/232015118-5558f863-7ce3-43be-8a5b-435bbb1f8bba.png">
On eprojectproject screen also
<img width="1315" alt="image" src="https://user-images.githubusercontent.com/124244361/232015263-cba8ffea-f77f-4d7d-9424-4d1f9eb3a4b9.png">

- [ ] 37. After requesting for changes as a VP, the interface started showing the resubmit option which is for the staff actually. 
<img width="1343" alt="image" src="https://user-images.githubusercontent.com/124244361/232016308-053de6c4-00c1-4991-9a82-a5b40347546e.png">

- [x] 38. I think i missed considering this condition in design that when changes have been requested, the next steps to other should probably show "Changes requested. Awaiting documents to be resubmitted." Would this work or should we say Changes requested by [Abhishek VP] using the user name.
<img width="1354" alt="image" src="https://user-images.githubusercontent.com/124244361/232016775-8c7a384f-6cab-42a5-8dce-0adc144bb65b.png">

- [ ] 39. In parallel case, when Abhishek staff resubmitted the project documents after making changes. everyone again received the emails. i think it makes sense to send it to the ones who requested changes only? because those who approved don't need it and neither the people who haven't reviewed it yet. And then the people who have approved it earlier shouldn't see `update status` for the project. 

- [x] 40. Please check the button styling. Let's remove the outline. While on it, let's also **increase the button padding** (can refer to design). Both, for upload and reupload and any other place i think
<img width="957" alt="image" src="https://user-images.githubusercontent.com/124244361/232020388-7d9ef5db-120e-458d-892f-a7fe70bcf9c8.png">
<img width="939" alt="image" src="https://user-images.githubusercontent.com/124244361/232022496-facddac1-b84d-4dc0-b36f-c64630d12b67.png">


- [x] 41. Are we adding the dropdown icon for completed stages?
<img width="956" alt="image" src="https://user-images.githubusercontent.com/124244361/232020676-fda80c5b-5205-472d-8cba-8c199224e674.png">

- [x] 42. The text here doesn't seem very valuable. can you please change it to "The signed contract will be sent to Applicant once you submit." as per the design.
<img width="601" alt="image" src="https://user-images.githubusercontent.com/124244361/232022227-a66efacb-8530-4430-91e3-c197d7ccbd03.png">

- [x] 43. From the item 21 above 
<img width="896" alt="image" src="https://user-images.githubusercontent.com/124244361/232025386-372a7595-e158-4e11-bfd2-bad770d8177c.png">

- [x] 44. I missed this earlier but i think we should say Upload instead of submit when the Applicant is submitting countersigned contract just to avoid minor confusion that it would get submitted. Because there's a submit button after uploading this doc.
Also, we don't need the text "The signed contract will be uploaded once you submit" here. 
<img width="843" alt="image" src="https://user-images.githubusercontent.com/124244361/232025974-126689f2-31f5-47f6-b027-0b6e7ac6cb64.png">

- [x] 45. Should we restrict Reupload contract by applicant after they have submitted?
<img width="975" alt="image" src="https://user-images.githubusercontent.com/124244361/232026579-32798881-5377-4e5a-80ba-eb89faacba0b.png">

- [x] 46. Can we please update this sentence - it should be "Contractor documents have been approved. You can  receive invoices from applicant now." Basically remove the word 'start'. It shows up when Staff approves the contractor documents.
<img width="608" alt="image" src="https://user-images.githubusercontent.com/124244361/232028230-19bd8b91-2145-4ae1-b986-150b51e6458f.png">

- [ ] 47. We need an update status button when Staff is reviewing invoice. We can remove Delete button from here in case we need to make space since that is less likely to be used. When removing from here, we can place it on the next page with save, [like this](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=1108-1514&t=5mcSoqUkT0uFrgOC-4). 
Another reason why we should do this is because the 'main action' for Staff in this case is not clear if we don't do that.
<img width="949" alt="image" src="https://user-images.githubusercontent.com/124244361/232029701-b4e64fbc-f263-4073-a030-c927fa02c65a.png">
Note: in this case, the `Add invoice` button styling will have to change to make it look like a secondary action.

- [x] 48. We need update status for Finance also.
<img width="940" alt="image" src="https://user-images.githubusercontent.com/124244361/232038446-548ab174-8715-47df-8a99-2c46130a39d6.png">

**Comment by sandeepsajan0** [comment]
> 32. This is showing twice - maybe in the Parallel approval case?

It is showing twice because in wagtail admin, approvers are added twice.
<img width="1254" alt="image" src="https://user-images.githubusercontent.com/23638629/232372137-fa256ccd-7d5f-4ccb-b959-80ac09ee9cd7.png">

>33. Can we please open documents in a new tab for the ones that open directly

All documents are already getting opened in a new tab(we have used target="_blank") but it depends on the browser and its settings as well. I tried it locally and also on the test site, and it seems to be working fine. Can you please share the link of the project that is having issues regarding this.
> 36. Right after Abhishek Finance approved the PAF, i think we should hide the Update status button? Since it's not applicable anymore.

I think it is happening because it is added twice in wagtail so it also requires action twice here. I tried it locally, the button is hidden just after the action. It seems to be working fine.
>37. After requesting for changes as a VP, the interface started showing the resubmit option which is for the staff actually.

Hmm, technically VP also have staff permissions. We need to discuss it because staff and staff+approver both have staff permissions. We can deal with it but the point is, do we want to deal with it.

> 39. In parallel case, when Abhishek staff resubmitted the project documents after making changes. everyone again received the emails. i think it makes sense to send it to the ones who requested changes only? because those who approved don't need it and neither the people who haven't reviewed it yet. And then the people who have approved it earlier shouldn't see update status for the project.

Not everyone, only those who haven't approved it yet. We decided it because in parallel flow, anyone can look into or approve/reject project so when someone rejects it other will not be able to look into it(hidden from their dashboard), so we need to inform them that it has been added to your dashboard and you have to look into this project and take actions...  so that they can't say I got the mail but couldn't find it in my dashboard or there was no action required when I checked it via mail.

>45. Should we restrict Reupload contract by applicant after they have submitted?

The applicant might need to reupload the contract in case of any corrections/amendments(manual/mutual back & forth b/w staff, contracting, and applicant), I think we discussed that?


@abhiXII Seems like parallel workflow issues are due to admin configurations. I have fixed the other issues and comments on a few to clarify things. 
I am working on 47 and 48, I have added the button [here in the PR](https://github.com/HyphaApp/hypha/pull/3357) but it requires some restructuring to make it functional. So, it'll take a bit of time(I am looking for new approach or any other solution for this).

**Comment by abhiXII** [comment]
- [ ]  49. Can we please fix 11(reported earlier) also? 
- [x] 50. Can we please fix the vertical spacing between the text ([reference](https://www.figma.com/file/cmrfUklaIibgEYRFUIifuE/Hypha-designs?node-id=247-3851&t=Ash7hYVFa5YgQu09-4))
<img width="771" alt="image" src="https://user-images.githubusercontent.com/124244361/234368003-a6ff175e-1ee0-4bd7-8944-28f4e78eedee.png">

- [x] 51. Right after requesting for changes for Test round 3 project as Abhishek Finance, it started showing forbidden perhaps because project is not accessible by the user anymore https://test-apply.hypha.app/apply/projects/41/
<img width="1512" alt="image" src="https://user-images.githubusercontent.com/124244361/234370299-70040899-d7dc-4bd3-8f9a-89f61bce6066.png">

- [x] 52. this should be `Countersign` 
<img width="536" alt="image" src="https://user-images.githubusercontent.com/124244361/234371826-bbb0bebe-e286-4ba9-88d2-518eebffa030.png">

- [x] 53. I think we missed adding a next step box for Finance during the invoice stage. 
<img width="1307" alt="image" src="https://user-images.githubusercontent.com/124244361/234374093-128694c7-81ed-4c42-a834-4aece46c12b4.png">
should we keep it the same as staff? like this?
<img width="944" alt="image" src="https://user-images.githubusercontent.com/124244361/234374180-37eab2ca-050a-4b2b-9346-d00ca9894fac.png">

all else is good! 💯

**Comment by sandeepsajan0** [comment]
>49. Can we please fix 11(reported earlier) also?

This is configured from the Wagtail admin, maybe we have used the h1 tag for the "Scope of Work" text in wagtail admin field. You may also check it in Projects -> SOW forms
>50. Can we please fix the vertical spacing between the text 

I think it was fine in the [previous testing](https://github.com/HyphaApp/hypha/issues/3331#issuecomment-1508400927), right? Looks like it got overridden via PR #3365. I'll fix it.

>51. ...

I think I missed this case because after rejection project goes back to the committed state and the finance users don't have access to the project in committed state. It is kind of visibility issue that we will work on but for now I'll fix this for the PAF Approvers only.

@abhiXII I'll try to fix all of these in the same PR asap. Regarding 11 you may try to change it from admin.

**Comment by sandeepsajan0** [comment]
We have finished with all these changes and now we are moving with https://github.com/HyphaApp/hypha/issues/3387. @abhiXII can we close this issue?
