### ISSUE TITLE
Submit for approval button shouldn't show to Staff when it's already in approval

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3332]

**Comment by sandeepsajan0** [comment]
Is it there for projects with `waiting for approval` status? It shouldn't be there because we are showing `View/Update PAF Approvers` button at the same place. Can you please share the scenario?

**Comment by abhiXII** [comment]
@sandeepsajan0 i think i go it wrong that's why i deleted the issue. let me close it.
