### ISSUE TITLE
Update invoice related actions for Staff

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3336]
We need to update invoice related actions as a part of this project also:

![Image](https://user-images.githubusercontent.com/124244361/229836309-06a0eeed-db62-4675-9b56-441e9a521274.png)

it should be like this:

![Image](https://user-images.githubusercontent.com/124244361/229836462-e44c6858-ea0b-4208-97d8-dedb9ba4ff62.png)

**Comment by sandeepsajan0** [comment]
@abhiXII Staff can't delete the invoice?

**Comment by frjo** [comment]
I recommend we use `permission_required` decorator to check the role permissions for delete actions.

This is how it is done to check if someone has permission to delete submissions.

https://github.com/HyphaApp/hypha/blob/dde2ed4fa75af2598f62544f46924428065828b2/hypha/apply/funds/views.py#L1436-L1450

**Comment by sandeepsajan0** [comment]
I think it is already fixed and deployed.
