### ISSUE TITLE
Display average total score in the Reviews & assignee's box

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3340]
**Is your feature request related to an existing functionality? Please describe.**

On the Submission Details page, add Average Total Score (displaying the average of all total review scores) to the Reviews & assignee's box.

**Priority**

- Low priority

**Affected roles**

- Staff
- Admin
- Reviewers

**Comment by fourthletter** [comment]
Looks great!

![image](https://user-images.githubusercontent.com/20019656/234937609-57a7162d-6fcd-43fe-9970-00e8d46c4e53.png)
