### ISSUE TITLE
[Bug] You do not have permission to create that determination 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3342]
### Description

Users are getting this error message when they're sending out determinations. 

![Screenshot 2023-03-20 1 17 33 PM (1)](https://user-images.githubusercontent.com/20019656/230626855-fd691f88-0bdf-48ea-a033-2cc1dc9dbffa.png)

**Comment by frjo** [comment]
I think it is this code:

https://github.com/HyphaApp/hypha/blob/a77349a073eeeac06d7c2cc2398e9078af68e40c/hypha/apply/determinations/permissions.py#L13-L17

**Comment by frjo** [comment]
@fourthletter Is it so staff can not post determinations at all? Or does the bug only show up for some submission and/or some users?

**Comment by fourthletter** [comment]
@frjo Staff could post determinations according to the mail log. In other words, it appears as if messages are eventually sent from Hypha. They receive this error message occasionally, not every time someone sends out a determination. This is occurring across multiple Funds (ie IFF and other Funds)

**Comment by frjo** [comment]
@fourthletter So the determination is always posted in order but then they get this error?

**Comment by fourthletter** [comment]
@frjo 

A PM sends out three determinations from a single Fund. According to the mail log every determination was sent. One of the applicants reported they did NOT receive the message, but the other two received the determination. The PM received this error message when they sent out this determination.  This PM is the 'Lead' of this Fund. I thought this was a one off bug. 

A second PM reported they received a similar message when they sent out a determination from a different fund. This person was not the 'Lead' of that Fund.

I will be at the Tuesday maintainers' call next week and can discuss with you directly.
