### ISSUE TITLE
Automatically save text input in review forms

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3359]
### Description

Automatically save text input in review forms. As a user I would like to have my text saved when I am drafting a review (review form) and determination (determination form). 

### Proposed Solution/MVP

Text will be saved automatically for logged in users on local storage on the browser.

### Long-term 

Draft will save on the server automatically. The challenge is when there are two browsers open for users to enter information.

**Comment by frjo** [comment]
If we implement this we can as easily do it for all stream field forms in one go.

**Comment by theskumar** [comment]
Saving in the browser local storage with rich text field and tinymce looks bit tricky. If in long we are looking to just using the 'draft' feature. My current proposal would be to save the application on server as draft after a regular interval. Essentially, triggering a async/background task to save the form, as if the "Save Draft" button was clicked. 

For two browser issue, we'll need to add some checks to prevent overwriting the draft if a newer version of the draft is already in the database.

**Comment by frjo** [comment]
We have instead added an alert if you try to leave review form with unsaved changes.
