### ISSUE TITLE
Set margin-block for p-tags, Tailwind resets margins to 0

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3364]
### Description

Paragraph/line break not working in comments box on Comms tab

**Comment by frjo** [comment]
Can you point to an example? Can not replicate this in my setup.

**Comment by fourthletter** [comment]
This is what I type into the comment, but the rendering does not show line breaks. It is difficult to communicate with applicants when we can't write in easy to read paragraphs.

![image](https://user-images.githubusercontent.com/20019656/233778266-d49bcfe3-89a3-43ee-a1cf-8eafadd3969b.png)

**Comment by frjo** [comment]
Your issue is that the margins between p-tags are not the same in the editor and in the preview.

This is an TailWind issue, it resets margins on many elements to 0 so each site can customise it.

We missed that Hypa does not set any margins for p-tag, easy fix.
