### ISSUE TITLE
Inactive accounts receive email notifications from Hypha

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3372]
### Description 

Individuals in the staff user group will receive emails even through they NO longer have active user accounts on Hypha.

### Proposed Solution

Only active staff user group should receive notifications 

Example of email notification sent to an inactive user account on Hypha:

---------- Forwarded message ---------
From: <[test@hypha.app](mailto:test@hypha.app)>
Date: Tue, Apr 25, 2023 at 8:43 PM
Subject: [Hypha] Contract Documents required approval for the project: Test round 3
To: 

A Project's contract is awaiting your review.

Title: Test round 3
Link: https://test-apply.hypha.app/apply/projects/41/

Please contact Abhishek Staff - abhishek+staff@superbloom.design if you have any questions.

Kind Regards,
The Hypha Team

--
Hypha Test App
https://test.hypha.app/

**Comment by frjo** [comment]
I have created a PR that I think solves this. Will deploy to test when all tests clear.

**Comment by fourthletter** [comment]
Inactive accounts are still receiving emails.

**Comment by frjo** [comment]
Can you give us some examples of the e-mails they get? The subject line and, even better, part of the body.

Hypha sends a lot of them so some examples makes it easier to track down.

**Comment by fourthletter** [comment]
Here is an example

`------- Forwarded Message -------
From: [test@hypha.app](mailto:test@hypha.app) <[test@hypha.app](mailto:test@hypha.app)>
Date: On Thursday, May 18th, 2023 at 5:46 PM
Subject: [Hypha] Project documents are ready to be assigned for approval: Approver workflow update test 2
To: 


>

> Project documents are ready to be assigned for approval.
>

> Title: Approver workflow update test 2
> Link: https://test-apply.hypha.app/apply/projects/45/approval/
> Original Submission: https://test-apply.hypha.app/apply/submissions/615/simplified/
>

> Please contact Abhishek Staff - abhishek+staff@superbloom.design if you have any questions.
>

> Kind Regards,
> The Hypha Team
>

> --
> Hypha Test App
> https://test.hypha.app/`

**Comment by frjo** [comment]
This is form new code that is only on test yet. This function needs to check that the users retrieved are active.

https://github.com/HyphaApp/hypha/blob/84dc72ff9ebc321aec69172189f7e0c05cc84289/hypha/apply/activity/adapters/utils.py#L87-L103


I will close this issue and open a new to fix this.
