### ISSUE TITLE
Contract and Project document categories, replace "Recommended minimum" with checkbox

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3375]
There is no longer a requirement to have the option to require more than one file for each category. Therefor we can replace the "Recommended minimum" (int 0-n) with a checkbox named "Required".

When a category is required (checkbox is checked):

* One file is required
* The category is listed on the project detail pages with a red asterisk*

At all times (category is required or not):

* Only one uploaded file per category is possible.
* All categories are listed on the project detail page. Each with their own upload button.
* When a file is uploaded only a view button shows.
* If user want to replace a file they need to first delete the current file and then upload a new one.

**Comment by fourthletter** [comment]
Image: Check box for required documents

![image](https://github.com/HyphaApp/hypha/assets/20019656/3c8065b7-98a2-4827-8e8a-027cc872dd1e)
