### ISSUE TITLE
Filters are showing multiple items in the pick list

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3376]
When I click on the filters, the pick list shows multiple items and are stuck on these items

![image](https://user-images.githubusercontent.com/20019656/234935384-12a8a66d-a9e5-44aa-8961-b857fccabe09.png)

**Comment by frjo** [comment]
Do you see this on test or live? I can not replicate it on either. Maybe clear the cache on your browser?

**Comment by fourthletter** [comment]
@frjo this is on Hypha test.

**Comment by fourthletter** [comment]
Issue also appears on Saurabh's local.

**Comment by fourthletter** [comment]
I think this has been resolved.
