### ISSUE TITLE
Make it clear who sees an archived submission

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3388]
### Description

As a user I would need to know who gets to see that this submission has been archived. Other submissions have 'team' or 'applicant' with an eye icon.

![image](https://user-images.githubusercontent.com/20019656/235772941-b1b7e23c-1d28-4945-9826-c8e423952fcb.png)

**Comment by frjo** [comment]
The icons indicates who can see the messages, it does not related to the content of the message. Mostly relevant for comments.

We use the same templates for activity and comments so some activities get the icons to. I do not think we really need them there, see no purpose.

Showing who can see archived submissions should be solved somewhere else.

Currently there are three option for who can see archived submissions. By default, no one can see them. Each organisation can make setting that make them available to "Staff admin" and/or "Staff" user roles.

Maybe we can add some text to the red banner?

**Comment by frjo** [comment]
I have created a bigger issue with improvements to the archive feature, if it covers your issue you can close this one.

https://github.com/HyphaApp/hypha/issues/3389

**Comment by wes-otf** [comment]
@frjo what permissions do I need to set to recreate this in my local dev environment? I went through the process of:

1. Set my superuser group to Staff & Staff Admin
2. Setting up a new round & fund
3. Created another account as an applicant and applied for said fund
4. Back on my superuser account, archived the submission

I was then redirected to the dashboard, and when attempting to select the fund I get a "403 Forbidden" screen. Did I miss a step?

**Comment by frjo** [comment]
By default only superadmins can see archived submissions. See these settings to change that.

~~~~
# Provide permissions for Archived submissions
SUBMISSIONS_ARCHIVED_ACCESS_STAFF = env.bool("SUBMISSIONS_ARCHIVED_ACCESS_STAFF", False)
SUBMISSIONS_ARCHIVED_ACCESS_STAFF_ADMIN = env.bool(
    "SUBMISSIONS_ARCHIVED_ACCESS_STAFF_ADMIN", False
)
~~~~

Other user roles should never see archived submissions.
