### ISSUE TITLE
403 server error when uploading an image to Wagtail

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3396]
### Description

403 server error when uploading an image to Wagtail

![image](https://user-images.githubusercontent.com/20019656/236872253-ba280ebd-3944-4325-80f9-b5d8810f762f.png)

**Comment by frjo** [comment]
@fourthletter  Does this always happens and for all images?

**Comment by fourthletter** [comment]
@frjo This started last week. I am able to upload documents and images on test,  but not on OTF's live site. 

Live site:
![Screenshot 2023-05-10 11 55 57 AM](https://github.com/HyphaApp/hypha/assets/20019656/6f9c2b0e-2886-4796-9372-1966421e51d4)


Test site:
![Screenshot 2023-05-10 11 55 52 AM](https://github.com/HyphaApp/hypha/assets/20019656/c9a2e4f7-ab31-47f5-ab62-5e340326295f)

**Comment by frjo** [comment]
I tested to upload an image on OTF live just now and got no errors. Does the issue persist for you?

**Comment by fourthletter** [comment]
We are still experiencing this issue on OTF live. I will share a recording with you on Slack.

**Comment by frjo** [comment]
@fourthletter Was this resolved or still an issue?

**Comment by fourthletter** [comment]
@frjo this is still an issue. However, we will be unlikely to use this functionality once we move to the new website.

**Comment by fourthletter** [comment]
@frjo  Sharing my browser's dev console to help pin down the issue:

![Screenshot 2023-07-10 at 9 39 02 AM](https://github.com/HyphaApp/hypha/assets/20019656/748db6ed-db31-4aef-a95f-72b54505ff67)
