### ISSUE TITLE
Remove Wagtail admin menu from Hypha pages

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3397]
We want ot improve Hypha accessibility any way we can. But showing the errors to users, who can do nothing about them, is not helpful I think.

Maybe only show them to superadmins?

**Comment by theskumar** [comment]
Is the only with the accessibility link or we want to remove the complete userbar.
​  
​Unless we want to utilize is comprehensively, I don't see it been utilized. In the essence of keep things simple we can consider removing it altogether, thoughts? @frjo @fourthletter

Docs related to the userbar: https://docs.wagtail.org/en/stable/topics/writing_templates.html#wagtail-user-bar

Doc specific to the accessibility link: https://docs.wagtail.org/en/stable/releases/4.2.html#configuration-of-the-accessibility-checker-user-bar-item

**Comment by frjo** [comment]
Changed the title of the issue. I think we should hide the Wagtail menu all together.

**Comment by theskumar** [comment]
Alright, I've submitted a PR to remove it.
