### ISSUE TITLE
Add link for dashboard/log in after application submission

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3410]
**Is your feature request related to an existing functionality? Please describe.**

After submitting an application, the user should be presented with appropriate options based on their authentication status. If the user is logged in, a link should be provided to return to the dashboard. However, if the user is not logged in, they should be presented with a link to the login page. 

**Priority**

- Low priority 

**Affected roles**

- Staff
- Applicants
- Reviewers

**Comment by frjo** [comment]
@fourthletter After a person have submitted an new application they are sent to the "Thank you for your submission…" page. This issue is about adding some buttons to that page. IF they are not logged in they get a "Log in" button and if they are logged in they get a "Go to my dashboard." button.

**Comment by fourthletter** [comment]
@frjo Thank you!
