### ISSUE TITLE
Permit a user to set email preferences

### ISSUE THREAD

**Issue by gmurtaza00** [HyphaApp/hypha#3413]
**Is your feature request related to an existing functionality? Please describe.**

During the account creation process, permit a user to specify if they want to receive Hypha emails.

**Describe the solution you'd like**

 Under the Full name fields, display a checked checkbox and the language "Yes, I'd like to receive occasional emails from Hypha about their mission and programs." The user can uncheck the checkbox to opt out of receiving future emails.

**Priority**

- Low priority 

**Affected roles**

- Staff
- Applicants
- Reviewers

**Comment by frjo** [comment]
This sounds like a newsletter and that is outside the scope for Hypha in my opinion.

**Comment by gmurtaza00** [comment]
> This sounds like a newsletter and that is outside the scope for Hypha in my opinion.

Got it.
