### ISSUE TITLE
Add Secondary Reviewer notification via Hypha Slack

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3421]
### Description

Hubot, a Hypha slack integration, currently notifies users of activities on Hypha. This current integration does not include notifying secondary reviewers. 

### Proposed Enhancement

Hubot notifies primary reviewers when a secondary review has been submitted

### Related Issue

https://github.com/HyphaApp/hypha/pull/2867

**Comment by sandeepsajan0** [comment]
@fourthletter  There are two possibilities/options for a secondary reviewer.
1. Add a separate review similar to the primary reviewer.
2. Add an opinion(agree/disagree) to the primary reviewer's review.

So, for which action do we want to notify the primary reviewer?

**Comment by frjo** [comment]
@fourthletter We already send out a notification for new reviews tagged with the leads slack name.

Is it a good solution to add the slack names of the assigned staff reviewers to that notification? Then all of them get to know when new reviews/opinions are added.

**Comment by fourthletter** [comment]
> @fourthletter There are two possibilities/options for a secondary reviewer.
> 
> 1. Add a separate review similar to the primary reviewer.
> 2. Add an opinion(agree/disagree) to the primary reviewer's review.
> 
> So, for which action do we want to notify the primary reviewer?

Hello @sandeepsajan0 

Slack pings the **lead**  when both reviews have assignees (someone has signed up), and when reviews have been submitted. Notifications includes secondary reviewer adding an opinion(agree/disagree) to the primary reviewer's review and every time a review has been submitted. 

Slack should also ping the **secondary reviewer**  when the primary reviewer submits their review. 2nd reviewer has been waiting for 1st reviewer to submit their review so they could agree/disagree.


> @fourthletter We already send out a notification for new reviews tagged with the leads slack name.
> 
> Is it a good solution to add the slack names of the assigned staff reviewers to that notification? Then all of them get to know when new reviews/opinions are added.

@frjo Thanks for catching this, the 'lead' should also be notified of all activities associated with the submission.

**Comment by frjo** [comment]
@fourthletter What does "similar to the primary reviewer" exactly mean?

I now understand why the second reviewer need a notification, they are waiting for their turn.

But why do the first reviewer need to know? What action do the take after this notification?

**Comment by fourthletter** [comment]
> @fourthletter What does "similar to the primary reviewer" exactly mean?
> 
> I now understand why the second reviewer need a notification, they are waiting for their turn.
> 
> But why do the first reviewer need to know? What action do the take after this notification?

@frjo You're right. The primary reviewer does not need a notification.
