### ISSUE TITLE
Add nav-bar to Apply 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3427]
### Description

A nav-bar will need to be added to the apply page to align with the organization's website, including typology like font and color. As a user, I would need to be rerouted to a webpage on the main website. For example, clicking on 'Fund' would lead to the correct webpage.

### Current nav-bar
![Screenshot 2023-06-02 8 31 38 PM](https://github.com/HyphaApp/hypha/assets/20019656/1548d5fb-1dcf-42c9-a4dc-7c79ae8e5dd9)

### PROPOSED nav-bar
![Screenshot 2023-06-02 8 32 33 PM](https://github.com/HyphaApp/hypha/assets/20019656/91c377e7-c196-4274-be0f-67b1b9b08941)

**Comment by frjo** [comment]
This menu will be completely removed since it is part of the public site. Same thing with the footer.

The logo can continue to link back to https://www.opentech.fund/.

The https://apply.opentech.fund/ site will just be Hypha i.e. and app to handle submission etc.

**Comment by theskumar** [comment]
The open PR to remove the nav bar is at #3432 , and it was decided not to transfer the nav from the org's website should/would not be translated 1:1 to one to hypha. 

This issue should be safe to close and open a new PR, if any further improvement is needed in the primary nav for public facing login/register pages.

**Comment by wes-otf** [comment]
This issue will be partially completed by #3604 but I think it'd be beneficial to keep it around as the HTML nav template still needs to be created based off the WordPress nav theme and entered via wagtail admin.
