### ISSUE TITLE
comment visibility for applicant and partner user groups

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3436]
### Description

When staff writes a comment to someone with both 'applicant' and 'partner' user roles, this person cannot view communication/comments when these messages are only directed to 'applicant'. Does the staff need to select 'applicant' or 'partner'? Or could the individual with both applicant and partner roles receive comments to ONLY applicants?

**Comment by frjo** [comment]
Solving this in https://github.com/HyphaApp/hypha/issues/3486
