### ISSUE TITLE
Login Page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3444]
### Description

Add url to registration page if individual on login page has never registered on the platform

- [ ] add question 'reset or create password' to login page
- [ ] add question: "If you have never registration and wish to apply" - reroute applicant to registration page
- [ ] Funding organization could add instructions for login and 2FA guidance to this page

![Screenshot 2023-06-15 12 33 49 PM](https://github.com/HyphaApp/hypha/assets/20019656/bf5117c9-5911-41a7-a82c-1e9db79d6972)

**Comment by frjo** [comment]
The plan is to merge the login and registration forms. Users just enter their e-mail address and Hypha creates accounts as needed (if that feature is active).

Organisations can already add any text they like to the login form.

Do not understand the "reset or create password" question. Does not "Forget your password" link takes care of that.
