### ISSUE TITLE
Docs tell user to install missing debian package

### ISSUE THREAD

**Issue by ghost** [HyphaApp/hypha#3446]
The docs at https://github.com/HyphaApp/hypha/blob/main/docs/setup/deployment/stand-alone.md reference `postgresql-server-dev-12` but this package is not installable from the standard repos of any currently available version of Debian.  Perhaps the recent Debian release shuffled it out of the repos.

**To Reproduce**
Search for `postgresql-server-dev-12` on `https://packages.debian.org`:

```
You have searched for packages that names contain postgresql-server-dev-12 in all suites, all sections, and all architectures.

Sorry, your search gave no results
```
See https://packages.debian.org/search?keywords=postgresql-server-dev-12&searchon=names&suite=all&section=all

Alternatively, try to find it in apt or install it.  You'll get an error message: "No packages found"

**Expected behavior**

When the documentation instructs me to install a debian package, I expect it to be in the standard repos or to be told what PPA to pull it from.

**Priority**

- High (keeping you from completing day-to-day tasks)

I'm not sure if one cannot complete the install without this package, but I assume not, so I think this bug is fairly high priority, as new users will block on it.

**Affected roles**

- Staff (technical staff installing hypha)
- Developers

**Screenshots**

**Additional context**

Hypha tells users to install an old version of postgres.  At some point, more postgres-related Debian packages might stop being available.  At some point, should hypha consider documenting installation using a more recent version of postgres?

Also, I haven't checked the docker scripts, but I wonder if they might also fail on the same point.

**Comment by frjo** [comment]
These docs were written for Ubuntu 18.04LTS, we really need to update them.
