### ISSUE TITLE
Suggestions from the project's user testing

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3448]
**Part-1(miro board cards)**:
- [x] PAF waiting for approval table shouldn't show if no project in any tab.
- [x] Show requested by as well in PAF Approvals(sidebar). Right now only Pending and Approved are showing.
- [x] Remove the converted option from the invoice.
- [x] Show activities on the Invoice page.
- [x] Show price in US format.
- [x] Downloaded PAF add dates along with approver names, sync it with platform.
- [x] "Add Invoice' as next step even after invoice creation(remove next step after one invoice).
- [x] Add hyperlinks to comments and use those links for scrolling(request change comments)

**Part-2(figma design changes)**
- [x] #3458
- [x] #3462 
- [x] #3467
- [x] #3469
- [x] Update invoice table column name on project detail page, "Submitted" to "Date Submitted".
- [x] Update "Reporting" section header to "Reports".
- [x] Change Upload Contract modal "submit" button text to "Upload" for Applicant.
- [x] Update Next step text for "Awaiting Contract approval from Staff" to ".... approval by org_short_name"(for applicant role).
- [x] In "Submit for Approval" or "Resubmit" PAF modal, make optional line bold and update the text as per design.
- [x] "Invoice Uploaded" to "Invoice added" in alert/success message text on invoice creation.
- [x] "Create Invoice" to "Add invoice" on invoice form heading.
- [x] Update next step for applicant during PAF approval process, set it to a single/fix text.(see design for text)
- [x] Update Admin bar's "Download" button text fot PAF and SOW to "Download PAF" and "Download SOW".
- [x] Update PAF edit page submit button text to Save.
- [x] Update "Invoice created" to "Invoice added" in activities.
- [x] "View <related_object>" in activity feed instead of just <related_object>. Ex: Contract -> View Contract
- [x] "Edit" and "Delete" to "Edit Invoice" and "Delete Invoice" on the Invoice detail page.
- [x] Update applicant to vendor at every place in projects.
- [x] #3474
- [x] #3479
- [x] #3477
- [x] Update Approval section of PAF detailed page/pdf. Show as per PAF approvals sidebar section(include pending and request changes).
- [x] #3480
- [x] #3494
- [x] #3495
- [ ] - [ ] Make comment required if a user selects request_changes on updating paf status.

**Comment by frjo** [comment]
We can not hardcode US formatting of currency values in Hypha. There must be a setting for it.

We already have `CURRENCY_SYMBOL` in place.

I found this article: https://stackabuse.com/format-number-as-currency-string-in-python/

@theskumar Do you have suggestion here?

Personally I think formatting number according to browser locale makes the most sense. But if OTF do not want that we at least must make it configurable on a global level so each implementer can decide for themself.

We already use Babel in other places so this looks neat.

~~~~
import babel.numbers
number_string = 340020.8
babel.numbers.format_currency(number_string, "USD", locale='en_US')
~~~~

outputs: `$340,020.80`

If we have settings `CURRENCY_CODE` (replacing `CURRENCY_SYMBOL `) and `LOCALE`.

We also have setting `LANGUAGE_CODE` and an implementation here:

https://github.com/HyphaApp/hypha/blob/8c7ef98b265456c149af7ececfb537349ba223f8/hypha/apply/projects/forms/vendor.py#L84-L101

**Comment by theskumar** [comment]
> Personally I think formatting number according to browser locale makes the most sense. But if OTF do not want that we at least must make it configurable on a global level so each implementer can decide for themself.

This works great for translations and timezone based conversion. But if we are talking about $$, then forex and currency conversion need to be considered, so it's best we don't do any conversion. 

Setting allowed currency make sense at a global level, but I would suggest storing the anything related to money with the number + unit together. 

See and implementation here https://github.com/django-money/django-money

**Comment by frjo** [comment]
Definitely no currency conversion. The issue should only be about how to format numbers.

```
ISO:   $340 020,80
US:    $340,020.80
Other: $340.020,80
```
OTF want to lock it down to the US version. I want to at least add a setting for it, it can default to US.

The best option in my opinion is to check browser locale and format the number the way the user is used to.

**Comment by frjo** [comment]
Part 1 is on test now (in a few minuts from writing this).

**Comment by fourthletter** [comment]
@sandeepsajan0 Thank you for putting this list together. Do you need design support for any of the above items?

**Comment by sandeepsajan0** [comment]
@fourthletter No we don't need design support, we already have the design for these items. In fact, these are picked from figma itself. We just need to make sure these are all and there are no other suggestions left. I'll recheck it after finishing this list.
