### ISSUE TITLE
No access to submissions with multiple roles

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3449]
### Description

A user with an applicant, partner, and reviewer user roles is unable to access submissions when these submissions are in the 'external reviewer' stage. A majority of user have different user accounts on the platform. In certain edge cases a user account is used for multiple roles.

### Related 
https://github.com/HyphaApp/hypha/issues/3487

**Comment by frjo** [comment]
@fourthletter  Is the user the applicant of this particular application?

**Comment by fourthletter** [comment]
The user is not the applicant of this particular application.

**Comment by frjo** [comment]
I can not replicate this.

Can it be that the reviewer is not assigned to the submission and you have made settings so they then can not see it?

**Comment by fourthletter** [comment]
Thank you for looking into this. I could discuss more during our next stand up.

**Comment by fourthletter** [comment]
A user account that is both an 'applicant' and 'reviewer' cannot access submissions as a reviewer and does not appear in the reviewer pick list.

**Comment by fourthletter** [comment]
On September 21 we discussed revising the Reviewer User Group to prevent this role from submitting an application on Hypha.
