### ISSUE TITLE
If Docker isn't for prod, docs should say so

### ISSUE THREAD

**Issue by jvasile** [HyphaApp/hypha#3452]
I am told that in a recent hypha maintainer's call somebody new to hypha was advised not to use hypha's docker container in production.  If that is indeed the prevailing wisdom, we might want to note that at https://docs.hypha.app/setup/deployment/docker/

Perhaps the following text:

```
Docker is a good way to explore hypha, but we do not currently recommend these docker instructions for production use.
```

I'm happy to submit a PR if desired.

**Comment by frjo** [comment]
Thanks, A PR would be welcomed. The docs have a number of shortcomings as you no doubt have noticed.

**Comment by jvasile** [comment]
Will do.  I'm test-driving docs in prep for onboarding a new dev, so hopefully we'll get some improvements out of this process!
