### ISSUE TITLE
Update "Approved by staff" status for invoice to "Approved by Lead" if approver(user) is lead. Add status history section to invoice detail page

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3474]
1. When the invoice approver is the project lead, show 'Approved by Lead' instead of 'Approved by staff'.
<img width="687" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/e4711ab1-94ac-49d1-935b-fc9794ab8f24">

2. On the invoice detail page, add a status history section and show the status there with hidden history(arrow up/down).
<img width="687" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/29e316dc-464c-4bee-93fe-4f1245183b47">

<img width="687" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/3dd5a750-25a4-47b0-90f2-1f19315f5fd7">

**Comment by sandeepsajan0** [comment]
@abhiXII Do we want to show the status history section to Vendor/Applicant as well? Or is it just for staff and finance?

**Comment by fourthletter** [comment]
As discussed on July 13, we have decided to show individual names and not 'lead' next to these names because of the  extensive hard coding required.
