### ISSUE TITLE
Rebuild the comment visible to functionality

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3486]
Remove the "Visible to" functionality for applicants, partners and reviewers. Only staff (staff + finance + contracting) need to have these options.

- [ ] When an applicant post a comment it should be visible to the applicant themself, any partners and to staff.
- [ ] When an partner post a comment it should be visible to the applicant themself, any partners and to staff.
- [ ] When a reviewer post a comment it should be visible to the reviewers and to staff.
- [ ] Remove the partner option from "Visible to". Partners should see the same comments as the applicant themself.
- [ ] The staff default for "Visible to" should be that only "staff" are checked.
- [ ] The "reviewer" and "applicant" checkbox is left empty be default for staff.
- [ ] No other options but the three above are needed for "Visible to".

**Comment by fourthletter** [comment]
> * [ ]  When a reviewer post a comment it should be visible to the reviewers and to staff.

Could we clarify this? Does this mean the comment is visible to the entire reviewer user group?

> * [ ]  The staff default for "Visible to" should be that "applicant" and "staff" are checked. This means that partners will see the comment as well since they should see the same things as the applicant.

Staff's default now is 'staff' only. I think we should keep it this way because staff are more likely to keep internal notes than to communicate with applicants via the comment section within Hypha. A majority of correspondence with applicants is through 'determinations'

**Comment by frjo** [comment]
@fourthletter  This is now on test. Staff default is set to "Staf only" as per your comment above.

Regarding reviewers, yes that included all reviewers that have access to the submission. This is how it always have worked.
