### ISSUE TITLE
Give the partner role the exact same permissions and same things as applicant role

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3487]
The partner role is used to add additional applicants, co applicants, to a submission. Partners should in every instance have the exact same permissions and see the same things as the applicant. In most instances this should already be implemented. This issue is to make sure Hypha is consistent.

The permissions for partners regarding comments are fixed in a separate issue: #3486

- [ ] Make sure partners to an submission has the same permissions as the submission author.
- [ ] Where convenient/possible make it obvious in the code that partners of a submission has the same permissions and see the same things as applicants to a submission.

**Comment by wes-otf** [comment]
as per [#3455](https://github.com/HyphaApp/hypha/issues/3455#issuecomment-1921578385), the partner role slightly differs from applicant in OTF's usage of the role.
