### ISSUE TITLE
Add new fields to the invoice form.

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3494]
Add fields to Invoice form.
1. Invoice number.
2. Invoice amount.

<img width="385" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/c5c55fb1-c57a-4234-8ebd-470eee40b5b7">

@abhiXII We already show an automatically generated "Invoice number" in UI. Do we want to update that as well and show this new Invoice number instead of that?

<img width="582" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/cc570246-31ce-4ac6-9023-88325a2f5715">

**Comment by abhiXII** [comment]
Oh yes yes @sandeepsajan0 this won't be auto-generated after our implementation. We want to use the user-input invoice number.
