### ISSUE TITLE
Update/Hide invoice statuses on project detail page for Applicant/Vendor.(see design)

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3495]
As per design sugestions:

Invoice status for applicants/vendors should only be:

    Pending approval
    Approved (when it is approved by staff and finance)
    Declined
    Request for change or more information
    Paid
    Payment failed (new status to be added for finance when a payment goes wrong because of some errors)

These changes has to be done on project detail page.
<img width="540" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/834bb6f6-14ac-4209-bdf9-127529cca2fd">

All these statuses need to be designed over the current statuses as wrapper for applicant like APPLICANT_INVOICE_STATUS.

Payment failed is a new status, we don't have it in our current system. Do we need it throughout the system like for staff and finance as well? @fourthletter @frjo

**Comment by fourthletter** [comment]
@sandeepsajan0 (cc: @abhiXII ) We do NOT need a **Payment failed (new status to be added for finance when a payment goes wrong because of some errors)** for applicants. There are many reasons why a payment may fail so it's difficult to track internally.

**Comment by abhiXII** [comment]
@fourthletter so we'll just continue showing `Finance pending` till it's resolved?

although, we don't need to show any specific reason for Payment failed just that applicant know. But it's okay if we want to cover it under Finance pending

**Comment by fourthletter** [comment]
We could check with individuals working in Finance, but `Finance pending` makes sense for now.
