### ISSUE TITLE
Side-by-side view not responsive to all screens

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3497]
### Description

When reviewing the diff (side-by-side proposal view) or changes between revised/edited proposals, the page is not responsive to all screens. Users not using external monitors are unable to view the entire 100% side-by-side view on their laptop screens.

**Comment by frjo** [comment]
Example URL where you see this?

It does not seem to effect all submissions.

**Comment by fourthletter** [comment]
https://apply.opentech.fund/apply/submissions/14158/revisions/compare/17092/15853/

**Comment by frjo** [comment]
It depends on the content. Most submissions works fine but if there is e.g. a very long link it forces long lines and make it hard to use on small screens.

Solving it by adding "word-break: break-word;" to the diff view just as we have on the details view that forces long lines to break.

**Comment by fourthletter** [comment]
@frjo Could your fix potentially resolve  the distortion of side-by-side view when someone embeds an image into a text field? Thanks, Di
