### ISSUE TITLE
Multiple files upload field is not working properly for PAF and SOW.

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3505]

**Comment by abhiXII** [comment]
@sandeepsajan0 you mean after saving the files disappear from budget and cv upload fields right?

**Comment by sandeepsajan0** [comment]
Yes, It is happening because these are not getting saved in DB.

I found the issue, the main reason is two forms(PAF and SOW) are on the same page. Actually, 'django-file-form' pick the files via 'form_id' and 'field_id'. And it is picking the wrong form_id(sow form's id), where it doesn't find any uploaded file.
