### ISSUE TITLE
Add <ORG_NAME> in activities for applicant instead of users/staff name

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3508]
@abhiXII @fourthletter We want to update this only for Project activities or we want to generalize it for submissions as well?

<img width="457" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/d3928a32-6c78-4b47-a166-2169441cc2fe">

**Comment by frjo** [comment]
It should be the same everywhere I think.

**Comment by abhiXII** [comment]
Yeah makes sense to do it for submissions too. I hope there aren't any cases during submissions process where generalisation won't work.
