### ISSUE TITLE
Project public statuses for Applicant/Vendor

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3517]
Project public statuses

`Draft` - `Draft`
`Internal approval` - `OTF(org short name) approval`
`Contracting` - `Contracting`
`Invoicing and Reporting` - `Invoicing and reporting`
`Closing` - `Closing`
`Complete` - `Complete`

@abhiXII `Internal approval` is the only status that needs to be updated or do we have other changes as well?

**Comment by abhiXII** [comment]
@sandeepsajan0 so far I discovered change required for internal approval only. I believe we can still change if we find something in future?

**Comment by sandeepsajan0** [comment]
okay, I'll try to implement it in a way that it can be changed easily.
