### ISSUE TITLE
Remove hard coded fields from PAF

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3518]
We have a few hardcoded fields on the top of PAF. Some of them get duplicated by the wagtail form fields so decided to remove hardcoded ones.

Hardcoded fields:

- [x] 1. `Proposed start date`
- [x] 2. `Project Proposed end date`
- [x] 3. `Legal name`
- [x] 4. `E-mail`
- [x] 5. `Address`
- [x] 6. `Phone`
- [x] 7. `Value`
- [x] 8. `Sent to Compliance`

<img width="1272" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/b9a03756-a620-45fb-8005-e967e4fe3b99">

@abhiXII @frjo @fourthletter Which ones from the above list do we want to remove or just want to use from the wagtail form?

**Comment by abhiXII** [comment]
I believe we can only remove Proposed start date and Project Proposed end date?
else if want to remove all hardcoded, then I think they should be replaced by the same ones from Wagtail

**Comment by fourthletter** [comment]
On August 8 during standup we've discussed removing all hard coded fields.
