### ISSUE TITLE
Remove the option to submit an opinion to proposals

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3526]
### Description

As a user when staff 'agree' to a review they are unable to submit a written review. The staff reviewer is unable to 'agree' and submit a written review for a concept note. 

### Proposed Solution 

Staff could 'agree' with submissions in the concept note stage. However, staff (user group) should not be able to submit an opinion during the proposal stage. In OTF's instance, please disable the opinion option for proposals.

**Comment by frjo** [comment]
I think https://github.com/HyphaApp/hypha/issues/3527 is a better solution to this. Not allowing opinion on second stage submission on a particular workflow seems to me to be an edge case that will confuse most Hypha implementors.

We could add settings to each fund/lab where you can turn opinions off per stage. Default should be on in that case so not to surprise anyone.
