### ISSUE TITLE
Allow users to undo opinions

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3527]
### Description

As a user when staff 'agree' to a review they are unable to submit a written review. The staff reviewer is unable to 'agree' and submit a written review for a concept note. 

### Proposed Solution

Staff should be able to undo the opinion they have submitted

## Staff is given the option to agree or disagree with a review
![image](https://github.com/HyphaApp/hypha/assets/20019656/11b96d55-5c68-40ea-a346-2453f022f8c6)

## Staff 'agree' and could no longer submit their own written review
![image](https://github.com/HyphaApp/hypha/assets/20019656/d0d19c72-5f6a-4269-a70c-9871d2d4f772)

**Comment by frjo** [comment]
This feature makes sense to me, allowing staff to remove an opinion and instead submit a full review.

**Comment by fourthletter** [comment]
Thanks for the feedback. I think the ability to remove an opinion would be helpful for all adopters.

**Comment by fourthletter** [comment]
On August 29 we discussed adding a 'trash can' icon next to the opinion to remove the opinion
