### ISSUE TITLE
slack notifications

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3528]
### Description

Users designated as "Lead" are not tagged and notified in slack. 

Related https://github.com/HyphaApp/hypha/pull/3433

**Comment by frjo** [comment]
@fourthletter Please specify the specific notification this is happening on. Pasting in the text works, we can use that to find it in the code base.

**Comment by frjo** [comment]
Also make sure the user in question have set a slack name in the user account.

**Comment by fourthletter** [comment]
You're right. They're slack name wasn't included in their Hypha profiles.
