### ISSUE TITLE
[Staff Role] PAF table on Project Page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3536]
### Description

As a staff or program manager, I need a table to manage the entire contract and invoice approval process. Columns in the dashboard should provide information about the PAF (ie how many) are designated to a specific staff or program manager. 

Each program staff could be able to access all PAF's when they are the LEAD 

![image](https://github.com/HyphaApp/hypha/assets/20019656/319e8cb1-f165-4367-846e-864729cb12ff)

![image](https://github.com/HyphaApp/hypha/assets/20019656/008b0c0e-5b29-4bf4-b7f3-0d90520ed87c)

**Comment by sandeepsajan0** [comment]
@fourthletter It is not completed yet, It is a part of the dashboard designs.

**Comment by sandeepsajan0** [comment]
We didn't find any use case to have the PAF table explicitly on the Project page as it is already there on the dashboard. Maybe we can just close it for now and reopen it in the future if needed?

**Comment by frjo** [comment]
Yes, closing it now.
