### ISSUE TITLE
[Finance Role] Invoice Table on Project Page

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3537]
### Description

As finance I need to know the vendor name, date of when the invoice has been submitted, the period of performance, the amount on the invoice, and the invoice status (ie approved by program staff), and name of the Lead

- [ ] We will check with Finance which default sorting order do they prefer.
- [ ] Add sorting to date, Lead, and dollar amount columns, and perhaps status
- [ ] We will check with finance the purpose and need for Invoice date

Multiple select will have an update status batch action to update status to: Approve, Decline, Payment returned, Paid

![image](https://github.com/HyphaApp/hypha/assets/20019656/47d67fd0-1b5b-4f9a-a669-8fb79be9ddac)

**Comment by frjo** [comment]
@di @sandeepsajan0 I guess it is here OTF want US date format?

If that is the case I propose the following:

1. Create a list of the places where OTF need US date format (maybe only here?)
2. Create a new date format setting with a logical name. (INVOICE_SHORT_DATE_FORMAT or PROJECT_SHORT_DATE_FORMAT or something better?)
3. If the new date format setting *is not* set Hypha uses the Django date settings as now.
4. If the new date format setting *is* set Hypha uses it for the specific pages/views (see 1).
