### ISSUE TITLE
Invoice has name of approver and date stamp

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3539]
### Description

Manipulate PDF invoice submitted by vendor with the approver information and date stamp

**Comment by sandeepsajan0** [comment]
On the 7th Sept standup, we discussed that there would be performance issues with invoice manipulation and invoices batch download(zip). We will need celery or background service to use these features fluently or else bigger files(files in mbs) may create issues for other requests. 
However, we decided that we could give invoice manipulation for individual files a try and test how it would work. But for batch download(invoices zip), we can put it on hold and may try it later async or with a background service.  
cc_ @fourthletter @abhiXII

**Comment by theskumar** [comment]
@fourthletter please share the avg. sizes of the pdfs and also number of pages they have in general. Also, what is the information that needs to be added to the last page of the invoice.

**Comment by theskumar** [comment]
@frjo let me know if it fine for us to us pypdf for this? It has been actively maintained _(6k stars, updated last week)_

See: 
1. Adding annotations: https://pypdf.readthedocs.io/en/stable/user/adding-pdf-annotations.html
2. PDF streaming, reading/writing to cloud: https://pypdf.readthedocs.io/en/stable/user/streaming-data.html
3. Merging PDFs https://pypdf.readthedocs.io/en/stable/user/merging-pdfs.html

It doesn't support digital signature, and will be out of scope: 
- https://pypdf.readthedocs.io/en/stable/meta/scope-of-pypdf.html?highlight=signature#out-of-scope

**Comment by frjo** [comment]
@theskumar pypdf looks good and we already have it installed in Hypha. It is a dependency of xhtml2pdf.

**Comment by theskumar** [comment]
@Techslammer please add the pdf format and text.
