### ISSUE TITLE
Add a definition next to each user role in wagtail admin

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3541]
### Description

Add a definition next to each user role in the WagTail admin 

![image](https://github.com/HyphaApp/hypha/assets/20019656/0561aa6c-562d-4e61-808f-6a6630bd78d2)

**Comment by theskumar** [comment]
@fourthletter can you please add the text for each of the labels in the issue description please?

**Comment by fourthletter** [comment]
@wes-otf - here are definitions here. We could shorten the terms to fit on the Wagtail interface.

**Staff** view and edit all submissions, submit reviews, send determinations, and set up applications (this means creating Forms, Funds, and Rounds, and give other users (e.g. Reviewers or other Staff) access to applications/submissions.

**Staff Admin** view and edit all submissions, submit reviews, send determinations, and set up applications. Can disable 2FA, archive submissions, and other components not accessible to other roles.

**Community Reviewer** is an applicant with access to other applications for the Request with community review (peer review) workflow.

**Reviewer** has their own dashboard and can submit reviews. Advisory Council Members are typically assigned the 'Reviewer' role.

**Applicant** can access their own application and send communication in the communication/comment tab.

**Partner** could view, edit, and comment on a specific application they are assigned to.

**Contracting** could review and approve the PAF and access documents associated with contracting.

**Finance** could review and approve the PAF, access documents associated with contracting, and access invoices approved by Staff.

**Approver** is not a standalone role. This role has to be assigned in tandem with Staff, Contracting, or Finance. This role could review and approve PAF, and could access compliance documents.

**Comment by wes-otf** [comment]
@fourthletter Great! Thanks a ton.

**Comment by fourthletter** [comment]
@wes-otf - I forgot to add definitions for staff admin and community reviewer 

**Staff Admin** view and edit all submissions, submit reviews, send determinations, and set up applications. Can disable 2FA, archive submissions, and other components not accessible to other roles.

**Community Reviewer** is an applicant with access to other applications for the Request with community review (peer review) workflow.
