### ISSUE TITLE
Display a server side preview of the application form before submitting

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#3545]
_**PLEASE DO NOT INCLUDE SENSITIVE INFORMATION**_

[Use this form](https://docs.google.com/forms/d/e/1FAIpQLSdcn68IgWuk5-YyXF8ZuVK5Dxj5az6eemmLlqDsghJwEmxY6A/viewform). if you need to include the following information:
- Account name or name of person
- Account email
- Any personally identifying information
- Title of submission (app URLs alone are OK)
- When in doubt, use the above form.

**Is your feature request related to a problem? Please describe.**

Yes. The richtext allows a copy-paste of the html content and preserves the markup. After submission when the content of the richtext is displayed, html is cleaned up and only a part of the support html is display. This leads to the removal of content that might be visible in the richtext editor. 

This also allows for an applicant to check and confirm the content and prevents accidentally submitting the application form. 

**Is your feature request related to an existing functionality? Please describe.**

Submisison and display on the html content in the application form.

**Describe the solution you'd like**

- Update the application submit button to "Preview and Submit", which after clicking doesn't immediately submits the form but allows the applicant to preview the form on a new page. On the preview page, the application form should be show as it would appear to the reviewers and staff. 

**Describe alternatives you've considered**

1. Add a preview button on the rich-text that would cleanup editor html server side and render cleanup content.
2. Fix the editor display to not display the html content that is not allowed. Essentially browser based bleach.
3. Use simplified markdown based editor with lightweigth formatting.

**Additional context**

User able to page in a image in the editor
![image](https://github.com/HyphaApp/hypha/assets/236356/c8b53c78-18b9-41e9-a9a2-ab94e6671c08)

The image is not render after it's submitted, if any goes to edit the application the image is displayed again.
![image](https://github.com/HyphaApp/hypha/assets/236356/7509d5dc-6fb3-4e8e-950a-6649345bba71)

**Priority**

- High (keeping you from completing day-to-day tasks)
- Medium (slowing you down)
- ✅ **Low priority (annoying, would be nice to not see)**

**Affected roles**

- Staff
- ✅ **Applicants**
- Reviewers
- Partners
- Developers
- General public

**Ideal deadline**

Date when you'd like to see this accomplished and a reason, if appropriate.

**Comment by wes-otf** [comment]
taking another hint from Github, I was going to do some research and see the feasibility of a per-prompt tab system that would allow the user to preview within the field, rather than having to go to a different window/browser tab to ensure their application looks as expected. The preview would still be done server-side.

Something like this could allow for standardizing the previews between Markdown and Rich Text, as the PageDown widget current generates a preview. Something like this:
<img width="861" alt="Screenshot 2023-12-11 at 16 14 04" src="https://github.com/HyphaApp/hypha/assets/145372368/72d47723-9462-4fd8-b966-fb2529bd56ec">

any thoughts there @theskumar or @frjo?

**Comment by theskumar** [comment]
While it's an ideal implementation. Its really helpful.

The idea of full page preview came from the fact that it is quite easy to implement given the pages are already saved as draft and we already have a mechanism to display the draft applications. Effort to vaule creation is quite high + it stops user from accidental submissions. 

I see a space where we both implemented, per block preview and a full page preview.

**Comment by wes-otf** [comment]
That totally makes sense, thanks for that feedback! For this issue I'll prioritize the full page preview & maybe write up a "nice to have" issue to toss on the backlog for the per field preview.
