### ISSUE TITLE
Improvement to naming of cloned forms

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3546]
When a form is cloned in Hypha it automatically get a new name. Something like "Original name (name of round)". A cloned form can be it turn cloned etc. so the naming becomes quite convoluted.

Ideas it improve the algoritm that does the naming so the forms always get names that make sense to the users?

**Comment by theskumar** [comment]
Any inputs or suggestions on how to make the names relevant? maybe bring this up in the maintainers meeting?

**Comment by wes-otf** [comment]
This totally slipped my mind to bring up but I'm wondering if part of the solution here is dropping the `(<name of fund>)`. It seems somewhat redundant when that could be a column we can include in the `/admin/funds/applicationform/` view. In general I think the flow & UX for forms needs some TLC when it comes to the round interactions. I've seen it trip up users in a few places when they don't clearly understand that rounds copy forms/editing round forms thinking that it'll translate back to the original fund's form.

**Comment by frjo** [comment]
What do you all think about naming the clones with the creation date?

If the "original form name is "ICFP Fellowship proposal" the clone name would be "ICFP Fellowship proposal (2024-05-09 12:10:05.001)".

If that form is cloned it turn we remove the old date and add the current one avoiding longer and longer names.

This way users can at least see the age of the form and it what order they where created.

The date would need to contain time with microseconds to avoid possible conflicts.

**Comment by wes-otf** [comment]
yeah that makes total sense to me! especially because doing a regex or something to replace the date would be super accurate and not likely to overwrite anything that was typed by a user
