### ISSUE TITLE
Application form submission error

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3562]
1. I miss a mandatory input field for CIF application form
<img width="912" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/bc8ae0ff-6635-4e03-b93c-afe7c4626fa0">

3. When I submit, I get these alerts
<img width="796" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/4d209658-c913-49e4-ae3f-43e475c9fa96">
<img width="860" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/614eaa21-c7fe-490f-99fa-5667c13c3671">

4. Even after I fill those fields out, the submit for review button is inactive. There's no way to submit without refreshing and filling out all the fields at once 
<img width="890" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/5e4e2eae-f4d4-4a2e-b5d8-7ad089a8d6d2">

5. When I refresh and try submitting, I get this error:
<img width="712" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/9b144e9a-6dfc-4709-b1ac-768f3228750a">

**Comment by abhiXII** [comment]
Something else I noted:
1. When I save a submission as a draft and go to edit from the dashboard
<img width="1304" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/ef248784-2a12-4d5e-a35b-6022654de2e2">

2. I see these additional fields which were not there when filling out the form on this page(https://test-apply.hypha.app/core-infrastructure-fund/)
<img width="1085" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/b3ad77d0-376f-4e98-bfdc-55ab8de4d976">

**Comment by frjo** [comment]
The extra fields you are seeing are in a form group, they show/hide depending what you select in the form group question.

The errors etc. you are seeing above are also related to fields in the form group I believe. It is not a completely stable feature of Hypha.

For the current work we are doing I recommend we avoid using them and solve that problem later on.

**Comment by abhiXII** [comment]
Okay sure @frjo so should we use another application form for testing? because right now the 500 error is causing a roadblock because no submissions would get created

**Comment by frjo** [comment]
Yes, use another form or edit the current one.
