### ISSUE TITLE
Notify Secondary Reviewer when Primary Reviewer has submitted review

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3579]
### Description 

Configure Hypha's slackbot to alert secondary reviewers when a primary reviewer has submitted a review. This needs to occur in sequential order. Typically the secondary reviewer does not submit a reviewer until the primary reviewer has completed this activity.

Example:

Di is the PRIMARY and Abhi is the SECONDARY. Abhi was not notify when Di has submitted a review.

![image](https://github.com/HyphaApp/hypha/assets/20019656/8647ba46-9baf-45df-b803-37aa3ae3a1d3)

**Comment by frjo** [comment]
Is this not already implemented in https://github.com/HyphaApp/hypha/pull/3433

**Comment by fourthletter** [comment]
Was this in the latest release? I tested on the live site and don't see the feature.

**Comment by frjo** [comment]
PR #3433 is on live, see https://github.com/HyphaApp/hypha/releases/tag/v4.7.0

**Comment by fourthletter** [comment]
I tested this feature again on test and on live. On live I tested this on a newly submitted application. The secondary reviewer did not receive an alert when the primary reviewer submitted a review. https://test-apply.hypha.app/apply/submissions/670/

**Comment by frjo** [comment]
And the secondary reviewer have a Slack name configured for their account?

**Comment by fourthletter** [comment]
Secondary reviewers are receiving alerts. Thank you for following up.
