### ISSUE TITLE
Primary and Secondary Reviewers

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3580]
### Description

Reviewers are shifting when they have submitted a review. Primary reviewer should always appear on top, over secondary reviewer. Please remove 'Avg. Score' from reviewer panel.

Related
https://github.com/HyphaApp/hypha/pull/3548

**Comment by frjo** [comment]
'Avg. Score' is now inly visible if it is not 0, since OTF no longer use score it would never be visible for OTFs submissions.

**Comment by frjo** [comment]
@fourthletter  Can you link to an submission on test where this problem with spring is in effect?

**Comment by fourthletter** [comment]
here is the submission with the spring effect: 15725

**Comment by frjo** [comment]
@fourthletter Opinions are always show below the review they are related to.

**Comment by fourthletter** [comment]
Thank you for clarifying
