### ISSUE TITLE
NoReverseMatch: 'activity' is not a registered namespace

### ISSUE THREAD

**Issue by ramojo** [HyphaApp/hypha#3596]
**Describe the bug**

On logging in or visiting the /dashboard URL this error crops up: 

```
raise NoReverseMatch("%s is not a registered namespace" % key)
django.urls.exceptions.NoReverseMatch: ' activity' is not a registered namespace

```
**To Reproduce**

1. Go to 'hypha.test/dashboard'
2. See error

**Expected behavior**

See the dashboard

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers
- General public

**Screenshots**
![Screenshot from 2023-10-03 15-00-35](https://github.com/HyphaApp/hypha/assets/9459879/8c1ade2c-f1ef-4237-b3df-0b5a9070240e)

**Desktop (please complete the following information):**

 - OS: Ubuntu 22.04, Ubuntu 20.04 and macOS Monterey
 - Browser : Chrome, Safari, Firefox

Error can be bypassed by removing the url activity:notifications

**Comment by theskumar** [comment]
I see you have a space before the `activitity` in the `{% url " activity...`

**Comment by theskumar** [comment]
I did a quick search in the codebase and I couldn't fine the space before the activity text.

https://github.com/search?q=repo:HyphaApp/hypha+%22%7B%25+url+%5C%22+activi%22&type=code

**Comment by ramojo** [comment]
Thank you so much! Have no idea how that passed me by!
