### ISSUE TITLE
Staff can access the /apply/projects url even if the PROJECTS_ENABLED=False

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#3606]
**Describe the bug**

While the feature flag PROJECTS_ENABLED=False, the staff user can still visit the project urls directly and access them. 

Found it while the test started to fail at https://github.com/HyphaApp/hypha/actions/runs/6466044430/job/17553298947#step:7:267

This test were passing earlier as the ROOT_URLCONF is by default set to 'hypha.urls' and if you update the ROOT_URLCONF to hypha.apply.urls you can see that test fail. This test case also missing the positive test case, it only have negative testcase.

**To Reproduce**

1. Login as staff.
2. Have "PROJECTS_ENABLED=False" in settings, this should be default if not enabled.
3. Visit `/apply/projects` or in local https://localhost:9001/apply/projects
4. See projects overview

**Expected behavior**

**Priority**

- High (keeping you from completing day-to-day tasks)
- Medium (slowing you down)
- **Low priority (annoying, would be nice to not see)**

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers
- General public

**Additional context**

This currently breaks the test run at #3531

**Comment by frjo** [comment]
Good find, not urgent but should get fixed.
