### ISSUE TITLE
Wagtail User Filter 

### ISSUE THREAD

**Issue by fourthletter** [HyphaApp/hypha#3607]
### Description

Filter function does not show all user accounts in Wagtail

![image](https://github.com/HyphaApp/hypha/assets/20019656/24c95512-fb2d-4016-8d9b-3fad634a18b9)

### Related
https://github.com/HyphaApp/hypha/issues/2793

**Comment by frjo** [comment]
The pagination for that view is broken in current Hypha. Should not be that hard to fix. Most likely due to Wagtail upgrades that necessitate changes in out custom views.
