### ISSUE TITLE
Contract upload feature

### ISSUE THREAD

**Issue by abhiXII** [HyphaApp/hypha#3644]
- [ ] Is it okay if we continue to say "Pending signed contract by Contracting team" here? or should we say "Pending signed contract by OTF" or "Pending signed contract by the project lead" tagging @fourthletter for confirmation
<img width="1326" alt="image" src="https://github.com/HyphaApp/hypha/assets/124244361/fe7b7f6a-bf05-41c8-867a-45e6cd89069e">

- [ ] Also do we still want for the compliance team to be able to upload the contract if they wanted to? or should they be restricted from uploading the contract? in the latter case, we will have to hide the 'upload contract' button for compliance team.

**Comment by sandeepsajan0** [comment]
You're right, we need to update it as well. How about "Pending signed contract by Staff/Contracting team"? "Pending signed contract by OTF" is a public message right now we are using it only for applicants, and I think we should show the exact user group to the staff or internal members. 
Actually, it depends on the second question whether we want to restrict the contracting team or if it is fine to have it optional for both contracting and staff(as it is right now). With restriction, "Pending signed contract by Staff" makes sense and without restrictions(current implementation), "Pending signed contract by Staff/Contracting team" makes more sense.

@fourthletter @frjo What do you think about the restriction of the contracting team from uploading the contract, is there any issue if they have an option available but no need to use it(they can use it if they want) and staff can also upload the contract(both user groups having the option)?

**Comment by frjo** [comment]
@sandeepsajan0 Contracting group should still be able to upload contracts. It just that it will not be their responsibility at OTF. 

OTF will activate the setting to allow staff to upload contracts.

**Comment by fourthletter** [comment]
@sandeepsajan0 - no restrictions on which user role could upload the contract. Thanks!
