### ISSUE TITLE
Can not add new users in Wagtail admin when "Show consent checkbox?" is checked

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3649]
The form seems to never submit, just toggle between account/role tabs.

I suspect this is a bug from the Wagtail 5 upgrade. We have overriden code in the wagtail admin user section, we likely need to update that code with the Wagtail 5 changes to get it working again.

**Comment by frjo** [comment]
This seems to be an issue with the test db, not the code.

I can not replicate the issue with my local test db or the sandbox db.

**Comment by sandeepsajan0** [comment]
Yes, working fine locally for me as well.

**Comment by theskumar** [comment]
Any error in the browser console or server logs?

**Comment by frjo** [comment]
This bug show up on OTF test site as well, not good.

**Comment by frjo** [comment]
I have found the cause of the issue:

If the "Show consent checkbox?" is checked in Wagtail admin -> Settings -> Auth Settings  you can not add users in Wagtail admin. On test it is not checked but on OTF live it is.

This is the code:

https://github.com/HyphaApp/hypha/blob/40f78e269516ef6fc99d4e760823a2cc362fe768/hypha/apply/users/forms.py#L70-L86

This class is also used when creating a new users from Wagtail admin `/admin/users/add/´. The consent checkbox is required but is not shown, and should not be shown, when creating users in Wagtail admin. Since it is required but not checked the form fails to submit and you can not create users.

@theskumar Can you try to fix this issue? We want the consent checkbox when a user creates an account (path `/register/`) but not when admins create users (path `/admin/users/add/`).

**Comment by frjo** [comment]
I will hold v5.1.0 until next week so we can get this in.

**Comment by frjo** [comment]
@theskumar I took a stab at solving this, can you please take a look?

**Comment by theskumar** [comment]
Just reviewed
