### ISSUE TITLE
Upgrade xhtml2pdf to 0.2.13 and reportlab (or rebuild PDF generation with other tools)

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#3653]
Current version: 0.2.11

xhtml2pdf 0.2.12 depends on the reportlab>4 ([release notes](https://xhtml2pdf.readthedocs.io/en/latest/release-notes.html#id2)), while reportlab==3.6.13 is an explicit dependency on this project. 

Make sure the reportlab requirement doesn't break the code for the `make_pdf` code in  `hypha/apply/utils`

**Comment by frjo** [comment]
Take the opportunity to re-evaluate how Hypha generates PDFs. Also make sure we use the same method in all places.
