### ISSUE TITLE
Add redirect when deleting an invoice

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3663]

**Comment by wes-otf** [comment]
@frjo What did you see when deleting the invoice/what's the intended functionality? When I tried a delete on test I was brought back to the project details view

**Comment by theskumar** [comment]
This happens to me while delete the invoice from the projects landing page locally. See video for reference. 

![Screenshot 2023-12-05 at 4  02 05](https://github.com/HyphaApp/hypha/assets/236356/b9ef2a60-ec8e-4463-ae74-c33209abe345)

**Comment by wes-otf** [comment]
Ah this is super useful, thanks @theskumar!

**Comment by theskumar** [comment]
This was happening b/c I had `PROJECT_ENABLED=False` in my .env. I've a PR to improve this un-intensional behaviour.

- https://github.com/HyphaApp/hypha/pull/3690
