### ISSUE TITLE
Compare view formatting is sometimes confusing to read

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3671]
The formatting of the compare view needs some small touch-ups. The issues I've noticed are:

1. Lack of spacing between a heading and the previous data field
2. Inconsistent header sizes for different fields without clear section separation
3. Compare formatting for numbers sometimes has weird wrapping properties
4. If the application has short text fields, the compare view has little to no spacing between the two revisions

----

![Screenshot 2023-11-29 at 12 05 56 PM](https://github.com/HyphaApp/hypha/assets/145372368/33703d1e-7842-4ef3-87cb-9c31ba95a76f)
![Screenshot 2023-11-29 at 11 57 03 AM](https://github.com/HyphaApp/hypha/assets/145372368/24c1f016-7743-42fe-8fb8-b81295f43293)

----

Again, not critical by any means but a "nice to have".

**Comment by wes-otf** [comment]
The first screenshot was edited HTML to anonymize an actual application - hence the submission & edits happening in 2025. Should've mentioned that haha.

**Comment by frjo** [comment]
Headings levels are all out of whack as well, not in order and mainly used to get font styling. I think most can be removed and we use css to style the td-elements directly.

Good with some fresh eyes that find these neglected areas of Hypha! Do you know if this view is actively used by the staff?

I created it some years back but have not heard about it since then I think.

**Comment by theskumar** [comment]
I can take a stab at it given I did some improvements to the submission detail view.

**Comment by wes-otf** [comment]
> Do you know if this view is actively used by the staff?

It is! I've been sitting in on the program calls and have seen some compare links being passed around here and there which is actually how I discovered the feature originally. Seems super useful.
