### ISSUE TITLE
Attempting to create a project from a submission with a decimal value results in an error

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3680]
When attempting to create a project from an accepted submission that has `Requested Funding` with a decimal value (ie. 5478.50),  the error `Field 'value' expected a number but got <decimal funding value>` is produced.

I believe this issue lies within the project model only accepting a [positive integer](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/projects/models/project.py#L209).

**Comment by wes-otf** [comment]
I can take a stab at this one

**Comment by frjo** [comment]
We have earlier taken measures to only allow int values here. But since you have seen flots it is not working 100%.

**Comment by wes-otf** [comment]
So this should be an integer across the board? I've seen quite a few existing submissions on production that had cents in the requested funds

**Comment by frjo** [comment]
My comment only refer to the "Requested amount" custom field. I know OTF do not use that mush anymore, opting for a generic field instead. Do not now/remember the reasoning around that.

But values in generic fields are not copied over to projects so should not matter.
