### ISSUE TITLE
Status bar items are sometimed wrongly overlayed over other elements

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3700]
The z-index for some status bar items cause them to be overlayed over other items. An example can be see in the debug message prompt:

![Screenshot 2023-12-21 at 09 17 19](https://github.com/HyphaApp/hypha/assets/145372368/d9e9c659-dddf-4fa3-a607-19ff4b6a4508)

**Comment by sandeepsajan0** [comment]
Looks like it has been fixed already.

![image](https://github.com/HyphaApp/hypha/assets/23638629/6816da7f-3d2a-4d5f-806f-f38b81f82831)

**Comment by frjo** [comment]
Fixed in another issue.
