### ISSUE TITLE
`KeyError: 'password'` when trying to disable another user's 2FA

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3705]
As an administrator with an instance that has `ENFORCE_TWO_FACTOR=True`, when going to disable another user's 2FA via wagtail admin, a `KeyError: 'password'` results from the apply users' [views.py](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/users/views.py#L533), attempting to set the label of the password form field. 

This makes an administrator unable to disable 2FA for a user.

**Comment by wes-otf** [comment]
I took a brief look at this already, it seems like only form field in this view is `confirmation_text` so I was going to get rid of it or wrap it in a conditional (I didn't see it being used anywhere else but don't have the historical context).

**Comment by frjo** [comment]
Is this a new or old bug? I know OTF staff have used this function successfully in the past.

They might all have been logged in via Google so no 2FA however.

**Comment by wes-otf** [comment]
I believe this is a new bug as both Slammer & I couldn't disable 2FA on another user's account through Hypha, I had to do it manually in the heroku/python shell. I think this issue potentially came with #3531 as it removed the need for a password field in the 2FA disable prompt, but it's weird that a password field would be in the `TWOFAAdminDisableView`. 

@sandeepsajan0 maybe you might have better insight as I think you did the initial implementation, is [`form.fields["password"].label = "Password"`](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/users/views.py#L533) something that can be removed at this point?

**Comment by theskumar** [comment]
I'll try take a stab at it. As I don't believe I tested the wagtail admin disable 2FA flow throughly in the #3531
