### ISSUE TITLE
Investigate frameworks for E2E testing in Hypha

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3714]
Adding automated end to end testing in Hypha would hypothetically allow for the user testing to be a lot smoother, as many issues would be caught before manual testing took place.

This task seeks to find what frameworks and testing workflows would be best suited for Hypha.

Potential options:
- [Selenium](https://www.selenium.dev/)
- [Cypress](https://www.cypress.io/)
- [TestCafé](https://testcafe.io/)
- [Playwright](https://playwright.dev/)
- Add others that are of interest!

**Comment by wes-otf** [comment]
Upon completion of this issue a new one should be created for initial implementation of E2E tests

**Comment by sandeepsajan0** [comment]
I was looking for better options than selenium because it is a bit slower. I found this blog on Playwright https://sixfeetup.com/blog/end-to-end-testing-python-playwright

**Comment by wes-otf** [comment]
Will make another issue for implementation
