### ISSUE TITLE
Partners should be able to change visibility options on comments

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3737]
When a partner is added to an application, they should be able to change who can see comments they leave (**just** staff, or both staff and the applicant). There maybe be a need for the partner to share sensitive information of just communicate with OTF staff.

**Comment by frjo** [comment]
We try to treat partners exactly the same as applicants, same permissions, same views etc.

Is not a partner normally just another person at the same organisation (as the applicant)? Does OTF use it for some other group of people?

**Comment by wes-otf** [comment]
@frjo this issue came about trying to get Red Team Lab setup. For context, their ideal workflow looks like this:

1. Applicant applies to get their project a security audit.
2. OTF dicsusses and accepts/denies.
3. If approved, a security vendor is added as a partner.
4. Vendor communicates with staff sometimes uploading their own financial information or other communication intended for just staff.
5. Vendor will also need to communicate with applicant to ask questions & upload completed audit.

They were ideally hoping to use Hypha as a communication log to avoid losing comms in individual emails as people come & go. Let me know what you think and if that makes sense.

**Comment by frjo** [comment]
I see, this was a use case for "Partner" I was not aware of.

Should not be hard to add.

**Comment by wes-otf** [comment]
I can take a stab at this
