### ISSUE TITLE
Beta submissions view categories label is rendered as an ID rather than a title

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3741]
All bug bounty props to @Techslammer. When a category is filtered on in the new beta `All Submissions` view, the filter label appears at the category ID rather than the category name.

## Screenshots

*selecting the category*
<img width="303" alt="Screenshot 2024-01-30 at 15 22 56" src="https://github.com/HyphaApp/hypha/assets/145372368/80c6fe45-8cad-490f-885a-5b4a73300e23">

*the filter label*
<img width="1298" alt="Screenshot 2024-01-30 at 15 21 11" src="https://github.com/HyphaApp/hypha/assets/145372368/326a80aa-e15c-4e64-b3fa-4fb9127a8c05">

**Comment by Vayras** [comment]
@wes-otf I would like to contribute towards this can you assign this to me

**Comment by theskumar** [comment]
TBH, this was a performance convenience and MVP implementation of the concept. Glad people are finding it useful and should definitely be updated.

**Comment by wes-otf** [comment]
@theskumar that totally makes sense. We have some of our users actually starting to beta testing it now so hoping to bring more fixes over the next few weeks.

**Comment by wes-otf** [comment]
@Vayras all yours if you want it! Thanks for contributing.

**Comment by Vayras** [comment]
@wes-otf Thanks, will start working on this now

**Comment by wes-otf** [comment]
@Vayras any status on this? No worries if not, I'll probably put in a PR for this next week to get it through the gate.
