### ISSUE TITLE
Selections made under Wagtail Admin > Forms result in `'str' object has no attribute 'clean_name'`

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3745]
**Describe the bug**

When in Wagtail admin, navigating to the `Forms` menu item in the left pane and selecting a fund/lab/round results in `'str' object has no attribute 'clean_name'`. I don't have the historical context on what the funds option is used for but this is likely unintended. 

**Priority**
- Low priority (annoying, would be nice to not se

**Comment by wes-otf** [comment]
This was initially found on the test instance. There's a few items on live that seem to work, others give errors. Again, not sure if this is relevant or not - did it relate to the public site?

**Comment by frjo** [comment]
The "Form" menu item should be removed. It is a left over from the public site, unsure why it is listing application forms now.

**Comment by theskumar** [comment]
I'll take a stab at it.
