### ISSUE TITLE
Add migration to truncate mailchimp_newslettersettings table

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3770]
With the table content in place you get this error if you try to delete the public pages.

`django.db.utils.IntegrityError: update or delete on table "wagtailcore_site" violates foreign key constraint "mailchimp_newsletter_site_id_cf631b4e_fk_wagtailco" on table "mailchimp_newslettersettings"
DETAIL:  Key (id)=(3) is still referenced from table "mailchimp_newslettersettings".`

**Comment by frjo** [comment]
This most likely one effects OTF so we can perhaps skip it.

@wes-otf You will need to truncate `mailchimp_newslettersettings` table on OTF sites before deleting the public pages.

**Comment by theskumar** [comment]
Mailchimp module was removed without the delete migration in place. I'll look into creating a delete migration. 

But trimming the table should work as well.
