### ISSUE TITLE
Fund descriptions are missing on the new homepage

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3774]
With the new updates to the homepage, the fund descriptions seem to be missing:

**Before**:

<img width="600" alt="Screenshot 2024-02-16 at 11 15 35" src="https://github.com/HyphaApp/hypha/assets/145372368/63fdf09f-215e-42fa-ad76-34076f2e68a5">

**After**:
<img width="600" alt="Screenshot 2024-02-16 at 11 16 12" src="https://github.com/HyphaApp/hypha/assets/145372368/e4627e81-367f-494b-953e-ae3563a4a33d">

**Comment by frjo** [comment]
@wes-otf We should have added a note about this.

You need to copy the description from the old wagtail page to the new description field on the Fund/Lab itself.

**Comment by wes-otf** [comment]
sounds good!
