### ISSUE TITLE
Status bar active stage indicator seems squashed

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3775]
It seems that the active state has been pushed up into the status bar. This isn't unreadable, just looks a little odd.

![Screenshot 2024-02-16 at 11 34 05](https://github.com/HyphaApp/hypha/assets/145372368/da291ba9-1a24-49eb-869f-6db8b7e25234)
![Screenshot 2024-02-16 at 11 33 21](https://github.com/HyphaApp/hypha/assets/145372368/34720427-6d36-4063-a049-70cb55c956f6)

This was seen on Firefox 121, I didn't see if it was different on other browsers.

**Comment by frjo** [comment]
A bug from the rtl css PR. Fixed in a PR now.
