### ISSUE TITLE
Selecting `View Message Log` on submission redirects to the user's dashboard

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3782]
When looking at application details and selecting `View Message Log` on the right, a client-side error of `Uncaught ReferenceError: NProgress is not defined` occurs, redirecting the user to their dashboard.

<img width="1341" alt="Screenshot 2024-02-23 at 15 52 15" src="https://github.com/HyphaApp/hypha/assets/145372368/93b2e74a-3edd-427d-bbcd-287e8edd3505">

**Comment by theskumar** [comment]
I could not reproduce it with my local setup. This link is available to `is_apply_staff_admin` only, and also link directly to the django admin interface. 

https://github.com/HyphaApp/hypha/blob/37b2f494a1ec871f425719ff8f13978ee6aea57a/hypha/apply/funds/templates/funds/applicationsubmission_detail.html#L62-L66

On the surface doesn't feel any javascript should be involved in the `click` action.

**Comment by theskumar** [comment]
@wes-otf would be helpful if you can provide a screenshot of the error itself.

**Comment by frjo** [comment]
You can not access "django admin" if the `is_staff` is not set to `TRUE` on your user account.

Without it you get redirected to the dashboard.

**Comment by wes-otf** [comment]
@theskumar Yeah I think I was misguided, seems like that error was a coincidence because it doesn't log anything anymore

**Comment by wes-otf** [comment]
@frjo what does it take to be set as is_staff? I was both staff & staff admin

**Comment by frjo** [comment]
This pipeline should set it on any new user who's e-mail address are in `STAFF_EMAIL_DOMAINS`. 

https://github.com/HyphaApp/hypha/blob/37b2f494a1ec871f425719ff8f13978ee6aea57a/hypha/apply/users/pipeline.py#L7-L13

P.S. We should rename this to `make_hypha_staff`

**Comment by theskumar** [comment]
Do we need to anything for this issues or it's safe to close it?

**Comment by wes-otf** [comment]
@theskumar I think this is still unresolved. I can look at this next though because I don't think that `make_otf_staff` function is working properly as I wasn't able to see the message log, nor could any of the other staff. Could we just check for staff admin instead of `is_staff` and get rid of that function as a whole?
