### ISSUE TITLE
When editing an existing submission the save/submit button say "Preview and submit"

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3788]
Staff can not save when editing an existing submission. The button say "Preview and submit" but you are never given the option to submit.

Applicants can save but the submission does not seem to progress when it should.

**Comment by frjo** [comment]
@wes-otf Can you confirm this issue? If so it is a quite bad bug.

**Comment by frjo** [comment]
I will discuss this with @sandeepsajan0 tomorrow and hand of any info we dig up here so @wes-otf can take over.

**Comment by wes-otf** [comment]
Can confirm, exactly what you said in the issue. Am currently updating OTF's applicant guidebook today and found a whole host of issues with the preview that was missed on my own dev testing and on user testing.

Going to devote solid time to looking at this tomorrow but I think relying on the draft stage to preview the application is what's biting me here. I think there might need to be another stage potentially added that is dedicated to previews.
