### ISSUE TITLE
Batch determination `KeyError` for non-Staff user

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3793]
**Describe the bug**

Given a user not having the "Staff" role, e.g. "Admin" or "Staff Admin", when submitting a Batch Determination, then a `KeyError` (shown via an HTTP 500 error) occurs.

**To Reproduce**

1. Log in as a non-Staff user (or remove the Staff group from your user in Wagtail Admin)
2. Visit `apply/submissions/all/`
3. Select a couple of submissions having the same status
4. Click "Status" button (at the top of the table)
5. Select "Dismiss" from the dropdown
6. Click "Update"
7. Click "Send"

See the 500 error.

**Expected behavior**

Either a permission error or a successful update to the submissions' status.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Non-Staff who do Batch Determination
- Developers
- Testers

**Desktop (please complete the following information):**

 - OS: GNU/Linux, PureOS 10
 - Browser: Firefox 115
 - Version: v5.3.1

**Additional context**

Found and/or refined by @tris-ots, @frankduncan, and me.

**Comment by wes-otf** [comment]
Hey, thanks for submitting this! What user role were you exactly? I tried this as `Applicant` & `Partner` and couldn't get the submissions page to render, just hung at a white screen (which should also prob result in a 404). It also isn't in the nav bar at that point.

**Comment by bickelj** [comment]
@wes-otf Admin

**Comment by bickelj** [comment]
@wes-otf See the suggested fix in #3796. If there's a better way we are all for it. Have a great weekend!

**Comment by wes-otf** [comment]
Closed via #3796.
