### ISSUE TITLE
`View Live` on a round in Wagtail always results in a 404

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3794]
When given the option to view a round live, it always results in a 404 due to the live round existing at the fund's slug. For cases like these, the `View Live` button should bring the user to the fund's URL. Are there cases where the content would exist at the round's slug?

https://github.com/HyphaApp/hypha/assets/145372368/76705215-513a-4670-8062-0d52766ab0e4

**Comment by theskumar** [comment]
As per the current implementation, the rounds doesn't get it's own url or can't be served at it's url. A round is always served at the Fund's url, and the fund url always shows the first open round in that fund. 

Considering that, it might be best not to display the `View Live` button unless it's actually live/open. 

Relevant code: 
- ApplicationBase -> Serve: Check it's a round, find it's open round and delegate the rendering to RoundBase's serve method to actual serve the page. https://github.com/HyphaApp/hypha/blob/d6110bfeb81143cbf37e890925502ef3896923b9/hypha/apply/funds/models/applications.py#L162-L163
- RoundBase -> Serve: It blocks access to the page unless it's routed via fund or is preview. https://github.com/HyphaApp/hypha/blob/d6110bfeb81143cbf37e890925502ef3896923b9/hypha/apply/funds/models/applications.py#L461-L463

**Comment by wes-otf** [comment]
This totally makes sense! That's what I assumed was happening but didn't have a chance to dig in. For context this came up because staff was trying to verify that a round was actually live and the 404 just added confusion so making the `View Live` only available if it's actually live would be super helpful.

**Comment by theskumar** [comment]
Alright, thanks for the insights, that totally make sense. Since I already looked into the logic, etc. I'll take it up
