### ISSUE TITLE
Clicking the search button in Wagtail admin results in `'NoneType' object has no attribute 'preview_modes'`

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3808]
In Wagtail admin, selecting the search button (rather than typing a query in the input field) results in the error `'NoneType' object has no attribute 'preview_modes'`, which stems from Wagtails [`models.__init__`](https://github.com/wagtail/wagtail/blob/main/wagtail/models/__init__.py#L2426)

![Screenshot 2024-03-14 at 09 17 32](https://github.com/HyphaApp/hypha/assets/145372368/352f1924-89b4-49b1-a8fd-4d547e874e89)

**Comment by frjo** [comment]
We should disable the Wagtail search menu item. Was only useful with the old public part of Hypha.
