### ISSUE TITLE
When logged out, the mobile "hamburger" menu is blank

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3811]
When selecting the hamburger menu from a mobile view while also logged out, it is blank. There should be the option to at least login on this menu.

https://github.com/HyphaApp/hypha/assets/145372368/f8b881b0-1a2f-46d4-a493-de58f8302b0f

**Comment by frjo** [comment]
I suggest we show the login/signup buttons directly, even on mobile.

Mobil menu then only for logged in users.
