### ISSUE TITLE
Modals/Prompt shouldn't close on submit if there is a validation error

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#3834]
**Is your feature request related to a problem? Please describe.**

Refers to https://github.com/HyphaApp/hypha/pull/3807#issuecomment-2013140208

**Is your feature request related to an existing functionality? Please describe.**

Related to all modals/prompts

**Describe the solution you'd like**

Modal shouldn't close on submit if there is a validation error. Users can use the cross sign(X) to close but the validation error should be visible otherwise it is confusing.

**Additional context**

Look for other modals as well.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers
- Partners

**Comment by wes-otf** [comment]
It also seems like it gives a false indication of an update to the users. ie. the example given in #3807 is still applicable even when there isn't a validation error, as if you add a valid reviewer to the application and close the modal without pressing `Update`, reopening the model will still show the reviewer as added despite them not being a reviewer on the submission.


https://github.com/HyphaApp/hypha/assets/145372368/3a88e6a8-d88a-4ad4-afb2-b984dc4d6494



So (to me) the expectation would be that when you re-opened the modal and changes made before pressing `Update` would be gone

**Comment by frjo** [comment]
The modal is not a separate page, just some HTML at the bottom of the current page. Therefor it is not reset until you reload the page.

Maybe rebuild all the modals with htmx?

**Comment by frjo** [comment]
Converting all modals to htmx should fix this.
