### ISSUE TITLE
Rename PAF, "Project approval form" to something more generic

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3840]
Maybe to the generic the "Project form"?

This will make it more clear the form can be used for whatever is needed.

**Comment by frankduncan** [comment]
Some UI ideas we've talked about:

* Have the information form data be displayed on the project landing page (so you don't have to click into the information)
* Have the information entered at project creation as part of that dialog coming from the submission

We're less sure of the second one, as it puts up a potential barrier to someone creating projects, but it would be a nice user experience.
