### ISSUE TITLE
Password error formatting

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3842]
Small but wanted to document it somewhere, the error prompt should be right next to the password field but instead there's quite a bit of space between the two. Should the error appear on the first prompt instead of the confirmation too? Not sure if it matters.

<img width="1060" alt="Screenshot 2024-03-29 at 14 01 19" src="https://github.com/HyphaApp/hypha/assets/145372368/ff804812-9af2-47b4-92aa-7e9249d68ffe">

**Comment by frjo** [comment]
Good catch. Would look better to have it on the first password field.
