### ISSUE TITLE
Notification list should be user specific

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3856]
The notifications in the top right should be specific to the user. From my conversations with the program team, this feature is unused as it's hard to weed out what notifications are important to them and what ones are irrelevant. Instead, they're heavily reliant on slack tagging them when an action occurs. For adopters that don't want to use slack, this could prove to be an issue.

**Comment by frjo** [comment]
I suspect it is not easy to set up rules that allow Hypha to figure out "what notifications are important to them".

My experience tells me it is not as simple as "show my stuff I'm lead for".

The task list will be personal.

**Comment by wes-otf** [comment]
Yeah I completely agree - logically and technically it will probably be a lift. Slack usage might be a good place to start for that thought from an OTF perspective, would be curious to hear what adopters think though.

**Comment by theskumar** [comment]
can we close this now, as have task list in the notifications
