### ISSUE TITLE
Submission flagging

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3858]
As it stands staff flags are unused due to their lack of specificity. Feedback I received is that  would make it a bit more useful:

- Specificity could be improved by allowing for a message to be attached to the flag. ie. A user coming back from leave after 2 weeks could understand why this item was flagged and action needed.
- The option to flag for specific member(s) of staff rather than all
- If all staff were selected rather than specific staff member(s) flag, show the flagging as an activity in the comms tag with the message for the team
- If #3856 was implemented, show the flag in the user's notifications

**Comment by wes-otf** [comment]
regarding that third item, maybe it would also make sense to show when a specific member is flagged along with all staff

**Comment by frjo** [comment]
To me this sounds like another, separate, feature.

Or flagging as it works now is of little use and we should replace it with this feature.

I can envision a feature that allows staff to put a submission in their own or other(s) task list with a short message.

I see the task list as a core feature in Hypha moving forward. The thing that makes everyone know what they should do to make things move forward.

**Comment by wes-otf** [comment]
> Or flagging as it works now is of little use and we should replace it with this feature.

I think this would likely be the case. I like the idea that it would be oriented towards the task list. The feedback I got seemed like it was leaning more toward that being ideal. Again would be curious to hear what implementers thought.

**Comment by frjo** [comment]
My suggestion then is that we build a new feature that allows staff to put a submission in their own or other(s) task list with a short message.

* What should we name it?
* When should the task be removed? Only manually?
* Notifications sent out when someone add to your task list?

**Comment by frjo** [comment]
Closing this, see https://github.com/HyphaApp/hypha/issues/3872
