### ISSUE TITLE
The submission summary for reviewers doesn't match the results

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#3861]
Create a reviewer account (after creating an account with role "Reviewer') from admin, do not assign any submission to that account. 

The "reviewer" can access the "All submissions" from the nav. The user doesn't see any submissions, which is expected but the user can see the submissions under different status in the summary box.

To be it feels odd, what do you think @frjo @abhiXII @sandeepsajan0 @wes-otf 

![Screenshot 2024-04-08 at 7  51 22@2x](https://github.com/HyphaApp/hypha/assets/236356/01553dc6-f757-454c-9780-ff8e96160f55)

**Comment by frjo** [comment]
The quick filter or what we should call them should only show for staff I think.

**Comment by theskumar** [comment]
@frjo I think that's a good idea. 

@wes-otf @Techslammer @abhiXII Thoughts?

**Comment by wes-otf** [comment]
yeah that makes sense to me!

**Comment by Techslammer** [comment]
it makes sense to me too

**Comment by sandeepsajan0** [comment]
Yes, I found there is a queryset mismatch. As we all agreed to hide it for reviewers, I have created a PR to avail this section only to staff members. #3870
