### ISSUE TITLE
Rename old and new/beta submission all views to list and grid

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3863]
- [ ] Make list (i.e. new/beta) the default with path `apply/submissions/all/`.
- [ ] Give the grid view (.i.e. the old/current view) the path `apply/submissions/all-grid/`
- [ ] Instead of the links saying "Try newer version/View older version" go with something like "Switch to grid view/Switch to list view".

**Comment by frjo** [comment]
@wes-otf Sounds like a good solution?

**Comment by wes-otf** [comment]
yeah! this sounds good to me, I agree that it'd help with adoption. While we wait for design feedback lets still keep the grid the default and once that's all done we can switch to the now "beta" view.
