### ISSUE TITLE
Rebuild Screening (thumb up/down) feature to use htmx

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3873]
This function on the submission detail page now uses jQuery ajax. Would be nice to convert it to htmx.

![Skärmavbild 2024-04-16 kl  09 52 51](https://github.com/HyphaApp/hypha/assets/191392/80282013-cbcc-40e9-b915-7c495b2320d6)

https://github.com/HyphaApp/hypha/blob/main/hypha/static_src/javascript/screening-status.js

https://github.com/HyphaApp/hypha/blob/main/hypha/apply/api/v1/screening/views.py

https://github.com/HyphaApp/hypha/blob/main/hypha/apply/funds/templates/funds/includes/screening_status_block.html

**Comment by theskumar** [comment]
I can take a stab at it.
