### ISSUE TITLE
Make the "My name" button in to a dropdown menu

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3888]
Making in to a dropdown menu allows us to have a place for things that are not specific submission or project.

By moving "Log out" in to this menu we also free up some space.

Start with these items:

- [ ] My account
- [ ] Activity feed (used to be in the notification bell, only for staff)
- [ ] My flagged (only for staff)
- [ ] Wagtail admin (only for staff)
- [ ] Log out

Might be a good idea to change the url for the activity feed from "/activity/notifications/" in to something better. They are not really notifications.

**Comment by sandeepsajan0** [comment]
@theskumar @frjo @wes-otf Here are the various versions of user menu button and dropdown. Please check and provide your opinions.
1. Simple transparent button with border.
<img width="1279" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/95148502-d8f6-4189-bf86-fbd6db5728c7">  
<img width="465" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/20b89261-31d9-46ec-aea8-5aa5560b0821">

2. Button without border
<img width="1279" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/5d63e436-f104-4218-b958-ec0311af67a8">
<img width="459" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/32c8ffa3-4a5d-4a6d-8f2b-d97c4cb51415">

3. User circle icon with text and without border(just like 2nd but circle icon)
<img width="1280" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/7fa5fc3d-ab74-4d7b-859c-8cb3c134ef3a">

4. Only Icon as a button(no text)
<img width="1280" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/a9608944-44ee-4bda-ad41-43419829a02c">
<img width="459" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/3292ba56-cb9e-4b21-92a7-10805bd71b2a">

5. Same as 4th with header text in dropdown(text is same as it was in the button).
<img width="459" alt="image" src="https://github.com/HyphaApp/hypha/assets/23638629/010945a4-8ed2-46dd-a71d-68ccb0742ffd">

**Comment by frjo** [comment]
Well presented options! I lean towards 3 or 5.

Option 5 looks the best to me, but users might find it more intuitive with 3?

**Comment by wes-otf** [comment]
yeah I agree with 3! I think that's my favorite of all of them, seems most intuitive
