### ISSUE TITLE
What is a good session time for Hypha

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3890]
We now have it set to two (2) weeks by default. For security reasons this might not be optimal.

If you login on a public/shared computer and forget to logout manually, anyone accessing that computer within two weeks have access to that Hypha install as you.

What is a good `SESSION_COOKIE_AGE` Hypha default? One day?

**Comment by frjo** [comment]
@wes-otf What do you think?

**Comment by wes-otf** [comment]
Yeah especially in some sensitive environments I could see this being pretty critical. What about keeping the two week expiration and letting the user decide with a `Remember me`/`This is a shared computer` checkbox at login? Will also loop @Techslammer in if they have thoughts.

**Comment by frjo** [comment]
Good idea, I might prefer an opt in version. Something like "Remember me on this computer" checkbox.

**Comment by theskumar** [comment]
I would vote for somewhere around 12hr as default session length, and then an org could have it extend or reduce to a different number. 

This default could also be paired with the what Wes is suggesting to implemented a "Remember me" feature.

**Comment by frjo** [comment]
What do we think of: 

* A new default of something low like 12 hours.
* Then if user check "Remember me" we set it to two (2) weeks (the current default).
* An org can then change it as needed for them.

**Comment by wes-otf** [comment]
yeah that makes sense to me!

**Comment by frjo** [comment]
See https://github.com/HyphaApp/hypha/issues/3897
