### ISSUE TITLE
Combining a reviewer with a fund in the `/submissions/reviews/` view causes an error

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3891]
When filtering the `/submissions/reviews/`, using a reviewer combined with a fund as the criteria results in an error of:

```
Cannot resolve keyword 'submission' into field. Choices are: activity, applicationbase_reviewers, ...
```

Not sure how often staff use this view (I don't think much) but what's the historical context with this? Is this supposed to only be for external reviewers or all reviewers of any application?

**Comment by frjo** [comment]
Both the "fund" and "round" filters in that view seem to be broken.

The view ("ReviewerLeaderboard") is only for staff reviews.

**Comment by wes-otf** [comment]
Interesting! When I looked there seemed to only be data on the external reviewers

**Comment by frjo** [comment]
Yes, you are correct. I think I remembered another leaderboard for staff that we removed.

**Comment by wes-otf** [comment]
How would y'all feel about removing this? After some conversations with staff it seems like this isn't currently used/needed in OTF's context. I could see down the road where a smaller variation of this is a part of some form of "Staff Admin Statistics" view (maybe that also gets combined with `/submissions/result/`) but that seems like a non-priority right now.

**Comment by wes-otf** [comment]
Seems like a potentially easier solution to drawing up a fix

**Comment by frjo** [comment]
No issue with removing it.
