### ISSUE TITLE
Remove unused `register_admin_menu_item` in Dashboard

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3894]
Can this be removed?

https://github.com/HyphaApp/hypha/blob/476e07857133a7e3409290644eb69f6e85c6fe1e/hypha/apply/dashboard/wagtail_hooks.py#L10-L18

**Comment by theskumar** [comment]
@frjo This for the this particular item. I believe it serve a useful purpose here, atleast I use that button often. 

![Screenshot 2024-04-22 at 6  40 24@2x](https://github.com/HyphaApp/hypha/assets/236356/94d950f9-8df0-4f26-8bbf-fba30ef981ec)

**Comment by frjo** [comment]
Forgot that one, closing.

Found it via this message "RemovedInWagtail60Warning: The `classnames` kwarg for MenuItem is deprecated - use `classname` instead.".
