### ISSUE TITLE
External reviewers shouldn't be able to interact with applicants & vice versa

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3907]
In OTF's instance, the bylaws regarding external reviewers do not allow them to interact with the applicant at all. Currently, when a comment is left by an external reviewer the user can see it and vice versa, the external reviewer can see all comments left by the applicant.

**Comment by wes-otf** [comment]
Added discussion tag so we can chat about this in Monday's standup, along with hearing if/how the other adopters use external reviewers on Tuesday. Seems like this would be pretty applicable across the board though.

**Comment by frjo** [comment]
In my local instance reviewers and applicants can not see each other's comments.

**Comment by wes-otf** [comment]
that's so odd, locally it seemed to work fine & I couldn't recreate what I saw happen here: https://test-apply.hypha.app/apply/submissions/628/#communications

**Comment by wes-otf** [comment]
I wasn't able to recreate what I saw in the previously mentioned comment so I'll close this out for now
