### ISSUE TITLE
Applicants should not be able to see what staff member is lead on their application

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3936]
Currently when a user submits an application, they can see who the staff lead is. In other cases we obscure the staff members name and it probably also makes sense to do so here as it's PII.

<img width="410" alt="Screenshot 2024-05-22 at 11 21 05" src="https://github.com/HyphaApp/hypha/assets/145372368/fac2c6c5-e45f-46fd-b17d-a845079bd818">

**Comment by wes-otf** [comment]
to me the only people who really need this info would likely be staff, curious to hear your thoughts @frjo

**Comment by frjo** [comment]
We already hide staff names in comments for applicants so apparently it is important for OTF staff to stay anonymous. This is a logical extension of that.

When we implement this I think we should add a setting `HIDE_STAFF_IDENTITY` or similar. I suggest it is false be default but OTF would set it to true. This would then hide staff identity in comments, lead and any other place we find.

**Comment by frjo** [comment]
We should also add a function so we do not need to do `user.is_apply_staff or user.is_finance or user.is_contracting`. Maybe `def is_employed(self):`?

**Comment by frjo** [comment]
We could at the same time add a def `is_external(self):`.

All groups should belong to one of these criteria.

**Comment by wes-otf** [comment]
yeah I totally agree, sounds like a nice solution! I can toss something up quick.

**Comment by wes-otf** [comment]
basically have everything figured out for the new config option and having the lead/comment names hidden based on that, but one thing I'm logically struggling with is the activity tab, as activities like this are shown:
![Screenshot 2024-05-24 at 11 17 03](https://github.com/HyphaApp/hypha/assets/145372368/d445719f-f4ef-4a3f-8b26-c6c43e107324)
with how we currently handle visibility it seems like filtering this activity based on the `HIDE_STAFF_IDENTITY` may add another level of activity visibility complexity. For now should we just make this activity `team` visibility only and when visibility refactoring happens in #3915 consider how to reincorporate it? Open to any alternative ideas too

**Comment by frjo** [comment]
I see no problem with making this staff only.
