### ISSUE TITLE
Results page fixes & enhancements

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3941]
The results view (`/apply/submissions/result/`) is something staff has voiced they would like to utilize more to see how funds have preformed and get more overall stats on. There are a few current issues that could use some TLC:

- [ ] **Backend overload** - When initially loading the page or removing all filters, the load speed either crawls or crashes Hypha
- [ ] **Intuitive-ness** - The UI flow could use a bit of a face lift in how data is presented and filters are used (ie. does it make sense to have a submission search functionality?)
- [ ] **Bugs**
    - [ ] Round amount numbers to two decimal places
    - [ ] Filtering by drafts always shows 0 results

**Comment by frjo** [comment]
Glad to see things happening here! I build this years back as an example of the stats that Hypha can provide.

**Comment by wes-otf** [comment]
definitely! it's gotten praise recently as the FOSS fund wrapped, I saw it used a few times to calculate requested amount totals of all the submitted concept notes which is so much better than adding by hand
