### ISSUE TITLE
All projects with the status of `Internal Approval` cannot be opened

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#3945]
While testing project features, I went to open a project in `Internal Approval` and that resulted in an error of `'internal_approval' is not in list`, which looks to stem from the [this code in the test branch](https://github.com/HyphaApp/hypha/blob/test/hypha/apply/projects/views/project.py#L1297). Didn't have a chance to dig too deep on it yet.

**Comment by frjo** [comment]
Adding an "PAF Reviewers Roles" (should also be renamed) fixes this issue.

We do not have a solution in place for projects that are being approved and the organisation desided to delete all the "PAF Reviewers Roles". They end up in a limbo.

I think we can see this as an edge case but would be good to have it just work in any case.
