### ISSUE TITLE
Let contract uploader skip the countersigning step by default

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3954]
**Is your feature request related to a problem? Please describe.**

Not every funding organization uses Hypha for signing and countersigning. They might have the already-signed contract in another system but would like a copy in Hypha. To streamline the process of uploading such a contract, a Wagtail option to help skip the countersigning step is helpful.

**Is your feature request related to an existing functionality? Please describe.**

This is in the Projects functionality, e.g. `apply/projects/1/` where `1` is in the `Contracting` state but does not have any contracts uploaded.

**Describe the solution you'd like**

A Wagtail option that makes it easy to upload once instead of twice.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Applicants
- Contracting

**Comment by frjo** [comment]
This was addressed in https://github.com/HyphaApp/hypha/pull/3938

**Comment by bickelj** [comment]
> This was addressed in #3938

Oh, excellent! Thank you!

**Comment by bickelj** [comment]
This is ~~a duplicate~~ related to #3923.

**Comment by bickelj** [comment]
Hmm, on second glance, I think what we want is an option to default to that checkbox being already checked.

**Comment by frjo** [comment]
Should not be hard to add a setting for that. As long as the default does not change current behaviour I'm happy to merge it in.

**Comment by bickelj** [comment]
@frjo Thanks, there are some slight differences in our implementations as well. For example, `signed_by_applicant` is `false` with the `signed_and_approved` separate option. But that may or may not matter.

**Comment by bickelj** [comment]
@frjo Pasting this question here in the issue, I Just mentioned it in a PR which may not be the best place:

When staff uploads a countersigned contract it truly is `signed_by_applicant`, right?

**Comment by frjo** [comment]
@bickelj If they check the "Signed" box then yes.

**Comment by bickelj** [comment]
@frjo I just tried it on main at a64852aeb4d3f05b9164848cec45265f58ddd345 and when I approved as staff I see this:
```
select signed_by_applicant, signed_and_approved from application_projects_contract;
 signed_by_applicant | signed_and_approved 
---------------------+---------------------
 f                   | t
(1 row)
```

I would not pick this nit except for the differing implementation that I had which didn't introduce a new field but rather re-used `signed_by_applicant`. Anyway, this was the question I wanted to raise. Is this a bug that `signed_by_applicant` remains `false`?

**Comment by frjo** [comment]
@bickelj Thanks for looking in to this. I assumed `signed_by_applicant` would be set to true but that was wrong.

If it is a bug or not depends on if we see `signed_by_applicant` as an action taken by the applicant on the system or if it is stating whats on the uploads PDF.

I will add an issue and set it as a bug and see what the team thinks.
