### ISSUE TITLE
Let Reviewers see all submissions on dashboard

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3966]
**Is your feature request related to an existing functionality? Please describe.**

Reviewer dashboard.

**Describe the solution you'd like**

When Reviewer Settings permit, on the Reviewer dashboard Reviewers should see all submissions.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Reviewers

**Comment by frjo** [comment]
The dashboard is meant for things related to you.

If reviewers are allowed to and want to see all submissions they should go to "submission/all/" just like staff.

**Comment by bickelj** [comment]
> The dashboard is meant for things related to you.

Yes, of course.

> If reviewers are allowed to and want to see all submissions they should go to "submission/all/" just like staff.

Yes, they can do that. But if Reviewers are supposed to be able to review anything and they go to "My Dashboard" it can be argued that they should be able to do it from there as well.

Edit: it looks like @gmurtaza00's implementation has the "all submissions" as a separate table on the dashboard, so it's not as though they are mixed into the existing tables that are directly related to the reviewer.

**Comment by frjo** [comment]
If you add all reviewers on all the  Funds/Labs they will be automatically assigned to all incoming submissions.

Assigned submissions will show up on the dashboard.

**Comment by bickelj** [comment]
@frjo This may not be needed then. We will have to come back and see. At the moment I'm trying to send a list of changes some of which may be overcome by events or not needed. Thank you for the feedback and pointing this out. At the moment I have a branch with the commits merged so I will still add the PR but I understand if this ends up getting the axe.

**Comment by bickelj** [comment]
#3967 was rejected for reasons explained above.
