### ISSUE TITLE
Make the Reviews box collapsible

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3975]
**Is your feature request related to an existing functionality? Please describe.**

Reviews box on Submissions Details pages. Example `apply/submissions/2/`.

**Describe the solution you'd like**

On Submission Details pages, make the Reviews & assignees box collapsible. The default setting should be closed so that Reviewers can't see other Reviewer's scores before they submit their reviews:

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Reviewers

**Comment by frjo** [comment]
I think a better option is to add a setting to completely hide the other reviews from reviewers. I think OTF is moving in this direction as well. We could even make it the default.
