### ISSUE TITLE
On the review form, present unsaved changes notifications

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3977]
**Is your feature request related to an existing functionality? Please describe.**

The Review form.

**Describe the solution you'd like**

When there are unsaved changes

* User cannot go back
* User cannot close browser tab
* User cannot shift application tab i.e. My dashboard, projects

...without confirmation.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Reviewers

**Comment by frjo** [comment]
I'm hesitant about features that interfere with how browsers work. Modern browsers are good at restoring forms when you go back, reopen tabs etc.

**Comment by bickelj** [comment]
> I'm hesitant about features that interfere with how browsers work. Modern browsers are good at restoring forms when you go back, reopen tabs etc.

If I recall correctly, I tested this before and after, and before the change I don't think there was any notification. Either I didn't remember correctly or something prevented the browser from notifying.
