### ISSUE TITLE
User is not receiving email notifications when assigned to review an application

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#3983]
**Describe the bug**

User has several roles including staff and admin. Email notifications for review are not happening.

**Expected behavior**

Emails should go out.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff

**Comment by frjo** [comment]
They only receive e-mails if the submission is in a state where they can submit reviews.

In other cases they get the e-mail when the submission reach such a state.

I believe this is how it should work, if you disagree please reopen.
