### ISSUE TITLE
Add a table style to the new submission list view

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#3988]
The current submission table view is old and creaky. Some user however prefer viewing information in a table like view.

Let's test adding a table styling to the new submission list view. This would only affect the styling of each row. We would have one "list row style" and one "table row style".

Make it have, more or less, the same columns in the same order. The search, filtering, batch functions are to be unchanged.

A extra benefit would we that users will be able to switch between list and table row style while keeping the search/filter state.

Hopefully this would make it possible to completely remove the old table view.

**Comment by wes-otf** [comment]
totally agreed. would also be nice to allow the user to set a default - maybe something that is stored in local storage or as a cookie? definitely not mission critical, especially if filter params will be preserved on switching.

**Comment by frjo** [comment]
This is done.
