### ISSUE TITLE
Implement `Remember me` for OAuth/Magic Link

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4009]
Staff have asked if the "remember me" option could be implemented for OAuth as they have to re-login daily. This has had some small residual effects like staff losing a typed up determination that they tried to submit 12 hours later (which should have been drafted but nonetheless). More of an inconvenience than a mission critical addition.

**Comment by frjo** [comment]
Can you test to set this in `base.py` in the OTF instance?

`SOCIAL_AUTH_SESSION_EXPIRATION = True`

See https://python-social-auth.readthedocs.io/en/latest/configuration/settings.html#miscellaneous-settings

Then we can see if it works and what session length Google in that case sets.

**Comment by wes-otf** [comment]
oh perfect! I didn't even do a deep dive into the social auth so I'll change this today.

**Comment by wes-otf** [comment]
alright so turns out the Google OAuth expiry is one hour so that didn't workout too well hahaha. I already reverted it but it looks like we may need to put more dev time into OAuth + magic link remember me's

**Comment by frjo** [comment]
@wes-otf Found https://support.google.com/a/answer/7576830?hl=en#zippy=%2Cthird-party-identity-providers

Can you check and see if you pr @Techslammer can adjust this for OTF on the Google side?
