### ISSUE TITLE
`Activity Feed` in the user drop down menu is broken

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4012]
Selecting the `Activity Feed` option in the new user drop down results in the error `Invalid filter: 'source_type'`.

**Comment by frjo** [comment]
Found the issue and created a PR.

Seems the "source_type" was removed by mistake in https://github.com/HyphaApp/hypha/pull/3913 and we all missed it.

**Comment by wes-otf** [comment]
gahhh that was totally my bad. For some reason I thought I added that and when my rebase had conflicts I tossed it. Great catch.
