### ISSUE TITLE
Partially filling out reviewers when there are multiple reviewer roles fails to save

### ISSUE THREAD

**Issue by frankduncan** [HyphaApp/hypha#4020]
**Describe the bug**

When you have 3+ reviewer roles, and you fill out only one reviewer for a submission, saving fails.  This is due to the "duplicate reivewers" check working on the "None" object passed in by the "---" selections

**To Reproduce**

1. Create 3+ reviewer roles
2. Set only one reviewer on a submission when updating reviewers
3. Save
4. Shift-Refresh page to ensure browser did not cache selections (or navigate away and back)
5. Open up update reviewers, see non eare saved

**Expected behavior**

The one reviewer is saved correctly

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Staff

**Desktop (please complete the following information):**

 - OS: Linux
 - Browser Firefox

**Additional context**

PR incoming

**Comment by frjo** [comment]
Good to get this fixed, this bug must be many years old.

**Comment by frankduncan** [comment]
Another PR is coming that also fixes this for batch reviewer changes!  The code is in a different place but has the same error.
