### ISSUE TITLE
For sealed round the banner blocks the primary navigation

### ISSUE THREAD

**Issue by theskumar** [HyphaApp/hypha#4072]
![Screenshot 2024-07-30 at 7  24 12@2x](https://github.com/user-attachments/assets/b66d86bb-dad3-4dcb-ab54-9f905e09392b)

**Comment by frjo** [comment]
Good catch! Could we make this alert behave the same as the archive alert? Reuse placement and styles?

**Comment by theskumar** [comment]
Modify it to be similar to archive alert, would make sense.
