### ISSUE TITLE
Remove unused CSS related to Submissions

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#4073]
**Describe the bug**

Unused or inconsistent style code around Edit, Delete, Withdraw submission links.

**To Reproduce**

See `static_src/sass/components/_link.scss` and resulting `static_compiled/css/main.css` for `--edit-submission`, `--delete-submission`, `--withdraw-submission`, and maybe others. Some of these classes do not appear to be used anymore.

**Expected behavior**

The styles should be used or deleted.

**Priority**

- Very Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Applicants
- Reviewers
- Partners
- Developers

**Comment by frjo** [comment]
We have been using tailwind more and more in the last year or so. If you find any scss declaration we missed to remove we welcome PRs to fix it.
