### ISSUE TITLE
Assign Reviewer button is not working

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#4084]
**Describe the bug**

Assign Reviewer button is not working. It might be a leftover from the fancy box modals removal.

![image](https://github.com/user-attachments/assets/f3d63007-cc8e-4703-a963-04333b864e2f)

![image](https://github.com/user-attachments/assets/f73a148b-cbab-4cb1-9836-7d954246c2fa)

**To Reproduce**

Pick a submission in external review status and click on assign reviewer. 
[Submission on test site](https://test-apply.hypha.app/apply/submissions/628)

**Priority**

- High (keeping you from completing day-to-day tasks)
- Medium (slowing you down)
- Low priority (annoying, would be nice to not see)

**Affected roles**

- Staff
- Reviewers

**Comment by frjo** [comment]
Good catch! That button was missed in converting to htmx. I believe I have fixed it in https://github.com/HyphaApp/hypha/pull/4085.
