### ISSUE TITLE
Group project permissions in wagtail have no effect

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#4093]
**Describe the bug**

I want to let the Reviewer group see Project Reports. By default, the group gets permission denied. When an Admin adds "View" for every "Project ..." in Wagtail Admin (e.g. `/admin/groups/edit/3/`), the member of Reviewer still gets permission denied on `/apply/projects` URLs.

**To Reproduce**

0. Use Hypha v5.13.1,
1. Restore the sandbox database,
2. Run migrations,
3. Log in as reviewer@example.com,
4. Try to access `/apply/projects`,
5. See permission denied.
6. Log in as administrator,
7. Go to Reviewer group settings (`/admin/groups/edit/3/` in a fresh sandbox db),
8. Check all "View" permissions for "Project ..." settings,
9. Log in as reviewer@example.com,
10. See that there is no "Projects" link available,
11. Visit projects directly, `/apply/projects/`, see permission denied,
12. Visit a visible Submission with a project link, `/apply/submissions/5/`,
13. Click the individual project link there, `/apply/projects/2/`,
14. See permission denied.

**Expected behavior**

The permissions in Wagtail to be effective.

Given a group, when I set "View" on any one Project-related permission for a group, then that group should gain access to Projects.

A less-desired alternative is to remove the appearance of being able to set those permissions. An OK alternative would be to let an administrator set the permissions outside of Wagtail admin somehow.

**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Reviewers

**Desktop (please complete the following information):**

 - OS: GNU/Linux, PureOS 10, kernel 5.10.0-31-amd64
 - Browser: Mozilla Firefox
 - Version: 115.14.0esr (64-bit)

**Additional context**

Some funders have no distinction (or less of a distinction) between a Submission and a Project. For example, the reviewers of a Submission may be the same folks who review the Project Reports. In this case it is useful to let them see the Projects and specifically reports. Fine-grained permissions presented in Wagtail look like they give the needed controls. For example, reviewers may need to see reports but not Project Form.

**Comment by frjo** [comment]
Wagtail admin permission on groups mainly affect what the users of that group can do in Wagtail admin.

If a users group has Add/Change/Delete checked on e.g. "Project report form" they can Add/Change/Delete report forms at "/admin/application_projects/projectreportform/".

It is rarely we use these settings in Hypha itself.

We have plans to improve permission handling overall in Hypha. We can talk about this in the next meeting.

**Comment by bickelj** [comment]
@frjo Do you have a rough outline of the improvement to permission handling you can share? Does the permission improvement seem like a heavy undertaking to you (e.g. months not days)?

**Comment by frjo** [comment]
It will be month but before the end of the year in my estimate. One move we already started implementing is concentrating permission code to `permission.py` files.

We will move from things like `if request.user.is_apply_staff` to `user_can_*()` calls that can be used in code as well as in templates.
