### ISSUE TITLE
Reviews block on submission detail view gets stuck on loading if not in viewport

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4094]
Caught by a staff member - with the new HTMX implementation sometimes the reviews card gets stuck on the loading animation and will never populate reviews
![Screenshot 2024-08-14 at 14 54 39](https://github.com/user-attachments/assets/5b5f68c1-5cf0-4fdc-930f-c6bbc9360ee9)

sometimes refreshing the page will fix this

**Comment by wes-otf** [comment]
pretty sure the issue comes from the [`revealed`](https://github.com/HyphaApp/hypha/blob/698ebcde53d80c8ee7bd480c7118dc440522d68e/hypha/apply/funds/templates/funds/applicationsubmission_admin_detail.html#L27) trigger, if I have staff center on the card & refresh their browser it seems to load without issue. Only breaks with it's out of view

**Comment by frjo** [comment]
I can confirm this, making my window less tall so the review block is "below the fold" it will not load.

The neatest would be to have it lazy load when scrolled in to view (or just before, browsers handle this differently).

If that is tricky we can just have it always load.

I assume this issue affects any htmx block, it just so happens that the reviews block is the furthest down.
