### ISSUE TITLE
Hide tax forms/banking info from staff, only showing finance/admins

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4119]
Today finance had requested that sensitive forms like tax forms & banking info when uploaded in the project documents only be visible to them. It would be nice if PMs and other staff could still see that status (uploaded/not uploaded), just not the document itself.

**Comment by frjo** [comment]
Make sense. We should add a setting for this. By default I think staff should see it but with the setting it can be hidden.

Most organisations are far smaller than OTF and the same person does many roles.

**Comment by frjo** [comment]
Or we add an optional setting to the contract document categories to restrict permissions.

**Comment by frjo** [comment]
Add a setting to Wagtail admin "Contract Document Categories". Each category gets a checkbox to restrict document view access from staff. Staff should see that a document has been uploaded but not view the actual document.

**Comment by frjo** [comment]
@wes-otf Contract and Finance always need access to these documents I assume? Finance has no access today but should I think, if it is banking info e.g.?
