### ISSUE TITLE
Link Projects more tightly to Submissions

### ISSUE THREAD

**Issue by bickelj** [HyphaApp/hypha#4129]
**Is your feature request related to a problem? Please describe.**

When using the Projects capability, the seemingly hard separation of Projects from Submissions can be confusing.

**Is your feature request related to an existing functionality? Please describe.**

Projects feel disconnected from their respective Submissions.

**Describe the solution you'd like**

At least some users have staff and reviewers continuing to monitor the grant all the way from start to finish. In this case, there is not a hard distinction between "Submission" and "Project" (other than the obvious "a Project happens when a Submission is accepted"). So these users refer to Submissions by their integer ID for convenience. The Project does not have that same ID so there is friction with IDs when going between Project and Submission. There are some other links that could be added too, some of which is captured in issue #4117.

We and they would like the same ID, especially given that there is already a one-to-one relationship from Project back to Submission (not vice versa). Unless there are specific plans for multiple projects derived from a single grant, there should be no issue with re-using the same ID for the Project as the Submission.

**Priority**

- Medium (slowing you down)

**Affected roles**

- Staff
- Reviewers

**Comment by frjo** [comment]
Divided up in to several issues.
