### ISSUE TITLE
Renaming `Past submissions` under `Related submissions`

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4141]
In the submission detail view, the `Related submissions` sidebar item has a subheading titled `Past submissions` which can contain submissions that are newer that the current submission. The context here is submissions that have been previously submitted by the applicant, but staff have said the "Past" wording confuses them into thinking it should be submitted before the viewed application.

It was suggested to have either a `Newer submissions` subheading too or just rename `Past submissions` to `Other submissions`

**Comment by frjo** [comment]
"Other submissions" is good I think.
