### ISSUE TITLE
UI alignment issue

### ISSUE THREAD

**Issue by sandeepsajan0** [HyphaApp/hypha#4172]
'Project information' part(text) seems a bit misaligned to left(same for submission detail page).
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/5ebfe31d-9fe0-4ae9-9778-a6eee0da3f99">

Should we align these headings on the dashboard as well?
<img width="1280" alt="image" src="https://github.com/user-attachments/assets/34113e02-7bba-4661-8651-d1073eb7439e">

**Comment by frjo** [comment]
At 1280 pixels (xl) we remove the padding on "wrapper--main" class:

~~~~
    &--main {
        padding: 0 $mobile-gutter;
        min-height: calc(100vh - 260px - 160px); // viewport - (header + footer)

        @include media-query(xl) {
            padding: 0;
        }
    }
~~~~

If you make the window 1320 pixels the adminbar with the title falls in to place as well. Then it is only the header with the logo that still has inline padding.

One way to fix it is in https://github.com/HyphaApp/hypha/pull/4173.

It works well and everything align but does not look perfect between 1280 and about 1300 pixels. Suggestions?
