### ISSUE TITLE
Filters are lost in both list & table views when navigating to next page

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4183]
**Describe the bug**

When filtering the list/table views that have enough results to be paginated, selecting `Next`/`Previous`/`Last`/`First` at the bottom of the view will result in navigating to the selected page of All Submissions rather than the filtered criteria

**To Reproduce**

1. Navigate either the list or table view
2. Use a broad filter to cause pagination (ie. `No Screening`)
3. Scroll down to the page nav buttons at the bottom (ie. Next`/`Previous`/`Last`/`First`)
4. Select any of the buttons & notice page has been changed but filters are gone

**Expected behavior**

Filters are preserved while the page is changed

**Priority**

- Medium (slowing you down)
**Screenshots**

**Additional context**

Manually entering the page query param in the URL causes the filter to be preserved while navigating to the intended page.

**Comment by frjo** [comment]
Definitely a bug. The search query is missing from the pagination links, `/apply/submissions/all/?page=2` instead of e.g. `/apply/submissions/all/?page=2&status=dismissed`.

If I manually enter `/apply/submissions/all/?page=2&status=dismissed` it works as it should so should be an easy fix.

**Comment by wes-otf** [comment]
sweet! I think I fixed it w a pagination tag to add the params
