### ISSUE TITLE
When multiple tables are in different fields of an application form, they get grouped all under the same field

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4189]
**Describe the bug**

Submitted application forms that contain two or more tables in separate fields (either markdown and/or rich text) will result in all tables jumping into the value of the last field containing a table.

**To Reproduce**

1. Submit an application that has multiple tables spread across different fields (ie. multiple rich text fields, multiple markdown fields, or combinations of markdown & rich text)
2. Submit the application
3. Tables will now have all combined to the last field containing a table

**Expected behavior**

All tables stay in their respective fields

**Screenshots**

*when populating the form*
<img width="500" alt="Screenshot 2024-10-29 at 10 49 57" src="https://github.com/user-attachments/assets/e9fbfef9-766d-45ed-b5e2-6e5dcad696af">

*after submitting & viewing in application preview* 
<img width="500" alt="Screenshot 2024-10-29 at 10 50 09" src="https://github.com/user-attachments/assets/1749cbf5-9952-4074-9117-abcd9e944a0a">

**Additional context**

I think this is a problem with how the fields are sanitized & populated when presented to the user but this doesn't occur on application previews. When an application is ready to be submitted then previewed it appears as expected.

**Comment by wes-otf** [comment]
as mentioned this isn't a problem with the application preview before submission, but also doesn't occur when using the `Show Application` feature with determinations/reviews

**Comment by frjo** [comment]
Found the issue. I added this bug when I converted this javascript from jquery to vanilla.

https://github.com/HyphaApp/hypha/blob/11f8bb68c47c4ad46212b576d9b5bd6790a36a3f/hypha/static_src/javascript/submission-text-cleanup.js#L15-L20
