### ISSUE TITLE
Project Form/SOW workflow can be confusing

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4204]
When a Project Form & SOW exist on a fund, populating them in Hypha can be a bit confusing. From my experience, both are initially populated under `Project Form`. Once you select `Fill in`, you first populate the Project Form then the SOW immediately under it. Once you press `Save`, that's when the SOW field will appear under `Project Documents`. But, to edit it the user needs to select edit on `Project Form and scroll back down`

*before filling in PAF/SOW*
![Screenshot 2024-11-08 at 11 44 01](https://github.com/user-attachments/assets/aeaffe61-f5e1-4e30-94fd-08171e37b607)

*after hitting save while editing `Project Form`*
![Screenshot 2024-11-08 at 11 57 20](https://github.com/user-attachments/assets/8684b143-9321-4c3b-be08-2da0f67d2d40)

I'm not sure if there's context I'm missing or if this is a bug but to me it'd make more sense to have the SOW be it's own line from the start, rather than having to go through Project Forms to edit it.

**Comment by frjo** [comment]
Do OTF still require them to be separate forms?

The reson for the SOW was I believe to have a subsection of the PAF that a separate group of people needed. This people did not need or should see the other parts of the PAF, like names, addresses etc.

We merged them since staff then did not want to add things in two separate forms.

If OTF still needs the separate SOW we should make it easier to edit. If they do not we can removed the features, I'm pretty sure no one else has any use of it.

**Comment by wes-otf** [comment]
ah okay that makes sense. OTF does still utilize them as separate forms for the time being - maybe that could be a configurable option in wagtail though to combine the two?

**Comment by wes-otf** [comment]
even when combined though does it still make sense to have the SOW be it's own "line" if it's intended to be a subsection of the PAF?

**Comment by frjo** [comment]
I believe OTF want the option to view the SOW separately, download it as a PDF etc.

**Comment by wes-otf** [comment]
@frjo yeah that should be kept but if other implementers wanted to configure the SOW to be a subsection of the PAF it makes sense to me that we wouldn't show it as separate in that use case? but if y'all have heard different from the adopters then that works fine for me.

**Comment by frjo** [comment]
I do not think anyone else is going to use a SOW form at all. OTF use case is quite specific. Most likely have no need for a project form at all.

**Comment by wes-otf** [comment]
ahh alright that makes sense, so maybe just keep it separate if an SOW exists? I can take a stab at that if so

**Comment by frjo** [comment]
Adding an edit link to the SOW makes sense I think. Could be as easy as a link to the current PAF edit form that scrolls down to the SOW part.

If it makes more sense to OTF we can also add a separate SOW edit form. The question is then if it also should show when staff edit the PAF.

Whatever makes sense to staff.
