### ISSUE TITLE
Proposal stuck in draft when language code is set

### ISSUE THREAD

**Issue by notaprodev** [HyphaApp/hypha#4211]
When `LANGUAGE_CODE` is set to another language every application gets stuck in draft.

A separate issue is that the menu does not show if the applicant only have draft applications.

**To Reproduce**

1. Apply for a proposal
2. Fill the form
3. Click submit
4. The proposal stock in draft

**Expected behavior**

The form should go to review, even though a language is set on env vars
**Priority**

- High (keeping you from completing day-to-day tasks)

**Affected roles**

- Applicants

**Comment by frjo** [comment]
I can confirm this bug. Will get right on figuring out what the issue is. Thanks for reporting it!

**Comment by frjo** [comment]
I think the error is from this code:

https://github.com/HyphaApp/hypha/blob/b9bd67e8df67c22b330a89eb67c5153844ede497/hypha/apply/funds/views.py#L1406-L1418

The transition keys are translated but the post keys are not, so no match.

@theskumar Any ideas how to best solve this?

**Comment by frjo** [comment]
@notaprodev I do not recognise your name. Would love to hear how you are using Hypha!

We have online meetings where Hypha users discuss and share. Please join us at https://we.hypha.app/.

**Comment by notaprodev** [comment]
I work for cloud68.co an open source hosting provider, bugs reports are usually created by the support agents. One of our subscribers requested Hypha and after having a call with one of the main devs we deployed Hypha in production.

**Comment by frjo** [comment]
@notaprodev  Thanks for the info! If possible, please let your customer know that we would very mush would like to hear from them, https://we.hypha.app/.

Will also definitely bookmark cloud68.co, we get request from funds that want to use Hypha and hosting is complicated if you do not have your own dev team.

**Comment by theskumar** [comment]
@notaprodev I've created a patch  https://github.com/HyphaApp/hypha/pull/4220/commits/e6656d62f6db57426bb15f298127c106ea4f6397 at #4220 please check if that resolves your issue.

**Comment by notaprodev** [comment]
Thanks for the patch. We will test it on our testing env and will let you know the result

**Comment by frjo** [comment]
@notaprodev This fix is now released as part of https://github.com/HyphaApp/hypha/releases/tag/v5.19.0

Thanks again for taking the time to report this! It took some time for us to get a fix in place but I believe it is a solid solution.
