### ISSUE TITLE
PAF capitalization is weird in the assignment activity

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4252]
When the PAF is assigned to a user, the activity message in the communications tab says `pAF assigned to...`

I think this stems from [activity_feed.py](https://github.com/HyphaApp/hypha/blob/main/hypha/apply/activity/adapters/activity_feed.py#L206) but in my brief look nothing jumped out at me as wrong

## Screenshots
![Screenshot 2024-12-05 at 14 32 53](https://github.com/user-attachments/assets/67aee20b-d2e2-4560-b3d7-b5d7920ce2ed)

**Comment by frjo** [comment]
I have created a PR that rename the last of "PAF" (hopefully) to "project form".

Let's see if that fixes the capitalisation as well.
