### ISSUE TITLE
When Contracting/Finance tries to view a Project Document, they recieve a `Permission Denied` screen

### ISSUE THREAD

**Issue by wes-otf** [HyphaApp/hypha#4274]
When a user with both `Finance`/`Contracting` & `Approver` roles tries to select `View` on an uploaded Project Document, it results in a permission denied screen. In OTF's case, it's necessary for both parties to be able to access things like CVs & budgets during the initial approval process

**Comment by frjo** [comment]
So this is for "Project Document Categories" and not "Contract Document Categories"?

The first is uploaded by staff the other is uploaded by applicants.

**Comment by wes-otf** [comment]
yeah `Project Document Categories` is correct

**Comment by frjo** [comment]
It is this code that controls access:

https://github.com/HyphaApp/hypha/blob/1f0a8c7ab50c3c772880612fd83a1a88e32ec598/hypha/apply/projects/views/project.py#L1743-L1755

Finance and Contracting users only have access when they are assigned to approve and it has not been approved yet.

So the code seems to work as intended, but OTFs requirements have changed.

Maybe simplify the access check to this?

~~~~
    def test_func(self):
        if self.request.user.is_org_faculty:
            return True

        if self.request.user == self.project.user:
            return True

        return False
~~~~

Then any staff/finance/contracting (org_faculty) user have access.

**Comment by wes-otf** [comment]
That makes sense to me to update it to your simplified version or at least indicate to the user they can't view it (ie. don't show the view button) and explain who can. In OTFs use case the former would be better, as anyone in that group could have a need to view those documents
