### ISSUE TITLE
E-mail sent on report submit, what are we informing the applicant of?

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#4285]
The message is only sent if the project user (applicant) is submitting the report. But the message states that a staff member posted a report. 

This is code from 2019 so we likely need to rethink it from the ground. 

Is the message even needed at all? If so what purpose have it?

We send the report in this function:

https://github.com/HyphaApp/hypha/blob/01a98aa286b554e4d6eba2bb75a52e5eada354ef/hypha/apply/projects/views/report.py#L173-L192

This is the template.

https://github.com/HyphaApp/hypha/blob/01a98aa286b554e4d6eba2bb75a52e5eada354ef/hypha/apply/activity/templates/messages/email/report_submitted.html#L1-L12

**Comment by frjo** [comment]
@wes-otf What are OTFs needs around this?

**Comment by wes-otf** [comment]
I think all OTF would really need is for the lead to be notified when a new report is completed - and maybe for the edge cases we handle it like we do comments where if a staff member submits a report on behalf of the applicant the applicant gets a notification but not staff? ie. the report author won't get the notification

**Comment by frjo** [comment]
A slack message is sent out but leads slack name is not added, will create an issue about that.

**Comment by frjo** [comment]
Something is wrong with how we save reports, closing this and creating a new issue.
