### ISSUE TITLE
Allow staff to change author of submission

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#663]
[<img alt="Issuehunt badges" src="https://img.shields.io/badge/IssueHunt-%2422%20Funded-%2300A156.svg" />](https://issuehunt.io/r/OpenTechFund/opentech.fund/issues/663)

Applicant may already have an account but forgot and used another e-mail address or misspells the e-mail address.

---

<details>
<summary>
<b>IssueHunt Summary</b>
</summary>

### Backers (Total: $22.00)

- [<img src='https://avatars1.githubusercontent.com/u/620336?v=4' alt='danblah' width=24 height=24> danblah](https://issuehunt.io/u/danblah) ($22.00)

### Tips

- Checkout the [Issuehunt explorer](https://issuehunt.io/r/OpenTechFund/opentech.fund/) to discover more funded issues.
- Need some help from other developers? [Add your repositories](https://issuehunt.io/r/new) on IssueHunt to raise funds.
---
IssueHunt has been backed by the following sponsors. [Become a sponsor](https://issuehunt.io/membership/members)
</details>

**Comment by danblah** [comment]
- [ ] Create an new action call "Author" or something.
- [ ] Add it to the Actions to take
- [ ] On press, pop an interface for staff to add an email.
- [ ] If existing user, replace them as the author
- [ ] If unknown user, kick off new user process, and add them as author

**Comment by shtuffit** [comment]
In familiarizing myself with the source code I found a work around. Details can be changed in apply.your.domain/admin/users/ with staff level privileges. I would think it would be better to make the email box in the actual review interface read only as to not accidentally change someones contact email.

Thoughts?
