### ISSUE TITLE
Ability to tag or @ team members, reviewers, etc in communication comments, that sends a notification to the person 

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#690]

**Comment by frjo** [comment]
@saoun We could add a "Slack notice" field to comments for staff where they could check one ot more persons that have Slack usernames in the system. The user name would then be added to the Slack notification.

How do you envision it should work for reviewers etc., they do not have Slack so a notification would need to be e-mailed I assume. There are a lot more revirers so the UI would need some thought.

My suggestion is to build the Slack/staff part first and see how mush it's used.

**Comment by saoun** [comment]
We could definitely try with just the slack notification first. 

I also pinged @georgiamoon to think through what the UI would look like on a user's dashboard, where they could get notifications about tags. This definitely needs some spec'ing out and thinking through.

**Comment by georgiamoon** [comment]
Adding myself and @ei8fdb to this issue. @saoun I think we might need a bit more context on the current ecosystem of emails/messaging to get a sense for this. Would you or @fourthletter have time to show us a bit more about what you are imagining? Also just wondering if this is about the overall feature development or a question about where in the UI of the main dashboard for staff to have the notifications. Anymore context folks can share is great!

**Comment by saoun** [comment]
Sure, happy to chat more @georgiamoon !

**Comment by fourthletter** [comment]
Could be closed because it related to an overarching issue of #2161
