### ISSUE TITLE
Add print, export to (pdf,csv,json) buttons on all submission pages

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#783]

**Comment by frjo** [comment]
Is this not built in to all browse/OS nowadays. I added some print CSS some time back. 

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by danblah** [comment]
Apparently not. a quick scan of https://github.com/OpenTechFund/opentech.fund/blob/master/opentech/static_src/src/sass/print.scss doesn't show a @page size declaration. I've just added size: letter. We could also try try size: auto.
