### ISSUE TITLE
Offer a post final determination survey to applicants to complete to capture their feedback on the workflow

### ISSUE THREAD

**Issue by danblah** [HyphaApp/hypha#835]
This is something that would go out as a separate standalone notification (email, etc).

**Comment by saoun** [comment]
@di, could you bring this up with Simply Secure so that they can integrate in their recommendations / work?

**Comment by fourthletter** [comment]
related to #2288

**Comment by ei8fdb** [comment]
@danblah As @fourthletter mentions above, we've made the post-application submission page modifiable by the Hypha PM user. This means they can ask applicants for feedback *right after submission*.

Your request is a bit different - asking for a mechanism to get feedback about the application process **at the very end** - but does what's been built in #2288 satisfy your want? 

If not, then I'll add that to the list.

**Comment by ei8fdb** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [https://github.com/OpenTechFund/hypha/issues/835](https://trello.com/c/nDNIZNdy/28-https-githubcom-opentechfund-hypha-issues-835)

**Comment by fourthletter** [comment]
@ei8fdb Sorry for the confusion. I linked these issues because the newly modified landing page means that I am now able to edit the landing page with any type of applicant survey I want in the future. After the user feedback on new application forms have been collected and analyzed, it would be helpful to implement a post-applicant survey about the workflow.

**Comment by ei8fdb** [comment]
This story seems to be specific to OTF? If so, @fourthletter @saoun a few questions:

- do you have an idea of what questions, you'd like to ask? If not, I can put together a list of questions to begin.
- is there any survey platform you'd prefer to use? Would a Google Form be sufficient?

**Comment by fourthletter** [comment]
@ei8fdb I have a questionnaire in mind, would be great if Sim Sec could administer the survey. I'm closing this issue because it's no longer dev related.
