### ISSUE TITLE
Implement the django-registration package

### ISSUE THREAD

**Issue by frjo** [HyphaApp/hypha#893]
Implement the django-registration package

Assuming this is this: https://django-registration-redux.readthedocs.io/en/latest/quickstart.html

 It would improve the code around user registration but not add any functionality at the moment.

**Priority**

- Low priority (annoying, would be nice to not see)

**Affected roles**

- Applicants
- Developers

**Ideal deadline**

* Recommend review in Q2 rebasing for priority level.

**Comment by saoun** [comment]
anything that is needed to implement this @frjo ?

**Comment by frjo** [comment]
Some work to implement. It would improve the code around user registration but not add any functionality at the moment.

Good to get done for the future but not urgent.

**Comment by Erioldoesdesign** [comment]
Q1 2022 Rebasing updates:
* Assuming this is this: https://django-registration-redux.readthedocs.io/en/latest/quickstart.html
* Updated description
* Removed priority needed label
* Size estimated at S
* Technical enhancement, not feature enhancement
* Recommend review in Q2 rebasing for priority level.

**Comment by Erioldoesdesign** [comment]
@frjo do you think maybe this one can be closed? I wonder what might have changed given the recent Django 3 updates? anyways, this was opened in 2019 and we've survived without it for that long so maybe it really is a 'very nice to have' 😅
